// d3d9-methods.js — shared spec of the Direct3D 9 COM interfaces we answer.
// Consumed by gen_api_table.js (to append API entries, contiguous per
// interface so init_com_vtable can build a vtable from one base id) and by
// gen_d3d9_stubs.js (one-time generator for src/09ad-handlers-d3d9.wat).
//
// Method ORDER IS THE VTABLE and must not be reordered or trimmed: a slot's
// index is what the guest calls through, so an interface listed short here
// silently redirects every later method of a real d3d9.dll caller.
//
// nargs is the stdcall argument count including `this`; stub bodies pop
// 4 + nargs*4 off ESP with it.
//
// ret/body tags understood by the generator:
//   'OK'      — return D3D_OK (0), the default for a method whose no-op
//               answer is harmless.
//   'ADDREF'/'RELEASE' — refcount on the DX_OBJECTS entry.
//   'CRASH'   — $crash_unimplemented. The default: an unimplemented D3D9
//               method that silently returned 0 would hand the app a NULL
//               resource or stale output buffer and fail somewhere unrelated.

'use strict';

const interfaces = [
  // ── IDirect3D9 — the object Direct3DCreate9 returns ────────────────
  { prefix: 'IDirect3D9', methods: [
    { name: 'QueryInterface',              nargs: 3, ret: 'CRASH' },
    { name: 'AddRef',                      nargs: 1, ret: 'ADDREF', handler: 'dx_com_addref' },
    { name: 'Release',                     nargs: 1, ret: 'RELEASE', handler: 'dx_com_release_basic' },
    { name: 'RegisterSoftwareDevice',      nargs: 2, ret: 'OK' },
    { name: 'GetAdapterCount',             nargs: 1, ret: 'OK' },
    { name: 'GetAdapterIdentifier',        nargs: 4, ret: 'CRASH' },
    { name: 'GetAdapterModeCount',         nargs: 3, ret: 'OK' },
    { name: 'EnumAdapterModes',            nargs: 5, ret: 'OK' },
    { name: 'GetAdapterDisplayMode',       nargs: 3, ret: 'OK' },
    { name: 'CheckDeviceType',             nargs: 6, ret: 'OK' },
    { name: 'CheckDeviceFormat',           nargs: 7, ret: 'OK' },
    { name: 'CheckDeviceMultiSampleType',  nargs: 7, ret: 'OK' },
    { name: 'CheckDepthStencilMatch',      nargs: 6, ret: 'OK' },
    { name: 'CheckDeviceFormatConversion', nargs: 5, ret: 'OK' },
    { name: 'GetDeviceCaps',               nargs: 4, ret: 'CRASH' },
    { name: 'GetAdapterMonitor',           nargs: 2, ret: 'OK' },
    { name: 'CreateDevice',                nargs: 7, ret: 'OK' },
  ]},

  // ── IDirect3DDevice9 — 119 slots ───────────────────────────────────
  { prefix: 'IDirect3DDevice9', methods: [
    { name: 'QueryInterface',            nargs: 3, ret: 'CRASH' },
    { name: 'AddRef',                    nargs: 1, ret: 'ADDREF', handler: 'dx_com_addref' },
    { name: 'Release',                   nargs: 1, body: 'RELEASE_DEVICE9' },
    { name: 'TestCooperativeLevel',      nargs: 1, ret: 'OK' },
    { name: 'GetAvailableTextureMem',    nargs: 1, ret: 'OK' },
    { name: 'EvictManagedResources',     nargs: 1, ret: 'OK' },
    { name: 'GetDirect3D',               nargs: 2 },
    { name: 'GetDeviceCaps',             nargs: 2, ret: 'CRASH' },
    { name: 'GetDisplayMode',            nargs: 3, ret: 'CRASH' },
    { name: 'GetCreationParameters',     nargs: 2 },
    { name: 'SetCursorProperties',       nargs: 4, ret: 'OK' },
    { name: 'SetCursorPosition',         nargs: 4, ret: 'OK' },
    { name: 'ShowCursor',                nargs: 2, ret: 'OK' },
    { name: 'CreateAdditionalSwapChain', nargs: 3 },
    { name: 'GetSwapChain',              nargs: 3 },
    { name: 'GetNumberOfSwapChains',     nargs: 1, ret: 'OK' },
    { name: 'Reset',                     nargs: 2, ret: 'OK' },
    { name: 'Present',                   nargs: 5, ret: 'OK' },
    { name: 'GetBackBuffer',             nargs: 5, ret: 'OK' },
    { name: 'GetRasterStatus',           nargs: 3 },
    { name: 'SetDialogBoxMode',          nargs: 2, ret: 'OK' },
    { name: 'SetGammaRamp',              nargs: 4, ret: 'OK' },
    { name: 'GetGammaRamp',              nargs: 3, ret: 'CRASH' },
    { name: 'CreateTexture',             nargs: 9, ret: 'CRASH' },
    { name: 'CreateVolumeTexture',       nargs: 10 },
    { name: 'CreateCubeTexture',         nargs: 8 },
    { name: 'CreateVertexBuffer',        nargs: 7 },
    { name: 'CreateIndexBuffer',         nargs: 7 },
    { name: 'CreateRenderTarget',        nargs: 9 },
    { name: 'CreateDepthStencilSurface', nargs: 9, ret: 'CRASH' },
    { name: 'UpdateSurface',             nargs: 5 },
    { name: 'UpdateTexture',             nargs: 3 },
    { name: 'GetRenderTargetData',       nargs: 3 },
    { name: 'GetFrontBufferData',        nargs: 3 },
    { name: 'StretchRect',               nargs: 6 },
    { name: 'ColorFill',                 nargs: 4 },
    { name: 'CreateOffscreenPlainSurface', nargs: 7 },
    { name: 'SetRenderTarget',           nargs: 3, ret: 'OK' },
    { name: 'GetRenderTarget',           nargs: 3, ret: 'CRASH' },
    { name: 'SetDepthStencilSurface',    nargs: 2, ret: 'OK' },
    { name: 'GetDepthStencilSurface',    nargs: 2, ret: 'CRASH' },
    { name: 'BeginScene',                nargs: 1, ret: 'OK' },
    { name: 'EndScene',                  nargs: 1, ret: 'OK' },
    // this, Count, pRects, Flags, Color, Z, Stencil
    { name: 'Clear',                     nargs: 7, ret: 'OK' },
    { name: 'SetTransform',              nargs: 3, ret: 'OK' },
    { name: 'GetTransform',              nargs: 3, ret: 'CRASH' },
    { name: 'MultiplyTransform',         nargs: 3, ret: 'OK' },
    { name: 'SetViewport',               nargs: 2, ret: 'OK' },
    { name: 'GetViewport',               nargs: 2, ret: 'CRASH' },
    { name: 'SetMaterial',               nargs: 2, ret: 'OK' },
    { name: 'GetMaterial',               nargs: 2, ret: 'CRASH' },
    { name: 'SetLight',                  nargs: 3, ret: 'OK' },
    { name: 'GetLight',                  nargs: 3, ret: 'CRASH' },
    { name: 'LightEnable',               nargs: 3, ret: 'OK' },
    { name: 'GetLightEnable',            nargs: 3, ret: 'CRASH' },
    { name: 'SetClipPlane',              nargs: 3, ret: 'OK' },
    { name: 'GetClipPlane',              nargs: 3, ret: 'CRASH' },
    { name: 'SetRenderState',            nargs: 3, ret: 'OK' },
    { name: 'GetRenderState',            nargs: 3, ret: 'CRASH' },
    { name: 'CreateStateBlock',          nargs: 3 },
    { name: 'BeginStateBlock',           nargs: 1, ret: 'OK' },
    { name: 'EndStateBlock',             nargs: 2 },
    { name: 'SetClipStatus',             nargs: 2, ret: 'OK' },
    { name: 'GetClipStatus',             nargs: 2, ret: 'CRASH' },
    { name: 'GetTexture',                nargs: 3, ret: 'CRASH' },
    { name: 'SetTexture',                nargs: 3, ret: 'OK' },
    { name: 'GetTextureStageState',      nargs: 4, ret: 'CRASH' },
    { name: 'SetTextureStageState',      nargs: 4, ret: 'OK' },
    { name: 'GetSamplerState',           nargs: 4, ret: 'CRASH' },
    { name: 'SetSamplerState',           nargs: 4, ret: 'OK' },
    { name: 'ValidateDevice',            nargs: 2, ret: 'OK' },
    { name: 'SetPaletteEntries',         nargs: 3, ret: 'OK' },
    { name: 'GetPaletteEntries',         nargs: 3, ret: 'CRASH' },
    { name: 'SetCurrentTexturePalette',  nargs: 2, ret: 'OK' },
    { name: 'GetCurrentTexturePalette',  nargs: 2, ret: 'CRASH' },
    { name: 'SetScissorRect',            nargs: 2, ret: 'OK' },
    { name: 'GetScissorRect',            nargs: 2, ret: 'CRASH' },
    { name: 'SetSoftwareVertexProcessing', nargs: 2, ret: 'OK' },
    { name: 'GetSoftwareVertexProcessing', nargs: 1, ret: 'OK' },
    { name: 'SetNPatchMode',             nargs: 2, ret: 'OK' },
    { name: 'GetNPatchMode',             nargs: 1, ret: 'OK' },
    { name: 'DrawPrimitive',             nargs: 4 },
    { name: 'DrawIndexedPrimitive',      nargs: 7 },
    { name: 'DrawPrimitiveUP',           nargs: 5, ret: 'OK' },
    { name: 'DrawIndexedPrimitiveUP',    nargs: 9 },
    { name: 'ProcessVertices',           nargs: 7 },
    { name: 'CreateVertexDeclaration',   nargs: 3 },
    { name: 'SetVertexDeclaration',      nargs: 2 },
    { name: 'GetVertexDeclaration',      nargs: 2 },
    { name: 'SetFVF',                    nargs: 2, ret: 'OK' },
    { name: 'GetFVF',                    nargs: 2, ret: 'CRASH' },
    { name: 'CreateVertexShader',        nargs: 3 },
    { name: 'SetVertexShader',           nargs: 2 },
    { name: 'GetVertexShader',           nargs: 2 },
    { name: 'SetVertexShaderConstantF',  nargs: 4 },
    { name: 'GetVertexShaderConstantF',  nargs: 4 },
    { name: 'SetVertexShaderConstantI',  nargs: 4 },
    { name: 'GetVertexShaderConstantI',  nargs: 4 },
    { name: 'SetVertexShaderConstantB',  nargs: 4 },
    { name: 'GetVertexShaderConstantB',  nargs: 4 },
    { name: 'SetStreamSource',           nargs: 5 },
    { name: 'GetStreamSource',           nargs: 5 },
    { name: 'SetStreamSourceFreq',       nargs: 3 },
    { name: 'GetStreamSourceFreq',       nargs: 3 },
    { name: 'SetIndices',                nargs: 2 },
    { name: 'GetIndices',                nargs: 2 },
    { name: 'CreatePixelShader',         nargs: 3 },
    { name: 'SetPixelShader',            nargs: 2 },
    { name: 'GetPixelShader',            nargs: 2 },
    { name: 'SetPixelShaderConstantF',   nargs: 4 },
    { name: 'GetPixelShaderConstantF',   nargs: 4 },
    { name: 'SetPixelShaderConstantI',   nargs: 4 },
    { name: 'GetPixelShaderConstantI',   nargs: 4 },
    { name: 'SetPixelShaderConstantB',   nargs: 4 },
    { name: 'GetPixelShaderConstantB',   nargs: 4 },
    { name: 'DrawRectPatch',             nargs: 4 },
    { name: 'DrawTriPatch',              nargs: 4 },
    { name: 'DeletePatch',               nargs: 2 },
    { name: 'CreateQuery',               nargs: 3 },
  ]},

  // ── IDirect3DTexture9 — IUnknown + Resource9 + BaseTexture9 + own ──
  { prefix: 'IDirect3DTexture9', methods: [
    { name: 'QueryInterface',        nargs: 3, ret: 'CRASH' },
    { name: 'AddRef',                nargs: 1, ret: 'ADDREF' },
    { name: 'Release',               nargs: 1, ret: 'RELEASE' },
    { name: 'GetDevice',             nargs: 2 },
    { name: 'SetPrivateData',        nargs: 5, ret: 'OK' },
    { name: 'GetPrivateData',        nargs: 4 },
    { name: 'FreePrivateData',       nargs: 2, ret: 'OK' },
    { name: 'SetPriority',           nargs: 2, ret: 'OK' },
    { name: 'GetPriority',           nargs: 1, ret: 'OK' },
    { name: 'PreLoad',               nargs: 1, ret: 'OK' },
    { name: 'GetType',               nargs: 1, ret: 'OK' },
    { name: 'SetLOD',                nargs: 2, ret: 'OK' },
    { name: 'GetLOD',                nargs: 1, ret: 'OK' },
    { name: 'GetLevelCount',         nargs: 1, ret: 'OK' },
    { name: 'SetAutoGenFilterType',  nargs: 2, ret: 'OK' },
    { name: 'GetAutoGenFilterType',  nargs: 1, ret: 'OK' },
    { name: 'GenerateMipSubLevels',  nargs: 1, ret: 'OK' },
    { name: 'GetLevelDesc',          nargs: 3, ret: 'CRASH' },
    { name: 'GetSurfaceLevel',       nargs: 3, ret: 'CRASH' },
    { name: 'LockRect',              nargs: 5, ret: 'CRASH' },
    { name: 'UnlockRect',            nargs: 2, ret: 'OK' },
    { name: 'AddDirtyRect',          nargs: 2, ret: 'OK' },
  ]},

  // ── IDirect3DSurface9 ──────────────────────────────────────────────
  { prefix: 'IDirect3DSurface9', methods: [
    { name: 'QueryInterface',  nargs: 3, ret: 'CRASH' },
    { name: 'AddRef',          nargs: 1, ret: 'ADDREF' },
    { name: 'Release',         nargs: 1, ret: 'RELEASE' },
    { name: 'GetDevice',       nargs: 2 },
    { name: 'SetPrivateData',  nargs: 5, ret: 'OK' },
    { name: 'GetPrivateData',  nargs: 4 },
    { name: 'FreePrivateData', nargs: 2, ret: 'OK' },
    { name: 'SetPriority',     nargs: 2, ret: 'OK' },
    { name: 'GetPriority',     nargs: 1, ret: 'OK' },
    { name: 'PreLoad',         nargs: 1, ret: 'OK' },
    { name: 'GetType',         nargs: 1, ret: 'OK' },
    { name: 'GetContainer',    nargs: 3 },
    { name: 'GetDesc',         nargs: 2, ret: 'CRASH' },
    { name: 'LockRect',        nargs: 4, ret: 'CRASH' },
    { name: 'UnlockRect',      nargs: 1, ret: 'OK' },
    { name: 'GetDC',           nargs: 2 },
    { name: 'ReleaseDC',       nargs: 2 },
  ]},

  // ── IDirect3DSwapChain9 ────────────────────────────────────────────
  { prefix: 'IDirect3DSwapChain9', methods: [
    { name: 'QueryInterface',       nargs: 3 },
    { name: 'AddRef',               nargs: 1, ret: 'ADDREF', handler: 'dx_com_addref' },
    { name: 'Release',              nargs: 1, ret: 'RELEASE', handler: 'IDirect3DDevice9_Release' },
    { name: 'Present',              nargs: 6 },
    { name: 'GetFrontBufferData',   nargs: 2 },
    { name: 'GetBackBuffer',        nargs: 4 },
    { name: 'GetRasterStatus',      nargs: 2 },
    { name: 'GetDisplayMode',       nargs: 2 },
    { name: 'GetDevice',            nargs: 2 },
    { name: 'GetPresentParameters', nargs: 2 },
  ]},
];

// prefix → WAT global holding the built vtable. Consumed by gen_dispatch.js,
// which appends these to the shared COM registry; $dx_sync_thread_vtables in
// src/09a8-handlers-directx.wat reads them back by offset in worker threads,
// so this order must match the loads there.
const vtableGlobals = [
  { prefix: 'IDirect3D9',        global: 'DX_VTBL_D3D9' },
  { prefix: 'IDirect3DDevice9',  global: 'DX_VTBL_D3DDEV9' },
  { prefix: 'IDirect3DTexture9', global: 'DX_VTBL_D3DTEX9' },
  { prefix: 'IDirect3DSurface9', global: 'DX_VTBL_D3DSURF9' },
];

module.exports = { interfaces, vtableGlobals };
