/*
 * Generate a Windows 3.x NE .FON containing monochrome FNT 3.0 strikes.
 *
 * This is intentionally a build-time tool.  FreeType supplies outline loading,
 * selectable hinting, and one-bit rasterization; Wine-Assembly's WAT FNT
 * backend consumes the generated bytes without a runtime FreeType dependency.
 */

#include <ft2build.h>
#include FT_FREETYPE_H

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
  uint8_t *data;
  size_t len;
  size_t cap;
} Buffer;

typedef struct {
  int width;
  uint8_t *bits;
  size_t bits_len;
} Glyph;

typedef struct {
  Buffer bytes;
  int height;
  int raster_height;
  int ascent;
  int average_width;
  int maximum_width;
} Strike;

typedef enum {
  HINTING_AUTO,
  HINTING_AUTO_NORMAL,
  HINTING_AUTO_LIGHT,
  HINTING_NATIVE,
  HINTING_NONE
} HintingMode;

typedef enum {
  RASTER_FIT_CELL,
  RASTER_EXACT_SIZE
} RasterSizing;

typedef enum {
  CHARSET_ANSI,
  CHARSET_OEM
} CharacterSet;

static void die(const char *message) {
  fprintf(stderr, "gen-bitmap-fon: %s\n", message);
  exit(1);
}

static void die_ft(const char *operation, FT_Error error) {
  fprintf(stderr, "gen-bitmap-fon: %s failed (FreeType error %d)\n",
          operation, error);
  exit(1);
}

static void reserve(Buffer *buffer, size_t needed) {
  size_t next;
  uint8_t *data;
  if (needed <= buffer->cap) return;
  next = buffer->cap ? buffer->cap : 256;
  while (next < needed) {
    if (next > SIZE_MAX / 2) die("output is too large");
    next *= 2;
  }
  data = (uint8_t *)realloc(buffer->data, next);
  if (!data) die("out of memory");
  memset(data + buffer->cap, 0, next - buffer->cap);
  buffer->data = data;
  buffer->cap = next;
}

static void resize_zero(Buffer *buffer, size_t length) {
  size_t old = buffer->len;
  reserve(buffer, length);
  if (length > old) memset(buffer->data + old, 0, length - old);
  buffer->len = length;
}

static size_t append(Buffer *buffer, const void *data, size_t length) {
  size_t offset = buffer->len;
  resize_zero(buffer, offset + length);
  if (length) memcpy(buffer->data + offset, data, length);
  return offset;
}

static size_t append_zero(Buffer *buffer, size_t length) {
  size_t offset = buffer->len;
  resize_zero(buffer, offset + length);
  return offset;
}

static void align_buffer(Buffer *buffer, size_t alignment) {
  size_t aligned = (buffer->len + alignment - 1) & ~(alignment - 1);
  resize_zero(buffer, aligned);
}

static void put_u8(Buffer *buffer, size_t offset, uint8_t value) {
  if (offset >= buffer->len) die("internal byte write overflow");
  buffer->data[offset] = value;
}

static void put_u16(Buffer *buffer, size_t offset, uint16_t value) {
  if (offset + 2 > buffer->len) die("internal word write overflow");
  buffer->data[offset] = (uint8_t)value;
  buffer->data[offset + 1] = (uint8_t)(value >> 8);
}

static void put_u32(Buffer *buffer, size_t offset, uint32_t value) {
  if (offset + 4 > buffer->len) die("internal dword write overflow");
  buffer->data[offset] = (uint8_t)value;
  buffer->data[offset + 1] = (uint8_t)(value >> 8);
  buffer->data[offset + 2] = (uint8_t)(value >> 16);
  buffer->data[offset + 3] = (uint8_t)(value >> 24);
}

static uint32_t cp1252_codepoint(unsigned byte) {
  static const uint16_t high[32] = {
    0x20ac, 0x0081, 0x201a, 0x0192, 0x201e, 0x2026, 0x2020, 0x2021,
    0x02c6, 0x2030, 0x0160, 0x2039, 0x0152, 0x008d, 0x017d, 0x008f,
    0x0090, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2013, 0x2014,
    0x02dc, 0x2122, 0x0161, 0x203a, 0x0153, 0x009d, 0x017e, 0x0178
  };
  if (byte >= 0x80 && byte <= 0x9f) return high[byte - 0x80];
  return byte;
}

static uint32_t cp437_codepoint(unsigned byte) {
  static const uint16_t controls[32] = {
    0x0020, 0x263a, 0x263b, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022,
    0x25d8, 0x25cb, 0x25d9, 0x2642, 0x2640, 0x266a, 0x266b, 0x263c,
    0x25ba, 0x25c4, 0x2195, 0x203c, 0x00b6, 0x00a7, 0x25ac, 0x21a8,
    0x2191, 0x2193, 0x2192, 0x2190, 0x221f, 0x2194, 0x25b2, 0x25bc
  };
  static const uint16_t high[128] = {
    0x00c7, 0x00fc, 0x00e9, 0x00e2, 0x00e4, 0x00e0, 0x00e5, 0x00e7,
    0x00ea, 0x00eb, 0x00e8, 0x00ef, 0x00ee, 0x00ec, 0x00c4, 0x00c5,
    0x00c9, 0x00e6, 0x00c6, 0x00f4, 0x00f6, 0x00f2, 0x00fb, 0x00f9,
    0x00ff, 0x00d6, 0x00dc, 0x00a2, 0x00a3, 0x00a5, 0x20a7, 0x0192,
    0x00e1, 0x00ed, 0x00f3, 0x00fa, 0x00f1, 0x00d1, 0x00aa, 0x00ba,
    0x00bf, 0x2310, 0x00ac, 0x00bd, 0x00bc, 0x00a1, 0x00ab, 0x00bb,
    0x2591, 0x2592, 0x2593, 0x2502, 0x2524, 0x2561, 0x2562, 0x2556,
    0x2555, 0x2563, 0x2551, 0x2557, 0x255d, 0x255c, 0x255b, 0x2510,
    0x2514, 0x2534, 0x252c, 0x251c, 0x2500, 0x253c, 0x255e, 0x255f,
    0x255a, 0x2554, 0x2569, 0x2566, 0x2560, 0x2550, 0x256c, 0x2567,
    0x2568, 0x2564, 0x2565, 0x2559, 0x2558, 0x2552, 0x2553, 0x256b,
    0x256a, 0x2518, 0x250c, 0x2588, 0x2584, 0x258c, 0x2590, 0x2580,
    0x03b1, 0x00df, 0x0393, 0x03c0, 0x03a3, 0x03c3, 0x00b5, 0x03c4,
    0x03a6, 0x0398, 0x03a9, 0x03b4, 0x221e, 0x03c6, 0x03b5, 0x2229,
    0x2261, 0x00b1, 0x2265, 0x2264, 0x2320, 0x2321, 0x00f7, 0x2248,
    0x00b0, 0x2219, 0x00b7, 0x221a, 0x207f, 0x00b2, 0x25a0, 0x00a0
  };
  if (byte < 0x20) return controls[byte];
  if (byte == 0x7f) return 0x2302;
  if (byte >= 0x80) return high[byte - 0x80];
  return byte;
}

static uint32_t encoded_codepoint(unsigned byte, CharacterSet charset) {
  return charset == CHARSET_OEM ? cp437_codepoint(byte) : cp1252_codepoint(byte);
}

static int ceil_26_6(FT_Pos value) {
  if (value <= 0) return 0;
  return (int)((value + 63) >> 6);
}

static int round_26_6(FT_Pos value) {
  if (value >= 0) return (int)((value + 32) >> 6);
  return -(int)((-value + 32) >> 6);
}

static uint8_t mono_source_bit(const FT_Bitmap *bitmap, int x, int y) {
  int pitch = bitmap->pitch;
  const uint8_t *row;
  if (x < 0 || y < 0 || x >= (int)bitmap->width || y >= (int)bitmap->rows)
    return 0;
  row = pitch >= 0
    ? bitmap->buffer + (size_t)y * (size_t)pitch
    : bitmap->buffer + (size_t)(bitmap->rows - 1 - y) * (size_t)(-pitch);
  return (uint8_t)(row[x >> 3] & (0x80u >> (x & 7)));
}

static FT_Int32 hinting_load_flags(HintingMode hinting) {
  FT_Int32 flags = hinting == HINTING_AUTO_NORMAL
    ? FT_LOAD_TARGET_NORMAL
    : hinting == HINTING_AUTO_LIGHT ? FT_LOAD_TARGET_LIGHT : FT_LOAD_TARGET_MONO;
  if (hinting == HINTING_AUTO || hinting == HINTING_AUTO_NORMAL ||
      hinting == HINTING_AUTO_LIGHT) flags |= FT_LOAD_FORCE_AUTOHINT;
  if (hinting == HINTING_NATIVE) flags |= FT_LOAD_NO_AUTOHINT;
  if (hinting == HINTING_NONE) flags |= FT_LOAD_NO_HINTING;
  return flags;
}

static void render_glyph(FT_Face face, unsigned byte, int cell_height,
                         int ascent, int fixed_width, HintingMode hinting,
                         int bitmap_only, CharacterSet charset, Glyph *glyph) {
  FT_Error error;
  FT_GlyphSlot slot;
  int advance;
  int draw_x;
  int draw_y;
  int x;
  int y;
  int width_bytes;
  uint32_t codepoint = encoded_codepoint(byte, charset);

  if (charset == CHARSET_OEM && FT_Get_Char_Index(face, codepoint) == 0) {
    fprintf(stderr, "gen-bitmap-fon: source is missing CP437 byte 0x%02x (U+%04x)\n",
            byte, codepoint);
    exit(1);
  }
  error = FT_Load_Char(face, codepoint, hinting_load_flags(hinting));
  if (error) {
    error = FT_Load_Char(face, '?', hinting_load_flags(hinting));
  }
  if (error) die_ft("FT_Load_Char", error);
  slot = face->glyph;
  /* A glyph with no embedded bitmap is acceptable in exactly two cases, and
     both mean "there is nothing to draw" rather than "draw it another way":

       - the glyph is blank, which is how space is stored in Wine's larger
         Tahoma strikes: it has an advance and no ink, so the strike carries
         no bitmap for it;
       - the byte is not mapped by the face at all, so it would resolve to
         .notdef, and the strike does not carry .notdef either. Wine's Tahoma
         includes .notdef up to 10ppem and drops it above, so the five bytes
         CP1252 leaves undefined show Wine's box at the small sizes and
         nothing at the large ones - which is what the strikes contain.

     Any other glyph reaching here would be silently rasterized from its
     outline and substituted for strike pixels, which is the one thing
     --bitmap-only exists to prevent. */
  if (bitmap_only && slot->format != FT_GLYPH_FORMAT_BITMAP) {
    int blank = slot->format == FT_GLYPH_FORMAT_OUTLINE &&
                slot->outline.n_contours == 0;
    if (!blank && FT_Get_Char_Index(face, codepoint) == 0) blank = 1;
    if (!blank) {
      fprintf(stderr,
              "gen-bitmap-fon: byte 0x%02x (U+%04x) has no embedded bitmap "
              "and is not blank\n", byte, codepoint);
      exit(1);
    }
    /* Drop whatever outline came back so the cell is emitted empty. */
    slot->outline.n_contours = 0;
    slot->outline.n_points = 0;
  }
  if (slot->format == FT_GLYPH_FORMAT_OUTLINE) {
    error = FT_Render_Glyph(slot, FT_RENDER_MODE_MONO);
    if (error) die_ft("FT_Render_Glyph", error);
  }
  if (slot->bitmap.pixel_mode != FT_PIXEL_MODE_MONO && slot->bitmap.width)
    die("FreeType did not return a monochrome glyph");

  advance = round_26_6(slot->advance.x);
  if (advance < 1) advance = 1;
  if (advance > 255) advance = 255;
  if (fixed_width) advance = fixed_width;
  glyph->width = advance;
  width_bytes = (advance + 7) / 8;
  glyph->bits_len = (size_t)width_bytes * (size_t)cell_height;
  glyph->bits = (uint8_t *)calloc(glyph->bits_len ? glyph->bits_len : 1, 1);
  if (!glyph->bits) die("out of memory");

  draw_x = slot->bitmap_left;
  draw_y = ascent - slot->bitmap_top;
  for (y = 0; y < (int)slot->bitmap.rows; y++) {
    int dest_y = draw_y + y;
    if (dest_y < 0 || dest_y >= cell_height) continue;
    for (x = 0; x < (int)slot->bitmap.width; x++) {
      int dest_x = draw_x + x;
      size_t dest;
      if (dest_x < 0 || dest_x >= advance || !mono_source_bit(&slot->bitmap, x, y))
        continue;
      /* Windows FNT stores byte-columns, each containing all glyph rows. */
      dest = (size_t)(dest_x >> 3) * (size_t)cell_height + (size_t)dest_y;
      glyph->bits[dest] |= (uint8_t)(0x80u >> (dest_x & 7));
    }
  }
}

static Strike make_strike(FT_Face face, int requested_height,
                          const char *face_name, int force_fixed,
                          const char *copyright, HintingMode hinting,
                          RasterSizing raster_sizing, int bitmap_only,
                          CharacterSet charset, int weight) {
  enum { LAST_CHAR = 255, MAX_GLYPH_COUNT = 256 };
  Strike strike;
  Glyph glyphs[MAX_GLYPH_COUNT];
  FT_Error error;
  int raster_height;
  int ascent;
  int descent;
  int height;
  int max_width = 1;
  long printable_width = 0;
  int printable_count = 0;
  int width_bytes = 0;
  int fixed_width = 0;
  int first_char = charset == CHARSET_OEM ? 0 : 32;
  int glyph_count = LAST_CHAR - first_char + 1;
  size_t char_table;
  size_t bits_offset;
  size_t face_offset;
  int i;

  memset(&strike, 0, sizeof(strike));
  memset(glyphs, 0, sizeof(glyphs));
  /*
   * FNT selects strikes by cell height.  Some outlines (including W95FA at
   * 12px) round ascender and descender outward to one pixel more than the
   * requested em.  Reduce the rasterized em until it fits instead of silently
   * emitting a differently named strike or clipping the bottom row.
   */
  raster_height = requested_height;
  for (;;) {
    error = FT_Set_Pixel_Sizes(face, 0, (FT_UInt)raster_height);
    if (error) die_ft("FT_Set_Pixel_Sizes", error);
    ascent = ceil_26_6(face->size->metrics.ascender);
    descent = ceil_26_6(-face->size->metrics.descender);
    if (raster_sizing == RASTER_EXACT_SIZE ||
        ascent + descent <= requested_height || raster_height <= 4) break;
    raster_height--;
  }
  height = requested_height;
  if (height < 1 || height > 256) die("generated cell height is outside FNT limits");
  if (ascent < 1) ascent = height;
  if (ascent > height) ascent = height;

  if (force_fixed) {
    error = FT_Load_Char(face, 'M', hinting_load_flags(hinting));
    if (error) die_ft("FT_Load_Char", error);
    fixed_width = round_26_6(face->glyph->advance.x);
    if (fixed_width < 1) fixed_width = 1;
    if (fixed_width > 255) fixed_width = 255;
  }

  for (i = 0; i < glyph_count; i++) {
    int byte = first_char + i;
    render_glyph(face, (unsigned)byte, height, ascent, fixed_width, hinting, bitmap_only,
                 charset, &glyphs[i]);
    if (glyphs[i].width > max_width) max_width = glyphs[i].width;
    width_bytes += (glyphs[i].width + 7) / 8;
    if (byte >= 32 && byte <= 126) {
      printable_width += glyphs[i].width;
      printable_count++;
    }
  }

  resize_zero(&strike.bytes, 148 + (glyph_count + 1) * 6);
  char_table = 148;
  bits_offset = strike.bytes.len;
  for (i = 0; i < glyph_count; i++) {
    size_t entry = char_table + (size_t)i * 6;
    put_u16(&strike.bytes, entry, (uint16_t)glyphs[i].width);
    put_u32(&strike.bytes, entry + 2, (uint32_t)strike.bytes.len);
    append(&strike.bytes, glyphs[i].bits, glyphs[i].bits_len);
    free(glyphs[i].bits);
  }
  put_u16(&strike.bytes, char_table + glyph_count * 6, 0);
  put_u32(&strike.bytes, char_table + glyph_count * 6 + 2,
          (uint32_t)strike.bytes.len);
  face_offset = append(&strike.bytes, face_name, strlen(face_name) + 1);

  put_u16(&strike.bytes, 0, 0x0300);
  put_u32(&strike.bytes, 2, (uint32_t)strike.bytes.len);
  {
    size_t n = strlen(copyright);
    if (n > 60) n = 60;
    memcpy(strike.bytes.data + 6, copyright, n);
  }
  put_u16(&strike.bytes, 66, 0); /* raster font */
  put_u16(&strike.bytes, 68, (uint16_t)((raster_height * 72 + 48) / 96));
  put_u16(&strike.bytes, 70, 96);
  put_u16(&strike.bytes, 72, 96);
  put_u16(&strike.bytes, 74, (uint16_t)ascent);
  put_u16(&strike.bytes, 76, (uint16_t)(height - raster_height));
  put_u16(&strike.bytes, 78, 0);
  put_u8(&strike.bytes, 80, 0);
  put_u8(&strike.bytes, 81, 0);
  put_u8(&strike.bytes, 82, 0);
  put_u16(&strike.bytes, 83, (uint16_t)weight);
  put_u8(&strike.bytes, 85, (uint8_t)(charset == CHARSET_OEM ? 255 : 0));
  put_u16(&strike.bytes, 86, (uint16_t)fixed_width);
  put_u16(&strike.bytes, 88, (uint16_t)height);
  put_u8(&strike.bytes, 90,
         (uint8_t)(force_fixed ? 0x30 : 0x21)); /* fixed Modern / variable Swiss */
  put_u16(&strike.bytes, 91,
          (uint16_t)(printable_count ? (printable_width + printable_count / 2) / printable_count : 1));
  put_u16(&strike.bytes, 93, (uint16_t)max_width);
  put_u8(&strike.bytes, 95, (uint8_t)first_char);
  put_u8(&strike.bytes, 96, LAST_CHAR);
  put_u8(&strike.bytes, 97, (uint8_t)('?' - first_char));
  put_u8(&strike.bytes, 98, (uint8_t)(' ' - first_char));
  put_u16(&strike.bytes, 99, (uint16_t)width_bytes);
  put_u32(&strike.bytes, 101, 0); /* device name */
  put_u32(&strike.bytes, 105, (uint32_t)face_offset);
  put_u32(&strike.bytes, 109, 0); /* in-memory bits pointer */
  put_u32(&strike.bytes, 113, (uint32_t)bits_offset);
  put_u32(&strike.bytes, 118, 1); /* one-color fixed/proportional raster data */
  put_u16(&strike.bytes, 122, 0);
  put_u16(&strike.bytes, 124, 0);
  put_u16(&strike.bytes, 126, 0);
  put_u32(&strike.bytes, 128, 0);

  strike.height = height;
  strike.raster_height = raster_height;
  strike.ascent = ascent;
  strike.average_width = printable_count
    ? (int)((printable_width + printable_count / 2) / printable_count) : 1;
  strike.maximum_width = max_width;
  return strike;
}

static Buffer make_fontdir(const Strike *strikes, int count,
                           const char *face_name) {
  Buffer dir = {0};
  int i;
  append_zero(&dir, 2);
  put_u16(&dir, 0, (uint16_t)count);
  for (i = 0; i < count; i++) {
    size_t entry = append_zero(&dir, 2);
    put_u16(&dir, entry, (uint16_t)(i + 1));
    append(&dir, strikes[i].bytes.data, 109); /* FONTDIRENTRY through dfFace */
    append_zero(&dir, 4);                    /* dfReserved */
    append_zero(&dir, 1);                    /* empty device name */
    append(&dir, face_name, strlen(face_name) + 1);
  }
  return dir;
}

static Buffer make_fon(const Strike *strikes, int count,
                       const char *face_name) {
  enum { NE_OFFSET = 0x80, NE_SIZE = 0x40, RESOURCE_SHIFT = 4 };
  Buffer fon = {0};
  Buffer fontdir = make_fontdir(strikes, count, face_name);
  size_t resource_table = NE_OFFSET + NE_SIZE;
  size_t resource_table_size = 32 + (size_t)count * 12;
  size_t resident_names = resource_table + resource_table_size;
  size_t resident_length = 1 + strlen(face_name) + 2 + 1;
  size_t fontdir_offset;
  size_t *font_offsets;
  size_t p;
  int i;

  if (count < 1 || count > 16) die("a FON must contain between 1 and 16 strikes");
  font_offsets = (size_t *)calloc((size_t)count, sizeof(size_t));
  if (!font_offsets) die("out of memory");

  resize_zero(&fon, resident_names + resident_length);
  align_buffer(&fon, 1u << RESOURCE_SHIFT);
  fontdir_offset = fon.len;
  append(&fon, fontdir.data, fontdir.len);
  align_buffer(&fon, 1u << RESOURCE_SHIFT);
  for (i = 0; i < count; i++) {
    font_offsets[i] = fon.len;
    append(&fon, strikes[i].bytes.data, strikes[i].bytes.len);
    align_buffer(&fon, 1u << RESOURCE_SHIFT);
  }
  if ((fontdir_offset >> RESOURCE_SHIFT) > UINT16_MAX ||
      (((fontdir.len + 15) & ~(size_t)15) >> RESOURCE_SHIFT) > UINT16_MAX)
    die("FONTDIR exceeds the NE resource table's 16-bit range");
  for (i = 0; i < count; i++) {
    if ((font_offsets[i] >> RESOURCE_SHIFT) > UINT16_MAX ||
        (((strikes[i].bytes.len + 15) & ~(size_t)15) >> RESOURCE_SHIFT) > UINT16_MAX)
      die("font strike exceeds the NE resource table's 16-bit range");
  }

  /* Minimal DOS header. */
  put_u16(&fon, 0x00, 0x5a4d);
  put_u16(&fon, 0x02, (uint16_t)(fon.len & 511));
  put_u16(&fon, 0x04, (uint16_t)((fon.len + 511) / 512));
  put_u16(&fon, 0x08, 4);
  put_u16(&fon, 0x0a, 0);
  put_u16(&fon, 0x0c, 0xffff);
  put_u16(&fon, 0x18, 0x40);
  put_u32(&fon, 0x3c, NE_OFFSET);

  /* Resource-only Windows 3.x NE module header. */
  put_u16(&fon, NE_OFFSET + 0x00, 0x454e);
  put_u8(&fon, NE_OFFSET + 0x02, 5);
  put_u8(&fon, NE_OFFSET + 0x03, 1);
  put_u16(&fon, NE_OFFSET + 0x04,
          (uint16_t)(resident_names + resident_length - NE_OFFSET));
  put_u16(&fon, NE_OFFSET + 0x06, 0);
  put_u16(&fon, NE_OFFSET + 0x0c, 0x8300);
  put_u16(&fon, NE_OFFSET + 0x22, NE_SIZE);
  put_u16(&fon, NE_OFFSET + 0x24, NE_SIZE);
  put_u16(&fon, NE_OFFSET + 0x26, (uint16_t)(resident_names - NE_OFFSET));
  put_u16(&fon, NE_OFFSET + 0x28,
          (uint16_t)(resident_names + resident_length - NE_OFFSET));
  put_u16(&fon, NE_OFFSET + 0x2a,
          (uint16_t)(resident_names + resident_length - NE_OFFSET));
  put_u16(&fon, NE_OFFSET + 0x32, RESOURCE_SHIFT);
  put_u8(&fon, NE_OFFSET + 0x36, 2); /* Windows */
  put_u16(&fon, NE_OFFSET + 0x3e, 0x0300);

  /* Numeric RT_FONTDIR and RT_FONT resource table. */
  p = resource_table;
  put_u16(&fon, p, RESOURCE_SHIFT);
  p += 2;
  put_u16(&fon, p, 0x8007);
  put_u16(&fon, p + 2, 1);
  p += 8;
  put_u16(&fon, p, (uint16_t)(fontdir_offset >> RESOURCE_SHIFT));
  put_u16(&fon, p + 2,
          (uint16_t)(((fontdir.len + 15) & ~(size_t)15) >> RESOURCE_SHIFT));
  put_u16(&fon, p + 4, 0x0c50);
  put_u16(&fon, p + 6, 0x8001);
  p += 12;
  put_u16(&fon, p, 0x8008);
  put_u16(&fon, p + 2, (uint16_t)count);
  p += 8;
  for (i = 0; i < count; i++) {
    put_u16(&fon, p, (uint16_t)(font_offsets[i] >> RESOURCE_SHIFT));
    put_u16(&fon, p + 2,
            (uint16_t)(((strikes[i].bytes.len + 15) & ~(size_t)15) >> RESOURCE_SHIFT));
    put_u16(&fon, p + 4, 0x1c30);
    put_u16(&fon, p + 6, (uint16_t)(0x8000 | (i + 1)));
    p += 12;
  }
  put_u16(&fon, p, 0);

  /* Resident module-name table. */
  if (strlen(face_name) > 255) die("face name is too long");
  put_u8(&fon, resident_names, (uint8_t)strlen(face_name));
  memcpy(fon.data + resident_names + 1, face_name, strlen(face_name));
  put_u16(&fon, resident_names + 1 + strlen(face_name), 0);
  put_u8(&fon, resident_names + resident_length - 1, 0);

  free(font_offsets);
  free(fontdir.data);
  return fon;
}

static int parse_height(const char *text) {
  char *end = NULL;
  long value;
  errno = 0;
  value = strtol(text, &end, 10);
  if (errno || !end || *end || value < 4 || value > 128)
    die("pixel heights must be integers from 4 through 128");
  return (int)value;
}

int main(int argc, char **argv) {
  static const int defaults[] = {11, 12, 16, 24, 32, 48, 64};
  static const char default_copyright[] =
    "W95FA bitmap derivative; SIL Open Font License 1.1";
  const char *input;
  const char *output;
  const char *face_name;
  const char *copyright = default_copyright;
  const char *hinting_name = "auto";
  /* dfWeight. A bold strike that reported 400 would be indistinguishable
     from its regular sibling to any face-selection code reading the FNT. */
  int weight = 400;
  HintingMode hinting = HINTING_AUTO;
  RasterSizing raster_sizing = RASTER_FIT_CELL;
  CharacterSet charset = CHARSET_ANSI;
  int force_fixed = 0;
  int bitmap_only = 0;
  int first_height = 4;
  int *heights;
  int count;
  FT_Library library;
  FT_Face face;
  Strike *strikes;
  Buffer fon;
  FILE *file;
  int i;
  FT_Error error;

  if (argc < 4) {
    fprintf(stderr,
      "usage: %s INPUT.otf OUTPUT.fon FACE [--fixed] [--copyright=TEXT]"
      " [--bitmap-only]"
      " [--charset=ansi|oem]"
      " [--hinting=auto|auto-normal|auto-light|native|none]"
      " [--raster=fit|exact]"
      " [--weight=N]"
      " [PIXEL_HEIGHT ...]\n"
      "default heights: 11 12 16 24 32 48 64\n", argv[0]);
    return 2;
  }
  input = argv[1];
  output = argv[2];
  face_name = argv[3];
  if (!*face_name || strlen(face_name) >= 32)
    die("face name must contain 1 through 31 bytes");

  while (first_height < argc && strncmp(argv[first_height], "--", 2) == 0) {
    if (strcmp(argv[first_height], "--fixed") == 0) {
      force_fixed = 1;
    } else if (strcmp(argv[first_height], "--bitmap-only") == 0) {
      bitmap_only = 1;
    } else if (strcmp(argv[first_height], "--charset=ansi") == 0) {
      charset = CHARSET_ANSI;
    } else if (strcmp(argv[first_height], "--charset=oem") == 0) {
      charset = CHARSET_OEM;
    } else if (strncmp(argv[first_height], "--weight=", 9) == 0) {
      weight = atoi(argv[first_height] + 9);
      if (weight < 1 || weight > 1000)
        die("--weight must be between 1 and 1000");
    } else if (strncmp(argv[first_height], "--copyright=", 12) == 0) {
      copyright = argv[first_height] + 12;
      if (!*copyright) die("copyright text must not be empty");
    } else if (strncmp(argv[first_height], "--hinting=", 10) == 0) {
      hinting_name = argv[first_height] + 10;
      if (strcmp(hinting_name, "auto") == 0) {
        hinting = HINTING_AUTO;
      } else if (strcmp(hinting_name, "auto-normal") == 0) {
        hinting = HINTING_AUTO_NORMAL;
      } else if (strcmp(hinting_name, "auto-light") == 0) {
        hinting = HINTING_AUTO_LIGHT;
      } else if (strcmp(hinting_name, "native") == 0) {
        hinting = HINTING_NATIVE;
      } else if (strcmp(hinting_name, "none") == 0) {
        hinting = HINTING_NONE;
      } else {
        die("hinting mode must be auto, auto-normal, auto-light, native, or none");
      }
    } else if (strcmp(argv[first_height], "--raster=fit") == 0) {
      raster_sizing = RASTER_FIT_CELL;
    } else if (strcmp(argv[first_height], "--raster=exact") == 0) {
      raster_sizing = RASTER_EXACT_SIZE;
    } else {
      die("unknown option");
    }
    first_height++;
  }

  if (argc > first_height) {
    count = argc - first_height;
    heights = (int *)calloc((size_t)count, sizeof(int));
    if (!heights) die("out of memory");
    for (i = 0; i < count; i++) heights[i] = parse_height(argv[i + first_height]);
  } else {
    count = (int)(sizeof(defaults) / sizeof(defaults[0]));
    heights = (int *)calloc((size_t)count, sizeof(int));
    if (!heights) die("out of memory");
    for (i = 0; i < count; i++) heights[i] = defaults[i];
  }
  if (count > 16) die("at most 16 strikes can be emitted");

  error = FT_Init_FreeType(&library);
  if (error) die_ft("FT_Init_FreeType", error);
  error = FT_New_Face(library, input, 0, &face);
  if (error) die_ft("FT_New_Face", error);
  error = FT_Select_Charmap(face, FT_ENCODING_UNICODE);
  if (error) die_ft("FT_Select_Charmap", error);

  strikes = (Strike *)calloc((size_t)count, sizeof(Strike));
  if (!strikes) die("out of memory");
  for (i = 0; i < count; i++) {
    strikes[i] = make_strike(face, heights[i], face_name, force_fixed, copyright,
                             hinting, raster_sizing, bitmap_only, charset,
                             weight);
    fprintf(stderr, "strike request=%dpx cell=%dpx em=%dpx ascent=%d avg=%d max=%d hinting=%s bytes=%zu\n",
      heights[i], strikes[i].height, strikes[i].raster_height, strikes[i].ascent,
      strikes[i].average_width, strikes[i].maximum_width, hinting_name,
      strikes[i].bytes.len);
  }
  fon = make_fon(strikes, count, face_name);

  file = fopen(output, "wb");
  if (!file) {
    fprintf(stderr, "gen-bitmap-fon: cannot open %s: %s\n", output, strerror(errno));
    return 1;
  }
  if (fwrite(fon.data, 1, fon.len, file) != fon.len || fclose(file) != 0) {
    fprintf(stderr, "gen-bitmap-fon: cannot write %s: %s\n", output, strerror(errno));
    return 1;
  }
  fprintf(stderr, "wrote %s (%zu bytes, %d strikes, face %s)\n",
          output, fon.len, count, face_name);

  for (i = 0; i < count; i++) free(strikes[i].bytes.data);
  free(strikes);
  free(heights);
  free(fon.data);
  FT_Done_Face(face);
  FT_Done_FreeType(library);
  return 0;
}
