#!/usr/bin/env node
// gen_dispatch.js — Generate 09b2-dispatch-table.generated.wat
//
// Reads api_table.json and generates the $dispatch_api_table function
// containing just the br_table that calls $handle_{Name} functions.
// The hand-written $win32_dispatch wrapper lives in 09b-dispatch.wat.

const fs = require('fs');
const path = require('path');

const apiTable = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'src', 'api_table.json'), 'utf8'));
const outPath = path.join(__dirname, '..', 'src', '09b2-dispatch-table.generated.wat');

// Clean up old generated file if it exists
const oldPath = path.join(__dirname, '..', 'src', '09b-dispatch.generated.wat');
if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);

const N = apiTable.length;
const out = [];

out.push('  ;; ============================================================');
out.push('  ;; API BR_TABLE DISPATCH — GENERATED, do not edit');
out.push('  ;; Generated by tools/gen_dispatch.js from api_table.json');
out.push('  ;; Hand-written dispatch wrapper is in 09b-dispatch.wat');
out.push('  ;; ============================================================');
out.push('  (func $dispatch_api_table (param $api_id i32) (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)');
out.push('');
out.push('    ;; === O(1) br_table dispatch ===');

// Block declarations: fallback outermost, then N-1 down to 0 innermost
out.push('    (block $fallback');
for (let id = N - 1; id >= 0; id--) {
  out.push(`    (block $api_${id}`);
}

// br_table line
let br = '      (br_table';
for (let id = 0; id < N; id++) br += ` $api_${id}`;
br += ' $fallback (local.get $api_id))';
out.push(br);

// Handler call slots
for (let id = 0; id < N; id++) {
  const api = apiTable[id];
  out.push(`    ) ;; ${id}: ${api.name}`);
  out.push(`      (call $handle_${api.name} (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3) (local.get $arg4) (local.get $name_ptr))`);
  out.push('      (return)');
}

// Fallback
out.push('    ) ;; fallback');
out.push('    (call $handle_fallback (local.get $name_ptr) (local.get $api_id))');
out.push('  )');

// ── Validate paren balance ──────────────────────────────────────────
const result = out.join('\n') + '\n';
let depth = 0;
for (let ci = 0; ci < result.length; ci++) {
  if (result[ci] === '"') { while (ci + 1 < result.length && result[++ci] !== '"') { if (result[ci] === '\\') ci++; } continue; }
  if (result[ci] === ';' && result[ci + 1] === ';') { while (ci < result.length && result[ci] !== '\n') ci++; continue; }
  if (result[ci] === '(') depth++;
  if (result[ci] === ')') depth--;
}
if (depth !== 0) {
  console.error(`WARNING: paren imbalance, final depth = ${depth}`);
}

fs.writeFileSync(outPath, result);
console.error(`Written ${outPath} (${N} APIs)`);
