#!/usr/bin/env node
// gen_dispatch.js — Generate 09b2-dispatch-table.generated.wat
//
// Reads api_table.json and generates the $dispatch_api_table function
// containing just the br_table that calls $handle_{Name} functions.
// The hand-written $win32_dispatch wrapper lives in 09b-dispatch.wat.

const fs = require('fs');
const path = require('path');

const apiTable = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'src', 'api_table.json'), 'utf8'));
const outPath = path.join(__dirname, '..', 'src', '09b2-dispatch-table.generated.wat');

// Clean up old generated file if it exists
const oldPath = path.join(__dirname, '..', 'src', '09b-dispatch.generated.wat');
if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);

const N = apiTable.length;
const out = [];

out.push('  ;; ============================================================');
out.push('  ;; API BR_TABLE DISPATCH — GENERATED, do not edit');
out.push('  ;; Generated by tools/gen_dispatch.js from api_table.json');
out.push('  ;; Hand-written dispatch wrapper is in 09b-dispatch.wat');
out.push('  ;; ============================================================');
out.push('  (func $dispatch_api_table (param $api_id i32) (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)');
out.push('');
out.push('    ;; === O(1) br_table dispatch ===');

// Block declarations: fallback outermost, then N-1 down to 0 innermost
out.push('    (block $fallback');
for (let id = N - 1; id >= 0; id--) {
  out.push(`    (block $api_${id}`);
}

// br_table line
let br = '      (br_table';
for (let id = 0; id < N; id++) br += ` $api_${id}`;
br += ' $fallback (local.get $api_id))';
out.push(br);

// Handler call slots
for (let id = 0; id < N; id++) {
  const api = apiTable[id];
  out.push(`    ) ;; ${id}: ${api.name}`);
  out.push(`      (call $handle_${api.name} (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3) (local.get $arg4) (local.get $name_ptr))`);
  out.push('      (return)');
}

// Fallback
out.push('    ) ;; fallback');
out.push('    (call $handle_fallback (local.get $name_ptr) (local.get $api_id))');
out.push('  )');

// ── Generate $init_dx_com_thunks from api_table.json ────────────────
// COM interfaces: prefix → WAT global name.  Order matters (parent before child).
const comInterfaces = [
  { prefix: 'IDirectDraw',          global: 'DX_VTBL_DDRAW' },
  { prefix: 'IDirectDraw2',         global: 'DX_VTBL_DDRAW2',   extends: 'IDirectDraw' },
  { prefix: 'IDirectDrawSurface',   global: 'DX_VTBL_DDSURF' },
  { prefix: 'IDirectDrawSurface2',  global: 'DX_VTBL_DDSURF2', extends: 'IDirectDrawSurface' },
  { prefix: 'IDirectDrawPalette',   global: 'DX_VTBL_DDPAL' },
  { prefix: 'IDirectDrawClipper',  global: 'DX_VTBL_DDCLIP' },
  { prefix: 'IDirectSound',         global: 'DX_VTBL_DSOUND' },
  { prefix: 'IDirectSoundBuffer',   global: 'DX_VTBL_DSBUF' },
  { prefix: 'IDirectInput',         global: 'DX_VTBL_DINPUT' },
  { prefix: 'IDirectInputDevice',   global: 'DX_VTBL_DIDEV' },
  { prefix: 'IDirect3D',            global: 'DX_VTBL_D3D' },
  { prefix: 'IDirect3D3',           global: 'DX_VTBL_D3D3' },
  { prefix: 'IDirectDrawFactory',   global: 'DX_VTBL_DDFACTORY' },
  { prefix: 'IDirect3DDevice3',     global: 'DX_VTBL_D3DDEV3' },
  { prefix: 'IDirect3DViewport3',   global: 'DX_VTBL_D3DVP3' },
  { prefix: 'IDirect3DLight',       global: 'DX_VTBL_D3DLIGHT' },
  { prefix: 'IDirect3DMaterial3',   global: 'DX_VTBL_D3DMAT3' },
];

// Append Direct3D Immediate Mode interfaces from shared spec.
const { vtableGlobals: d3dimVtables } = require('./d3dim-methods');
for (const v of d3dimVtables) comInterfaces.push(v);

// Build a map of prefix → { startId, count } from the api_table
const byName = new Map(apiTable.map(a => [a.name, a]));
const ifaceInfo = new Map();
for (const iface of comInterfaces) {
  // Find all APIs matching this interface (prefix + "_")
  const methods = apiTable.filter(a => a.name.startsWith(iface.prefix + '_'));
  if (methods.length === 0) {
    console.error(`WARNING: no methods found for ${iface.prefix}`);
    continue;
  }
  methods.sort((a, b) => a.id - b.id);
  const startId = methods[0].id;
  // Verify contiguous
  for (let i = 1; i < methods.length; i++) {
    if (methods[i].id !== startId + i) {
      console.error(`WARNING: ${iface.prefix} IDs not contiguous: expected ${startId + i}, got ${methods[i].id} (${methods[i].name})`);
    }
  }
  ifaceInfo.set(iface.prefix, { startId, count: methods.length });
}

out.push('');
out.push('  ;; ============================================================');
out.push('  ;; COM VTABLE INIT — GENERATED, do not edit');
out.push('  ;; Generated by tools/gen_dispatch.js from api_table.json');
out.push('  ;; ============================================================');
out.push('  (func $init_dx_com_thunks (export "init_dx_com_thunks")');

for (const iface of comInterfaces) {
  const info = ifaceInfo.get(iface.prefix);
  if (!info) continue;
  if (iface.extends) {
    // Extended interface: copy parent vtable + append extra methods
    const parentInfo = ifaceInfo.get(iface.extends);
    if (!parentInfo) { console.error(`WARNING: parent ${iface.extends} not found`); continue; }
    const totalCount = parentInfo.count + info.count;
    out.push(`    ;; ${iface.prefix}: extends ${iface.extends} (${parentInfo.count}) + ${info.count} extra = ${totalCount} total, extra at api_id ${info.startId}`);
    out.push(`    (global.set $${iface.global} (call $extend_com_vtable`);
    out.push(`      (global.get $${ifaceInfo.get(iface.extends) ? comInterfaces.find(c => c.prefix === iface.extends).global : '??'}) (i32.const ${parentInfo.count}) (i32.const ${info.startId}) (i32.const ${totalCount})))`);
  } else {
    out.push(`    ;; ${iface.prefix}: ${info.count} methods starting at api_id ${info.startId}`);
    out.push(`    (global.set $${iface.global} (call $init_com_vtable (i32.const ${info.startId}) (i32.const ${info.count})))`);
  }
}

out.push('  )');

// ── Validate paren balance ──────────────────────────────────────────
const result = out.join('\n') + '\n';
let depth = 0;
for (let ci = 0; ci < result.length; ci++) {
  if (result[ci] === '"') { while (ci + 1 < result.length && result[++ci] !== '"') { if (result[ci] === '\\') ci++; } continue; }
  if (result[ci] === ';' && result[ci + 1] === ';') { while (ci < result.length && result[ci] !== '\n') ci++; continue; }
  if (result[ci] === '(') depth++;
  if (result[ci] === ')') depth--;
}
if (depth !== 0) {
  console.error(`WARNING: paren imbalance, final depth = ${depth}`);
}

fs.writeFileSync(outPath, result);
console.error(`Written ${outPath} (${N} APIs)`);
