#!/usr/bin/env node
// gen_d3d9_stubs.js — One-time generator for src/09ad-handlers-d3d9.wat
//
// Reads tools/d3d9-methods.js and writes one COM handler per method of
// IDirect3D9 / IDirect3DDevice9 / IDirect3DTexture9 / IDirect3DSurface9.
//
// USAGE: node tools/gen_d3d9_stubs.js
//
// After this initial run the generated WAT is the hand-edited source of
// truth — the methods the guest actually drives get real bodies written by
// hand on top of the existing $d3dim_* device state and rasterizer.
// DO NOT re-run afterwards: it will clobber those edits.
//
// Methods with no `ret`/`body` tag in the spec emit $crash_unimplemented
// rather than a silent return 0, so an app reaching an unwritten slot names
// itself instead of failing later with a NULL resource.

const fs = require('fs');
const path = require('path');
const { interfaces } = require('./d3d9-methods');

const out = [];
out.push('  ;; ============================================================');
out.push('  ;; DIRECT3D 9 HANDLERS — generated by tools/gen_d3d9_stubs.js');
out.push('  ;; IDirect3D9, IDirect3DDevice9, IDirect3DTexture9, IDirect3DSurface9.');
out.push('  ;; Vtable order is the spec in tools/d3d9-methods.js — do not reorder.');
out.push('  ;; ============================================================');
out.push('');

function popExpr(nargs) {
  // 4 bytes for return addr + 4 bytes per stdcall arg (incl. `this`).
  const n = 4 + nargs * 4;
  return `(global.set $esp (i32.add (global.get $esp) (i32.const ${n})))`;
}

function emit(name, nargs, body) {
  const sig = `(func $handle_${name} (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)`;
  out.push('  ;; ' + name + ' — ' + nargs + ' args (incl. this)');
  out.push('  ' + sig);
  for (const line of body) out.push('    ' + line);
  out.push('    ' + popExpr(nargs) + ')');
  out.push('');
}

function bodyFor(method) {
  const tag = method.body || method.ret || 'CRASH';
  switch (tag) {
    case 'OK':
      return ['(global.set $eax (i32.const 0))'];
    case 'ADDREF':
      return [
        '(local $entry i32) (local $rc i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))',
        '(i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))',
        '(global.set $eax (local.get $rc))',
      ];
    case 'RELEASE':
      return [
        '(local $entry i32) (local $rc i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))',
        '(if (i32.le_s (local.get $rc) (i32.const 0))',
        '  (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))',
        '  (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))',
      ];
    case 'CRASH':
    default:
      return ['(call $crash_unimplemented (local.get $name_ptr))'];
  }
}

for (const iface of interfaces) {
  out.push(`  ;; ── ${iface.prefix} — ${iface.methods.length} methods ─────────────`);
  for (const m of iface.methods) {
    emit(iface.prefix + '_' + m.name, m.nargs, bodyFor(m));
  }
  out.push('');
}

const watPath = path.join(__dirname, '..', 'src', '09ad-handlers-d3d9.wat');
if (fs.existsSync(watPath) && !process.argv.includes('--force')) {
  console.error(`${watPath} already exists — refusing to clobber hand edits. Pass --force if you really mean it.`);
  process.exit(1);
}
fs.writeFileSync(watPath, out.join('\n'));
console.log(`Wrote ${watPath} (${out.length} lines)`);
