#!/usr/bin/env node
// gen_dispatch.js — Generate 09b2-dispatch-table.generated.wat
//
// Reads api_table.json and generates the $dispatch_api_table function
// containing just the br_table that calls $handle_{Name} functions.
// The hand-written $win32_dispatch wrapper lives in 09b-dispatch.wat.

const fs = require('fs');
const path = require('path');

const apiTable = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'src', 'api_table.json'), 'utf8'));
const outPath = path.join(__dirname, '..', 'src', '09b2-dispatch-table.generated.wat');

// --check: generate in memory and compare with the file on disk. Used as a build
// gate so a stale generated table fails the build instead of dispatching to the
// wrong handler at runtime.
const CHECK_ONLY = process.argv.includes('--check');

// A COM vtable whose api_ids are not contiguous produces a table that dispatches
// method N to some unrelated API. This used to print WARNING and generate the
// broken table anyway; it is now fatal.
const errors = [];
function fatal(msg) { errors.push(msg); console.error(`ERROR: ${msg}`); }

// Clean up old generated file if it exists
const oldPath = path.join(__dirname, '..', 'src', '09b-dispatch.generated.wat');
if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);

const N = apiTable.length;
const out = [];
const PAGE_SIZE = 256;

function handlerCall(api) {
  const daSlot = api.name.match(/^IDirectAnimationDA(View|Statics|Behavior)_DirectSlot(\d+)$/);
  if (daSlot) {
    const iface = daSlot[1];
    const slot = parseInt(daSlot[2], 10);
    return `      (call $handle_IDirectAnimationDA${iface}_DirectSlot (i32.const ${slot}) (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3) (local.get $arg4) (local.get $name_ptr))`;
  }
  return `      (call $handle_${api.name} (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3) (local.get $arg4) (local.get $name_ptr))`;
}

out.push('  ;; ============================================================');
out.push('  ;; API BR_TABLE DISPATCH — GENERATED, do not edit');
out.push('  ;; Generated by tools/gen_dispatch.js from api_table.json');
out.push('  ;; Hand-written dispatch wrapper is in 09b-dispatch.wat');
out.push('  ;; ============================================================');
out.push('  (func $dispatch_api_table (param $api_id i32) (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)');
out.push('');
out.push('    ;; === Paged br_table dispatch ===');
for (let base = 0, page = 0; base < N; base += PAGE_SIZE, page++) {
  const end = Math.min(base + PAGE_SIZE, N);
  out.push(`    (if (i32.lt_u (local.get $api_id) (i32.const ${end}))`);
  out.push('      (then');
  out.push(`        (call $dispatch_api_table_page_${page} (i32.sub (local.get $api_id) (i32.const ${base})) (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3) (local.get $arg4) (local.get $name_ptr))`);
  out.push('        (return)))');
}
out.push('    (call $handle_fallback (local.get $name_ptr) (local.get $api_id))');
out.push('  )');

for (let base = 0, page = 0; base < N; base += PAGE_SIZE, page++) {
  const end = Math.min(base + PAGE_SIZE, N);
  const count = end - base;
  out.push('');
  out.push(`  (func $dispatch_api_table_page_${page} (param $api_id i32) (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)`);
  out.push(`    ;; api ids ${base}..${end - 1}`);
  out.push('    (block $fallback');
  for (let slot = count - 1; slot >= 0; slot--) {
    out.push(`    (block $api_${slot}`);
  }
  let br = '      (br_table';
  for (let slot = 0; slot < count; slot++) br += ` $api_${slot}`;
  br += ' $fallback (local.get $api_id))';
  out.push(br);
  for (let slot = 0; slot < count; slot++) {
    const id = base + slot;
    const api = apiTable[id];
    out.push(`    ) ;; ${id}: ${api.name}`);
    out.push(handlerCall(api));
    out.push('      (return)');
  }
  out.push('    ) ;; fallback');
  out.push(`    (call $handle_fallback (local.get $name_ptr) (i32.add (local.get $api_id) (i32.const ${base})))`);
  out.push('  )');
}

// ── Generate $init_dx_com_thunks from api_table.json ────────────────
// COM interfaces: prefix → WAT global name.  Order matters (parent before child).
const comInterfaces = [
  { prefix: 'IDirectDraw',          global: 'DX_VTBL_DDRAW' },
  { prefix: 'IDirectDraw2',         global: 'DX_VTBL_DDRAW2',   extends: 'IDirectDraw' },
  { prefix: 'IDirectDrawSurface',   global: 'DX_VTBL_DDSURF' },
  { prefix: 'IDirectDrawSurface2',  global: 'DX_VTBL_DDSURF2', extends: 'IDirectDrawSurface' },
  { prefix: 'IDirectDrawPalette',   global: 'DX_VTBL_DDPAL' },
  { prefix: 'IDirectDrawClipper',  global: 'DX_VTBL_DDCLIP' },
  { prefix: 'IDirectSound',         global: 'DX_VTBL_DSOUND' },
  { prefix: 'IDirectSoundBuffer',   global: 'DX_VTBL_DSBUF' },
  { prefix: 'IDirectInput',         global: 'DX_VTBL_DINPUT' },
  { prefix: 'IDirectInputDevice',   global: 'DX_VTBL_DIDEV' },
  { prefix: 'IDirectPlay3',         global: 'DX_VTBL_DPLAY3' },
  { prefix: 'IDirectPlayLobby2',    global: 'DX_VTBL_DPLAYLOBBY2' },
  { prefix: 'IDirect3D',            global: 'DX_VTBL_D3D' },
  { prefix: 'IDirect3D3',           global: 'DX_VTBL_D3D3' },
  { prefix: 'IDirectDrawFactory',   global: 'DX_VTBL_DDFACTORY' },
  { prefix: 'IDirectAnimationDAView', global: 'DX_VTBL_DA_VIEW' },
  { prefix: 'IDirectAnimationDAStatics', global: 'DX_VTBL_DA_STATICS' },
  { prefix: 'IDirectAnimationDABehavior', global: 'DX_VTBL_DA_BEHAVIOR' },
  { prefix: 'IMalloc',              global: 'DX_VTBL_IMALLOC' },
  { prefix: 'IRunningObjectTable',   global: 'DX_VTBL_OLE_ROT' },
  { prefix: 'IEnumMoniker',         global: 'DX_VTBL_OLE_ENUMMONIKER' },
  { prefix: 'IMoniker',             global: 'DX_VTBL_OLE_MONIKER' },
  { prefix: 'IBindCtx',             global: 'DX_VTBL_OLE_BINDCTX' },
  { prefix: 'IEnumString',          global: 'DX_VTBL_OLE_ENUMSTRING' },
  { prefix: 'ILockBytes',           global: 'DX_VTBL_OLE_LOCKBYTES' },
  { prefix: 'IStream',              global: 'DX_VTBL_OLE_STREAM' },
  { prefix: 'IStorage',             global: 'DX_VTBL_OLE_STORAGE' },
  { prefix: 'IDataObject',          global: 'DX_VTBL_OLE_DATAOBJECT' },
  { prefix: 'IEnumFORMATETC',       global: 'DX_VTBL_OLE_ENUMFORMATETC' },
  { prefix: 'IEnumSTATSTG',         global: 'DX_VTBL_OLE_ENUMSTATSTG' },
  { prefix: 'IOleObject',           global: 'DX_VTBL_OLE_OBJECT' },
  { prefix: 'IPersistStorage',      global: 'DX_VTBL_OLE_PERSISTSTORAGE' },
  { prefix: 'IOleCache',            global: 'DX_VTBL_OLE_CACHE' },
  { prefix: 'IViewObject',          global: 'DX_VTBL_OLE_VIEWOBJECT' },
  { prefix: 'IViewObject2',         global: 'DX_VTBL_OLE_VIEWOBJECT2', extends: 'IViewObject' },
  { prefix: 'IDirect3DDevice3',     global: 'DX_VTBL_D3DDEV3' },
  { prefix: 'IDirect3DViewport3',   global: 'DX_VTBL_D3DVP3' },
  { prefix: 'IDirect3DLight',       global: 'DX_VTBL_D3DLIGHT' },
  { prefix: 'IDirect3DMaterial3',   global: 'DX_VTBL_D3DMAT3' },
];

// Append Direct3D Immediate Mode interfaces from shared spec.
const { vtableGlobals: d3dimVtables } = require('./d3dim-methods');
for (const v of d3dimVtables) comInterfaces.push(v);

// OLE Automation font object (OleCreateFontIndirect). Kept last so its
// registry slot is appended rather than shifting every existing one.
comInterfaces.push({ prefix: 'IFont', global: 'DX_VTBL_OLE_FONT' });

// Build a map of prefix → { startId, count } from the api_table
const byName = new Map(apiTable.map(a => [a.name, a]));
const ifaceInfo = new Map();
for (const iface of comInterfaces) {
  // Find all APIs matching this interface (prefix + "_")
  const methods = apiTable.filter(a => a.name.startsWith(iface.prefix + '_'));
  if (methods.length === 0) {
    fatal(`no methods found for COM interface ${iface.prefix}`);
    continue;
  }
  methods.sort((a, b) => a.id - b.id);
  const startId = methods[0].id;
  // Verify contiguous
  for (let i = 1; i < methods.length; i++) {
    if (methods[i].id !== startId + i) {
      fatal(`${iface.prefix} api_ids not contiguous: expected ${startId + i}, got ${methods[i].id} (${methods[i].name}). ` +
        'COM vtable slots are computed as startId + slot, so this table would call the wrong method.');
    }
  }
  ifaceInfo.set(iface.prefix, { startId, count: methods.length });
}

out.push('');
out.push('  ;; ============================================================');
out.push('  ;; COM VTABLE INIT — GENERATED, do not edit');
out.push('  ;; Generated by tools/gen_dispatch.js from api_table.json');
out.push('  ;; ============================================================');
out.push('  (func $init_dx_com_thunks (export "init_dx_com_thunks")');

for (const iface of comInterfaces) {
  const info = ifaceInfo.get(iface.prefix);
  if (!info) continue;
  if (iface.extends) {
    // Extended interface: copy parent vtable + append extra methods
    const parentInfo = ifaceInfo.get(iface.extends);
    if (!parentInfo) { fatal(`COM interface ${iface.prefix} extends ${iface.extends}, which has no methods in api_table.json`); continue; }
    const totalCount = parentInfo.count + info.count;
    out.push(`    ;; ${iface.prefix}: extends ${iface.extends} (${parentInfo.count}) + ${info.count} extra = ${totalCount} total, extra at api_id ${info.startId}`);
    out.push(`    (global.set $${iface.global} (call $extend_com_vtable`);
    out.push(`      (global.get $${ifaceInfo.get(iface.extends) ? comInterfaces.find(c => c.prefix === iface.extends).global : '??'}) (i32.const ${parentInfo.count}) (i32.const ${info.startId}) (i32.const ${totalCount})))`);
  } else {
    out.push(`    ;; ${iface.prefix}: ${info.count} methods starting at api_id ${info.startId}`);
    out.push(`    (global.set $${iface.global} (call $init_com_vtable (i32.const ${info.startId}) (i32.const ${info.count})))`);
  }
}

out.push('  )');

// ── Validate paren balance ──────────────────────────────────────────
const result = out.join('\n') + '\n';
let depth = 0;
for (let ci = 0; ci < result.length; ci++) {
  if (result[ci] === '"') { while (ci + 1 < result.length && result[++ci] !== '"') { if (result[ci] === '\\') ci++; } continue; }
  if (result[ci] === ';' && result[ci + 1] === ';') { while (ci < result.length && result[ci] !== '\n') ci++; continue; }
  if (result[ci] === '(') depth++;
  if (result[ci] === ')') depth--;
}
if (depth !== 0) {
  fatal(`paren imbalance in generated output, final depth = ${depth}`);
}

if (errors.length) {
  console.error(`${errors.length} fatal problem(s); ${CHECK_ONLY ? 'not checking' : 'not writing'} ${path.relative(process.cwd(), outPath)}.`);
  process.exit(1);
}

if (CHECK_ONLY) {
  const onDisk = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
  if (onDisk !== result) {
    console.error(`ERROR: ${path.relative(process.cwd(), outPath)} is stale — it does not match what api_table.json generates.`);
    console.error('       Run: node tools/gen_dispatch.js');
    process.exit(1);
  }
  console.log(`dispatch table OK: 09b2-dispatch-table.generated.wat matches api_table.json (${N} APIs).`);
} else {
  fs.writeFileSync(outPath, result);
  console.error(`Written ${outPath} (${N} APIs)`);
}
