#!/usr/bin/env node
// gen_d3dim_stubs.js — One-time generator for src/09aa-handlers-d3dim.wat
//
// Reads tools/d3dim-methods.js and writes ~211 stub COM handlers for the
// missing Direct3D Immediate Mode interfaces (D3D2/D3D7, Device v1/v2/v7,
// Viewport v1/v2, Material v1/v2, ExecuteBuffer, VertexBuffer{,7}, Texture{,2}).
//
// USAGE: node tools/gen_d3dim_stubs.js
//
// After this initial run, the generated WAT becomes the hand-edited source of
// truth. Stubs marked `body:` route to richer cores added in Phase 1+ (matrix,
// rasterizer, etc.). DO NOT re-run after manual edits — it will clobber them.

const fs = require('fs');
const path = require('path');
const { interfaces } = require('./d3dim-methods');

const out = [];
out.push('  ;; ============================================================');
out.push('  ;; DIRECT3D IMMEDIATE MODE HANDLERS — generated by tools/gen_d3dim_stubs.js');
out.push('  ;; Initial pass: stubs for ~211 IM methods (D3D v2/v7, Device v1/v2/v7,');
out.push('  ;; Viewport v1/v2, Material v1/v2, ExecuteBuffer, VertexBuffer{,7},');
out.push('  ;; Texture{,2}). Phase 1+ replaces stub bodies with real implementations.');
out.push('  ;; ============================================================');
out.push('');

function popExpr(nargs) {
  // 4 bytes for return addr + 4 bytes per stdcall arg (incl. `this`).
  const n = 4 + nargs * 4;
  return `(global.set $esp (i32.add (global.get $esp) (i32.const ${n})))`;
}

function emit(name, nargs, body) {
  const sig = `(func $handle_${name} (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)`;
  out.push('  ;; ' + name + ' — ' + nargs + ' args (incl. this)');
  out.push('  ' + sig);
  for (const line of body) out.push('    ' + line);
  out.push('    ' + popExpr(nargs) + ')');
  out.push('');
}

// Family IDs passed to $d3dim_qi: 0 = no upgrade, 1 = D3D, 2 = Device,
// 3 = Viewport, 4 = Material, 5 = Texture, 6 = VertexBuffer.
const qiFamily = {
  IDirect3D2: 1, IDirect3D7: 1,
  IDirect3DDevice: 2, IDirect3DDevice2: 2, IDirect3DDevice7: 2,
  IDirect3DViewport: 3, IDirect3DViewport2: 3,
  IDirect3DMaterial: 4, IDirect3DMaterial2: 4,
  IDirect3DTexture: 5, IDirect3DTexture2: 5,
  IDirect3DVertexBuffer: 6, IDirect3DVertexBuffer7: 6,
  IDirect3DExecuteBuffer: 0,
};

function bodyFor(method, prefix) {
  const tag = method.body || method.ret || 'OK';
  const fullName = prefix + '_' + method.name;
  // Special-case QueryInterface across all interfaces.
  if (method.name === 'QueryInterface') {
    const fam = qiFamily[prefix] || 0;
    return [
      `(global.set $eax (call $d3dim_qi (i32.const ${fam}) (local.get $arg0) (local.get $arg1) (local.get $arg2)))`,
    ];
  }
  switch (tag) {
    case 'OK':
      return ['(global.set $eax (i32.const 0))'];
    case 'ADDREF':
      // Read DX entry, refcount++ at +4, return new count
      return [
        '(local $entry i32) (local $rc i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))',
        '(i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))',
        '(global.set $eax (local.get $rc))',
      ];
    case 'RELEASE':
      return [
        '(local $entry i32) (local $rc i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))',
        '(if (i32.le_s (local.get $rc) (i32.const 0))',
        '  (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))',
        '  (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))',
      ];
    case 'CREATE_LIGHT':
      // arg1 = lplpDirect3DLight, arg2 = pUnkOuter — mirror IDirect3D3_CreateLight
      return [
        '(local $obj i32)',
        '(local.set $obj (call $dx_create_com_obj (i32.const 24) (global.get $DX_VTBL_D3DLIGHT)))',
        '(if (i32.eqz (local.get $obj)) (then (global.set $eax (i32.const 0x80004005))',
        `  ${popExpr(method.nargs)} (return)))`,
        '(call $gs32 (local.get $arg1) (local.get $obj))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'CREATE_MATERIAL':
      return [
        '(local $obj i32)',
        '(local.set $obj (call $dx_create_com_obj (i32.const 25) (global.get $DX_VTBL_D3DMAT3)))',
        '(if (i32.eqz (local.get $obj)) (then (global.set $eax (i32.const 0x80004005))',
        `  ${popExpr(method.nargs)} (return)))`,
        '(call $gs32 (local.get $arg1) (local.get $obj))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'CREATE_VIEWPORT':
      return [
        '(local $obj i32)',
        '(local.set $obj (call $dx_create_com_obj (i32.const 23) (global.get $DX_VTBL_D3DVP3)))',
        '(if (i32.eqz (local.get $obj)) (then (global.set $eax (i32.const 0x80004005))',
        `  ${popExpr(method.nargs)} (return)))`,
        '(call $gs32 (local.get $arg1) (local.get $obj))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'CREATE_DEVICE2':
      // IDirect3D2::CreateDevice(this, refclsid, lpDDSurface, lplpD3DDevice) — 4 args
      // Forward to common core. We allocate as DX_VTBL_D3DDEV3 since QI handles upgrade.
      return [
        '(call $d3dim_create_device (local.get $arg0) (local.get $arg2) (local.get $arg3))',
      ];
    case 'CREATE_DEVICE7':
      // IDirect3D7::CreateDevice(this, refclsid, lpDDSurface, lplpD3DDevice) — 4 args
      return [
        '(call $d3dim_create_device (local.get $arg0) (local.get $arg2) (local.get $arg3))',
      ];
    case 'CREATE_VB7':
      // IDirect3D7::CreateVertexBuffer — same as v3
      return [
        '(local $obj i32)',
        '(local.set $obj (call $dx_create_com_obj (i32.const 22) (global.get $DX_VTBL_D3DVB7)))',
        '(if (i32.eqz (local.get $obj)) (then (global.set $eax (i32.const 0x80004005))',
        `  ${popExpr(method.nargs)} (return)))`,
        '(call $gs32 (local.get $arg2) (local.get $obj))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'CREATE_EXEC':
      // IDirect3DDevice::CreateExecuteBuffer(this, lpDesc, lplpExec, pUnkOuter)
      return [
        '(local $obj i32)',
        '(local.set $obj (call $dx_create_com_obj (i32.const 21) (global.get $DX_VTBL_D3DEXEC)))',
        '(if (i32.eqz (local.get $obj)) (then (global.set $eax (i32.const 0x80004005))',
        `  ${popExpr(method.nargs)} (return)))`,
        '(call $gs32 (local.get $arg2) (local.get $obj))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'BEGIN_SCENE':
      return [
        '(call $d3dim_begin_scene (local.get $arg0))',
      ];
    case 'END_SCENE':
      return [
        '(call $d3dim_end_scene (local.get $arg0))',
      ];
    case 'SET_XFORM':
      // Forward to the existing IDirect3DDevice3 handler core. We call the
      // d3dim-shared helper `$d3dim_set_transform(this, xtype, lpmat)`.
      return [
        '(call $d3dim_set_transform (local.get $arg0) (local.get $arg1) (local.get $arg2))',
      ];
    case 'SET_RS':
      return [
        '(call $d3dim_set_render_state (local.get $arg0) (local.get $arg1) (local.get $arg2))',
      ];
    case 'SET_LS':
      return [
        '(call $d3dim_set_light_state (local.get $arg0) (local.get $arg1) (local.get $arg2))',
      ];
    case 'SET_TEX':
      // IDirect3DDevice7::SetTexture(stage, tex) — store on state block.
      return [
        '(call $d3dim_set_texture (local.get $arg0) (local.get $arg1) (local.get $arg2))',
      ];
    case 'SET_TSS':
      return [
        '(call $d3dim_set_tss (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3))',
      ];
    case 'SET_VP_DEV':
      // IDirect3DDevice::SetCurrentViewport(this, lpDirect3DViewport) — store slot
      return [
        '(call $d3dim_set_current_viewport (local.get $arg0) (local.get $arg1))',
      ];
    case 'GET_VP_DEV':
      return [
        '(call $d3dim_get_current_viewport (local.get $arg0) (local.get $arg1))',
      ];
    case 'VP_GET':
      return [
        '(call $d3dim_viewport_get (local.get $arg0) (local.get $arg1))',
      ];
    case 'VP_SET':
      return [
        '(call $d3dim_viewport_set (local.get $arg0) (local.get $arg1))',
      ];
    case 'VP_CLEAR':
      // IDirect3DViewport::Clear(this, dwCount, lpRects, dwFlags) — 4 args
      return [
        '(call $d3dim_viewport_clear (local.get $arg0) (local.get $arg1) (local.get $arg2) (local.get $arg3))',
      ];
    case 'MAT_HANDLE':
      // GetHandle(lpDevice, lpHandle) — return slot index as handle
      return [
        '(local $entry i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(call $gs32 (local.get $arg2) (call $dx_slot_of (local.get $entry)))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'TEX_HANDLE':
      return [
        '(local $entry i32)',
        '(local.set $entry (call $dx_from_this (local.get $arg0)))',
        '(call $gs32 (local.get $arg2) (call $dx_slot_of (local.get $entry)))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'TEX_LOAD':
      // IDirect3DTexture2::Load(this, lpD3DTexture) — copy ref into dst slot.
      // Real impl arrives in Step 7; for now record the source slot at +12 of
      // the dst entry so SetTexture can find it.
      return [
        '(local $dst i32) (local $src i32)',
        '(local.set $dst (call $dx_from_this (local.get $arg0)))',
        '(if (local.get $arg1) (then',
        '  (local.set $src (call $dx_from_this (local.get $arg1)))',
        '  (i32.store (i32.add (local.get $dst) (i32.const 12)) (call $dx_slot_of (local.get $src)))))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'VB_LOCK':
      // IDirect3DVertexBuffer::Lock(this, dwFlags, lplpData, lpdwSize) — 4 args
      // Stub returns NULL data + 0 size; Phase 1 fills in real heap-backed buf.
      return [
        '(if (local.get $arg2) (then (call $gs32 (local.get $arg2) (i32.const 0))))',
        '(if (local.get $arg3) (then (call $gs32 (local.get $arg3) (i32.const 0))))',
        '(global.set $eax (i32.const 0))',
      ];
    case 'EXEC_LOCK':
      // IDirect3DExecuteBuffer::Lock(this, lpDesc) — 2 args. Caller provides
      // a D3DEXECUTEBUFFERDESC; we'd fill lpData. Stub for now.
      return [
        '(global.set $eax (i32.const 0))',
      ];
    case 'EXEC_SETDATA':
      return [
        '(global.set $eax (i32.const 0))',
      ];
    default:
      return ['(global.set $eax (i32.const 0))'];
  }
}

for (const iface of interfaces) {
  out.push(`  ;; ── ${iface.prefix} — ${iface.methods.length} methods ─────────────`);
  for (const m of iface.methods) {
    emit(iface.prefix + '_' + m.name, m.nargs, bodyFor(m, iface.prefix));
  }
  out.push('');
}

const watPath = path.join(__dirname, '..', 'src', '09aa-handlers-d3dim.wat');
fs.writeFileSync(watPath, out.join('\n'));
console.log(`Wrote ${watPath} (${out.length} lines)`);
