#!/usr/bin/env node
// region-alloc.js — can the allocator reproduce the map we already have?
//
// Stage A of docs/watx-region-safety-design.md §9 must not move a byte, and §4.1
// commits to exactly two mechanisms for that: declaration ORDER (first-fit above
// a floor, never backfilling) and explicit GAPS where the current map has a
// deliberate hole. This tool applies both to the real declaration set:
//
//   node tools/region-alloc.js --emit         # the allocated form of src/00-regions.wat
//   node tools/region-alloc.js --diff         # allocated base vs declared base, per region
//   node tools/region-alloc.js --list         # the resulting layout
//   node tools/region-alloc.js --shake=gap    # what a permuted layout looks like
//
// `--diff` is the gate the design names: it must be EMPTY before stage A can
// ship. It is honest about what that proves and what it does not. The gaps are
// derived from the current map, so an empty diff is partly true by construction;
// what it actually establishes is that the allocator — declaration order,
// alignment, first-fit, gap arithmetic, the memory bound — lands on a real
// 160-region map with no adjustment, and that the emitted allocated source is a
// legal module. The load-bearing proof is the one downstream of it: compile the
// tree with the emitted form substituted for src/00-regions.wat and check the
// canonical hashes (01daf6ccfbd115e3 / 0ee6414668129ac4) did not move.
//
// There is ONE allocator. This tool does not reimplement it — it emits source
// and asks the vendored compiler where the regions landed (`result.regions`), so
// a bug here cannot disagree with a build.
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DECLS = path.join(ROOT, 'src', '00-regions.wat');

// 512 MB — `(import "host" "memory" (memory 8192 8192 shared))` in
// src/01-header.wat. The allocator refuses anything that ends past the memory
// guaranteed at instantiation, and the map's top regions (VIRTUAL_BACKING_BASE
// at 0x08000000, THREAD_RPC at 0x1FF00000) are well above 128 MB, so the
// synthetic module has to declare the real size.
const MEMORY_PAGES = 8192;

// The floor. Below it live NULL_SENTINEL at 0xF0 and the decoder scratch, which
// $g2w's sink behaviour pins; nothing there may be allocated.
const ALLOC_FLOOR = 0x1000;

const hex = (n) => `0x${(n >>> 0).toString(16).toUpperCase().padStart(8, '0')}`;
const alignUp = (n, a) => Math.ceil(n / a) * a;

function arg(name, fallback = null) {
  const hit = process.argv.find(a => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return fallback;
  const eq = hit.indexOf('=');
  return eq < 0 ? true : hit.slice(eq + 1);
}

// A small dedicated reader, for the same reason tools/check-region-decls.js has
// one: this runs beside the build's gates, and reading the file with the
// compiler it is describing makes a failure recursive.
function readDeclarations() {
  const text = fs.readFileSync(DECLS, 'utf8');
  const lines = text.split(/\r?\n/);
  const decls = [];
  for (let i = 0; i < lines.length; i++) {
    const head = /^\s*\(region\.declare-fixed\s+(\$[A-Za-z0-9_]+)\b/.exec(lines[i]);
    if (!head) continue;
    let depth = 0, body = '', j = i;
    do {
      body += lines[j] + '\n';
      for (const ch of lines[j]) { if (ch === '(') depth++; else if (ch === ')') depth--; }
      j++;
    } while (depth > 0 && j < lines.length);
    const num = (name) => {
      const m = new RegExp(`\\(${name}\\s+([^)\\s]+)\\)`).exec(body);
      if (!m) return null;
      return /^0x/i.test(m[1]) ? Number.parseInt(m[1], 16) : Number.parseInt(m[1], 10);
    };
    const owner = (/\(owner\s+"([^"]*)"\)/.exec(body) || [])[1] || null;
    const base = num('base');
    const end = num('end');
    const size = num('size') !== null ? num('size') : (end !== null && base !== null ? end - base : null);
    decls.push({ name: head[1], base, size, align: num('align') || 4, owner, line: i + 1 });
    i = j - 1;
  }
  return decls;
}

// Declaration order is the allocator's input, so the emitted file keeps it and
// inserts a gap wherever the hand-placed map left a hole. Every gap carries a
// reason: "unknown, preserved" is an honest marker, a silent constant is not.
function emitAllocatedSource(decls) {
  const out = [];
  out.push(';; GENERATED by tools/region-alloc.js — the allocated form of src/00-regions.wat.');
  out.push(';; Declaration order + explicit gaps reproduce the hand-placed map exactly');
  out.push(';; (docs/watx-region-safety-design.md §4.1). Do not hand-edit; regenerate.');
  out.push('');
  out.push(`  (region.floor ${hex(ALLOC_FLOOR)})`);
  let cursor = ALLOC_FLOOR;
  let gaps = 0, gapBytes = 0;
  for (const d of decls) {
    const natural = alignUp(cursor, d.align);
    if (natural > d.base) {
      throw new Error(`region-alloc: ${d.name} at ${hex(d.base)} is BELOW where the cursor already ` +
        `reached (${hex(natural)}); the declaration order is not ascending and first-fit cannot ` +
        `reproduce it without backfilling`);
    }
    if (natural < d.base) {
      const size = d.base - cursor;
      out.push(`  (region.gap ${hex(size)} (reason "unknown, preserved — hole ahead of ${d.name} in the hand-placed map"))`);
      gaps++; gapBytes += size;
      cursor = d.base;
    }
    out.push(`  (region.declare ${d.name} (size ${hex(d.size)}) (align ${hex(d.align)})` +
      (d.owner ? `\n    (owner ${JSON.stringify(d.owner)})` : '') + ')');
    cursor = d.base + d.size;
  }
  return { text: out.join('\n') + '\n', gaps, gapBytes };
}

// Where the regions actually land, straight from the compiler.
function allocate(source, shake) {
  const { compile } = require(path.join(__dirname, 'watx.js'));
  const module = `(memory ${MEMORY_PAGES} ${MEMORY_PAGES})\n${source}\n` +
    `(func $noop (effects heap) (nop))\n(wasm-export "noop" $noop)\n`;
  const options = { mode: 'production', standardWat: true, runtimeBuiltins: false, tailCalls: true };
  if (shake) options.regionShake = shake;
  const r = compile(module, new Map(), options);
  if (!r.success) {
    throw new Error(`region-alloc: the emitted allocated form does not compile: ${r.error}`);
  }
  return r.regions;
}

// The load-bearing proof: build the WHOLE tree with the emitted allocated form
// substituted for src/00-regions.wat, in both canonical modes, and print the
// hashes. Nothing is written to src/ and nothing is written to build/ — the
// substitution happens in the in-memory VFS the closure compiles from, so this
// can run at any time without disturbing a tree somebody else is building.
function prove() {
  const crypto = require('crypto');
  const { watxSourceClosure, compileClosure } = require(path.join(__dirname, 'watx-closure.js'));
  const decls = readDeclarations();
  const emitted = emitAllocatedSource(decls);
  const closure = watxSourceClosure();
  // The declarations live inside the module's paren wrapper, so the substituted
  // text is the emitted body with the file's own (module-less) shape preserved.
  let replaced = 0;
  for (const key of [...closure.vfs.keys()]) {
    if (!/(^|\/)00-regions\.wat$/.test(key.replace(/^\.\//, ''))) continue;
    closure.vfs.set(key, emitted.text);
    replaced++;
  }
  if (!replaced) throw new Error('region-alloc --prove: 00-regions.wat is not in the source closure');
  // The comparison is against THIS tree's own declare-fixed build, not against a
  // hash written down last week: src/ moves under other work all day, and a
  // stale constant would turn "somebody else edited a handler" into "the
  // allocator is broken". The historical canonical pair is still printed, so a
  // tree that happens to be at that commit says so.
  const pinned = watxSourceClosure();
  const hash = (buf) => require('crypto').createHash('sha256').update(buf).digest('hex').slice(0, 16);
  const CANONICAL = { tail: '01daf6ccfbd115e3', compat: '0ee6414668129ac4' };
  let ok = true;
  for (const [label, tailCalls] of [['tail', true], ['compat', false]]) {
    const a = compileClosure(closure, { tailCalls });
    if (!a.success) throw new Error(`region-alloc --prove: allocated ${label} build failed: ${a.error}`);
    const p = compileClosure(pinned, { tailCalls });
    if (!p.success) throw new Error(`region-alloc --prove: declare-fixed ${label} build failed: ${p.error}`);
    const ab = Buffer.from(a.wasmBinary), pb = Buffer.from(p.wasmBinary);
    const same = ab.equals(pb);
    if (!same) ok = false;
    console.log(`region-alloc --prove: ${label.padEnd(6)} allocated ${ab.length} B ${hash(ab)}  ` +
      `declare-fixed ${pb.length} B ${hash(pb)}  ${same ? 'IDENTICAL' : 'DIFFER'}` +
      (hash(pb) === CANONICAL[label] ? '  (tree is at the recorded canonical bytes)' : ''));
  }
  console.log(ok
    ? `region-alloc --prove: the ALLOCATOR reproduces this tree's map exactly ` +
      `(160 regions allocated, ${emitted.gaps} gaps)`
    : 'region-alloc --prove: the allocated map does NOT reproduce this tree\'s bytes');
  process.exit(ok ? 0 : 1);
}

function main() {
  if (arg('prove')) return prove();
  const decls = readDeclarations();
  const emitted = emitAllocatedSource(decls);

  const emitTarget = arg('emit');
  if (emitTarget) {
    if (emitTarget === true) process.stdout.write(emitted.text);
    else fs.writeFileSync(path.resolve(emitTarget), emitted.text);
  }

  const shake = arg('shake');
  const layout = allocate(emitted.text, shake === true ? 'gap' : shake);
  const placed = new Map(layout.regions.map(r => [r.name, r]));

  if (arg('list')) {
    for (const r of layout.regions) {
      console.log(`${hex(r.base)} +${String(r.size).padStart(9)}  ${r.name}`);
    }
  }

  const diffs = [];
  for (const d of decls) {
    const got = placed.get(d.name);
    if (!got) { diffs.push(`${d.name}: not placed at all`); continue; }
    if (got.base !== d.base) {
      diffs.push(`${d.name}: declared ${hex(d.base)}, allocated ${hex(got.base)} ` +
        `(${got.base > d.base ? '+' : ''}${got.base - d.base})`);
    }
  }

  if (arg('emit') && arg('emit') !== true) {
    console.log(`region-alloc: wrote ${arg('emit')}`);
  }
  console.log(`region-alloc: ${decls.length} regions, ${emitted.gaps} explicit gap(s) ` +
    `totalling ${hex(emitted.gapBytes)} bytes, floor ${hex(ALLOC_FLOOR)}` +
    (shake ? `, SHAKEN (${layout.shake})` : ''));
  if (!diffs.length) {
    console.log(shake
      ? 'region-alloc: no region moved under the shake — that is a FAILURE of the shake, not a pass'
      : 'region-alloc: --diff is EMPTY — the allocator reproduces the map exactly');
    process.exit(shake ? 1 : 0);
  }
  for (const line of diffs) console.log(`  ${line}`);
  console.log(`region-alloc: ${diffs.length} of ${decls.length} regions differ`);
  process.exit(shake ? 0 : 1);
}

if (require.main === module) {
  try { main(); } catch (err) { console.error(String(err && err.message || err)); process.exit(2); }
}

module.exports = { readDeclarations, emitAllocatedSource, allocate, ALLOC_FLOOR, MEMORY_PAGES };
