  ;; ============================================================
  ;; src/00-regions.wat — THE memory map, declared.
  ;;
  ;; Milestone 6 step 1 of docs/watx-migration-plan.md; designed in
  ;; docs/watx-region-safety-design.md.
  ;;
  ;; THE MAP IS ALLOCATED, NOT WRITTEN DOWN (since c409c554, wave 3). Almost
  ;; every entry is `region.declare`: it states a region's SIZE and alignment
  ;; and the compiler's allocator chooses the base. There is no base in this
  ;; file to read for those, and a tool that scans the text for one gets an
  ;; empty map with no error — ask `tools/region-layout.js`, which puts the
  ;; question to the compiler, or read the generated JS mirror.
  ;;
  ;; ONLY A HANDFUL OF REGIONS ARE PINNED. `region.declare-fixed` is the one
  ;; head in the family that does not allocate: the base is an input and the
  ;; compiler verifies it. It is spelled here only where an address is load
  ;; bearing outside this file — $GUEST_BASE, $VIRTUAL_BACKING_BASE,
  ;; $DIB_BACKING_BASE and $THREAD_RPC — plus the three `region.declare-derived`
  ;; entries that hang off $GUEST_BASE and the $DIRECT_WINDOW span. Everything
  ;; else may and does MOVE when a size changes or a region is added, so a JS
  ;; copy of an allocated base is a bug waiting for the next edit; consumers
  ;; read `lib/region-map.generated.js`, regenerated by
  ;; `tools/gen-region-map.js`.
  ;;
  ;; What the compiler now proves, on every build, in both modes:
  ;;   - no two declared regions overlap (a deliberate nesting says (within $R))
  ;;   - every base meets its declared alignment
  ;;   - no region runs past the memory that exists at instantiation
  ;;   - no region is declared twice
  ;; and, at any use site that adopts them, that a constant offset is inside its
  ;; region — (region.addr $R 0x40), which emits exactly the i32.const the raw
  ;; hex literal emits.
  ;;
  ;; DECLARATIONS EMIT NOTHING. This whole file adds zero bytes to the shipped
  ;; wasm: a declaration is compile-time-only under WATX, and the canonical
  ;; artifacts were byte-identical with and without it when the set landed
  ;; (tail 984347 B 01daf6ccfbd115e3, compat 984796 B 0ee6414668129ac4).
  ;; The `WINE_WAT_COMPILER=legacy` rollback that used to be quoted here is
  ;; RETIRED (24b79256, docs/watx-region-safety-design.md §11): declarations
  ;; alone were legacy-safe, but the region spellings the tree now uses in
  ;; expression and data position compile to `unreachable` under the legacy
  ;; path, so it is a hard error rather than a second opinion.
  ;;
  ;; RELATIONSHIP TO THE EXISTING GLOBALS. Each declaration mirrors a
  ;; `(global $NAME i32 ...)` / `(global $NAME_SIZE i32 ...)` pair, which is
  ;; still what the code reads and what tools/wat-memory-map.js and
  ;; test/test-wat-memory-map.js derive their map from.
  ;; tools/check-region-decls.js holds the two in step and fails the build on
  ;; any disagreement, so this file cannot rot into a decorative second opinion.
  ;; `(owner ...)` names the source location of the base global.
  ;;
  ;; Converting consumers to address regions by name is Milestone 6 stage B and
  ;; is UNDER WAY: wave 1 (2026-08-31) symbolized ~96 sites across src/ and
  ;; lib/, and wave 2 added the regions this map was missing entirely. So both
  ;; `$NAME` in expression position and `(data (region.addr $NAME OFF) ...)`
  ;; now appear in src/ — see docs/watx-region-safety-design.md §5 and §13.
  ;;
  ;; TO ADD A REGION: declare its $NAME/$NAME_SIZE globals where the feature
  ;; lives, as before, then add the mirror here. The build fails if you skip it
  ;; or get it wrong, which is the entire point.
  ;; ============================================================

  ;; The low string-constant pool and the MapVirtualKey byte tables. Neither
  ;; had a _SIZE global, so neither was visible to wat-memory-map.js or to any
  ;; overlap gate; 57 data segments lived here in no region at all.
  ;; The allocator starts here. Below it: NULL_SENTINEL at 0xF0, which
  ;; $g2w's sink behaviour pins and nothing may be placed on top of.
  (region.floor 0x00000100)

  (region.declare $STRING_CONSTANTS (size 0x00000280) (align 0x00000100)
    (owner "01-header.wat:$STRING_CONSTANTS"))
  (region.declare $VK_SCAN_TABLES (size 0x00000080) (align 0x00000080)
    (owner "09a7-handlers-dispatch.wat:$VK_SCAN_TABLES"))
  (region.declare $UPDATE_RECT (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$UPDATE_RECT"))
  (region.declare $UPDATE_FLAGS (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$UPDATE_FLAGS"))
  ;; WIDENED 0x80 -> 0x1A0 (wave 2). The declaration covered only as far as
  ;; "SysLink"; the class-name block runs to the RGB555 masks at 0x32A0, so
  ;; everything past 0x3180 -- the DirectAnimation names, SysTreeView32, the
  ;; statusbar/toolbar classes -- sat outside every region and outside every
  ;; gate. The three blocks that follow used to be undeclared data segments.
  (region.declare $CLASS_NAME_STRINGS (size 0x000001A0) (align 0x00000100)
    (owner "01-header.wat:$CLASS_NAME_STRINGS"))
  (region.declare $DIB_DEFAULT_RGB555_MASKS (size 0x0000000C) (align 0x00000010)
    (owner "01-header.wat:$DIB_DEFAULT_RGB555_MASKS"))
  (region.declare $OLE_STRINGS (size 0x000000E0) (align 0x00000010)
    (owner "01-header.wat:$OLE_STRINGS"))
  (region.declare $ENV_DEFAULTS (size 0x000000C0) (align 0x00000010)
    (owner "01-header.wat:$ENV_DEFAULTS"))
  (region.declare $WND_BG_BRUSH_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$WND_BG_BRUSH_TABLE"))
  (region.declare $WND_CLASS_CURSOR_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$WND_CLASS_CURSOR_TABLE"))
  (region.declare $CLASS_EXTRA_TABLE (size 0x00000100) (align 0x00000100)
    (stride $CLASS_EXTRA_STRIDE (count 64))
    (owner "01-header.wat:$CLASS_EXTRA_TABLE"))
  ;; The two Win16 name tables in the hole after CLASS_EXTRA_TABLE. Both were
  ;; raw (data (i32.const ...)) segments in no region at all; each is sized to
  ;; exactly the bytes its segment emits, so growing one is a compile error.
  (region.declare $WIN16_FONT_FACES (size 0x00000030) (align 0x00000100)
    (owner "09e-win16-api.wat:$WIN16_FONT_FACES"))
  (region.declare $WIN16_MMSYSTEM_NAMES (size 0x0000005D) (align 0x00000010)
    (owner "09e-win16-api.wat:$WIN16_MMSYSTEM_NAMES"))
  (region.declare $DIALOG_STATE_TABLE (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$DIALOG_STATE_TABLE"))
  (region.declare $WINDOW_UNICODE_TABLE (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$WINDOW_UNICODE_TABLE"))
  (region.declare $SHARED_PROCESS_ID (size 0x00000004) (align 0x00000100)
    (owner "01-header.wat:$SHARED_PROCESS_ID"))
  (region.declare $SHARED_DLG_ENDED (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_ENDED"))
  (region.declare $SHARED_DLG_RESULT (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_RESULT"))
  (region.declare $SHARED_DLG_PUMP_HWND (size 0x00000004)
    (owner "01-header.wat:$SHARED_DLG_PUMP_HWND"))
  ;; Host-supplied environment overrides. The 240-byte extent is the bound
  ;; $test_launch_env_add already enforced as a bare literal; it now reads the
  ;; region's own size, so the two cannot disagree.
  (region.declare $LAUNCH_ENV_OVERRIDES (size 0x000000F0) (align 0x00000010)
    (owner "01-header.wat:$LAUNCH_ENV_OVERRIDES"))
  (region.declare $WINDOW_EXTRA_TABLE (size 0x00001000) (align 0x00000100)
    (owner "01-header.wat:$WINDOW_EXTRA_TABLE"))
  (region.declare $PAINT_SCRATCH (size 0x00000100) (align 0x00000100)
    (stride 0x10 (count $PAINT_SCRATCH_SLOTS))
    (owner "01-header.wat:$PAINT_SCRATCH"))
  (region.declare $WND_CLASS_SLOT_TABLE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$WND_CLASS_SLOT_TABLE"))
  (region.declare $WND_RECORDS (size 0x00001800) (align 0x00001000)
    (stride 0x18 (count $MAX_WINDOWS))
    (owner "01-header.wat:$WND_RECORDS"))
  (region.declare $CONTROL_TABLE (size 0x00001000) (align 0x00000100)
    (owner "01-header.wat:$CONTROL_TABLE"))
  (region.declare $CONTROL_GEOM (size 0x00000800) (align 0x00000100)
    (owner "01-header.wat:$CONTROL_GEOM"))
  (region.declare $CLASS_RECORDS (size 0x00000C00) (align 0x00001000)
    (owner "01-header.wat:$CLASS_RECORDS"))
  (region.declare $TIMER_TABLE (size 0x00000140) (align 0x00000100)
    (stride $TIMER_ENTRY_SIZE (count $TIMER_MAX))
    (owner "01-header.wat:$TIMER_TABLE"))
  (region.declare $ACCEL_TABLES (size 0x00000400) (align 0x00000100)
    (stride $ACCEL_TABLE_STRIDE (count $ACCEL_TABLE_COUNT))
    (owner "01-header.wat:$ACCEL_TABLES"))
  (region.declare $MENU_DATA_TABLE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$MENU_DATA_TABLE"))
  (region.declare $WND_DLG_RECORDS (size 0x00002000) (align 0x00000010)
    (owner "01-header.wat:$WND_DLG_RECORDS"))
  ;; Four dwords of cross-instance waveOut identity in the 16-byte hole
  ;; between WND_DLG_RECORDS and SCROLL_TABLE. Declared rather than spelled
  ;; (region.end $WND_DLG_RECORDS): it is its own object, and an adjacency is
  ;; not an address (docs/watx-region-safety-design.md 5.1).
  (region.declare $WAVE_OUT_SHARED (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$WAVE_OUT_SHARED"))
  (region.declare $SCROLL_TABLE (size 0x00001800) (align 0x00000010)
    (owner "01-header.wat:$SCROLL_TABLE"))
  (region.declare $FLASH_TABLE (size 0x00000100) (align 0x00000010)
    (owner "01-header.wat:$FLASH_TABLE"))
  (region.declare $NC_FLAGS (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$NC_FLAGS"))
  (region.declare $TITLE_TABLE (size 0x00000800) (align 0x00000010)
    (owner "01-header.wat:$TITLE_TABLE"))
  (region.declare $CLIENT_RECT (size 0x00001000) (align 0x00000010)
    (owner "01-header.wat:$CLIENT_RECT"))
  (region.declare $SHOW_STATE_TABLE (size 0x00000100) (align 0x00000010)
    (owner "01-header.wat:$SHOW_STATE_TABLE"))
  (region.declare $WINDOW_REGION_BITS (size 0x00000020) (align 0x00000010)
    (owner "01-header.wat:$WINDOW_REGION_BITS"))
  (region.declare $NATIVE_STATUS_BITS (size 0x00000020) (align 0x00000010)
    (owner "01-header.wat:$NATIVE_STATUS_BITS"))
  (region.declare $NATIVE_TAB_BITS (size 0x00000020) (align 0x00000010)
    (owner "01-header.wat:$NATIVE_TAB_BITS"))
  (region.declare $SHARED_MODAL_DLG_HWND (size 0x00000004) (align 0x00000010)
    (owner "01-header.wat:$SHARED_MODAL_DLG_HWND"))
  (region.declare $SHARED_MODAL_RESULT (size 0x00000004)
    (owner "01-header.wat:$SHARED_MODAL_RESULT"))
  (region.declare $SHARED_MODAL_DONE (size 0x00000004)
    (owner "01-header.wat:$SHARED_MODAL_DONE"))
  (region.declare $CS_RING (size 0x00000100) (align 0x00000100)
    (stride 0x4 (count 64)) (mask $CS_MASK) (size-is-power-of-2)
    (owner "01-header.wat:$CS_RING"))
  ;; timeSetEvent slots: 8 x 24 bytes, then the id allocator in its own region.
  ;; Sized from $MM_TIMER_MAX x $MM_TIMER_ENTRY, so growing either without
  ;; growing this is a compile error rather than a silent overrun into whatever
  ;; the allocator packed next.
  (region.declare $MM_TIMER_TABLE (size 0x000000C0) (align 0x00000010)
    (stride $MM_TIMER_ENTRY (count 8))
    (owner "01-header.wat:$MM_TIMER_TABLE"))
  (region.declare $MM_TIMER_NEXT_ID (size 0x00000004)
    (owner "01-header.wat:$MM_TIMER_NEXT_ID"))
  (region.declare $MCI_DEVICE_TABLE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$MCI_DEVICE_TABLE"))
  (region.declare $OWNER_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$OWNER_TABLE"))
  ;; The reserved page just below GUEST_BASE. Four undeclared string blocks
  ;; interleaved with the declared tables that already lived here; each is
  ;; bounded by the next declared region, so the extents are not guesses.
  (region.declare $USER_DIALOG_STRINGS (size 0x00000270) (align 0x00001000)
    (owner "01-header.wat:$USER_DIALOG_STRINGS"))
  (region.declare $BROWSE_DIALOG_STRINGS (size 0x00000060) (align 0x00000010)
    (owner "01-header.wat:$BROWSE_DIALOG_STRINGS"))
  (region.declare $DX_VERSION_INFO (size 0x0000005C) (align 0x00000010)
    (owner "01-header.wat:$DX_VERSION_INFO"))
  ;; Storage for every string the compiler interns from a `"text"` literal.
  ;; Named by `(string.pool $WATX_STRING_POOL)` in 01-header.wat; without that
  ;; declaration the pool is placed above the last data segment, which in this
  ;; map is the middle of $D3DIM_AUX. Nothing hand-places bytes in here and no
  ;; offset into it is ever written down — that is the entire point. Growing it
  ;; is a one-line edit and the compiler says exactly how many bytes short it is.
  (region.declare $WATX_STRING_POOL (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$WATX_STRING_POOL"))
  (region.declare $DI_DIK_VK_TABLE (size 0x00000100) (align 0x00000100)
    (owner "09a8-handlers-directx.wat:$DI_DIK_VK_TABLE"))
  (region.declare $RICHEDIT_FORMAT_TABLE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$RICHEDIT_FORMAT_TABLE"))
  (region.declare $RICHEDIT_PARA_TABLE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$RICHEDIT_PARA_TABLE"))
  (region.declare $RESERVED_PAGE_STRINGS (size 0x00000280) (align 0x00000080)
    (owner "01-header.wat:$RESERVED_PAGE_STRINGS"))
  ;; The texts on the shutting-down / safe-to-turn-off screens.
  (region.declare $POWER_SCREEN_STRINGS (size 0x000000C0) (align 0x00000010)
    (owner "09c3-controls.wat:$POWER_SCREEN_STRINGS"))
  (region.declare-fixed $GUEST_BASE (base 0x00012000) (size 0x03C00000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_BASE"))
  ;; Per-owner USER activation history fits in the remaining aligned table gap
  ;; before the fixed guest mirror. Keep the address allocator-owned rather
  ;; than pinning another raw address.
  (region.declare $LAST_ACTIVE_POPUP_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$LAST_ACTIVE_POPUP_TABLE"))
  ;; WIDENED 0x100000 -> 0x3EE000 (wave 3). The low heap never fitted in 1MB:
  ;; $heap_low_reserve hands out 1MB chunks and stopped only when the next
  ;; chunk would reach $PAGE_INDEX_ARENA, which the hand-placed map happened to
  ;; put 4MB further up. The room a table grows into belongs in its own (size),
  ;; where a bound is checked, not in an anonymous hole beside it — reclaiming
  ;; that hole moved the page indexes down to 0x03E12000 and left the heap with
  ;; one chunk, which is a broken emulator, not a broken declaration.
  (region.declare-derived $GUEST_HEAP_BASE (base (g2w 0x04100000)) (size 0x003EE000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_HEAP_BASE"))
  (region.declare $HANDLER_PAIR_HIST_COUNTS (size 0x00100000) (align 0x00001000)
    (owner "01-header.wat:$HANDLER_PAIR_HIST_COUNTS"))
  (region.declare $PAGE_INDEX_ARENA (size 0x00800000) (align 0x00001000)
    (stride $PAGE_INDEX_STRIDE (count 8))
    (owner "01-header.wat:$PAGE_INDEX_ARENA"))
  (region.declare $PAGE_DIR_BASE (size 0x00020000) (align 0x00001000)
    (stride $PAGE_DIR_STRIDE (count 8))
    (owner "01-header.wat:$PAGE_DIR_BASE"))
  (region.declare $WIN16_APP_DLL_STAGING (size 0x00600000) (align 0x00001000)
    (stride $WIN16_APP_DLL_STRIDE (count 6))
    (owner "01-header.wat:$WIN16_APP_DLL_STAGING"))
  (region.declare $THREAD_CACHE_BASE (size 0x01E00000) (align 0x00001000)
    (stride $THREAD_CACHE_STRIDE (count 8))
    (owner "01-header.wat:$THREAD_CACHE_BASE"))
  (region.declare-derived $GUEST_STACK (base (g2w 0x07400000)) (size 0x00100000) (align 0x00001000)
    (owner "01-header.wat:$GUEST_STACK"))
  (region.declare-derived $THUNK_BASE (base (g2w 0x07500000)) (size 0x00040000) (align 0x00001000)
    (owner "01-header.wat:$THUNK_BASE"))
  (region.declare $PE_STAGING (size 0x00800000) (align 0x00001000)
    (owner "01-header.wat:$PE_STAGING"))
  (region.declare $DLL_TABLE (size 0x00000200) (align 0x00001000)
    (stride 0x20 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_TABLE"))
  (region.declare $DLL_RSRC_TABLE (size 0x00000080) (align 0x00000100)
    (stride 0x8 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_RSRC_TABLE"))
  (region.declare $DLL_PATH_TABLE (size 0x00000040) (align 0x00000100)
    (stride 0x4 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_PATH_TABLE"))
  (region.declare $DLL_FLAGS_TABLE (size 0x00000040) (align 0x00000100)
    (stride 0x4 (count $DLL_TABLE_CAPACITY))
    (owner "01-header.wat:$DLL_FLAGS_TABLE"))
  (region.declare $GDI_BITMAP_TEXT_LAYOUT (size 0x00021000) (align 0x00001000)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_TEXT_LAYOUT"))
  (region.declare $GDI_BITMAP_TEXT_PREFIX (size 0x00011000) (align 0x00001000)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_TEXT_PREFIX"))
  (region.declare $WND_Z_ORDER_TABLE (size 0x00000400) (align 0x00001000)
    (owner "01-header.wat:$WND_Z_ORDER_TABLE"))
  (region.declare $WND_CLASS_ICON_TABLE (size 0x00000400) (align 0x00001000)
    (owner "01-header.wat:$WND_CLASS_ICON_TABLE"))
  (region.declare $WIN16_FILE_TABLE (size 0x00000400) (align 0x00000100)
    (stride 0x4 (count $WIN16_FILE_MAX))
    (owner "01-header.wat:$WIN16_FILE_TABLE"))
  (region.declare $WND_OWN_DC_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$WND_OWN_DC_TABLE"))
  (region.declare $WND_HINSTANCE_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$WND_HINSTANCE_TABLE"))
  (region.declare $WIN16_BUILTIN_NAMES (size 0x00000240) (align 0x00001000)
    (owner "09e-win16-api.wat:$WIN16_BUILTIN_NAMES"))
  (region.declare $WND_THREAD_TABLE (size 0x00000400) (align 0x00000100)
    (owner "01-header.wat:$WND_THREAD_TABLE"))
  (region.declare $THREAD_MSG_QUEUES (size 0x00002080) (align 0x00000100)
    (stride $THREAD_MSG_QUEUE_STRIDE (count 8))
    (owner "01-header.wat:$THREAD_MSG_QUEUES"))
  ;; $gdi_nearest_cache_slot hashes a colour and masks with SLOTS-1, so the
  ;; slot count being a power of two is what makes the mask a bound.
  (region.declare $GDI_NEAREST_CACHE (size 0x00008000) (align 0x00001000)
    (stride 0x8 (count $GDI_NEAREST_CACHE_SLOTS)) (size-is-power-of-2)
    (owner "10g-gdi-raster.wat:$GDI_NEAREST_CACHE"))
  (region.declare $WIN16_THUNK_TABLE (size 0x00002000) (align 0x00001000)
    (stride 0x4 (count $WIN16_THUNK_MAX))
    (owner "01-header.wat:$WIN16_THUNK_TABLE"))
  (region.declare $WIN16_SEG_TABLE (size 0x00004000) (align 0x00001000)
    (owner "01-header.wat:$WIN16_SEG_TABLE"))
  (region.declare $API_HASH_TABLE (size 0x00008000) (align 0x00001000)
    (owner "01-header.wat:$API_HASH_TABLE"))
  (region.declare $TEXT_SCRATCH (size 0x00000400) (align 0x00001000)
    (owner "01-header.wat:$TEXT_SCRATCH"))
  (region.declare $CONSOLE_TEXT (size 0x00003000) (align 0x00001000)
    (stride 0x2 (count $CONSOLE_MAX_CELLS))
    (owner "01-header.wat:$CONSOLE_TEXT"))
  (region.declare $CONSOLE_ATTR (size 0x00003000) (align 0x00001000)
    (stride 0x2 (count $CONSOLE_MAX_CELLS))
    (owner "01-header.wat:$CONSOLE_ATTR"))
  (region.declare $CONSOLE_INPUT (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$CONSOLE_INPUT"))
  (region.declare $DIB_PAGE_USED (size 0x00004000) (align 0x00001000)
    (owner "01-header.wat:$DIB_PAGE_USED"))
  (region.declare $DIB_PAGE_RUNS (size 0x00008000) (align 0x00001000)
    (owner "01-header.wat:$DIB_PAGE_RUNS"))
  (region.declare $GDI_REGION_BANDS (size 0x000D0000) (align 0x00001000)
    (owner "01-header.wat:$GDI_REGION_BANDS"))
  (region.declare $GDI_REGION_WORK (size 0x00003400) (align 0x00001000)
    (owner "01-header.wat:$GDI_REGION_WORK"))
  (region.declare $GDI_DC_CLIP_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x8 (count $GDI_DC_CLIP_COUNT))
    (owner "01-header.wat:$GDI_DC_CLIP_TABLE"))
  (region.declare $GDI_DC_SAVE_TABLE (size 0x00000800) (align 0x00000100)
    (stride 0x8 (count $GDI_DC_SAVE_COUNT))
    (owner "01-header.wat:$GDI_DC_SAVE_TABLE"))
  (region.declare $GDI_LINE_DESC (size 0x00000050) (align 0x00001000)
    (owner "01-header.wat:$GDI_LINE_DESC"))
  (region.declare $GDI_BLIT_DESC (size 0x000000A0) (align 0x00000100)
    (owner "01-header.wat:$GDI_BLIT_DESC"))
  (region.declare $GDI_BITMAP_PLAN (size 0x00000030) (align 0x00000010)
    (owner "01-header.wat:$GDI_BITMAP_PLAN"))
  (region.declare $GDI_BITMAP_NAME (size 0x00000100) (align 0x00000010)
    (owner "01-header.wat:$GDI_BITMAP_NAME"))
  (region.declare $WINDOW_RECT_SCRATCH (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$WINDOW_RECT_SCRATCH"))
  (region.declare $GDI_BRUSH_DESC (size 0x00000050) (align 0x00000010)
    (owner "01-header.wat:$GDI_BRUSH_DESC"))
  (region.declare $GDI_PALETTE_RESOLVE (size 0x00000400) (align 0x00000010)
    (owner "01-header.wat:$GDI_PALETTE_RESOLVE"))
  (region.declare $GDI_OBJECT_GEN (size 0x00000004) (align 0x00000010)
    (owner "01-header.wat:$GDI_OBJECT_GEN"))
  (region.declare $GDI_WINDOW_SURFACE_HWM (size 0x00000004)
    (owner "01-header.wat:$GDI_WINDOW_SURFACE_HWM"))
  (region.declare $GDI_DC_STATE_TABLE (size 0x0000C000) (align 0x00000100)
    (stride $GDI_DC_STATE_STRIDE (count $GDI_DC_STATE_COUNT))
    (owner "01-header.wat:$GDI_DC_STATE_TABLE"))
  (region.declare $GDI_OBJECT_TABLE (size 0x00006000) (align 0x00000100)
    (stride $GDI_OBJECT_STRIDE (count $GDI_OBJECT_COUNT))
    (owner "01-header.wat:$GDI_OBJECT_TABLE"))
  (region.declare $GDI_WINDOW_SURFACE_TABLE (size 0x00002000) (align 0x00000100)
    (stride $GDI_WINDOW_SURFACE_STRIDE (count $GDI_WINDOW_SURFACE_COUNT))
    (owner "01-header.wat:$GDI_WINDOW_SURFACE_TABLE"))
  (region.declare $GDI_DC_AUX_TABLE (size 0x00002000) (align 0x00000100)
    (stride $GDI_DC_AUX_STRIDE (count $GDI_DC_AUX_COUNT))
    (owner "01-header.wat:$GDI_DC_AUX_TABLE"))
  (region.declare $GDI_COLOR_ADJUST_TABLE (size 0x00001800) (align 0x00000100)
    (owner "01-header.wat:$GDI_COLOR_ADJUST_TABLE"))
  (region.declare $PROP_TABLE (size 0x00000C00) (align 0x00000100)
    (owner "01-header.wat:$PROP_TABLE"))
  (region.declare $PAINT_FLAGS (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$PAINT_FLAGS"))
  (region.declare $TAB_NATIVE_STATE_TABLE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$TAB_NATIVE_STATE_TABLE"))
  (region.declare $ICON_TABLE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$ICON_TABLE"))
  (region.declare $CURSOR_TABLE (size 0x00000300) (align 0x00000100)
    (stride $CURSOR_TABLE_STRIDE (count 32))
    (owner "01-header.wat:$CURSOR_TABLE"))
  (region.declare $CURSOR_MASK_DESC (size 0x00000050) (align 0x00000100)
    (owner "01-header.wat:$CURSOR_MASK_DESC"))
  (region.declare $CURSOR_COLOR_DESC (size 0x00000050) (align 0x00000010)
    (owner "01-header.wat:$CURSOR_COLOR_DESC"))
  (region.declare $EDIT_LAYOUT_SCRATCH (size 0x00000C00) (align 0x00000100)
    (owner "01-header.wat:$EDIT_LAYOUT_SCRATCH"))
  (region.declare $VIRTUAL_MAP_STATE (size 0x00000010) (align 0x00000100)
    (owner "01-header.wat:$VIRTUAL_MAP_STATE"))
  (region.declare $VIRTUAL_MAP_TABLE (size 0x00008000) (align 0x00000010)
    (owner "01-header.wat:$VIRTUAL_MAP_TABLE"))
  (region.declare $GDI_BITMAP_FONT_IO (size 0x00000004) (align 0x00000010)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_IO"))
  (region.declare $GDI_BITMAP_FONT_DESC (size 0x00000050) (align 0x00000010)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_DESC"))
  (region.declare $GDI_BITMAP_FONT_STATIC (size 0x00000170) (align 0x00000010)
    (owner "01-header.wat:$GDI_BITMAP_FONT_STATIC"))
  (region.declare $GDI_BITMAP_FONT_LRU (size 0x000000C0) (align 0x00000100)
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_LRU"))
  (region.declare $GDI_BITMAP_FONT_TABLE (size 0x00000C00) (align 0x00000100)
    (stride $GDI_BITMAP_FONT_STRIDE (count $GDI_BITMAP_FONT_COUNT))
    (owner "10b-gdi-font.wat:$GDI_BITMAP_FONT_TABLE"))
  (region.declare $TT_SUBST_TABLE (size 0x00000800) (align 0x00000100)
    (owner "10c-truetype.wat:$TT_SUBST_TABLE"))
  (region.declare $TT_SUBST_ALIAS_TABLE (size 0x00000300) (align 0x00000100)
    (owner "10c-truetype.wat:$TT_SUBST_ALIAS_TABLE"))
  (region.declare $TT_FONT_STRING_STORAGE (size 0x00000100) (align 0x00000100)
    (owner "01-header.wat:$TT_FONT_STRING_STORAGE"))
  (region.declare $GDI_DC_SYSTEM_CLIP_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x8 (count $GDI_DC_SYSTEM_CLIP_COUNT))
    (owner "01-header.wat:$GDI_DC_SYSTEM_CLIP_TABLE"))
  (region.declare $HEAP_SHARED (size 0x00000040) (align 0x00000100)
    (owner "01-header.wat:$HEAP_SHARED"))
  (region.declare $LOCK_TABLE (size 0x00000200) (align 0x00000010)
    (owner "01-header.wat:$LOCK_TABLE"))
  (region.declare $CS_TABLE (size 0x00000400) (align 0x00000010)
    (stride 0x4 (count $CS_TABLE_ENTRIES))
    (owner "01-header.wat:$CS_TABLE"))
  (region.declare $SHARED_COUNTERS (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$SHARED_COUNTERS"))
  (region.declare $CLIPBOARD_SEQUENCE (size 0x00000004) (align 0x00000004)
    (owner "01-header.wat:$CLIPBOARD_SEQUENCE"))
  (region.declare $GDI_TABLE_MARKS (size 0x00000010) (align 0x00000010)
    (owner "01-header.wat:$GDI_TABLE_MARKS"))
  (region.declare $TV_SLOT_MARK (size 0x00000004) (align 0x00000010)
    (owner "01-header.wat:$TV_SLOT_MARK"))
  (region.declare $TV_HANDLE_SEQ (size 0x00000004)
    (owner "01-header.wat:$TV_HANDLE_SEQ"))
  (region.declare $DX_PROCESS_STATE (size 0x0000001C) (align 0x00000010)
    (owner "09a8-handlers-directx.wat:$DX_PROCESS_STATE"))
  (region.declare $LOOP_PROCESS_STATE (size 0x00000004) (align 0x00000010)
    (owner "07b-loop-match.wat:$LOOP_PROCESS_STATE"))
  (region.declare $TV_VIEW_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x10 (count $TV_VIEW_COUNT))
    (owner "01-header.wat:$TV_VIEW_TABLE"))
  (region.declare $GDI_REGION_TABLE (size 0x00002000) (align 0x00001000)
    (owner "01-header.wat:$GDI_REGION_TABLE"))
  (region.declare $GDI_DC_PATH_TABLE (size 0x00001000) (align 0x00001000)
    (stride $GDI_DC_PATH_STRIDE (count $GDI_DC_PATH_COUNT))
    (owner "01-header.wat:$GDI_DC_PATH_TABLE"))
  (region.declare $HANDLER_HIST_COUNTS (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$HANDLER_HIST_COUNTS"))
  (region.declare $CODE_PAGE_BITMAP (size 0x00002000) (align 0x00001000)
    (owner "01-header.wat:$CODE_PAGE_BITMAP"))
  (region.declare $SYNC_TABLE (size 0x00002000) (align 0x00001000)
    (owner "01-header.wat:$SYNC_TABLE"))
  (region.declare $D3DIM_VIEWPORT_LIGHT_HEAD (size 0x00004000) (align 0x00001000)
    (owner "09aa-handlers-d3dim.wat:$D3DIM_VIEWPORT_LIGHT_HEAD"))
  (region.declare $HIT_COUNT_BASE (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$HIT_COUNT_BASE"))
  (region.declare $TIMER_SHARED (size 0x00000050) (align 0x00000100)
    (owner "01-header.wat:$TIMER_SHARED"))
  (region.declare $EXTRA_CMDLINE_BUFFER (size 0x00000100) (align 0x00000100)
    (owner "10-helpers.wat:$EXTRA_CMDLINE_BUFFER"))
  (region.declare $TLS_NEXT_INDEX_SHARED (size 0x00000040) (align 0x00000100)
    (owner "01-header.wat:$TLS_NEXT_INDEX_SHARED"))
  (region.declare $DI_MOUSE_INPUT_STATE (size 0x00000118) (align 0x00000100)
    (owner "09a8-handlers-directx.wat:$DI_MOUSE_INPUT_STATE"))
  ;; One byte per WND_RECORDS slot: bits 0..1 are the horizontal ESB_* mask,
  ;; bits 2..3 are the vertical mask. Keeping arrow enablement beside, but
  ;; separate from, SCROLLINFO avoids stealing range/track bits from callers.
  ;; Declare it before the 4KB-aligned aux table so it occupies existing
  ;; allocator padding instead of moving every later region by a page.
  (region.declare $SCROLL_ARROW_TABLE (size 0x00000100) (align 0x00000100)
    (stride 0x1 (count $MAX_WINDOWS))
    (owner "01-header.wat:$SCROLL_ARROW_TABLE"))
  (region.declare $SCROLL_AUX_TABLE (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$SCROLL_AUX_TABLE"))
  (region.declare $TV_TABLE (size 0x00004000) (align 0x00001000)
    (stride 0x20 (count $TV_SLOT_COUNT))
    (owner "01-header.wat:$TV_TABLE"))
  (region.declare $TV_IMAGE_TABLE (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$TV_IMAGE_TABLE"))
  (region.declare $TV_OWNER_TABLE (size 0x00000800) (align 0x00001000)
    (stride 0x4 (count $TV_SLOT_COUNT))
    (owner "01-header.wat:$TV_OWNER_TABLE"))
  ;; The five DX_SURF_* tables and DX_CURSOR_SAVE are parallel-indexed to
  ;; DX_OBJECTS by $dx_slot_of, so every one of them is $DX_MAX records wide
  ;; and only the record size differs.
  (region.declare $DX_SURF_META (size 0x00008000) (align 0x00001000)
    (stride 0x8 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_SURF_META"))
  (region.declare $OP_INDEX (size 0x00002000) (align 0x00001000)
    (stride 0x4 (count $OP_INDEX_MAX))
    (owner "01-header.wat:$OP_INDEX"))
  (region.declare $DX_SURF_PAL (size 0x00004000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_SURF_PAL"))
  (region.declare $DX_SURF_STATE (size 0x00020000) (align 0x00001000)
    (stride 0x20 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_SURF_STATE"))
  (region.declare $DX_CURSOR_SAVE (size 0x00008000) (align 0x00001000)
    (stride 0x8 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_CURSOR_SAVE"))
  ;; Harness-only. The worker-thread tests rendezvous here and the GDI region
  ;; tests marshal a RECT and a POINT array through it; no WAT reads any of it.
  ;; Declared for the reason everything else here is: every one of these cells
  ;; used to be a raw address picked out of a hole, or out of somebody else's
  ;; table, and both are free only until something moves.
  (region.declare $TEST_SCRATCH (size 0x00000100) (align 0x00001000)
    (owner "01-header.wat:$TEST_SCRATCH"))
  (region.declare $DX_OBJECTS (size 0x00020000) (align 0x00001000)
    (stride $DX_ENTRY_SIZE (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_OBJECTS"))
  (region.declare $COM_WRAPPERS (size 0x00008000) (align 0x00001000)
    (owner "09a8-handlers-directx.wat:$COM_WRAPPERS"))
  (region.declare $DX_SURF_FMT (size 0x00004000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_SURF_FMT"))
  (region.declare $DX_SURF_OWNER (size 0x00004000) (align 0x00001000)
    (stride 0x4 (count $DX_MAX))
    (owner "09a8-handlers-directx.wat:$DX_SURF_OWNER"))
  (region.declare $CP1252_TO_CP437 (size 0x00000100) (align 0x00001000)
    (owner "09a-handlers.wat:$CP1252_TO_CP437"))
  (region.declare $CP437_TO_CP1252 (size 0x00000100) (align 0x00000100)
    (owner "09a-handlers.wat:$CP437_TO_CP1252"))
  (region.declare $BRANCH_CMP_JCC_HIST (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$BRANCH_CMP_JCC_HIST"))
  (region.declare $BRANCH_TEST_JCC_HIST (size 0x00001000) (align 0x00001000)
    (owner "01-header.wat:$BRANCH_TEST_JCC_HIST"))
  (region.declare $BRANCH_ALU_M32_RO_JCC_HIST (size 0x00008000) (align 0x00001000)
    (owner "01-header.wat:$BRANCH_ALU_M32_RO_JCC_HIST"))
  ;; Both are open-addressed hash tables of 8-byte {key,count} records whose
  ;; probe masks the slot index, so the record count must stay a power of two.
  (region.declare $HOT_BLOCK_HIST (size 0x00040000) (align 0x00001000)
    (stride 0x8 (count $HOT_BLOCK_HIST_COUNT)) (size-is-power-of-2)
    (owner "01-header.wat:$HOT_BLOCK_HIST"))
  (region.declare $SIB_CONSUMER_HIST (size 0x00010000) (align 0x00001000)
    (stride 0x8 (count $SIB_CONSUMER_HIST_COUNT)) (size-is-power-of-2)
    (owner "01-header.wat:$SIB_CONSUMER_HIST"))
  (region.declare $D3DIM_AUX (size 0x00001000) (align 0x00001000)
    (owner "09ab-handlers-d3dim-core.wat:$D3DIM_AUX"))
  (region.declare $D3DIM_MATRICES (size 0x00004000) (align 0x00001000)
    (stride 0x40 (count $D3DIM_MATRIX_MAX))
    (owner "09a8-handlers-directx.wat:$D3DIM_MATRICES"))
  ;; NO (stride) LAW ON THE NEXT TWO, and both declines are structural, not
  ;; laziness. COM_WRAPPERS_AUX is $COM_WRAPPERS_AUX_MAX x 8 bytes ROUNDED UP
  ;; to a whole region (0x3EFC vs 2015*8 = 0x3EF8): the tail is four bytes of
  ;; padding, so stride x count is deliberately less than the size, which is
  ;; exactly the shape a law refuses. DX_VTBL_REGISTRY carries a HEADER — its
  ;; size is ($DX_VTBL_REGISTRY_COUNT + 1) * 4, the +1 being the live count
  ;; stored at +0 — and a law over a headered table would have to lie about
  ;; either the stride or the count. test/test-wat-memory-map.js states both
  ;; relations as inequalities for that reason; that is where they belong.
  (region.declare $COM_WRAPPERS_AUX (size 0x00003EFC) (align 0x00001000)
    (owner "09a8-handlers-directx.wat:$COM_WRAPPERS_AUX"))
  (region.declare $DX_VTBL_REGISTRY (size 0x00000104)
    (owner "09a8-handlers-directx.wat:$DX_VTBL_REGISTRY"))
  (region.declare $VSOCK_TABLE (size 0x00002000) (align 0x00001000)
    (stride $VSOCK_REC_SIZE (count $VSOCK_MAX))
    (owner "01-header.wat:$VSOCK_TABLE"))
  ;; Per-process shell image-list identity plus the short immutable strings
  ;; SHGetFileInfo copies into SHFILEINFO.  WAT globals are per instance, so
  ;; the two HIMAGELIST handles themselves must live in shared memory for a
  ;; process whose API calls arrive through more than one Worker instance.
  (region.declare $SHELL_FILE_INFO (size 0x00000080) (align 0x00000010)
    (owner "09a9-comctl32.wat:$SHELL_FILE_INFO"))
  (region.declare-fixed $VIRTUAL_BACKING_BASE (base 0x08000000) (size 0x14000000) (align 0x00001000)
    (owner "01-header.wat:$VIRTUAL_BACKING_BASE"))
  (region.declare-fixed $DIB_BACKING_BASE (base 0x1C000000) (size 0x03F00000) (align 0x00001000)
    (owner "01-header.wat:$DIB_BACKING_BASE"))
  (region.declare-fixed $THREAD_RPC (base 0x1FF00000) (size 0x00100000) (align 0x00001000)
    (owner "01-header.wat:$THREAD_RPC"))

  ;; ============================================================
  ;; SPANS — address-range LIMITS, not storage.
  ;;
  ;; A span names a boundary somebody's arithmetic tests against. It owns no
  ;; bytes, so it is TRANSPARENT to the overlap check: the regions it bounds
  ;; live inside it, which is the whole point and the one thing no other head
  ;; can express. It is never allocated and never shaken, and it has no
  ;; $NAME/$NAME_SIZE globals behind it — there is nothing to store — so
  ;; tools/check-region-decls.js neither requires nor reads one.
  ;; ============================================================

  ;; $g2w's direct guest window (docs/watx-region-safety-design.md §5.1). A
  ;; guest address translates by the flat `ga - image_base + GUEST_BASE` rule
  ;; only while the result lands below this limit; past it $g2w falls through to
  ;; the DIB window, then the sparse VirtualAlloc map, then NULL_SENTINEL. The
  ;; window is a UNION of regions — $GUEST_BASE, the guest heap, the stack, the
  ;; thunk zone, PE staging, the DLL tables and the whole WAT-private high map —
  ;; so it cannot be declared with any head that participates in the overlap
  ;; sweep. Its end is $VIRTUAL_BACKING_BASE's base: everything at or above
  ;; 0x08000000 is backing store reached through a translation, never directly.
  ;; Written as the bare literal 0x8000000 three times in 03-registers.wat until
  ;; this declaration; those three sites now spell it (region.end $DIRECT_WINDOW).
  (region.declare-span $DIRECT_WINDOW (base 0x00000000) (end 0x08000000)
    (owner "03-registers.wat:81,177,179 — $g2w / $g2w_affine_span direct-window limit"))
