  ;; GENERATED by tools/generate-wat-slot-packet.js. Do not edit directly.
  ;; Four packet-local value slots are mapped to arbitrary guest registers
  ;; by two packed descriptors (four 4-bit guest-register IDs, 0xF=unused).
  (func $wat_slot_packet
    (local $l0 i32) (local $l1 i32) (local $l2 i32) (local $l3 i32)
    (local $imports i32) (local $exports i32) (local $reg i32)
    (local $code i32) (local $a i32) (local $b i32) (local $res i32)
    (local $cc i32) (local $target i32) (local $fall i32)

    (if (global.get $wat_slot_packet_count_enabled)
      (then (global.set $wat_slot_packet_entries
        (i32.add (global.get $wat_slot_packet_entries) (i32.const 1)))))
    (local.set $imports (call $read_thread_word))
    (local.set $exports (call $read_thread_word))
    (local.set $reg (i32.and (i32.shr_u (local.get $imports) (i32.const 0)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (local.set $l0 (call $get_reg (local.get $reg)))))
    (local.set $reg (i32.and (i32.shr_u (local.get $imports) (i32.const 4)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (local.set $l1 (call $get_reg (local.get $reg)))))
    (local.set $reg (i32.and (i32.shr_u (local.get $imports) (i32.const 8)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (local.set $l2 (call $get_reg (local.get $reg)))))
    (local.set $reg (i32.and (i32.shr_u (local.get $imports) (i32.const 12)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (local.set $l3 (call $get_reg (local.get $reg)))))

    (block $packet_done
      (loop $packet
        (local.set $code (call $read_thread_word))
        ;; EXPORT_SLOT_GUEST: opcodes 1..32
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 1))
                     (i32.le_u (local.get $code) (i32.const 32)))
          (then
            (block $EXPORT_SLOT_GUEST_31
            (block $EXPORT_SLOT_GUEST_30
            (block $EXPORT_SLOT_GUEST_29
            (block $EXPORT_SLOT_GUEST_28
            (block $EXPORT_SLOT_GUEST_27
            (block $EXPORT_SLOT_GUEST_26
            (block $EXPORT_SLOT_GUEST_25
            (block $EXPORT_SLOT_GUEST_24
            (block $EXPORT_SLOT_GUEST_23
            (block $EXPORT_SLOT_GUEST_22
            (block $EXPORT_SLOT_GUEST_21
            (block $EXPORT_SLOT_GUEST_20
            (block $EXPORT_SLOT_GUEST_19
            (block $EXPORT_SLOT_GUEST_18
            (block $EXPORT_SLOT_GUEST_17
            (block $EXPORT_SLOT_GUEST_16
            (block $EXPORT_SLOT_GUEST_15
            (block $EXPORT_SLOT_GUEST_14
            (block $EXPORT_SLOT_GUEST_13
            (block $EXPORT_SLOT_GUEST_12
            (block $EXPORT_SLOT_GUEST_11
            (block $EXPORT_SLOT_GUEST_10
            (block $EXPORT_SLOT_GUEST_9
            (block $EXPORT_SLOT_GUEST_8
            (block $EXPORT_SLOT_GUEST_7
            (block $EXPORT_SLOT_GUEST_6
            (block $EXPORT_SLOT_GUEST_5
            (block $EXPORT_SLOT_GUEST_4
            (block $EXPORT_SLOT_GUEST_3
            (block $EXPORT_SLOT_GUEST_2
            (block $EXPORT_SLOT_GUEST_1
            (block $EXPORT_SLOT_GUEST_0
              (br_table $EXPORT_SLOT_GUEST_0 $EXPORT_SLOT_GUEST_1 $EXPORT_SLOT_GUEST_2 $EXPORT_SLOT_GUEST_3 $EXPORT_SLOT_GUEST_4 $EXPORT_SLOT_GUEST_5 $EXPORT_SLOT_GUEST_6 $EXPORT_SLOT_GUEST_7 $EXPORT_SLOT_GUEST_8 $EXPORT_SLOT_GUEST_9 $EXPORT_SLOT_GUEST_10 $EXPORT_SLOT_GUEST_11 $EXPORT_SLOT_GUEST_12 $EXPORT_SLOT_GUEST_13 $EXPORT_SLOT_GUEST_14 $EXPORT_SLOT_GUEST_15 $EXPORT_SLOT_GUEST_16 $EXPORT_SLOT_GUEST_17 $EXPORT_SLOT_GUEST_18 $EXPORT_SLOT_GUEST_19 $EXPORT_SLOT_GUEST_20 $EXPORT_SLOT_GUEST_21 $EXPORT_SLOT_GUEST_22 $EXPORT_SLOT_GUEST_23 $EXPORT_SLOT_GUEST_24 $EXPORT_SLOT_GUEST_25 $EXPORT_SLOT_GUEST_26 $EXPORT_SLOT_GUEST_27 $EXPORT_SLOT_GUEST_28 $EXPORT_SLOT_GUEST_29 $EXPORT_SLOT_GUEST_30 $EXPORT_SLOT_GUEST_31 $EXPORT_SLOT_GUEST_0
                (i32.sub (local.get $code) (i32.const 1)))
            ) ;; $EXPORT_SLOT_GUEST_0
            (call $set_reg (i32.const 0) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_1
            (call $set_reg (i32.const 1) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_2
            (call $set_reg (i32.const 2) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_3
            (call $set_reg (i32.const 3) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_4
            (call $set_reg (i32.const 4) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_5
            (call $set_reg (i32.const 5) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_6
            (call $set_reg (i32.const 6) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_7
            (call $set_reg (i32.const 7) (local.get $l0))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_8
            (call $set_reg (i32.const 0) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_9
            (call $set_reg (i32.const 1) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_10
            (call $set_reg (i32.const 2) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_11
            (call $set_reg (i32.const 3) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_12
            (call $set_reg (i32.const 4) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_13
            (call $set_reg (i32.const 5) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_14
            (call $set_reg (i32.const 6) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_15
            (call $set_reg (i32.const 7) (local.get $l1))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_16
            (call $set_reg (i32.const 0) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_17
            (call $set_reg (i32.const 1) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_18
            (call $set_reg (i32.const 2) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_19
            (call $set_reg (i32.const 3) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_20
            (call $set_reg (i32.const 4) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_21
            (call $set_reg (i32.const 5) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_22
            (call $set_reg (i32.const 6) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_23
            (call $set_reg (i32.const 7) (local.get $l2))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_24
            (call $set_reg (i32.const 0) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_25
            (call $set_reg (i32.const 1) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_26
            (call $set_reg (i32.const 2) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_27
            (call $set_reg (i32.const 3) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_28
            (call $set_reg (i32.const 4) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_29
            (call $set_reg (i32.const 5) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_30
            (call $set_reg (i32.const 6) (local.get $l3))
            (br $packet)
            ) ;; $EXPORT_SLOT_GUEST_31
            (call $set_reg (i32.const 7) (local.get $l3))
            (br $packet)
          ))
        ;; STORE32_ABS: opcodes 33..36
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 33))
                     (i32.le_u (local.get $code) (i32.const 36)))
          (then
            (block $STORE32_ABS_3
            (block $STORE32_ABS_2
            (block $STORE32_ABS_1
            (block $STORE32_ABS_0
              (br_table $STORE32_ABS_0 $STORE32_ABS_1 $STORE32_ABS_2 $STORE32_ABS_3 $STORE32_ABS_0
                (i32.sub (local.get $code) (i32.const 33)))
            ) ;; $STORE32_ABS_0
            (i32.store (call $g2w (call $read_thread_word)) (local.get $l0))
            (br $packet)
            ) ;; $STORE32_ABS_1
            (i32.store (call $g2w (call $read_thread_word)) (local.get $l1))
            (br $packet)
            ) ;; $STORE32_ABS_2
            (i32.store (call $g2w (call $read_thread_word)) (local.get $l2))
            (br $packet)
            ) ;; $STORE32_ABS_3
            (i32.store (call $g2w (call $read_thread_word)) (local.get $l3))
            (br $packet)
          ))
        ;; COPY: opcodes 37..52
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 37))
                     (i32.le_u (local.get $code) (i32.const 52)))
          (then
            (block $COPY_15
            (block $COPY_14
            (block $COPY_13
            (block $COPY_12
            (block $COPY_11
            (block $COPY_10
            (block $COPY_9
            (block $COPY_8
            (block $COPY_7
            (block $COPY_6
            (block $COPY_5
            (block $COPY_4
            (block $COPY_3
            (block $COPY_2
            (block $COPY_1
            (block $COPY_0
              (br_table $COPY_0 $COPY_1 $COPY_2 $COPY_3 $COPY_4 $COPY_5 $COPY_6 $COPY_7 $COPY_8 $COPY_9 $COPY_10 $COPY_11 $COPY_12 $COPY_13 $COPY_14 $COPY_15 $COPY_0
                (i32.sub (local.get $code) (i32.const 37)))
            ) ;; $COPY_0
            (local.set $l0 (local.get $l0))
            (br $packet)
            ) ;; $COPY_1
            (local.set $l0 (local.get $l1))
            (br $packet)
            ) ;; $COPY_2
            (local.set $l0 (local.get $l2))
            (br $packet)
            ) ;; $COPY_3
            (local.set $l0 (local.get $l3))
            (br $packet)
            ) ;; $COPY_4
            (local.set $l1 (local.get $l0))
            (br $packet)
            ) ;; $COPY_5
            (local.set $l1 (local.get $l1))
            (br $packet)
            ) ;; $COPY_6
            (local.set $l1 (local.get $l2))
            (br $packet)
            ) ;; $COPY_7
            (local.set $l1 (local.get $l3))
            (br $packet)
            ) ;; $COPY_8
            (local.set $l2 (local.get $l0))
            (br $packet)
            ) ;; $COPY_9
            (local.set $l2 (local.get $l1))
            (br $packet)
            ) ;; $COPY_10
            (local.set $l2 (local.get $l2))
            (br $packet)
            ) ;; $COPY_11
            (local.set $l2 (local.get $l3))
            (br $packet)
            ) ;; $COPY_12
            (local.set $l3 (local.get $l0))
            (br $packet)
            ) ;; $COPY_13
            (local.set $l3 (local.get $l1))
            (br $packet)
            ) ;; $COPY_14
            (local.set $l3 (local.get $l2))
            (br $packet)
            ) ;; $COPY_15
            (local.set $l3 (local.get $l3))
            (br $packet)
          ))
        ;; ADD: opcodes 53..68
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 53))
                     (i32.le_u (local.get $code) (i32.const 68)))
          (then
            (block $ADD_15
            (block $ADD_14
            (block $ADD_13
            (block $ADD_12
            (block $ADD_11
            (block $ADD_10
            (block $ADD_9
            (block $ADD_8
            (block $ADD_7
            (block $ADD_6
            (block $ADD_5
            (block $ADD_4
            (block $ADD_3
            (block $ADD_2
            (block $ADD_1
            (block $ADD_0
              (br_table $ADD_0 $ADD_1 $ADD_2 $ADD_3 $ADD_4 $ADD_5 $ADD_6 $ADD_7 $ADD_8 $ADD_9 $ADD_10 $ADD_11 $ADD_12 $ADD_13 $ADD_14 $ADD_15 $ADD_0
                (i32.sub (local.get $code) (i32.const 53)))
            ) ;; $ADD_0
            (local.set $l0 (i32.add (local.get $l0) (local.get $l0)))
            (br $packet)
            ) ;; $ADD_1
            (local.set $l0 (i32.add (local.get $l0) (local.get $l1)))
            (br $packet)
            ) ;; $ADD_2
            (local.set $l0 (i32.add (local.get $l0) (local.get $l2)))
            (br $packet)
            ) ;; $ADD_3
            (local.set $l0 (i32.add (local.get $l0) (local.get $l3)))
            (br $packet)
            ) ;; $ADD_4
            (local.set $l1 (i32.add (local.get $l1) (local.get $l0)))
            (br $packet)
            ) ;; $ADD_5
            (local.set $l1 (i32.add (local.get $l1) (local.get $l1)))
            (br $packet)
            ) ;; $ADD_6
            (local.set $l1 (i32.add (local.get $l1) (local.get $l2)))
            (br $packet)
            ) ;; $ADD_7
            (local.set $l1 (i32.add (local.get $l1) (local.get $l3)))
            (br $packet)
            ) ;; $ADD_8
            (local.set $l2 (i32.add (local.get $l2) (local.get $l0)))
            (br $packet)
            ) ;; $ADD_9
            (local.set $l2 (i32.add (local.get $l2) (local.get $l1)))
            (br $packet)
            ) ;; $ADD_10
            (local.set $l2 (i32.add (local.get $l2) (local.get $l2)))
            (br $packet)
            ) ;; $ADD_11
            (local.set $l2 (i32.add (local.get $l2) (local.get $l3)))
            (br $packet)
            ) ;; $ADD_12
            (local.set $l3 (i32.add (local.get $l3) (local.get $l0)))
            (br $packet)
            ) ;; $ADD_13
            (local.set $l3 (i32.add (local.get $l3) (local.get $l1)))
            (br $packet)
            ) ;; $ADD_14
            (local.set $l3 (i32.add (local.get $l3) (local.get $l2)))
            (br $packet)
            ) ;; $ADD_15
            (local.set $l3 (i32.add (local.get $l3) (local.get $l3)))
            (br $packet)
          ))
        ;; ADD_FLAGS: opcodes 69..84
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 69))
                     (i32.le_u (local.get $code) (i32.const 84)))
          (then
            (block $ADD_FLAGS_15
            (block $ADD_FLAGS_14
            (block $ADD_FLAGS_13
            (block $ADD_FLAGS_12
            (block $ADD_FLAGS_11
            (block $ADD_FLAGS_10
            (block $ADD_FLAGS_9
            (block $ADD_FLAGS_8
            (block $ADD_FLAGS_7
            (block $ADD_FLAGS_6
            (block $ADD_FLAGS_5
            (block $ADD_FLAGS_4
            (block $ADD_FLAGS_3
            (block $ADD_FLAGS_2
            (block $ADD_FLAGS_1
            (block $ADD_FLAGS_0
              (br_table $ADD_FLAGS_0 $ADD_FLAGS_1 $ADD_FLAGS_2 $ADD_FLAGS_3 $ADD_FLAGS_4 $ADD_FLAGS_5 $ADD_FLAGS_6 $ADD_FLAGS_7 $ADD_FLAGS_8 $ADD_FLAGS_9 $ADD_FLAGS_10 $ADD_FLAGS_11 $ADD_FLAGS_12 $ADD_FLAGS_13 $ADD_FLAGS_14 $ADD_FLAGS_15 $ADD_FLAGS_0
                (i32.sub (local.get $code) (i32.const 69)))
            ) ;; $ADD_FLAGS_0
            (local.set $a (local.get $l0))
            (local.set $b (local.get $l0))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l0 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_1
            (local.set $a (local.get $l0))
            (local.set $b (local.get $l1))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l0 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_2
            (local.set $a (local.get $l0))
            (local.set $b (local.get $l2))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l0 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_3
            (local.set $a (local.get $l0))
            (local.set $b (local.get $l3))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l0 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_4
            (local.set $a (local.get $l1))
            (local.set $b (local.get $l0))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l1 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_5
            (local.set $a (local.get $l1))
            (local.set $b (local.get $l1))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l1 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_6
            (local.set $a (local.get $l1))
            (local.set $b (local.get $l2))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l1 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_7
            (local.set $a (local.get $l1))
            (local.set $b (local.get $l3))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l1 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_8
            (local.set $a (local.get $l2))
            (local.set $b (local.get $l0))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l2 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_9
            (local.set $a (local.get $l2))
            (local.set $b (local.get $l1))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l2 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_10
            (local.set $a (local.get $l2))
            (local.set $b (local.get $l2))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l2 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_11
            (local.set $a (local.get $l2))
            (local.set $b (local.get $l3))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l2 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_12
            (local.set $a (local.get $l3))
            (local.set $b (local.get $l0))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l3 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_13
            (local.set $a (local.get $l3))
            (local.set $b (local.get $l1))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l3 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_14
            (local.set $a (local.get $l3))
            (local.set $b (local.get $l2))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l3 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
            ) ;; $ADD_FLAGS_15
            (local.set $a (local.get $l3))
            (local.set $b (local.get $l3))
            (local.set $res (i32.add (local.get $a) (local.get $b)))
            (local.set $l3 (local.get $res))
            (call $set_flags_add (local.get $a) (local.get $b) (local.get $res))
            (br $packet)
          ))
        ;; ADD_I32: opcodes 85..88
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 85))
                     (i32.le_u (local.get $code) (i32.const 88)))
          (then
            (block $ADD_I32_3
            (block $ADD_I32_2
            (block $ADD_I32_1
            (block $ADD_I32_0
              (br_table $ADD_I32_0 $ADD_I32_1 $ADD_I32_2 $ADD_I32_3 $ADD_I32_0
                (i32.sub (local.get $code) (i32.const 85)))
            ) ;; $ADD_I32_0
            (local.set $l0 (i32.add (local.get $l0) (call $read_thread_word)))
            (br $packet)
            ) ;; $ADD_I32_1
            (local.set $l1 (i32.add (local.get $l1) (call $read_thread_word)))
            (br $packet)
            ) ;; $ADD_I32_2
            (local.set $l2 (i32.add (local.get $l2) (call $read_thread_word)))
            (br $packet)
            ) ;; $ADD_I32_3
            (local.set $l3 (i32.add (local.get $l3) (call $read_thread_word)))
            (br $packet)
          ))
        ;; SUB_I32: opcodes 89..92
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 89))
                     (i32.le_u (local.get $code) (i32.const 92)))
          (then
            (block $SUB_I32_3
            (block $SUB_I32_2
            (block $SUB_I32_1
            (block $SUB_I32_0
              (br_table $SUB_I32_0 $SUB_I32_1 $SUB_I32_2 $SUB_I32_3 $SUB_I32_0
                (i32.sub (local.get $code) (i32.const 89)))
            ) ;; $SUB_I32_0
            (local.set $l0 (i32.sub (local.get $l0) (call $read_thread_word)))
            (br $packet)
            ) ;; $SUB_I32_1
            (local.set $l1 (i32.sub (local.get $l1) (call $read_thread_word)))
            (br $packet)
            ) ;; $SUB_I32_2
            (local.set $l2 (i32.sub (local.get $l2) (call $read_thread_word)))
            (br $packet)
            ) ;; $SUB_I32_3
            (local.set $l3 (i32.sub (local.get $l3) (call $read_thread_word)))
            (br $packet)
          ))
        ;; AND_I32_FLAGS: opcodes 93..96
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 93))
                     (i32.le_u (local.get $code) (i32.const 96)))
          (then
            (block $AND_I32_FLAGS_3
            (block $AND_I32_FLAGS_2
            (block $AND_I32_FLAGS_1
            (block $AND_I32_FLAGS_0
              (br_table $AND_I32_FLAGS_0 $AND_I32_FLAGS_1 $AND_I32_FLAGS_2 $AND_I32_FLAGS_3 $AND_I32_FLAGS_0
                (i32.sub (local.get $code) (i32.const 93)))
            ) ;; $AND_I32_FLAGS_0
            (local.set $l0 (i32.and (local.get $l0) (call $read_thread_word)))
            (call $set_flags_logic (local.get $l0))
            (br $packet)
            ) ;; $AND_I32_FLAGS_1
            (local.set $l1 (i32.and (local.get $l1) (call $read_thread_word)))
            (call $set_flags_logic (local.get $l1))
            (br $packet)
            ) ;; $AND_I32_FLAGS_2
            (local.set $l2 (i32.and (local.get $l2) (call $read_thread_word)))
            (call $set_flags_logic (local.get $l2))
            (br $packet)
            ) ;; $AND_I32_FLAGS_3
            (local.set $l3 (i32.and (local.get $l3) (call $read_thread_word)))
            (call $set_flags_logic (local.get $l3))
            (br $packet)
          ))
        ;; SHR_U_I32_FLAGS: opcodes 97..100
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 97))
                     (i32.le_u (local.get $code) (i32.const 100)))
          (then
            (block $SHR_U_I32_FLAGS_3
            (block $SHR_U_I32_FLAGS_2
            (block $SHR_U_I32_FLAGS_1
            (block $SHR_U_I32_FLAGS_0
              (br_table $SHR_U_I32_FLAGS_0 $SHR_U_I32_FLAGS_1 $SHR_U_I32_FLAGS_2 $SHR_U_I32_FLAGS_3 $SHR_U_I32_FLAGS_0
                (i32.sub (local.get $code) (i32.const 97)))
            ) ;; $SHR_U_I32_FLAGS_0
            (local.set $a (local.get $l0))
            (local.set $b (call $read_thread_word))
            (local.set $l0 (i32.shr_u (local.get $a) (local.get $b)))
            (call $set_flags_shift (local.get $l0)
              (i32.and (i32.shr_u (local.get $a) (i32.sub (local.get $b) (i32.const 1))) (i32.const 1)))
            (br $packet)
            ) ;; $SHR_U_I32_FLAGS_1
            (local.set $a (local.get $l1))
            (local.set $b (call $read_thread_word))
            (local.set $l1 (i32.shr_u (local.get $a) (local.get $b)))
            (call $set_flags_shift (local.get $l1)
              (i32.and (i32.shr_u (local.get $a) (i32.sub (local.get $b) (i32.const 1))) (i32.const 1)))
            (br $packet)
            ) ;; $SHR_U_I32_FLAGS_2
            (local.set $a (local.get $l2))
            (local.set $b (call $read_thread_word))
            (local.set $l2 (i32.shr_u (local.get $a) (local.get $b)))
            (call $set_flags_shift (local.get $l2)
              (i32.and (i32.shr_u (local.get $a) (i32.sub (local.get $b) (i32.const 1))) (i32.const 1)))
            (br $packet)
            ) ;; $SHR_U_I32_FLAGS_3
            (local.set $a (local.get $l3))
            (local.set $b (call $read_thread_word))
            (local.set $l3 (i32.shr_u (local.get $a) (local.get $b)))
            (call $set_flags_shift (local.get $l3)
              (i32.and (i32.shr_u (local.get $a) (i32.sub (local.get $b) (i32.const 1))) (i32.const 1)))
            (br $packet)
          ))
        ;; LOAD8_U: opcodes 101..116
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 101))
                     (i32.le_u (local.get $code) (i32.const 116)))
          (then
            (block $LOAD8_U_15
            (block $LOAD8_U_14
            (block $LOAD8_U_13
            (block $LOAD8_U_12
            (block $LOAD8_U_11
            (block $LOAD8_U_10
            (block $LOAD8_U_9
            (block $LOAD8_U_8
            (block $LOAD8_U_7
            (block $LOAD8_U_6
            (block $LOAD8_U_5
            (block $LOAD8_U_4
            (block $LOAD8_U_3
            (block $LOAD8_U_2
            (block $LOAD8_U_1
            (block $LOAD8_U_0
              (br_table $LOAD8_U_0 $LOAD8_U_1 $LOAD8_U_2 $LOAD8_U_3 $LOAD8_U_4 $LOAD8_U_5 $LOAD8_U_6 $LOAD8_U_7 $LOAD8_U_8 $LOAD8_U_9 $LOAD8_U_10 $LOAD8_U_11 $LOAD8_U_12 $LOAD8_U_13 $LOAD8_U_14 $LOAD8_U_15 $LOAD8_U_0
                (i32.sub (local.get $code) (i32.const 101)))
            ) ;; $LOAD8_U_0
            (local.set $l0 (i32.load8_u (call $g2w (local.get $l0))))
            (br $packet)
            ) ;; $LOAD8_U_1
            (local.set $l0 (i32.load8_u (call $g2w (local.get $l1))))
            (br $packet)
            ) ;; $LOAD8_U_2
            (local.set $l0 (i32.load8_u (call $g2w (local.get $l2))))
            (br $packet)
            ) ;; $LOAD8_U_3
            (local.set $l0 (i32.load8_u (call $g2w (local.get $l3))))
            (br $packet)
            ) ;; $LOAD8_U_4
            (local.set $l1 (i32.load8_u (call $g2w (local.get $l0))))
            (br $packet)
            ) ;; $LOAD8_U_5
            (local.set $l1 (i32.load8_u (call $g2w (local.get $l1))))
            (br $packet)
            ) ;; $LOAD8_U_6
            (local.set $l1 (i32.load8_u (call $g2w (local.get $l2))))
            (br $packet)
            ) ;; $LOAD8_U_7
            (local.set $l1 (i32.load8_u (call $g2w (local.get $l3))))
            (br $packet)
            ) ;; $LOAD8_U_8
            (local.set $l2 (i32.load8_u (call $g2w (local.get $l0))))
            (br $packet)
            ) ;; $LOAD8_U_9
            (local.set $l2 (i32.load8_u (call $g2w (local.get $l1))))
            (br $packet)
            ) ;; $LOAD8_U_10
            (local.set $l2 (i32.load8_u (call $g2w (local.get $l2))))
            (br $packet)
            ) ;; $LOAD8_U_11
            (local.set $l2 (i32.load8_u (call $g2w (local.get $l3))))
            (br $packet)
            ) ;; $LOAD8_U_12
            (local.set $l3 (i32.load8_u (call $g2w (local.get $l0))))
            (br $packet)
            ) ;; $LOAD8_U_13
            (local.set $l3 (i32.load8_u (call $g2w (local.get $l1))))
            (br $packet)
            ) ;; $LOAD8_U_14
            (local.set $l3 (i32.load8_u (call $g2w (local.get $l2))))
            (br $packet)
            ) ;; $LOAD8_U_15
            (local.set $l3 (i32.load8_u (call $g2w (local.get $l3))))
            (br $packet)
          ))
        ;; LOAD32_ABS: opcodes 117..120
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 117))
                     (i32.le_u (local.get $code) (i32.const 120)))
          (then
            (block $LOAD32_ABS_3
            (block $LOAD32_ABS_2
            (block $LOAD32_ABS_1
            (block $LOAD32_ABS_0
              (br_table $LOAD32_ABS_0 $LOAD32_ABS_1 $LOAD32_ABS_2 $LOAD32_ABS_3 $LOAD32_ABS_0
                (i32.sub (local.get $code) (i32.const 117)))
            ) ;; $LOAD32_ABS_0
            (local.set $l0 (i32.load (call $g2w (call $read_thread_word))))
            (br $packet)
            ) ;; $LOAD32_ABS_1
            (local.set $l1 (i32.load (call $g2w (call $read_thread_word))))
            (br $packet)
            ) ;; $LOAD32_ABS_2
            (local.set $l2 (i32.load (call $g2w (call $read_thread_word))))
            (br $packet)
            ) ;; $LOAD32_ABS_3
            (local.set $l3 (i32.load (call $g2w (call $read_thread_word))))
            (br $packet)
          ))
        ;; SUB: opcodes 121..136
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 121))
                     (i32.le_u (local.get $code) (i32.const 136)))
          (then
            (block $SUB_15
            (block $SUB_14
            (block $SUB_13
            (block $SUB_12
            (block $SUB_11
            (block $SUB_10
            (block $SUB_9
            (block $SUB_8
            (block $SUB_7
            (block $SUB_6
            (block $SUB_5
            (block $SUB_4
            (block $SUB_3
            (block $SUB_2
            (block $SUB_1
            (block $SUB_0
              (br_table $SUB_0 $SUB_1 $SUB_2 $SUB_3 $SUB_4 $SUB_5 $SUB_6 $SUB_7 $SUB_8 $SUB_9 $SUB_10 $SUB_11 $SUB_12 $SUB_13 $SUB_14 $SUB_15 $SUB_0
                (i32.sub (local.get $code) (i32.const 121)))
            ) ;; $SUB_0
            (local.set $l0 (i32.sub (local.get $l0) (local.get $l0)))
            (br $packet)
            ) ;; $SUB_1
            (local.set $l0 (i32.sub (local.get $l0) (local.get $l1)))
            (br $packet)
            ) ;; $SUB_2
            (local.set $l0 (i32.sub (local.get $l0) (local.get $l2)))
            (br $packet)
            ) ;; $SUB_3
            (local.set $l0 (i32.sub (local.get $l0) (local.get $l3)))
            (br $packet)
            ) ;; $SUB_4
            (local.set $l1 (i32.sub (local.get $l1) (local.get $l0)))
            (br $packet)
            ) ;; $SUB_5
            (local.set $l1 (i32.sub (local.get $l1) (local.get $l1)))
            (br $packet)
            ) ;; $SUB_6
            (local.set $l1 (i32.sub (local.get $l1) (local.get $l2)))
            (br $packet)
            ) ;; $SUB_7
            (local.set $l1 (i32.sub (local.get $l1) (local.get $l3)))
            (br $packet)
            ) ;; $SUB_8
            (local.set $l2 (i32.sub (local.get $l2) (local.get $l0)))
            (br $packet)
            ) ;; $SUB_9
            (local.set $l2 (i32.sub (local.get $l2) (local.get $l1)))
            (br $packet)
            ) ;; $SUB_10
            (local.set $l2 (i32.sub (local.get $l2) (local.get $l2)))
            (br $packet)
            ) ;; $SUB_11
            (local.set $l2 (i32.sub (local.get $l2) (local.get $l3)))
            (br $packet)
            ) ;; $SUB_12
            (local.set $l3 (i32.sub (local.get $l3) (local.get $l0)))
            (br $packet)
            ) ;; $SUB_13
            (local.set $l3 (i32.sub (local.get $l3) (local.get $l1)))
            (br $packet)
            ) ;; $SUB_14
            (local.set $l3 (i32.sub (local.get $l3) (local.get $l2)))
            (br $packet)
            ) ;; $SUB_15
            (local.set $l3 (i32.sub (local.get $l3) (local.get $l3)))
            (br $packet)
          ))
        ;; JMP_TABLE: opcodes 137..140
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 137))
                     (i32.le_u (local.get $code) (i32.const 140)))
          (then
            (block $JMP_TABLE_3
            (block $JMP_TABLE_2
            (block $JMP_TABLE_1
            (block $JMP_TABLE_0
              (br_table $JMP_TABLE_0 $JMP_TABLE_1 $JMP_TABLE_2 $JMP_TABLE_3 $JMP_TABLE_0
                (i32.sub (local.get $code) (i32.const 137)))
            ) ;; $JMP_TABLE_0
            (local.set $a (call $read_thread_word))
            (local.set $b (call $read_thread_word))
            (global.set $eip (i32.load (call $g2w
              (i32.add (local.get $a) (i32.shl (local.get $l0) (local.get $b))))))
            (br $packet_done)
            (br $packet)
            ) ;; $JMP_TABLE_1
            (local.set $a (call $read_thread_word))
            (local.set $b (call $read_thread_word))
            (global.set $eip (i32.load (call $g2w
              (i32.add (local.get $a) (i32.shl (local.get $l1) (local.get $b))))))
            (br $packet_done)
            (br $packet)
            ) ;; $JMP_TABLE_2
            (local.set $a (call $read_thread_word))
            (local.set $b (call $read_thread_word))
            (global.set $eip (i32.load (call $g2w
              (i32.add (local.get $a) (i32.shl (local.get $l2) (local.get $b))))))
            (br $packet_done)
            (br $packet)
            ) ;; $JMP_TABLE_3
            (local.set $a (call $read_thread_word))
            (local.set $b (call $read_thread_word))
            (global.set $eip (i32.load (call $g2w
              (i32.add (local.get $a) (i32.shl (local.get $l3) (local.get $b))))))
            (br $packet_done)
            (br $packet)
          ))
        ;; CMP_RM32_JCC: opcodes 141..156
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 141))
                     (i32.le_u (local.get $code) (i32.const 156)))
          (then
            (block $CMP_RM32_JCC_15
            (block $CMP_RM32_JCC_14
            (block $CMP_RM32_JCC_13
            (block $CMP_RM32_JCC_12
            (block $CMP_RM32_JCC_11
            (block $CMP_RM32_JCC_10
            (block $CMP_RM32_JCC_9
            (block $CMP_RM32_JCC_8
            (block $CMP_RM32_JCC_7
            (block $CMP_RM32_JCC_6
            (block $CMP_RM32_JCC_5
            (block $CMP_RM32_JCC_4
            (block $CMP_RM32_JCC_3
            (block $CMP_RM32_JCC_2
            (block $CMP_RM32_JCC_1
            (block $CMP_RM32_JCC_0
              (br_table $CMP_RM32_JCC_0 $CMP_RM32_JCC_1 $CMP_RM32_JCC_2 $CMP_RM32_JCC_3 $CMP_RM32_JCC_4 $CMP_RM32_JCC_5 $CMP_RM32_JCC_6 $CMP_RM32_JCC_7 $CMP_RM32_JCC_8 $CMP_RM32_JCC_9 $CMP_RM32_JCC_10 $CMP_RM32_JCC_11 $CMP_RM32_JCC_12 $CMP_RM32_JCC_13 $CMP_RM32_JCC_14 $CMP_RM32_JCC_15 $CMP_RM32_JCC_0
                (i32.sub (local.get $code) (i32.const 141)))
            ) ;; $CMP_RM32_JCC_0
            (local.set $a (local.get $l0))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l0) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_1
            (local.set $a (local.get $l0))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l1) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_2
            (local.set $a (local.get $l0))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l2) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_3
            (local.set $a (local.get $l0))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l3) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_4
            (local.set $a (local.get $l1))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l0) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_5
            (local.set $a (local.get $l1))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l1) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_6
            (local.set $a (local.get $l1))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l2) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_7
            (local.set $a (local.get $l1))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l3) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_8
            (local.set $a (local.get $l2))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l0) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_9
            (local.set $a (local.get $l2))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l1) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_10
            (local.set $a (local.get $l2))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l2) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_11
            (local.set $a (local.get $l2))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l3) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_12
            (local.set $a (local.get $l3))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l0) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_13
            (local.set $a (local.get $l3))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l1) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_14
            (local.set $a (local.get $l3))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l2) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
            ) ;; $CMP_RM32_JCC_15
            (local.set $a (local.get $l3))
            (local.set $b (i32.load (call $g2w
              (i32.add (local.get $l3) (call $read_thread_word)))))
            (local.set $res (i32.sub (local.get $a) (local.get $b)))
            (call $set_flags_sub (local.get $a) (local.get $b) (local.get $res))
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
          ))
        ;; JCC: opcodes 157..157
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 157))
                     (i32.le_u (local.get $code) (i32.const 157)))
          (then
            (block $JCC_0
              (br_table $JCC_0 $JCC_0
                (i32.sub (local.get $code) (i32.const 157)))
            ) ;; $JCC_0
            (local.set $cc (call $read_thread_word))
            (local.set $target (call $read_thread_word))
            (local.set $fall (call $read_thread_word))
            (global.set $eip (if (result i32) (call $eval_cc (local.get $cc))
              (then (local.get $target)) (else (local.get $fall))))
            (br $packet_done)
            (br $packet)
          ))
        ;; JMP_I32: opcodes 158..158
        (if (i32.and (i32.ge_u (local.get $code) (i32.const 158))
                     (i32.le_u (local.get $code) (i32.const 158)))
          (then
            (block $JMP_I32_0
              (br_table $JMP_I32_0 $JMP_I32_0
                (i32.sub (local.get $code) (i32.const 158)))
            ) ;; $JMP_I32_0
            (global.set $eip (call $read_thread_word))
            (br $packet_done)
            (br $packet)
          ))
        (call $host_log_i32 (i32.const 0x5107BAD))
        (global.set $eip (i32.const 0))
        (br $packet_done)))

    (local.set $reg (i32.and (i32.shr_u (local.get $exports) (i32.const 0)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (call $set_reg (local.get $reg) (local.get $l0))))
    (local.set $reg (i32.and (i32.shr_u (local.get $exports) (i32.const 4)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (call $set_reg (local.get $reg) (local.get $l1))))
    (local.set $reg (i32.and (i32.shr_u (local.get $exports) (i32.const 8)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (call $set_reg (local.get $reg) (local.get $l2))))
    (local.set $reg (i32.and (i32.shr_u (local.get $exports) (i32.const 12)) (i32.const 15)))
    (if (i32.ne (local.get $reg) (i32.const 15))
      (then (call $set_reg (local.get $reg) (local.get $l3))))
  )

  ;; Opcode bases: EXPORT=1, STORE_ABS=33, COPY=37,
  ;; ADD=53, ADD_FLAGS=69, ADD_I32=85, SUB_I32=89,
  ;; AND_I32_FLAGS=93, SHR_U_I32_FLAGS=97,
  ;; LOAD8_U=101, LOAD32_ABS=117, SUB=121,
  ;; JMP_TABLE=137, CMP_RM32_JCC=141, JCC=157, JMP_I32=158.
