  ;; ============================================================
  ;; DIRECT3D 9 HANDLERS — generated by tools/gen_d3d9_stubs.js
  ;; IDirect3D9, IDirect3DDevice9, IDirect3DTexture9, IDirect3DSurface9.
  ;; Vtable order is the spec in tools/d3d9-methods.js — do not reorder.
  ;; ============================================================

  ;; The device window of a *windowed* D3D9 device, or 0 for fullscreen and
  ;; for no device at all. A windowed device's render target holds that
  ;; window's client area starting at (0,0) -- it is not a screen-coordinate
  ;; DirectDraw primary, and the compositor has to know which of the two it is
  ;; being handed. Pawn makes the distinction visible: it creates a
  ;; screen-sized STATIC child of its 360x400 main window and points the
  ;; device at the child, so the board pixels live at surface (0,0) while the
  ;; place they belong on screen is the main window's client origin.
  (global $d3d9_windowed_hwnd (mut i32) (i32.const 0))

  ;; ── IDirect3D9 — 17 methods ─────────────
  ;; IDirect3D9_QueryInterface — 3 args (incl. this)
  (func $handle_IDirect3D9_QueryInterface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3D9_AddRef — 1 args (incl. this)
  (func $handle_IDirect3D9_AddRef (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))
    (global.set $eax (local.get $rc))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3D9_Release — 1 args (incl. this)
  (func $handle_IDirect3D9_Release (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (if (i32.le_s (local.get $rc) (i32.const 0))
      (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))
      (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3D9_RegisterSoftwareDevice — 2 args (incl. this)
  (func $handle_IDirect3D9_RegisterSoftwareDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; The adapter mode list we advertise. One adapter, and for each of the
  ;; three formats a real D3D9 caller enumerates (X8R8G8B8 22, R5G6B5 23,
  ;; X1R5G5B5 24) the same three sizes. An app that finds zero modes for
  ;; every format concludes DirectX 9 is absent and quits, so this list is
  ;; load-bearing, not cosmetic.
  (func $d3d9_mode_count (param $format i32) (result i32)
    (if (i32.or (i32.eq (local.get $format) (i32.const 22))
          (i32.or (i32.eq (local.get $format) (i32.const 23))
                  (i32.eq (local.get $format) (i32.const 24))))
      (then (return (i32.const 3))))
    (i32.const 0))

  (func $d3d9_mode_width (param $mode i32) (result i32)
    (if (i32.eq (local.get $mode) (i32.const 1)) (then (return (i32.const 800))))
    (if (i32.eq (local.get $mode) (i32.const 2)) (then (return (i32.const 1024))))
    (i32.const 640))

  (func $d3d9_mode_height (param $mode i32) (result i32)
    (if (i32.eq (local.get $mode) (i32.const 1)) (then (return (i32.const 600))))
    (if (i32.eq (local.get $mode) (i32.const 2)) (then (return (i32.const 768))))
    (i32.const 480))

  ;; Fill a D3DDISPLAYMODE { UINT Width, Height, RefreshRate; D3DFORMAT Format }
  (func $d3d9_fill_mode (param $p_guest i32) (param $mode i32) (param $format i32)
    (if (i32.eqz (local.get $p_guest)) (then (return)))
    (call $gs32 (local.get $p_guest) (call $d3d9_mode_width (local.get $mode)))
    (call $gs32 (i32.add (local.get $p_guest) (i32.const 4)) (call $d3d9_mode_height (local.get $mode)))
    (call $gs32 (i32.add (local.get $p_guest) (i32.const 8)) (i32.const 60))
    (call $gs32 (i32.add (local.get $p_guest) (i32.const 12)) (local.get $format)))

  ;; Allocate a DirectDraw-style surface object (dx type 2, DDSURF2 vtable) so
  ;; every existing surface consumer — the rasterizer, $dx_present, Lock/Blt —
  ;; works on D3D9 surfaces unchanged. Entry fields match
  ;; $handle_IDirectDraw_CreateSurface: +12 w, +14 h, +16 bpp, +18 pitch,
  ;; +20 DIB (WASM addr), +24 vidmem bytes, +28 flags (1=primary, 4=offscreen).
  ;; Returns the COM object, or 0 when the heap or the object table is full.
  (func $d3d9_create_surface (param $w i32) (param $h i32) (param $bpp i32) (param $flags i32) (result i32)
    (local $pitch i32) (local $size i32) (local $dib_guest i32)
    (local $obj i32) (local $entry i32)
    (local.set $pitch (i32.and
      (i32.add (i32.mul (local.get $w) (i32.div_u (local.get $bpp) (i32.const 8))) (i32.const 3))
      (i32.const 0xFFFFFFFC)))
    (local.set $size (i32.mul (local.get $pitch) (local.get $h)))
    (local.set $dib_guest (call $heap_alloc (local.get $size)))
    ;; g2w(0) is the base of the guest image; never zero a surface from there.
    (if (i32.eqz (local.get $dib_guest)) (then (return (i32.const 0))))
    (call $zero_memory (call $g2w (local.get $dib_guest)) (local.get $size))
    (local.set $obj (call $dx_create_com_obj (i32.const 2) (global.get $DX_VTBL_DDSURF2)))
    (if (i32.eqz (local.get $obj)) (then (return (i32.const 0))))
    (local.set $entry (call $dx_from_this (local.get $obj)))
    (i32.store16 (i32.add (local.get $entry) (i32.const 12)) (local.get $w))
    (i32.store16 (i32.add (local.get $entry) (i32.const 14)) (local.get $h))
    (i32.store16 (i32.add (local.get $entry) (i32.const 16)) (local.get $bpp))
    (i32.store16 (i32.add (local.get $entry) (i32.const 18)) (local.get $pitch))
    (i32.store (i32.add (local.get $entry) (i32.const 20)) (call $g2w (local.get $dib_guest)))
    (i32.store (i32.add (local.get $entry) (i32.const 24)) (local.get $size))
    (i32.store (i32.add (local.get $entry) (i32.const 28)) (local.get $flags))
    (global.set $dx_vidmem_used (i32.add (global.get $dx_vidmem_used) (local.get $size)))
    (local.get $obj))

  ;; IDirect3D9_GetAdapterCount — 1 args (incl. this)
  (func $handle_IDirect3D9_GetAdapterCount (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 1))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3D9_GetAdapterIdentifier — 4 args (incl. this)
  (func $handle_IDirect3D9_GetAdapterIdentifier (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3D9_GetAdapterModeCount — 3 args (incl. this)
  ;; IDirect3D9_GetAdapterModeCount(this, Adapter, Format) — 3 args
  (func $handle_IDirect3D9_GetAdapterModeCount (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (call $d3d9_mode_count (local.get $arg2)))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3D9_EnumAdapterModes(this, Adapter, Format, Mode, pMode) — 5 args
  (func $handle_IDirect3D9_EnumAdapterModes (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (if (i32.ge_u (local.get $arg3) (call $d3d9_mode_count (local.get $arg2)))
      (then (global.set $eax (i32.const 0x8876086C))) ;; D3DERR_INVALIDCALL
      (else
        (call $d3d9_fill_mode (local.get $arg4) (local.get $arg3) (local.get $arg2))
        (global.set $eax (i32.const 0))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3D9_GetAdapterDisplayMode(this, Adapter, pMode) — 3 args.
  ;; Mode 0 (640x480) in X8R8G8B8 is the desktop we present into.
  (func $handle_IDirect3D9_GetAdapterDisplayMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $d3d9_fill_mode (local.get $arg2) (i32.const 0) (i32.const 22))
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3D9_CheckDeviceType — 6 args (incl. this)
  (func $handle_IDirect3D9_CheckDeviceType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3D9_CheckDeviceFormat — 7 args (incl. this)
  (func $handle_IDirect3D9_CheckDeviceFormat (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32))))

  ;; IDirect3D9_CheckDeviceMultiSampleType — 7 args (incl. this)
  (func $handle_IDirect3D9_CheckDeviceMultiSampleType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32))))

  ;; IDirect3D9_CheckDepthStencilMatch — 6 args (incl. this)
  (func $handle_IDirect3D9_CheckDepthStencilMatch (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3D9_CheckDeviceFormatConversion — 5 args (incl. this)
  (func $handle_IDirect3D9_CheckDeviceFormatConversion (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3D9_GetDeviceCaps — 4 args (incl. this)
  (func $handle_IDirect3D9_GetDeviceCaps (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3D9_GetAdapterMonitor — 2 args (incl. this)
  (func $handle_IDirect3D9_GetAdapterMonitor (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3D9_CreateDevice(this, Adapter, DeviceType, hFocusWindow,
  ;;                         BehaviorFlags, pPresentationParameters,
  ;;                         ppReturnedDeviceInterface) — 7 args.
  ;; Only 5 args arrive as locals; args 6 and 7 are read off the guest stack.
  ;; D3DPRESENT_PARAMETERS: +0 BackBufferWidth, +4 BackBufferHeight,
  ;;   +8 BackBufferFormat, +12 BackBufferCount, ... +24 SwapEffect,
  ;;   +28 hDeviceWindow, +32 Windowed.
  (func $handle_IDirect3D9_CreateDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $pp i32) (local $ppDev i32) (local $w i32) (local $h i32)
    (local $surf i32) (local $hwnd i32) (local $windowed i32) (local $cs i32)
    (local.set $pp (call $gl32 (i32.add (global.get $esp) (i32.const 24))))
    (local.set $ppDev (call $gl32 (i32.add (global.get $esp) (i32.const 28))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32)))
    (if (i32.eqz (local.get $ppDev)) (then
      (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
      (return)))
    (call $gs32 (local.get $ppDev) (i32.const 0))
    (if (local.get $pp) (then
      (local.set $w (call $gl32 (local.get $pp)))
      (local.set $h (call $gl32 (i32.add (local.get $pp) (i32.const 4))))
      (local.set $hwnd (call $gl32 (i32.add (local.get $pp) (i32.const 28))))
      (local.set $windowed (call $gl32 (i32.add (local.get $pp) (i32.const 32))))))
    (if (i32.eqz (local.get $hwnd)) (then (local.set $hwnd (local.get $arg3))))
    (if (local.get $hwnd) (then (global.set $dx_coop_hwnd (local.get $hwnd))))
    (global.set $d3d9_windowed_hwnd
      (select (local.get $hwnd) (i32.const 0) (local.get $windowed)))
    ;; A windowed device may leave the back-buffer size at 0 — that means "the
    ;; client area of the device window", which is also the only size Present
    ;; can land on without scaling. Fullscreen devices fall back to the
    ;; display mode instead.
    (if (i32.or (i32.eqz (local.get $w)) (i32.eqz (local.get $h))) (then
      (if (local.get $windowed)
        (then
          (local.set $cs (call $host_get_window_client_size (local.get $hwnd)))
          (local.set $w (i32.and (local.get $cs) (i32.const 0xFFFF)))
          (local.set $h (i32.shr_u (local.get $cs) (i32.const 16)))))
      (if (i32.eqz (local.get $w)) (then (local.set $w (global.get $dx_display_w))))
      (if (i32.eqz (local.get $h)) (then (local.set $h (global.get $dx_display_h))))))
    ;; The device's render target is the surface we present from, so it carries
    ;; the primary flag — EndScene blits it to the window's back-canvas.
    (local.set $surf (call $d3d9_create_surface (local.get $w) (local.get $h) (i32.const 32) (i32.const 1)))
    (if (i32.eqz (local.get $surf)) (then
      (global.set $eax (i32.const 0x8876017C)) ;; D3DERR_OUTOFVIDEOMEMORY
      (return)))
    ;; A fullscreen device owns the whole window; size it to the mode it asked
    ;; for. A windowed device must leave the app's own window geometry alone.
    (if (i32.eqz (local.get $windowed)) (then
      (if (call $dx_target_hwnd) (then
        (call $host_move_window (call $dx_target_hwnd)
          (i32.const 0) (i32.const 0) (local.get $w) (local.get $h) (i32.const 0))))))
    (call $d3dim_create_device (local.get $arg0) (local.get $surf)
      (local.get $ppDev) (global.get $DX_VTBL_D3DDEV9)))


  ;; ── IDirect3DDevice9 — 119 methods ─────────────
  ;; IDirect3DDevice9_QueryInterface — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_QueryInterface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_AddRef — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_AddRef (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))
    (global.set $eax (local.get $rc))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_Release — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_Release (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (if (i32.le_s (local.get $rc) (i32.const 0))
      (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))
      (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_TestCooperativeLevel — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_TestCooperativeLevel (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_GetAvailableTextureMem — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_GetAvailableTextureMem (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_EvictManagedResources — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_EvictManagedResources (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_GetDirect3D — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetDirect3D (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetDeviceCaps — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetDeviceCaps (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetDisplayMode — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetDisplayMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetCreationParameters — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetCreationParameters (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetCursorProperties — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetCursorProperties (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetCursorPosition — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetCursorPosition (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_ShowCursor — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_ShowCursor (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_CreateAdditionalSwapChain — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateAdditionalSwapChain (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetSwapChain — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetSwapChain (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $slot i32) (local $obj i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 16)))
    (if (i32.or (local.get $arg1) (i32.eqz (local.get $arg2)))
      (then
        (if (local.get $arg2) (then (call $gs32 (local.get $arg2) (i32.const 0))))
        (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
        (return)))
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (if (i32.eqz (local.get $entry))
      (then
        (call $gs32 (local.get $arg2) (i32.const 0))
        (global.set $eax (i32.const 0x8876086C))
        (return)))
    ;; A swap chain is a second COM interface over the device's same backing
    ;; slot: it therefore shares the device render target and reference count.
    (local.set $slot (call $dx_slot_of (local.get $entry)))
    (local.set $obj (call $dx_get_wrapper_for_vtbl
      (local.get $slot) (global.get $DX_VTBL_D3DSWAP9)))
    (i32.store offset=4 (local.get $entry)
      (i32.add (i32.load offset=4 (local.get $entry)) (i32.const 1)))
    (call $gs32 (local.get $arg2) (local.get $obj))
    (global.set $eax (i32.const 0)))

  ;; IDirect3DDevice9_GetNumberOfSwapChains — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_GetNumberOfSwapChains (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 1))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_Reset — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_Reset (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_Present(this, pSourceRect, pDestRect,
  ;;                          hDestWindowOverride, pDirtyRegion) — 5 args.
  ;; The render target is the surface the app drew into; push it to the
  ;; window's back-canvas. Sub-rect presents are not modelled — we always
  ;; present the whole target.
  (func $handle_IDirect3DDevice9_Present (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 24)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (local.get $rt) (then (call $dx_present (local.get $rt))))
    (global.set $eax (i32.const 0)))

  ;; IDirect3DDevice9_GetBackBuffer(this, iSwapChain, iBackBuffer, Type,
  ;;                                ppBackBuffer) — 5 args.
  ;; We render straight into the device's render target, so the back buffer is
  ;; that surface seen through the IDirect3DSurface9 vtable.
  (func $handle_IDirect3DDevice9_GetBackBuffer (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32) (local $slot i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 24)))
    (if (i32.eqz (local.get $arg4)) (then
      (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
      (return)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (i32.eqz (local.get $rt)) (then
      (call $gs32 (local.get $arg4) (i32.const 0))
      (global.set $eax (i32.const 0x8876086C))
      (return)))
    (local.set $slot (call $dx_slot_of (local.get $rt)))
    ;; Handing out a reference — the app will Release it.
    (i32.store (i32.add (local.get $rt) (i32.const 4))
      (i32.add (i32.load (i32.add (local.get $rt) (i32.const 4))) (i32.const 1)))
    (call $gs32 (local.get $arg4)
      (call $dx_get_wrapper_for_vtbl (local.get $slot) (global.get $DX_VTBL_D3DSURF9)))
    (global.set $eax (i32.const 0)))

  ;; IDirect3DDevice9_GetRasterStatus — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetRasterStatus (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetDialogBoxMode — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetDialogBoxMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetGammaRamp — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetGammaRamp (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetGammaRamp — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetGammaRamp (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_CreateTexture — 8 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 36))))

  ;; IDirect3DDevice9_CreateVolumeTexture — 9 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateVolumeTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 40))))

  ;; IDirect3DDevice9_CreateCubeTexture — 7 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateCubeTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32))))

  ;; IDirect3DDevice9_CreateVertexBuffer — 6 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateVertexBuffer (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3DDevice9_CreateIndexBuffer — 6 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateIndexBuffer (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3DDevice9_CreateRenderTarget — 8 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateRenderTarget (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 36))))

  ;; IDirect3DDevice9_CreateDepthStencilSurface — 8 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateDepthStencilSurface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 36))))

  ;; IDirect3DDevice9_UpdateSurface — 5 args (incl. this)
  (func $handle_IDirect3DDevice9_UpdateSurface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DDevice9_UpdateTexture — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_UpdateTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetRenderTargetData — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetRenderTargetData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetFrontBufferData — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetFrontBufferData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_StretchRect — 6 args (incl. this)
  (func $handle_IDirect3DDevice9_StretchRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3DDevice9_ColorFill — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_ColorFill (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_CreateOffscreenPlainSurface — 7 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateOffscreenPlainSurface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32))))

  ;; IDirect3DDevice9_SetRenderTarget — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetRenderTarget (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetRenderTarget — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetRenderTarget (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetDepthStencilSurface — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetDepthStencilSurface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetDepthStencilSurface — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetDepthStencilSurface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_BeginScene — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_BeginScene (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_EndScene — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_EndScene (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_Clear(this, Count, pRects, Flags, Color, Z, Stencil) —
  ;; 7 args. Only D3DCLEAR_TARGET (0x1) has anything to clear here; the Z and
  ;; stencil planes are owned by the d3dim z-buffer, which the rasterizer
  ;; resets per scene. pRects is ignored — every caller so far clears the
  ;; whole target.
  (func $handle_IDirect3DDevice9_Clear (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32) (local $dib i32) (local $w i32) (local $h i32)
    (local $pitch i32) (local $x i32) (local $y i32) (local $rowbase i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 32)))
    (global.set $eax (i32.const 0))
    (if (i32.eqz (i32.and (local.get $arg3) (i32.const 1))) (then (return)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (i32.eqz (local.get $rt)) (then (return)))
    (local.set $dib (i32.load (i32.add (local.get $rt) (i32.const 20))))
    (if (i32.eqz (local.get $dib)) (then (return)))
    ;; Our D3D9 render targets are always 32bpp (see $handle_IDirect3D9_CreateDevice).
    (if (i32.ne (i32.load16_u (i32.add (local.get $rt) (i32.const 16))) (i32.const 32))
      (then (return)))
    (local.set $w (i32.load16_u (i32.add (local.get $rt) (i32.const 12))))
    (local.set $h (i32.load16_u (i32.add (local.get $rt) (i32.const 14))))
    (local.set $pitch (i32.load16_u (i32.add (local.get $rt) (i32.const 18))))
    (local.set $y (i32.const 0))
    (block $rows_done (loop $row
      (br_if $rows_done (i32.ge_u (local.get $y) (local.get $h)))
      (local.set $rowbase (i32.add (local.get $dib) (i32.mul (local.get $y) (local.get $pitch))))
      (local.set $x (i32.const 0))
      (block $cols_done (loop $col
        (br_if $cols_done (i32.ge_u (local.get $x) (local.get $w)))
        (i32.store (i32.add (local.get $rowbase) (i32.mul (local.get $x) (i32.const 4)))
          (local.get $arg4))
        (local.set $x (i32.add (local.get $x) (i32.const 1)))
        (br $col)))
      (local.set $y (i32.add (local.get $y) (i32.const 1)))
      (br $row))))

  ;; IDirect3DDevice9_SetTransform — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetTransform (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetTransform — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetTransform (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_MultiplyTransform — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_MultiplyTransform (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetViewport — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetViewport (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetViewport — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetViewport (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetMaterial — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetMaterial (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetMaterial — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetMaterial (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetLight — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetLight (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetLight — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetLight (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_LightEnable — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_LightEnable (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetLightEnable — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetLightEnable (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetClipPlane — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetClipPlane (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetClipPlane — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetClipPlane (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetRenderState — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetRenderState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetRenderState — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetRenderState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_CreateStateBlock — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateStateBlock (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_BeginStateBlock — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_BeginStateBlock (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_EndStateBlock — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_EndStateBlock (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetClipStatus — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetClipStatus (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetClipStatus — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetClipStatus (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetTexture — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetTexture — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetTexture (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetTextureStageState — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetTextureStageState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetTextureStageState — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetTextureStageState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetSamplerState — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetSamplerState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetSamplerState — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetSamplerState (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_ValidateDevice — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_ValidateDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetPaletteEntries — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetPaletteEntries (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetPaletteEntries — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetPaletteEntries (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetCurrentTexturePalette — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetCurrentTexturePalette (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetCurrentTexturePalette — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetCurrentTexturePalette (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetScissorRect — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetScissorRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetScissorRect — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetScissorRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetSoftwareVertexProcessing — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetSoftwareVertexProcessing (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetSoftwareVertexProcessing — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_GetSoftwareVertexProcessing (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_SetNPatchMode — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetNPatchMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetNPatchMode — 1 args (incl. this)
  (func $handle_IDirect3DDevice9_GetNPatchMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DDevice9_DrawPrimitive — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawPrimitive (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_DrawIndexedPrimitive — 7 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawIndexedPrimitive (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 32))))

  ;; IDirect3DDevice9_DrawPrimitiveUP — 5 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawPrimitiveUP (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DDevice9_DrawIndexedPrimitiveUP — 9 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawIndexedPrimitiveUP (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 40))))

  ;; IDirect3DDevice9_ProcessVertices — 6 args (incl. this)
  (func $handle_IDirect3DDevice9_ProcessVertices (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 28))))

  ;; IDirect3DDevice9_CreateVertexDeclaration — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateVertexDeclaration (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetVertexDeclaration — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetVertexDeclaration (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetVertexDeclaration — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetVertexDeclaration (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetFVF — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetFVF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetFVF — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetFVF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_CreateVertexShader — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateVertexShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (if (local.get $arg2) (then (call $gs32 (local.get $arg2) (i32.const 0))))
    (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetVertexShader — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetVertexShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    ;; NULL selects the fixed-function vertex pipeline used by SDL's textured
    ;; quad renderer. Programmable shader objects are not exposed yet.
    (global.set $eax
      (select (i32.const 0x8876086C) (i32.const 0) (local.get $arg1)))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetVertexShader — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetVertexShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetVertexShaderConstantF — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetVertexShaderConstantF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetVertexShaderConstantF — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetVertexShaderConstantF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetVertexShaderConstantI — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetVertexShaderConstantI (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetVertexShaderConstantI — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetVertexShaderConstantI (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetVertexShaderConstantB — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetVertexShaderConstantB (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetVertexShaderConstantB — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetVertexShaderConstantB (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetStreamSource — 5 args (incl. this)
  (func $handle_IDirect3DDevice9_SetStreamSource (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DDevice9_GetStreamSource — 5 args (incl. this)
  (func $handle_IDirect3DDevice9_GetStreamSource (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DDevice9_SetStreamSourceFreq — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_SetStreamSourceFreq (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_GetStreamSourceFreq — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_GetStreamSourceFreq (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetIndices — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetIndices (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetIndices — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetIndices (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_CreatePixelShader — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreatePixelShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (if (local.get $arg2) (then (call $gs32 (local.get $arg2) (i32.const 0))))
    (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DDevice9_SetPixelShader — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_SetPixelShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    ;; NULL selects fixed-function texture/color stages.
    (global.set $eax
      (select (i32.const 0x8876086C) (i32.const 0) (local.get $arg1)))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_GetPixelShader — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_GetPixelShader (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_SetPixelShaderConstantF — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetPixelShaderConstantF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetPixelShaderConstantF — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetPixelShaderConstantF (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetPixelShaderConstantI — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetPixelShaderConstantI (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetPixelShaderConstantI — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetPixelShaderConstantI (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_SetPixelShaderConstantB — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_SetPixelShaderConstantB (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_GetPixelShaderConstantB — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_GetPixelShaderConstantB (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_DrawRectPatch — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawRectPatch (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_DrawTriPatch — 4 args (incl. this)
  (func $handle_IDirect3DDevice9_DrawTriPatch (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DDevice9_DeletePatch — 2 args (incl. this)
  (func $handle_IDirect3DDevice9_DeletePatch (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DDevice9_CreateQuery — 3 args (incl. this)
  (func $handle_IDirect3DDevice9_CreateQuery (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))


  ;; ── IDirect3DTexture9 — 22 methods ─────────────
  ;; IDirect3DTexture9_QueryInterface — 3 args (incl. this)
  (func $handle_IDirect3DTexture9_QueryInterface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DTexture9_AddRef — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_AddRef (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))
    (global.set $eax (local.get $rc))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_Release — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_Release (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (if (i32.le_s (local.get $rc) (i32.const 0))
      (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))
      (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_GetDevice — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_GetDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_SetPrivateData — 5 args (incl. this)
  (func $handle_IDirect3DTexture9_SetPrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DTexture9_GetPrivateData — 4 args (incl. this)
  (func $handle_IDirect3DTexture9_GetPrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DTexture9_FreePrivateData — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_FreePrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_SetPriority — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_SetPriority (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_GetPriority — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GetPriority (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_PreLoad — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_PreLoad (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_GetType — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GetType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_SetLOD — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_SetLOD (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_GetLOD — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GetLOD (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_GetLevelCount — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GetLevelCount (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_SetAutoGenFilterType — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_SetAutoGenFilterType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_GetAutoGenFilterType — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GetAutoGenFilterType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_GenerateMipSubLevels — 1 args (incl. this)
  (func $handle_IDirect3DTexture9_GenerateMipSubLevels (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DTexture9_GetLevelDesc — 3 args (incl. this)
  (func $handle_IDirect3DTexture9_GetLevelDesc (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DTexture9_GetSurfaceLevel — 3 args (incl. this)
  (func $handle_IDirect3DTexture9_GetSurfaceLevel (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DTexture9_LockRect — 5 args (incl. this)
  (func $handle_IDirect3DTexture9_LockRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DTexture9_UnlockRect — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_UnlockRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DTexture9_AddDirtyRect — 2 args (incl. this)
  (func $handle_IDirect3DTexture9_AddDirtyRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))


  ;; ── IDirect3DSurface9 — 17 methods ─────────────
  ;; IDirect3DSurface9_QueryInterface — 3 args (incl. this)
  (func $handle_IDirect3DSurface9_QueryInterface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DSurface9_AddRef — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_AddRef (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.add (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc))
    (global.set $eax (local.get $rc))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_Release — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_Release (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.sub (i32.load (i32.add (local.get $entry) (i32.const 4))) (i32.const 1)))
    (if (i32.le_s (local.get $rc) (i32.const 0))
      (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))
      (else (i32.store (i32.add (local.get $entry) (i32.const 4)) (local.get $rc)) (global.set $eax (local.get $rc))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_GetDevice — 2 args (incl. this)
  (func $handle_IDirect3DSurface9_GetDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DSurface9_SetPrivateData — 5 args (incl. this)
  (func $handle_IDirect3DSurface9_SetPrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 24))))

  ;; IDirect3DSurface9_GetPrivateData — 4 args (incl. this)
  (func $handle_IDirect3DSurface9_GetPrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DSurface9_FreePrivateData — 2 args (incl. this)
  (func $handle_IDirect3DSurface9_FreePrivateData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DSurface9_SetPriority — 2 args (incl. this)
  (func $handle_IDirect3DSurface9_SetPriority (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DSurface9_GetPriority — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_GetPriority (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_PreLoad — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_PreLoad (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_GetType — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_GetType (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_GetContainer — 3 args (incl. this)
  (func $handle_IDirect3DSurface9_GetContainer (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $crash_unimplemented (local.get $name_ptr))
    (global.set $esp (i32.add (global.get $esp) (i32.const 16))))

  ;; IDirect3DSurface9_GetDesc — 2 args (incl. this)
  (func $handle_IDirect3DSurface9_GetDesc (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  ;; IDirect3DSurface9_LockRect — 4 args (incl. this)
  (func $handle_IDirect3DSurface9_LockRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 20))))

  ;; IDirect3DSurface9_UnlockRect — 1 args (incl. this)
  (func $handle_IDirect3DSurface9_UnlockRect (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; IDirect3DSurface9_GetDC(this, phdc) — same DIB-backed DC binding the
  ;; DirectDraw surfaces use: hdc 0x200000 + slot resolves to this surface.
  (func $handle_IDirect3DSurface9_GetDC (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $hdc i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 12)))
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (if (i32.or (i32.eqz (local.get $entry)) (i32.eqz (local.get $arg1))) (then
      (global.set $eax (i32.const 0x8876086C)) ;; D3DERR_INVALIDCALL
      (return)))
    (local.set $hdc (i32.add (i32.const 0x200000) (call $dx_slot_of (local.get $entry))))
    (if (call $gdi_dx_dc_bind (local.get $hdc))
      (then
        (call $gs32 (local.get $arg1) (local.get $hdc))
        (global.set $eax (i32.const 0)))
      (else (global.set $eax (i32.const 0x8876086C)))))

  ;; IDirect3DSurface9_ReleaseDC(this, hdc). Unlike the DirectDraw twin this
  ;; does NOT present — under D3D9 the frame reaches the screen on Present.
  (func $handle_IDirect3DSurface9_ReleaseDC (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (call $gdi_dx_dc_release (local.get $arg1))
    (global.set $eax (i32.const 0))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))


  ;; ── Direct3DCreate9 ───────────────────────────────────────────────
  ;; Apps LoadLibraryA("d3d9.dll") + GetProcAddress("Direct3DCreate9"); the
  ;; name-keyed thunk fallback in $handle_GetProcAddress lands here.
  ;; arg0 = SDKVersion (ignored — we answer every SDK level).
  ;; DX object type 34: the first id past the OLE/DirectAnimation range.
  (func $handle_Direct3DCreate9 (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (call $dx_create_com_obj (i32.const 34) (global.get $DX_VTBL_D3D9)))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  ;; ── IDirect3DSwapChain9 — thin view over IDirect3DDevice9 ─────────
  (func $handle_IDirect3DSwapChain9_QueryInterface (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 16)))
    (if (i32.eqz (local.get $arg2))
      (then (global.set $eax (i32.const 0x80004003)) (return)))
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (i32.store offset=4 (local.get $entry)
      (i32.add (i32.load offset=4 (local.get $entry)) (i32.const 1)))
    (call $gs32 (local.get $arg2) (local.get $arg0))
    (global.set $eax (i32.const 0)))

  (func $handle_IDirect3DSwapChain9_AddRef (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.add (i32.load offset=4 (local.get $entry)) (i32.const 1)))
    (i32.store offset=4 (local.get $entry) (local.get $rc))
    (global.set $eax (local.get $rc))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  (func $handle_IDirect3DSwapChain9_Release (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $rc i32)
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $rc (i32.sub (i32.load offset=4 (local.get $entry)) (i32.const 1)))
    (if (i32.le_s (local.get $rc) (i32.const 0))
      (then (call $dx_free (local.get $entry)) (global.set $eax (i32.const 0)))
      (else
        (i32.store offset=4 (local.get $entry) (local.get $rc))
        (global.set $eax (local.get $rc))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 8))))

  (func $handle_IDirect3DSwapChain9_Present (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 28)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (local.get $rt) (then (call $dx_present (local.get $rt))))
    (global.set $eax (i32.const 0)))

  (func $handle_IDirect3DSwapChain9_GetFrontBufferData (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (global.set $eax (i32.const 0x8876086C))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  (func $handle_IDirect3DSwapChain9_GetBackBuffer (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32) (local $slot i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 20)))
    (if (i32.or (local.get $arg1) (i32.eqz (local.get $arg3)))
      (then
        (if (local.get $arg3) (then (call $gs32 (local.get $arg3) (i32.const 0))))
        (global.set $eax (i32.const 0x8876086C))
        (return)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (i32.eqz (local.get $rt))
      (then
        (call $gs32 (local.get $arg3) (i32.const 0))
        (global.set $eax (i32.const 0x8876086C))
        (return)))
    (local.set $slot (call $dx_slot_of (local.get $rt)))
    (i32.store offset=4 (local.get $rt)
      (i32.add (i32.load offset=4 (local.get $rt)) (i32.const 1)))
    (call $gs32 (local.get $arg3)
      (call $dx_get_wrapper_for_vtbl (local.get $slot) (global.get $DX_VTBL_D3DSURF9)))
    (global.set $eax (i32.const 0)))

  (func $handle_IDirect3DSwapChain9_GetRasterStatus (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (if (local.get $arg1)
      (then
        (call $gs32 (local.get $arg1) (i32.const 0))
        (call $gs32 (i32.add (local.get $arg1) (i32.const 4)) (i32.const 0))
        (global.set $eax (i32.const 0)))
      (else (global.set $eax (i32.const 0x8876086C))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  (func $handle_IDirect3DSwapChain9_GetDisplayMode (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32) (local $w i32) (local $h i32)
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (i32.or (i32.eqz (local.get $arg1)) (i32.eqz (local.get $rt)))
      (then (global.set $eax (i32.const 0x8876086C)))
      (else
        (local.set $w (i32.load16_u offset=12 (local.get $rt)))
        (local.set $h (i32.load16_u offset=14 (local.get $rt)))
        (call $gs32 (local.get $arg1) (local.get $w))
        (call $gs32 (i32.add (local.get $arg1) (i32.const 4)) (local.get $h))
        (call $gs32 (i32.add (local.get $arg1) (i32.const 8)) (i32.const 60))
        (call $gs32 (i32.add (local.get $arg1) (i32.const 12)) (i32.const 22))
        (global.set $eax (i32.const 0))))
    (global.set $esp (i32.add (global.get $esp) (i32.const 12))))

  (func $handle_IDirect3DSwapChain9_GetDevice (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $entry i32) (local $slot i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 12)))
    (if (i32.eqz (local.get $arg1))
      (then (global.set $eax (i32.const 0x8876086C)) (return)))
    (local.set $entry (call $dx_from_this (local.get $arg0)))
    (local.set $slot (call $dx_slot_of (local.get $entry)))
    (i32.store offset=4 (local.get $entry)
      (i32.add (i32.load offset=4 (local.get $entry)) (i32.const 1)))
    (call $gs32 (local.get $arg1)
      (call $dx_get_wrapper_for_vtbl (local.get $slot) (global.get $DX_VTBL_D3DDEV9)))
    (global.set $eax (i32.const 0)))

  (func $handle_IDirect3DSwapChain9_GetPresentParameters (param $arg0 i32) (param $arg1 i32) (param $arg2 i32) (param $arg3 i32) (param $arg4 i32) (param $name_ptr i32)
    (local $rt i32) (local $w i32) (local $h i32) (local $windowed i32)
    (global.set $esp (i32.add (global.get $esp) (i32.const 12)))
    (local.set $rt (call $d3ddev_rt_entry (local.get $arg0)))
    (if (i32.or (i32.eqz (local.get $arg1)) (i32.eqz (local.get $rt)))
      (then (global.set $eax (i32.const 0x8876086C)) (return)))
    (local.set $w (i32.load16_u offset=12 (local.get $rt)))
    (local.set $h (i32.load16_u offset=14 (local.get $rt)))
    (local.set $windowed (i32.ne (global.get $d3d9_windowed_hwnd) (i32.const 0)))
    (call $zero_memory (call $g2w (local.get $arg1)) (i32.const 56))
    (call $gs32 (local.get $arg1) (local.get $w))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 4)) (local.get $h))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 8)) (i32.const 22))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 12)) (i32.const 1))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 24)) (i32.const 1))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 28))
      (global.get $d3d9_windowed_hwnd))
    (call $gs32 (i32.add (local.get $arg1) (i32.const 32)) (local.get $windowed))
    (global.set $eax (i32.const 0)))
