  ;; ---- WAT-native WinHelp document core ------------------------------
  ;;
  ;; This is the first migration slice away from the semantic JS HLP
  ;; parser.  The canonical file bytes and directory index are WAT-owned.
  ;; UI cutover happens only after the remaining topic parsers are ready.

  (global $HELP_MAX_FILE_BYTES i32 (i32.const 0x02000000))
  (global $HELP_MAX_DIRECTORY_ENTRIES i32 (i32.const 4096))
  (global $HELP_MAX_BTREE_DEPTH i32 (i32.const 16))
  (global $HELP_MAX_BTREE_PAGES i32 (i32.const 65536))
  (global $HELP_MAX_TOPICS i32 (i32.const 65536))
  (global $HELP_MAX_PHRASES i32 (i32.const 65536))
  (global $HELP_MAX_PHRASE_BYTES i32 (i32.const 65536))
  (global $HELP_MAX_TOPIC_LINKS i32 (i32.const 262144))
  (global $HELP_MAX_TOPIC_TOKENS i32 (i32.const 262144))
  (global $HELP_MAX_DECOMPRESSED_TOPIC_BYTES i32 (i32.const 0x00400000))
  (global $HELP_MAX_FONT_FACES i32 (i32.const 4096))
  (global $HELP_MAX_FONT_DESCRIPTORS i32 (i32.const 65536))
  (global $HELP_MAX_BITMAP_RESOURCES i32 (i32.const 4096))
  (global $HELP_MAX_BITMAP_BYTES i32 (i32.const 0x01000000))
  (global $HELP_MAX_BITMAP_INTERMEDIATE_BYTES i32 (i32.const 0x04000000))
  (global $HELP_MAX_KEYWORDS i32 (i32.const 65536))
  (global $HELP_MAX_KEYWORD_POSTINGS i32 (i32.const 262144))
  (global $HELP_MAX_CNT_BYTES i32 (i32.const 0x00100000))
  (global $HELP_MAX_CNT_NODES i32 (i32.const 16384))
  (global $HELP_MAX_CNT_DEPTH i32 (i32.const 64))
  (global $HELP_MAX_WINDOWS i32 (i32.const 256))

  ;; Stable parser errors. Keep the first failure and its file offset.
  (global $HELP_ERROR_NONE i32 (i32.const 0))
  (global $HELP_ERROR_BAD_ARGUMENT i32 (i32.const 1))
  (global $HELP_ERROR_ALLOCATION i32 (i32.const 2))
  (global $HELP_ERROR_BAD_OUTER_HEADER i32 (i32.const 3))
  (global $HELP_ERROR_BAD_FILE_HEADER i32 (i32.const 4))
  (global $HELP_ERROR_DIRECTORY_BTREE i32 (i32.const 5))
  (global $HELP_ERROR_CAPACITY i32 (i32.const 6))
  (global $HELP_ERROR_VFS i32 (i32.const 7))
  (global $HELP_ERROR_MISSING_INTERNAL i32 (i32.const 8))
  (global $HELP_ERROR_SYSTEM i32 (i32.const 9))
  (global $HELP_ERROR_TOPIC_INDEX i32 (i32.const 10))
  (global $HELP_ERROR_CONTEXT_INDEX i32 (i32.const 11))
  (global $HELP_ERROR_PHRASE_TABLE i32 (i32.const 12))
  (global $HELP_ERROR_TOPIC_RECORD i32 (i32.const 13))
  (global $HELP_ERROR_TOPIC_FORMAT i32 (i32.const 14))
  (global $HELP_ERROR_FONT_TABLE i32 (i32.const 15))
  (global $HELP_ERROR_BITMAP_TABLE i32 (i32.const 16))
  (global $HELP_ERROR_KEYWORD_INDEX i32 (i32.const 17))
  (global $HELP_ERROR_CNT i32 (i32.const 18))

  ;; WinHelp command values from winuser.h. HELP_CONTENTS and HELP_INDEX are
  ;; the same legacy command value.
  (global $HELP_COMMAND_CONTEXT i32 (i32.const 0x0001))
  (global $HELP_COMMAND_QUIT i32 (i32.const 0x0002))
  (global $HELP_COMMAND_CONTENTS i32 (i32.const 0x0003))
  (global $HELP_COMMAND_SETCONTENTS i32 (i32.const 0x0005))
  (global $HELP_COMMAND_CONTEXTPOPUP i32 (i32.const 0x0008))
  (global $HELP_COMMAND_CONTEXTMENU i32 (i32.const 0x000a))
  (global $HELP_COMMAND_FINDER i32 (i32.const 0x000b))
  (global $HELP_COMMAND_WM_HELP i32 (i32.const 0x000c))
  (global $HELP_COMMAND_KEY i32 (i32.const 0x0101))
  (global $HELP_COMMAND_MACRO i32 (i32.const 0x0102))
  (global $HELP_COMMAND_PARTIALKEY i32 (i32.const 0x0105))
  (global $HELP_COMMAND_MULTIKEY i32 (i32.const 0x0201))
  (global $HELP_COMMAND_SETWINPOS i32 (i32.const 0x0203))

  ;; Dispatcher diagnostics are deliberately separate from file parser errors.
  (global $HELP_DISPATCH_NONE i32 (i32.const 0))
  (global $HELP_DISPATCH_ACCEPTED i32 (i32.const 1))
  (global $HELP_DISPATCH_NO_DOCUMENT i32 (i32.const 2))
  (global $HELP_DISPATCH_OWNER_MISMATCH i32 (i32.const 3))
  (global $HELP_DISPATCH_UNRESOLVED i32 (i32.const 4))
  (global $HELP_DISPATCH_BAD_DATA i32 (i32.const 5))
  (global $HELP_DISPATCH_UNSUPPORTED i32 (i32.const 6))
  (global $HELP_DISPATCH_LOAD_FAILED i32 (i32.const 7))

  ;; One canonical viewer session. Modes are 0=idle, 1=topic, 2=popup,
  ;; 3=Topics dialog, and 4=Index dialog with an optional prefix selection.
  (global $help_session_owner (mut i32) (i32.const 0))
  (global $help_session_topic_ref (mut i32) (i32.const -1))
  (global $help_session_topic_index (mut i32) (i32.const -1))
  (global $help_session_contents_override (mut i32) (i32.const -1))
  (global $help_session_mode (mut i32) (i32.const 0))
  (global $help_session_keyword_index (mut i32) (i32.const -1))
  (global $help_session_last_command (mut i32) (i32.const 0))
  (global $help_session_status (mut i32) (i32.const 0))
  ;; -1 retains the canonical main viewer presentation. Non-negative values
  ;; select a normalized |SYSTEM type-6 HelpWindow record for normal jumps.
  (global $help_session_window_index (mut i32) (i32.const -1))
  (global $help_topics_contents_selection (mut i32) (i32.const -1))
  (global $help_topics_first_visible (mut i32) (i32.const 0))
  (global $help_topics_return_mode (mut i32) (i32.const 0))

  ;; HelpDocument storage. Guest pointers are retained for HeapFree; the
  ;; corresponding WA pointers are used by the parser and test inspection.
  (global $help_doc_file_ga (mut i32) (i32.const 0))
  (global $help_doc_file_wa (mut i32) (i32.const 0))
  (global $help_doc_file_size (mut i32) (i32.const 0))
  (global $help_doc_path_ga (mut i32) (i32.const 0))
  (global $help_doc_path_wa (mut i32) (i32.const 0))
  (global $help_doc_path_len (mut i32) (i32.const 0))
  (global $help_doc_meta_ga (mut i32) (i32.const 0))
  (global $help_doc_meta_wa (mut i32) (i32.const 0))
  (global $help_doc_directory_ga (mut i32) (i32.const 0))
  (global $help_doc_directory_wa (mut i32) (i32.const 0))
  (global $help_doc_directory_count (mut i32) (i32.const 0))
  (global $help_doc_topics_ga (mut i32) (i32.const 0))
  (global $help_doc_topics_wa (mut i32) (i32.const 0))
  (global $help_doc_topic_count (mut i32) (i32.const 0))
  (global $help_doc_contexts_ga (mut i32) (i32.const 0))
  (global $help_doc_contexts_wa (mut i32) (i32.const 0))
  (global $help_doc_context_count (mut i32) (i32.const 0))
  ;; |CONTEXT entries dropped at load because they named no topic header.
  ;; Visible on purpose: a large count means the topic-header scan is wrong,
  ;; not that the file carries stale entries.
  (global $help_doc_context_dropped (mut i32) (i32.const 0))
  (global $help_doc_maps_ga (mut i32) (i32.const 0))
  (global $help_doc_maps_wa (mut i32) (i32.const 0))
  (global $help_doc_map_count (mut i32) (i32.const 0))
  (global $help_doc_phrase_offsets_ga (mut i32) (i32.const 0))
  (global $help_doc_phrase_offsets_wa (mut i32) (i32.const 0))
  (global $help_doc_phrase_image_ga (mut i32) (i32.const 0))
  (global $help_doc_phrase_image_wa (mut i32) (i32.const 0))
  (global $help_doc_phrase_count (mut i32) (i32.const 0))
  (global $help_doc_phrase_image_size (mut i32) (i32.const 0))
  ;; 0=no phrase table, 1=Hall |PhrIndex/|PhrImage, 2=legacy |Phrases.
  (global $help_doc_phrase_mode (mut i32) (i32.const 0))
  (global $help_doc_display_record_count (mut i32) (i32.const 0))
  (global $help_doc_paragraph_count (mut i32) (i32.const 0))
  (global $help_doc_table_count (mut i32) (i32.const 0))
  (global $help_doc_format_command_count (mut i32) (i32.const 0))
  (global $help_doc_font_faces_ga (mut i32) (i32.const 0))
  (global $help_doc_font_faces_wa (mut i32) (i32.const 0))
  (global $help_doc_font_face_count (mut i32) (i32.const 0))
  (global $help_doc_fonts_ga (mut i32) (i32.const 0))
  (global $help_doc_fonts_wa (mut i32) (i32.const 0))
  (global $help_doc_font_count (mut i32) (i32.const 0))
  ;; 0=old descriptors with half-point height, 1=new/MVB twip metrics.
  (global $help_doc_font_metric_mode (mut i32) (i32.const 0))
  (global $help_doc_bitmaps_ga (mut i32) (i32.const 0))
  (global $help_doc_bitmaps_wa (mut i32) (i32.const 0))
  (global $help_doc_bitmap_count (mut i32) (i32.const 0))
  (global $help_doc_keywords_ga (mut i32) (i32.const 0))
  (global $help_doc_keywords_wa (mut i32) (i32.const 0))
  (global $help_doc_keyword_count (mut i32) (i32.const 0))
  (global $help_doc_keyword_postings_ga (mut i32) (i32.const 0))
  (global $help_doc_keyword_postings_wa (mut i32) (i32.const 0))
  (global $help_doc_keyword_posting_count (mut i32) (i32.const 0))
  (global $help_doc_cnt_file_ga (mut i32) (i32.const 0))
  (global $help_doc_cnt_file_wa (mut i32) (i32.const 0))
  (global $help_doc_cnt_file_size (mut i32) (i32.const 0))
  (global $help_doc_cnt_nodes_ga (mut i32) (i32.const 0))
  (global $help_doc_cnt_nodes_wa (mut i32) (i32.const 0))
  (global $help_doc_cnt_node_count (mut i32) (i32.const 0))
  (global $help_doc_cnt_title_wa (mut i32) (i32.const 0))
  (global $help_doc_cnt_title_len (mut i32) (i32.const 0))
  (global $help_doc_cnt_base_wa (mut i32) (i32.const 0))
  (global $help_doc_cnt_base_len (mut i32) (i32.const 0))
  (global $help_doc_system_minor (mut i32) (i32.const 0))
  (global $help_doc_system_major (mut i32) (i32.const 0))
  (global $help_doc_system_flags (mut i32) (i32.const 0))
  (global $help_doc_system_date (mut i32) (i32.const 0))
  (global $help_doc_title_off (mut i32) (i32.const 0))
  (global $help_doc_title_len (mut i32) (i32.const 0))
  (global $help_doc_contents_ref (mut i32) (i32.const -1))
  (global $help_doc_cnt_off (mut i32) (i32.const 0))
  (global $help_doc_cnt_len (mut i32) (i32.const 0))
  (global $help_doc_windows_ga (mut i32) (i32.const 0))
  (global $help_doc_windows_wa (mut i32) (i32.const 0))
  (global $help_doc_window_count (mut i32) (i32.const 0))
  (global $help_last_error (mut i32) (i32.const 0))
  (global $help_last_error_offset (mut i32) (i32.const 0))

  ;; External hotspot navigation suspends at most four complete documents.
  ;; Each 412-byte heap record owns the detached document roots plus the
  ;; session/view-navigation scalars needed by cross-file Back or popup close.
  ;; Bytes 336..399 preserve the shared 16-entry Back stack contents; the
  ;; trailing triple owns the normalized secondary-window table.
  (global $HELP_DOCUMENT_SNAPSHOT_SIZE i32 (i32.const 412))
  (global $HELP_MAX_DOCUMENT_SNAPSHOTS i32 (i32.const 4))
  (global $help_document_snapshots_ga (mut i32) (i32.const 0))
  (global $help_document_snapshot_count (mut i32) (i32.const 0))

  ;; HelpInternalFile is 20 bytes:
  ;;   hash:u32, name_off:u32, name_len:u16, flags:u16,
  ;;   data_off:u32, data_len:u32.
  (global $HELP_INTERNAL_FILE_SIZE i32 (i32.const 20))

  ;; HelpTopic is 32 bytes:
  ;;   topic_ref, topic_record_off, title_off, title_len, context_hash,
  ;;   browse_prev_ref, browse_next_ref, flags.
  ;; Context hash and numeric-map records are both {key:u32, topic_ref:u32}.
  (global $HELP_TOPIC_SIZE i32 (i32.const 32))
  (global $HELP_CONTEXT_SIZE i32 (i32.const 8))
  (global $HELP_TOPIC_HAS_CONTEXT i32 (i32.const 1))

  ;; HelpTopicToken is 16 bytes:
  ;;   kind:u32, payload_off:u32, payload_len:u32, value:u32.
  ;; TEXT payload offsets address the caller's raw LinkData2 arena. Structured
  ;; token payload offsets address the caller's copied LinkData1 arena.
  (global $HELP_TOPIC_TOKEN_SIZE i32 (i32.const 16))
  (global $HELP_TOKEN_TEXT i32 (i32.const 1))
  (global $HELP_TOKEN_SPACE i32 (i32.const 2))
  (global $HELP_TOKEN_LINE_BREAK i32 (i32.const 3))
  (global $HELP_TOKEN_PARAGRAPH i32 (i32.const 4))
  (global $HELP_TOKEN_FONT i32 (i32.const 5))
  (global $HELP_TOKEN_COLOR i32 (i32.const 6))
  (global $HELP_TOKEN_HOTSPOT_BEGIN i32 (i32.const 7))
  (global $HELP_TOKEN_HOTSPOT_END i32 (i32.const 8))
  (global $HELP_TOKEN_BITMAP i32 (i32.const 9))
  (global $HELP_TOKEN_MACRO i32 (i32.const 10))
  (global $HELP_TOKEN_END_TOPIC i32 (i32.const 13))

  ;; HelpFontFace is {name_off:u32, name_len:u32}. HelpFont is 28 bytes:
  ;; face_index, height, family, attributes, weight, foreground, background.
  (global $HELP_FONT_FACE_SIZE i32 (i32.const 8))
  (global $HELP_FONT_SIZE i32 (i32.const 28))
  ;; HelpBitmap is 80 bytes; see the formatted-topic design for fields. The
  ;; decoded_size field is the exact caller-buffer requirement after packing.
  (global $HELP_BITMAP_SIZE i32 (i32.const 80))
  ;; HelpKeyword is {text_off, text_len, first_posting, posting_count}.
  ;; HelpKeywordPosting is {topic_ref, flags}; flag 1 marks a |Rose macro.
  (global $HELP_KEYWORD_SIZE i32 (i32.const 16))
  (global $HELP_KEYWORD_POSTING_SIZE i32 (i32.const 8))

  ;; HelpWindow is 56 bytes. String offsets address the canonical HLP image:
  ;; flags, type_off/type_len, name_off/name_len, caption_off/caption_len,
  ;; signed x/y/width/height, show/style word, scroll/non-scroll RGB colors.
  ;; A zero caption length means fall back to the document title.
  (global $HELP_WINDOW_SIZE i32 (i32.const 56))

  ;; Topic records may straddle physical block boundaries. The gather buffer
  ;; owns the reassembled copy; the cache keeps the walkers from decompressing
  ;; the same block once per link. Both are scratch, never document state.
  (global $HELP_TOPIC_GATHER_BYTES i32 (i32.const 65536))
  (global $help_topic_gather_ga (mut i32) (i32.const 0))
  (global $help_topic_gather_wa (mut i32) (i32.const 0))
  (global $help_topic_link_bytes (mut i32) (i32.const 0))
  (global $help_topic_block_cache_wa (mut i32) (i32.const 0))
  (global $help_topic_block_cache_number (mut i32) (i32.const -1))
  (global $help_topic_block_cache_bytes (mut i32) (i32.const 0))
  ;; Records reassembled by the walk in progress. Exposed so a fixture can
  ;; prove the straddling path ran instead of merely parsing.
  (global $help_topic_gather_count (mut i32) (i32.const 0))

  ;; Flag bits 0x0008..0x0040 mark a record whose x/y/width/height fields are
  ;; meaningful. A record missing any of them keeps the canonical geometry.
  (global $HELP_WINDOW_FLAG_CAPTION i32 (i32.const 0x0004))
  (global $HELP_WINDOW_FLAG_GEOMETRY i32 (i32.const 0x0078))

  ;; Geometry already pushed to the host, so an ordinary jump inside one
  ;; presentation never moves a window the user has repositioned.
  (global $help_window_applied_index (mut i32) (i32.const -1))

  ;; Owned NUL-terminated copy of the presented window caption. The |SYSTEM
  ;; field is fixed-width and need not be terminated, so the viewer never
  ;; hands the host a pointer into the HLP image itself.
  (global $HELP_WINDOW_CAPTION_BYTES i32 (i32.const 64))
  (global $help_window_caption_ga (mut i32) (i32.const 0))
  (global $help_window_caption_wa (mut i32) (i32.const 0))

  ;; HelpContentsNode is 32 bytes:
  ;; parent, first_child, next_sibling, depth:u16, flags:u16,
  ;; title_wa, title_len, topic_ref, target_wa.
  (global $HELP_CNT_NODE_SIZE i32 (i32.const 32))
  (global $HELP_CNT_BOOK i32 (i32.const 1))
  (global $HELP_CNT_LEAF i32 (i32.const 2))
  (global $HELP_CNT_EXPANDED i32 (i32.const 4))
  (global $HELP_CNT_UNRESOLVED i32 (i32.const 8))
  (global $HELP_CNT_MACRO i32 (i32.const 16))
  (global $HELP_CNT_EXTERNAL i32 (i32.const 32))
  (global $HELP_KEYWORD_POSTING_MACRO i32 (i32.const 1))

  ;; HelpSlice is 16 bytes:
  ;;   base_wa:u32, file_size:u32, offset:u32, length:u32.
  ;; The document metadata owns a root slice at +0 and page scratch at +16.
  (func $help_set_error (param $code i32) (param $file_off i32)
    (if (i32.eqz (global.get $help_last_error))
      (then
        (global.set $help_last_error (local.get $code))
        (global.set $help_last_error_offset (local.get $file_off)))))

  (func $help_document_release_storage
    (if (global.get $help_topic_gather_ga)
      (then
        (call $heap_free (global.get $help_topic_gather_ga))
        (global.set $help_topic_gather_ga (i32.const 0))
        (global.set $help_topic_gather_wa (i32.const 0))))
    (global.set $help_topic_block_cache_wa (i32.const 0))
    (global.set $help_topic_block_cache_number (i32.const -1))
    (if (global.get $help_doc_windows_ga)
      (then (call $heap_free (global.get $help_doc_windows_ga))))
    (if (global.get $help_doc_path_ga)
      (then (call $heap_free (global.get $help_doc_path_ga))))
    (if (global.get $help_doc_cnt_nodes_ga)
      (then (call $heap_free (global.get $help_doc_cnt_nodes_ga))))
    (if (global.get $help_doc_cnt_file_ga)
      (then (call $heap_free (global.get $help_doc_cnt_file_ga))))
    (if (global.get $help_doc_keyword_postings_ga)
      (then (call $heap_free (global.get $help_doc_keyword_postings_ga))))
    (if (global.get $help_doc_keywords_ga)
      (then (call $heap_free (global.get $help_doc_keywords_ga))))
    (if (global.get $help_doc_bitmaps_ga)
      (then (call $heap_free (global.get $help_doc_bitmaps_ga))))
    (if (global.get $help_doc_fonts_ga)
      (then (call $heap_free (global.get $help_doc_fonts_ga))))
    (if (global.get $help_doc_font_faces_ga)
      (then (call $heap_free (global.get $help_doc_font_faces_ga))))
    (if (global.get $help_doc_phrase_image_ga)
      (then (call $heap_free (global.get $help_doc_phrase_image_ga))))
    (if (global.get $help_doc_phrase_offsets_ga)
      (then (call $heap_free (global.get $help_doc_phrase_offsets_ga))))
    (if (global.get $help_doc_maps_ga)
      (then (call $heap_free (global.get $help_doc_maps_ga))))
    (if (global.get $help_doc_contexts_ga)
      (then (call $heap_free (global.get $help_doc_contexts_ga))))
    (if (global.get $help_doc_topics_ga)
      (then (call $heap_free (global.get $help_doc_topics_ga))))
    (if (global.get $help_doc_directory_ga)
      (then (call $heap_free (global.get $help_doc_directory_ga))))
    (if (global.get $help_doc_meta_ga)
      (then (call $heap_free (global.get $help_doc_meta_ga))))
    (if (global.get $help_doc_file_ga)
      (then (call $heap_free (global.get $help_doc_file_ga))))
    (global.set $help_doc_file_ga (i32.const 0))
    (global.set $help_doc_file_wa (i32.const 0))
    (global.set $help_doc_file_size (i32.const 0))
    (global.set $help_doc_path_ga (i32.const 0))
    (global.set $help_doc_path_wa (i32.const 0))
    (global.set $help_doc_path_len (i32.const 0))
    (global.set $help_doc_meta_ga (i32.const 0))
    (global.set $help_doc_meta_wa (i32.const 0))
    (global.set $help_doc_directory_ga (i32.const 0))
    (global.set $help_doc_directory_wa (i32.const 0))
    (global.set $help_doc_directory_count (i32.const 0))
    (global.set $help_doc_topics_ga (i32.const 0))
    (global.set $help_doc_topics_wa (i32.const 0))
    (global.set $help_doc_topic_count (i32.const 0))
    (global.set $help_doc_contexts_ga (i32.const 0))
    (global.set $help_doc_contexts_wa (i32.const 0))
    (global.set $help_doc_context_count (i32.const 0))
    (global.set $help_doc_context_dropped (i32.const 0))
    (global.set $help_doc_maps_ga (i32.const 0))
    (global.set $help_doc_maps_wa (i32.const 0))
    (global.set $help_doc_map_count (i32.const 0))
    (global.set $help_doc_phrase_offsets_ga (i32.const 0))
    (global.set $help_doc_phrase_offsets_wa (i32.const 0))
    (global.set $help_doc_phrase_image_ga (i32.const 0))
    (global.set $help_doc_phrase_image_wa (i32.const 0))
    (global.set $help_doc_phrase_count (i32.const 0))
    (global.set $help_doc_phrase_image_size (i32.const 0))
    (global.set $help_doc_phrase_mode (i32.const 0))
    (global.set $help_doc_display_record_count (i32.const 0))
    (global.set $help_doc_paragraph_count (i32.const 0))
    (global.set $help_doc_table_count (i32.const 0))
    (global.set $help_doc_format_command_count (i32.const 0))
    (global.set $help_doc_font_faces_ga (i32.const 0))
    (global.set $help_doc_font_faces_wa (i32.const 0))
    (global.set $help_doc_font_face_count (i32.const 0))
    (global.set $help_doc_fonts_ga (i32.const 0))
    (global.set $help_doc_fonts_wa (i32.const 0))
    (global.set $help_doc_font_count (i32.const 0))
    (global.set $help_doc_font_metric_mode (i32.const 0))
    (global.set $help_doc_bitmaps_ga (i32.const 0))
    (global.set $help_doc_bitmaps_wa (i32.const 0))
    (global.set $help_doc_bitmap_count (i32.const 0))
    (global.set $help_doc_keywords_ga (i32.const 0))
    (global.set $help_doc_keywords_wa (i32.const 0))
    (global.set $help_doc_keyword_count (i32.const 0))
    (global.set $help_doc_keyword_postings_ga (i32.const 0))
    (global.set $help_doc_keyword_postings_wa (i32.const 0))
    (global.set $help_doc_keyword_posting_count (i32.const 0))
    (global.set $help_doc_cnt_file_ga (i32.const 0))
    (global.set $help_doc_cnt_file_wa (i32.const 0))
    (global.set $help_doc_cnt_file_size (i32.const 0))
    (global.set $help_doc_cnt_nodes_ga (i32.const 0))
    (global.set $help_doc_cnt_nodes_wa (i32.const 0))
    (global.set $help_doc_cnt_node_count (i32.const 0))
    (global.set $help_doc_cnt_title_wa (i32.const 0))
    (global.set $help_doc_cnt_title_len (i32.const 0))
    (global.set $help_doc_cnt_base_wa (i32.const 0))
    (global.set $help_doc_cnt_base_len (i32.const 0))
    (global.set $help_doc_system_minor (i32.const 0))
    (global.set $help_doc_system_major (i32.const 0))
    (global.set $help_doc_system_flags (i32.const 0))
    (global.set $help_doc_system_date (i32.const 0))
    (global.set $help_doc_title_off (i32.const 0))
    (global.set $help_doc_title_len (i32.const 0))
    (global.set $help_doc_contents_ref (i32.const -1))
    (global.set $help_doc_cnt_off (i32.const 0))
    (global.set $help_doc_cnt_len (i32.const 0))
    (global.set $help_doc_windows_ga (i32.const 0))
    (global.set $help_doc_windows_wa (i32.const 0))
    (global.set $help_doc_window_count (i32.const 0)))

  (func $help_session_reset
    (global.set $help_session_owner (i32.const 0))
    (global.set $help_session_topic_ref (i32.const -1))
    (global.set $help_session_topic_index (i32.const -1))
    (global.set $help_session_contents_override (i32.const -1))
    (global.set $help_session_mode (i32.const 0))
    (global.set $help_session_keyword_index (i32.const -1))
    (global.set $help_session_last_command (i32.const 0))
    (global.set $help_session_status (global.get $HELP_DISPATCH_NONE))
    (global.set $help_session_window_index (i32.const -1))
    (global.set $help_topics_contents_selection (i32.const -1))
    (global.set $help_topics_first_visible (i32.const 0))
    (global.set $help_topics_return_mode (i32.const 0)))

  (func $help_document_snapshot_release_record (param $snapshot_ga i32)
    (local $p i32) (local $owned i32)
    (if (i32.eqz (local.get $snapshot_ga)) (then (return)))
    (local.set $p (call $g2w (local.get $snapshot_ga)))
    (local.set $owned (i32.load offset=4 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=16 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=28 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=36 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=48 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=60 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=72 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=84 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=92 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=128 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=140 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=156 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=168 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=180 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=192 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=204 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (local.set $owned (i32.load offset=400 (local.get $p)))
    (if (local.get $owned) (then (call $heap_free (local.get $owned))))
    (call $heap_free (local.get $snapshot_ga)))

  ;; Detach the current document roots without freeing them. The ordinary
  ;; loader may then reset and parse into the now-empty global document slot.
  (func $help_document_snapshot_push (result i32)
    (local $ga i32) (local $p i32)
    (if (i32.or (i32.eqz (global.get $help_doc_file_ga))
          (i32.ge_u (global.get $help_document_snapshot_count)
            (global.get $HELP_MAX_DOCUMENT_SNAPSHOTS)))
      (then (return (i32.const 0))))
    (local.set $ga (call $heap_alloc (global.get $HELP_DOCUMENT_SNAPSHOT_SIZE)))
    (if (i32.eqz (local.get $ga)) (then (return (i32.const 0))))
    (local.set $p (call $g2w (local.get $ga)))
    (memory.fill (local.get $p) (i32.const 0) (global.get $HELP_DOCUMENT_SNAPSHOT_SIZE))
    (i32.store (local.get $p) (global.get $help_document_snapshots_ga))
    (i32.store offset=4 (local.get $p) (global.get $help_doc_path_ga))
    (i32.store offset=8 (local.get $p) (global.get $help_doc_path_wa))
    (i32.store offset=12 (local.get $p) (global.get $help_doc_path_len))
    (i32.store offset=16 (local.get $p) (global.get $help_doc_file_ga))
    (i32.store offset=20 (local.get $p) (global.get $help_doc_file_wa))
    (i32.store offset=24 (local.get $p) (global.get $help_doc_file_size))
    (i32.store offset=28 (local.get $p) (global.get $help_doc_meta_ga))
    (i32.store offset=32 (local.get $p) (global.get $help_doc_meta_wa))
    (i32.store offset=36 (local.get $p) (global.get $help_doc_directory_ga))
    (i32.store offset=40 (local.get $p) (global.get $help_doc_directory_wa))
    (i32.store offset=44 (local.get $p) (global.get $help_doc_directory_count))
    (i32.store offset=48 (local.get $p) (global.get $help_doc_topics_ga))
    (i32.store offset=52 (local.get $p) (global.get $help_doc_topics_wa))
    (i32.store offset=56 (local.get $p) (global.get $help_doc_topic_count))
    (i32.store offset=60 (local.get $p) (global.get $help_doc_contexts_ga))
    (i32.store offset=64 (local.get $p) (global.get $help_doc_contexts_wa))
    (i32.store offset=68 (local.get $p) (global.get $help_doc_context_count))
    (i32.store offset=72 (local.get $p) (global.get $help_doc_maps_ga))
    (i32.store offset=76 (local.get $p) (global.get $help_doc_maps_wa))
    (i32.store offset=80 (local.get $p) (global.get $help_doc_map_count))
    (i32.store offset=84 (local.get $p) (global.get $help_doc_phrase_offsets_ga))
    (i32.store offset=88 (local.get $p) (global.get $help_doc_phrase_offsets_wa))
    (i32.store offset=92 (local.get $p) (global.get $help_doc_phrase_image_ga))
    (i32.store offset=96 (local.get $p) (global.get $help_doc_phrase_image_wa))
    (i32.store offset=100 (local.get $p) (global.get $help_doc_phrase_count))
    (i32.store offset=104 (local.get $p) (global.get $help_doc_phrase_image_size))
    (i32.store offset=108 (local.get $p) (global.get $help_doc_phrase_mode))
    (i32.store offset=112 (local.get $p) (global.get $help_doc_display_record_count))
    (i32.store offset=116 (local.get $p) (global.get $help_doc_paragraph_count))
    (i32.store offset=120 (local.get $p) (global.get $help_doc_table_count))
    (i32.store offset=124 (local.get $p) (global.get $help_doc_format_command_count))
    (i32.store offset=128 (local.get $p) (global.get $help_doc_font_faces_ga))
    (i32.store offset=132 (local.get $p) (global.get $help_doc_font_faces_wa))
    (i32.store offset=136 (local.get $p) (global.get $help_doc_font_face_count))
    (i32.store offset=140 (local.get $p) (global.get $help_doc_fonts_ga))
    (i32.store offset=144 (local.get $p) (global.get $help_doc_fonts_wa))
    (i32.store offset=148 (local.get $p) (global.get $help_doc_font_count))
    (i32.store offset=152 (local.get $p) (global.get $help_doc_font_metric_mode))
    (i32.store offset=156 (local.get $p) (global.get $help_doc_bitmaps_ga))
    (i32.store offset=160 (local.get $p) (global.get $help_doc_bitmaps_wa))
    (i32.store offset=164 (local.get $p) (global.get $help_doc_bitmap_count))
    (i32.store offset=168 (local.get $p) (global.get $help_doc_keywords_ga))
    (i32.store offset=172 (local.get $p) (global.get $help_doc_keywords_wa))
    (i32.store offset=176 (local.get $p) (global.get $help_doc_keyword_count))
    (i32.store offset=180 (local.get $p) (global.get $help_doc_keyword_postings_ga))
    (i32.store offset=184 (local.get $p) (global.get $help_doc_keyword_postings_wa))
    (i32.store offset=188 (local.get $p) (global.get $help_doc_keyword_posting_count))
    (i32.store offset=192 (local.get $p) (global.get $help_doc_cnt_file_ga))
    (i32.store offset=196 (local.get $p) (global.get $help_doc_cnt_file_wa))
    (i32.store offset=200 (local.get $p) (global.get $help_doc_cnt_file_size))
    (i32.store offset=204 (local.get $p) (global.get $help_doc_cnt_nodes_ga))
    (i32.store offset=208 (local.get $p) (global.get $help_doc_cnt_nodes_wa))
    (i32.store offset=212 (local.get $p) (global.get $help_doc_cnt_node_count))
    (i32.store offset=216 (local.get $p) (global.get $help_doc_cnt_title_wa))
    (i32.store offset=220 (local.get $p) (global.get $help_doc_cnt_title_len))
    (i32.store offset=224 (local.get $p) (global.get $help_doc_cnt_base_wa))
    (i32.store offset=228 (local.get $p) (global.get $help_doc_cnt_base_len))
    (i32.store offset=232 (local.get $p) (global.get $help_doc_system_minor))
    (i32.store offset=236 (local.get $p) (global.get $help_doc_system_major))
    (i32.store offset=240 (local.get $p) (global.get $help_doc_system_flags))
    (i32.store offset=244 (local.get $p) (global.get $help_doc_system_date))
    (i32.store offset=248 (local.get $p) (global.get $help_doc_title_off))
    (i32.store offset=252 (local.get $p) (global.get $help_doc_title_len))
    (i32.store offset=256 (local.get $p) (global.get $help_doc_contents_ref))
    (i32.store offset=260 (local.get $p) (global.get $help_doc_cnt_off))
    (i32.store offset=264 (local.get $p) (global.get $help_doc_cnt_len))
    (i32.store offset=268 (local.get $p) (global.get $help_session_owner))
    (i32.store offset=272 (local.get $p) (global.get $help_session_topic_ref))
    (i32.store offset=276 (local.get $p) (global.get $help_session_topic_index))
    (i32.store offset=280 (local.get $p) (global.get $help_session_contents_override))
    (i32.store offset=284 (local.get $p) (global.get $help_session_mode))
    (i32.store offset=288 (local.get $p) (global.get $help_session_keyword_index))
    (i32.store offset=292 (local.get $p) (global.get $help_session_last_command))
    (i32.store offset=296 (local.get $p) (global.get $help_session_status))
    (i32.store offset=300 (local.get $p) (global.get $help_topics_contents_selection))
    (i32.store offset=304 (local.get $p) (global.get $help_topics_first_visible))
    (i32.store offset=308 (local.get $p) (global.get $help_topics_return_mode))
    (i32.store offset=312 (local.get $p) (global.get $help_cur_topic))
    (i32.store offset=316 (local.get $p) (global.get $help_scroll_y))
    (i32.store offset=320 (local.get $p) (global.get $help_back_count))
    (i32.store offset=324 (local.get $p) (global.get $help_session_window_index))
    (i32.store offset=328 (local.get $p) (global.get $help_last_error))
    (i32.store offset=332 (local.get $p) (global.get $help_last_error_offset))
    (if (global.get $help_back_stack)
      (then
        (memory.copy (i32.add (local.get $p) (i32.const 336))
          (global.get $help_back_stack) (i32.const 64))))
    (i32.store offset=400 (local.get $p) (global.get $help_doc_windows_ga))
    (i32.store offset=404 (local.get $p) (global.get $help_doc_windows_wa))
    (i32.store offset=408 (local.get $p) (global.get $help_doc_window_count))
    ;; Prevent release_storage from freeing the detached owned roots.
    (global.set $help_doc_path_ga (i32.const 0))
    (global.set $help_doc_file_ga (i32.const 0))
    (global.set $help_doc_meta_ga (i32.const 0))
    (global.set $help_doc_directory_ga (i32.const 0))
    (global.set $help_doc_topics_ga (i32.const 0))
    (global.set $help_doc_contexts_ga (i32.const 0))
    (global.set $help_doc_maps_ga (i32.const 0))
    (global.set $help_doc_phrase_offsets_ga (i32.const 0))
    (global.set $help_doc_phrase_image_ga (i32.const 0))
    (global.set $help_doc_font_faces_ga (i32.const 0))
    (global.set $help_doc_fonts_ga (i32.const 0))
    (global.set $help_doc_bitmaps_ga (i32.const 0))
    (global.set $help_doc_keywords_ga (i32.const 0))
    (global.set $help_doc_keyword_postings_ga (i32.const 0))
    (global.set $help_doc_cnt_file_ga (i32.const 0))
    (global.set $help_doc_cnt_nodes_ga (i32.const 0))
    (global.set $help_doc_windows_ga (i32.const 0))
    (call $help_document_release_storage)
    (global.set $help_document_snapshots_ga (local.get $ga))
    (global.set $help_document_snapshot_count
      (i32.add (global.get $help_document_snapshot_count) (i32.const 1)))
    (i32.const 1))

  (func $help_document_snapshot_restore_top (result i32)
    (local $ga i32) (local $p i32)
    (local.set $ga (global.get $help_document_snapshots_ga))
    (if (i32.eqz (local.get $ga)) (then (return (i32.const 0))))
    (local.set $p (call $g2w (local.get $ga)))
    (call $help_document_release_storage)
    (global.set $help_doc_path_ga (i32.load offset=4 (local.get $p)))
    (global.set $help_doc_path_wa (i32.load offset=8 (local.get $p)))
    (global.set $help_doc_path_len (i32.load offset=12 (local.get $p)))
    (global.set $help_doc_file_ga (i32.load offset=16 (local.get $p)))
    (global.set $help_doc_file_wa (i32.load offset=20 (local.get $p)))
    (global.set $help_doc_file_size (i32.load offset=24 (local.get $p)))
    (global.set $help_doc_meta_ga (i32.load offset=28 (local.get $p)))
    (global.set $help_doc_meta_wa (i32.load offset=32 (local.get $p)))
    (global.set $help_doc_directory_ga (i32.load offset=36 (local.get $p)))
    (global.set $help_doc_directory_wa (i32.load offset=40 (local.get $p)))
    (global.set $help_doc_directory_count (i32.load offset=44 (local.get $p)))
    (global.set $help_doc_topics_ga (i32.load offset=48 (local.get $p)))
    (global.set $help_doc_topics_wa (i32.load offset=52 (local.get $p)))
    (global.set $help_doc_topic_count (i32.load offset=56 (local.get $p)))
    (global.set $help_doc_contexts_ga (i32.load offset=60 (local.get $p)))
    (global.set $help_doc_contexts_wa (i32.load offset=64 (local.get $p)))
    (global.set $help_doc_context_count (i32.load offset=68 (local.get $p)))
    (global.set $help_doc_maps_ga (i32.load offset=72 (local.get $p)))
    (global.set $help_doc_maps_wa (i32.load offset=76 (local.get $p)))
    (global.set $help_doc_map_count (i32.load offset=80 (local.get $p)))
    (global.set $help_doc_phrase_offsets_ga (i32.load offset=84 (local.get $p)))
    (global.set $help_doc_phrase_offsets_wa (i32.load offset=88 (local.get $p)))
    (global.set $help_doc_phrase_image_ga (i32.load offset=92 (local.get $p)))
    (global.set $help_doc_phrase_image_wa (i32.load offset=96 (local.get $p)))
    (global.set $help_doc_phrase_count (i32.load offset=100 (local.get $p)))
    (global.set $help_doc_phrase_image_size (i32.load offset=104 (local.get $p)))
    (global.set $help_doc_phrase_mode (i32.load offset=108 (local.get $p)))
    (global.set $help_doc_display_record_count (i32.load offset=112 (local.get $p)))
    (global.set $help_doc_paragraph_count (i32.load offset=116 (local.get $p)))
    (global.set $help_doc_table_count (i32.load offset=120 (local.get $p)))
    (global.set $help_doc_format_command_count (i32.load offset=124 (local.get $p)))
    (global.set $help_doc_font_faces_ga (i32.load offset=128 (local.get $p)))
    (global.set $help_doc_font_faces_wa (i32.load offset=132 (local.get $p)))
    (global.set $help_doc_font_face_count (i32.load offset=136 (local.get $p)))
    (global.set $help_doc_fonts_ga (i32.load offset=140 (local.get $p)))
    (global.set $help_doc_fonts_wa (i32.load offset=144 (local.get $p)))
    (global.set $help_doc_font_count (i32.load offset=148 (local.get $p)))
    (global.set $help_doc_font_metric_mode (i32.load offset=152 (local.get $p)))
    (global.set $help_doc_bitmaps_ga (i32.load offset=156 (local.get $p)))
    (global.set $help_doc_bitmaps_wa (i32.load offset=160 (local.get $p)))
    (global.set $help_doc_bitmap_count (i32.load offset=164 (local.get $p)))
    (global.set $help_doc_keywords_ga (i32.load offset=168 (local.get $p)))
    (global.set $help_doc_keywords_wa (i32.load offset=172 (local.get $p)))
    (global.set $help_doc_keyword_count (i32.load offset=176 (local.get $p)))
    (global.set $help_doc_keyword_postings_ga (i32.load offset=180 (local.get $p)))
    (global.set $help_doc_keyword_postings_wa (i32.load offset=184 (local.get $p)))
    (global.set $help_doc_keyword_posting_count (i32.load offset=188 (local.get $p)))
    (global.set $help_doc_cnt_file_ga (i32.load offset=192 (local.get $p)))
    (global.set $help_doc_cnt_file_wa (i32.load offset=196 (local.get $p)))
    (global.set $help_doc_cnt_file_size (i32.load offset=200 (local.get $p)))
    (global.set $help_doc_cnt_nodes_ga (i32.load offset=204 (local.get $p)))
    (global.set $help_doc_cnt_nodes_wa (i32.load offset=208 (local.get $p)))
    (global.set $help_doc_cnt_node_count (i32.load offset=212 (local.get $p)))
    (global.set $help_doc_cnt_title_wa (i32.load offset=216 (local.get $p)))
    (global.set $help_doc_cnt_title_len (i32.load offset=220 (local.get $p)))
    (global.set $help_doc_cnt_base_wa (i32.load offset=224 (local.get $p)))
    (global.set $help_doc_cnt_base_len (i32.load offset=228 (local.get $p)))
    (global.set $help_doc_system_minor (i32.load offset=232 (local.get $p)))
    (global.set $help_doc_system_major (i32.load offset=236 (local.get $p)))
    (global.set $help_doc_system_flags (i32.load offset=240 (local.get $p)))
    (global.set $help_doc_system_date (i32.load offset=244 (local.get $p)))
    (global.set $help_doc_title_off (i32.load offset=248 (local.get $p)))
    (global.set $help_doc_title_len (i32.load offset=252 (local.get $p)))
    (global.set $help_doc_contents_ref (i32.load offset=256 (local.get $p)))
    (global.set $help_doc_cnt_off (i32.load offset=260 (local.get $p)))
    (global.set $help_doc_cnt_len (i32.load offset=264 (local.get $p)))
    (global.set $help_session_owner (i32.load offset=268 (local.get $p)))
    (global.set $help_session_topic_ref (i32.load offset=272 (local.get $p)))
    (global.set $help_session_topic_index (i32.load offset=276 (local.get $p)))
    (global.set $help_session_contents_override (i32.load offset=280 (local.get $p)))
    (global.set $help_session_mode (i32.load offset=284 (local.get $p)))
    (global.set $help_session_keyword_index (i32.load offset=288 (local.get $p)))
    (global.set $help_session_last_command (i32.load offset=292 (local.get $p)))
    (global.set $help_session_status (i32.load offset=296 (local.get $p)))
    (global.set $help_topics_contents_selection (i32.load offset=300 (local.get $p)))
    (global.set $help_topics_first_visible (i32.load offset=304 (local.get $p)))
    (global.set $help_topics_return_mode (i32.load offset=308 (local.get $p)))
    (global.set $help_cur_topic (i32.load offset=312 (local.get $p)))
    (global.set $help_scroll_y (i32.load offset=316 (local.get $p)))
    (global.set $help_back_count (i32.load offset=320 (local.get $p)))
    (global.set $help_session_window_index (i32.load offset=324 (local.get $p)))
    (global.set $help_last_error (i32.load offset=328 (local.get $p)))
    (global.set $help_last_error_offset (i32.load offset=332 (local.get $p)))
    (if (global.get $help_back_stack)
      (then
        (memory.copy (global.get $help_back_stack)
          (i32.add (local.get $p) (i32.const 336)) (i32.const 64))))
    (global.set $help_doc_windows_ga (i32.load offset=400 (local.get $p)))
    (global.set $help_doc_windows_wa (i32.load offset=404 (local.get $p)))
    (global.set $help_doc_window_count (i32.load offset=408 (local.get $p)))
    (global.set $help_document_snapshots_ga (i32.load (local.get $p)))
    (global.set $help_document_snapshot_count
      (i32.sub (global.get $help_document_snapshot_count) (i32.const 1)))
    ;; Only the record is freed; every detached root is live in globals again.
    (call $heap_free (local.get $ga))
    (i32.const 1))

  (func $help_document_snapshot_release_all
    (local $ga i32) (local $p i32) (local $next i32)
    (block $done (loop $snapshots
      (local.set $ga (global.get $help_document_snapshots_ga))
      (br_if $done (i32.eqz (local.get $ga)))
      (local.set $p (call $g2w (local.get $ga)))
      (local.set $next (i32.load (local.get $p)))
      (call $help_document_snapshot_release_record (local.get $ga))
      (global.set $help_document_snapshots_ga (local.get $next))
      (br $snapshots)))
    (global.set $help_document_snapshot_count (i32.const 0)))

  (func $help_document_reset
    (call $help_document_release_storage)
    (call $help_session_reset)
    ;; A new document cannot inherit UI history/index state from the prior
    ;; file. View buffers may be reused by the window bridge after a new load.
    (global.set $help_cur_topic (i32.const 0))
    (global.set $help_scroll_y (i32.const 0))
    (global.set $help_back_count (i32.const 0))
    (global.set $help_last_error (i32.const 0))
    (global.set $help_last_error_offset (i32.const 0)))

  (func $help_slice_init
    (param $slice i32) (param $base i32) (param $file_size i32)
    (param $offset i32) (param $length i32)
    (i32.store (local.get $slice) (local.get $base))
    (i32.store offset=4 (local.get $slice) (local.get $file_size))
    (i32.store offset=8 (local.get $slice) (local.get $offset))
    (i32.store offset=12 (local.get $slice) (local.get $length)))

  ;; Return the bounded WA address or zero. Subtraction-based checks avoid
  ;; overflow in offset+length and relative_offset+width.
  (func $help_slice_address
    (param $slice i32) (param $relative_offset i32) (param $width i32)
    (result i32)
    (local $base i32) (local $file_size i32) (local $offset i32) (local $length i32)
    (local.set $base (i32.load (local.get $slice)))
    (local.set $file_size (i32.load offset=4 (local.get $slice)))
    (local.set $offset (i32.load offset=8 (local.get $slice)))
    (local.set $length (i32.load offset=12 (local.get $slice)))
    (if (i32.gt_u (local.get $offset) (local.get $file_size))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $length) (i32.sub (local.get $file_size) (local.get $offset)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $relative_offset) (local.get $length))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $width) (i32.sub (local.get $length) (local.get $relative_offset)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $offset) (i32.sub (i32.const -1) (local.get $relative_offset)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $base)
          (i32.sub (i32.const -1) (i32.add (local.get $offset) (local.get $relative_offset))))
      (then (return (i32.const 0))))
    (i32.add (local.get $base) (i32.add (local.get $offset) (local.get $relative_offset))))

  (func $help_subslice
    (param $slice i32) (param $relative_offset i32) (param $length i32)
    (param $out_slice i32) (result i32)
    (if (i32.eqz (call $help_slice_address
          (local.get $slice) (local.get $relative_offset) (local.get $length)))
      (then (return (i32.const 0))))
    (call $help_slice_init
      (local.get $out_slice)
      (i32.load (local.get $slice))
      (i32.load offset=4 (local.get $slice))
      (i32.add (i32.load offset=8 (local.get $slice)) (local.get $relative_offset))
      (local.get $length))
    (i32.const 1))

  ;; Return a bounded C-string length, or -1 if no terminator occurs inside
  ;; both max_length and the current slice.
  (func $help_read_cstring_length
    (param $slice i32) (param $relative_offset i32) (param $max_length i32)
    (result i32)
    (local $i i32) (local $p i32)
    (if (i32.eqz (local.get $max_length)) (then (return (i32.const -1))))
    (block $done (loop $scan
      (if (i32.ge_u (local.get $i) (local.get $max_length))
        (then (return (i32.const -1))))
      (local.set $p (call $help_slice_address
        (local.get $slice) (i32.add (local.get $relative_offset) (local.get $i)) (i32.const 1)))
      (if (i32.eqz (local.get $p)) (then (return (i32.const -1))))
      (br_if $done (i32.eqz (i32.load8_u (local.get $p))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (local.get $i))

  ;; Return the meaningful length of a fixed-width byte string. Unlike a
  ;; STRINGZ field, consuming the complete field is valid.
  (func $help_fixed_string_length
    (param $ptr i32) (param $width i32) (result i32)
    (local $i i32)
    (block $done (loop $scan
      (br_if $done (i32.ge_u (local.get $i) (local.get $width)))
      (br_if $done (i32.eqz (i32.load8_u
        (i32.add (local.get $ptr) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (local.get $i))

  (func $help_hash_bytes (param $wa i32) (param $length i32) (result i32)
    (local $i i32) (local $hash i32)
    (local.set $hash (i32.const 0x811C9DC5))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $i) (local.get $length)))
      (local.set $hash
        (i32.mul
          (i32.xor (local.get $hash) (i32.load8_u (i32.add (local.get $wa) (local.get $i))))
          (i32.const 0x01000193)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (local.get $hash))

  (func $help_bytes_equal
    (param $a i32) (param $b i32) (param $length i32) (result i32)
    (local $i i32)
    (block $equal (loop $loop
      (br_if $equal (i32.ge_u (local.get $i) (local.get $length)))
      (if (i32.ne
            (i32.load8_u (i32.add (local.get $a) (local.get $i)))
            (i32.load8_u (i32.add (local.get $b) (local.get $i))))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (i32.const 1))

  ;; Lexicographic byte comparison used to ensure the published directory is
  ;; strictly sorted and contains no duplicate names.
  (func $help_bytes_compare
    (param $a i32) (param $alen i32) (param $b i32) (param $blen i32)
    (result i32)
    (local $i i32) (local $limit i32) (local $av i32) (local $bv i32)
    (local.set $limit (local.get $alen))
    (if (i32.lt_u (local.get $blen) (local.get $limit))
      (then (local.set $limit (local.get $blen))))
    (block $same_prefix (loop $loop
      (br_if $same_prefix (i32.ge_u (local.get $i) (local.get $limit)))
      (local.set $av (i32.load8_u (i32.add (local.get $a) (local.get $i))))
      (local.set $bv (i32.load8_u (i32.add (local.get $b) (local.get $i))))
      (if (i32.lt_u (local.get $av) (local.get $bv)) (then (return (i32.const -1))))
      (if (i32.gt_u (local.get $av) (local.get $bv)) (then (return (i32.const 1))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (if (i32.lt_u (local.get $alen) (local.get $blen)) (then (return (i32.const -1))))
    (if (i32.gt_u (local.get $alen) (local.get $blen)) (then (return (i32.const 1))))
    (i32.const 0))

  (func $help_ascii_fold (param $ch i32) (result i32)
    (if (result i32)
      (i32.and (i32.ge_u (local.get $ch) (i32.const 0x41))
               (i32.le_u (local.get $ch) (i32.const 0x5a)))
      (then (i32.add (local.get $ch) (i32.const 0x20)))
      (else (local.get $ch))))

  ;; Keyword lookup is ASCII case-insensitive, matching WinHelp's default K
  ;; table behavior. Bytes outside ASCII are retained and compared exactly.
  (func $help_keyword_bytes_compare
    (param $a i32) (param $alen i32) (param $b i32) (param $blen i32)
    (result i32)
    (local $i i32) (local $limit i32) (local $av i32) (local $bv i32)
    (local.set $limit (local.get $alen))
    (if (i32.lt_u (local.get $blen) (local.get $limit))
      (then (local.set $limit (local.get $blen))))
    (block $same_prefix (loop $loop
      (br_if $same_prefix (i32.ge_u (local.get $i) (local.get $limit)))
      (local.set $av (call $help_ascii_fold
        (i32.load8_u (i32.add (local.get $a) (local.get $i)))))
      (local.set $bv (call $help_ascii_fold
        (i32.load8_u (i32.add (local.get $b) (local.get $i)))))
      (if (i32.lt_u (local.get $av) (local.get $bv)) (then (return (i32.const -1))))
      (if (i32.gt_u (local.get $av) (local.get $bv)) (then (return (i32.const 1))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (if (i32.lt_u (local.get $alen) (local.get $blen)) (then (return (i32.const -1))))
    (if (i32.gt_u (local.get $alen) (local.get $blen)) (then (return (i32.const 1))))
    (i32.const 0))

  ;; Normalized |SYSTEM window records. Index -1 always means the canonical
  ;; main viewer presentation, so callers can hold a selector without first
  ;; proving a window table exists.
  (func $help_window_record_at (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_window_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_windows_wa)
      (i32.mul (local.get $index) (global.get $HELP_WINDOW_SIZE))))

  (func $help_active_window_record (result i32)
    (if (i32.lt_s (global.get $help_session_window_index) (i32.const 0))
      (then (return (i32.const 0))))
    (call $help_window_record_at (global.get $help_session_window_index)))

  ;; Window names are ASCII case-insensitive, exactly like the `>window`
  ;; selectors HCW writes. Records without a name field never match.
  (func $help_find_window_index
    (param $name i32) (param $name_len i32) (result i32)
    (local $i i32) (local $record i32)
    (if (i32.eqz (local.get $name_len)) (then (return (i32.const -1))))
    (block $done (loop $scan
      (br_if $done (i32.ge_u (local.get $i) (global.get $help_doc_window_count)))
      (local.set $record (i32.add (global.get $help_doc_windows_wa)
        (i32.mul (local.get $i) (global.get $HELP_WINDOW_SIZE))))
      (if (i32.eqz (call $help_keyword_bytes_compare
            (i32.add (global.get $help_doc_file_wa)
              (i32.load offset=12 (local.get $record)))
            (i32.load offset=16 (local.get $record))
            (local.get $name) (local.get $name_len)))
        (then (return (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (i32.const -1))

  ;; A numeric type-1 selector indexes the same table. 0xFF is the documented
  ;; "current window" sentinel; any other out-of-range number is a hard error
  ;; rather than a silent fall back to the main window.
  (func $help_window_index_for_number (param $number i32) (result i32)
    (if (i32.eq (local.get $number) (i32.const 0xFF))
      (then (return (i32.const -1))))
    (if (i32.ge_u (local.get $number) (global.get $help_doc_window_count))
      (then (return (i32.const -2))))
    (local.get $number))

  ;; Lookup always verifies hash, length, and bytes. Hash collisions cannot
  ;; select an unrelated internal file.
  (func $help_find_internal_file
    (param $name_wa i32) (param $name_length i32) (result i32)
    (local $hash i32) (local $i i32) (local $rec i32) (local $stored_len i32)
    (if (i32.or (i32.eqz (local.get $name_wa)) (i32.gt_u (local.get $name_length) (i32.const 255)))
      (then (return (i32.const -1))))
    (local.set $hash (call $help_hash_bytes (local.get $name_wa) (local.get $name_length)))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $i) (global.get $help_doc_directory_count)))
      (local.set $rec (i32.add (global.get $help_doc_directory_wa)
        (i32.mul (local.get $i) (global.get $HELP_INTERNAL_FILE_SIZE))))
      (local.set $stored_len (i32.load16_u offset=8 (local.get $rec)))
      (if (i32.and
            (i32.and
              (i32.eq (i32.load (local.get $rec)) (local.get $hash))
              (i32.eq (local.get $stored_len) (local.get $name_length)))
            (call $help_bytes_equal
              (local.get $name_wa)
              (i32.add (global.get $help_doc_file_wa) (i32.load offset=4 (local.get $rec)))
              (local.get $name_length)))
        (then (return (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (i32.const -1))

  ;; Resolve the fixed semantic internal files without reserving another
  ;; low-memory string table. The document metadata has sixteen bytes of
  ;; parser scratch beginning at +32.
  (func $help_find_internal_literal (param $kind i32) (result i32)
    (local $scratch i32) (local $length i32)
    (local.set $scratch (i32.add (global.get $help_doc_meta_wa) (i32.const 32)))
    (memory.fill (local.get $scratch) (i32.const 0) (i32.const 16))
    (if (i32.eq (local.get $kind) (i32.const 1))
      (then
        (i64.store (local.get $scratch) (i64.const 0x004D45545359537C))
        (local.set $length (i32.const 7))))
    (if (i32.eq (local.get $kind) (i32.const 2))
      (then
        (i64.store (local.get $scratch) (i64.const 0x00004349504F547C))
        (local.set $length (i32.const 6))))
    (if (i32.eq (local.get $kind) (i32.const 3))
      (then
        (i64.store (local.get $scratch) (i64.const 0x455254424C54547C))
        (i32.store8 offset=8 (local.get $scratch) (i32.const 0x45))
        (local.set $length (i32.const 9))))
    (if (i32.eq (local.get $kind) (i32.const 4))
      (then
        (i64.store (local.get $scratch) (i64.const 0x545845544E4F437C))
        (local.set $length (i32.const 8))))
    (if (i32.eq (local.get $kind) (i32.const 5))
      (then
        (i64.store (local.get $scratch) (i64.const 0x50414D4F5854437C))
        (local.set $length (i32.const 8))))
    (if (i32.eq (local.get $kind) (i32.const 6))
      (then
        (i64.store (local.get $scratch) (i64.const 0x65646E497268507C))
        (i32.store8 offset=8 (local.get $scratch) (i32.const 0x78))
        (local.set $length (i32.const 9))))
    (if (i32.eq (local.get $kind) (i32.const 7))
      (then
        (i64.store (local.get $scratch) (i64.const 0x67616D497268507C))
        (i32.store8 offset=8 (local.get $scratch) (i32.const 0x65))
        (local.set $length (i32.const 9))))
    (if (i32.eq (local.get $kind) (i32.const 8))
      (then
        (i64.store (local.get $scratch) (i64.const 0x736573617268507C))
        (local.set $length (i32.const 8))))
    (if (i32.eq (local.get $kind) (i32.const 9))
      (then
        (i64.store (local.get $scratch) (i64.const 0x000000544E4F467C))
        (local.set $length (i32.const 5))))
    (if (i32.eq (local.get $kind) (i32.const 10))
      (then
        (i64.store (local.get $scratch) (i64.const 0x4545525442574B7C))
        (local.set $length (i32.const 8))))
    (if (i32.eq (local.get $kind) (i32.const 11))
      (then
        (i64.store (local.get $scratch) (i64.const 0x0041544144574B7C))
        (local.set $length (i32.const 7))))
    (if (i32.eqz (local.get $length)) (then (return (i32.const -1))))
    (call $help_find_internal_file (local.get $scratch) (local.get $length)))

  (func $help_find_keyword
    (param $query i32) (param $query_len i32) (param $prefix i32) (result i32)
    (local $memory_bytes i32) (local $i i32) (local $record i32)
    (local $stored_len i32) (local $compare_len i32)
    (if (i32.eqz (local.get $query_len)) (then (return (i32.const -1))))
    (local.set $memory_bytes (i32.shl (memory.size) (i32.const 16)))
    (if (i32.or
          (i32.gt_u (local.get $query) (local.get $memory_bytes))
          (i32.gt_u (local.get $query_len)
            (i32.sub (local.get $memory_bytes) (local.get $query))))
      (then (return (i32.const -1))))
    (block $missing (loop $scan
      (br_if $missing (i32.ge_u (local.get $i) (global.get $help_doc_keyword_count)))
      (local.set $record (i32.add (global.get $help_doc_keywords_wa)
        (i32.mul (local.get $i) (global.get $HELP_KEYWORD_SIZE))))
      (local.set $stored_len (i32.load offset=4 (local.get $record)))
      (if (i32.or
            (i32.and (i32.eqz (local.get $prefix))
              (i32.eq (local.get $stored_len) (local.get $query_len)))
            (i32.and (local.get $prefix)
              (i32.ge_u (local.get $stored_len) (local.get $query_len))))
        (then
          (local.set $compare_len
            (if (result i32) (local.get $prefix)
              (then (local.get $query_len)) (else (local.get $stored_len))))
          (if (i32.eqz (call $help_keyword_bytes_compare
                (local.get $query) (local.get $compare_len)
                (i32.add (global.get $help_doc_file_wa) (i32.load (local.get $record)))
                (local.get $compare_len)))
            (then (return (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (i32.const -1))

  (func $help_resolve_keyword_index (param $index i32) (result i32)
    (local $record i32) (local $first i32)
    (local $count i32) (local $i i32) (local $posting i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_count))
      (then (return (i32.const -1))))
    (local.set $record (i32.add (global.get $help_doc_keywords_wa)
      (i32.mul (local.get $index) (global.get $HELP_KEYWORD_SIZE))))
    (local.set $first (i32.load offset=8 (local.get $record)))
    (local.set $count (i32.load offset=12 (local.get $record)))
    (block $missing (loop $postings
      (br_if $missing (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $posting (i32.add (global.get $help_doc_keyword_postings_wa)
        (i32.mul (i32.add (local.get $first) (local.get $i))
          (global.get $HELP_KEYWORD_POSTING_SIZE))))
      (if (i32.eqz (i32.and (i32.load offset=4 (local.get $posting))
            (global.get $HELP_KEYWORD_POSTING_MACRO)))
        (then (return (i32.load (local.get $posting)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $postings)))
    (i32.const -1))

  (func $help_resolve_keyword
    (param $query i32) (param $query_len i32) (param $prefix i32) (result i32)
    (local $index i32)
    (local.set $index (call $help_find_keyword
      (local.get $query) (local.get $query_len) (local.get $prefix)))
    (if (i32.lt_s (local.get $index) (i32.const 0))
      (then (return (i32.const -1))))
    (call $help_resolve_keyword_index (local.get $index)))

  (func $help_find_topic_index_in
    (param $topics_wa i32) (param $count i32) (param $topic_ref i32)
    (result i32)
    (local $lo i32) (local $hi i32) (local $mid i32) (local $value i32)
    (local.set $hi (local.get $count))
    (block $missing (loop $search
      (br_if $missing (i32.ge_u (local.get $lo) (local.get $hi)))
      (local.set $mid
        (i32.add (local.get $lo)
          (i32.shr_u (i32.sub (local.get $hi) (local.get $lo)) (i32.const 1))))
      (local.set $value
        (i32.load (i32.add (local.get $topics_wa)
          (i32.mul (local.get $mid) (global.get $HELP_TOPIC_SIZE)))))
      (if (i32.eq (local.get $value) (local.get $topic_ref))
        (then (return (local.get $mid))))
      (if (i32.lt_u (local.get $value) (local.get $topic_ref))
        (then (local.set $lo (i32.add (local.get $mid) (i32.const 1))))
        (else (local.set $hi (local.get $mid))))
      (br $search)))
    (i32.const -1))

  (func $help_resolve_context_id (param $map_id i32) (result i32)
    (local $i i32) (local $record i32)
    (block $missing (loop $scan
      (br_if $missing (i32.ge_u (local.get $i) (global.get $help_doc_map_count)))
      (local.set $record (i32.add (global.get $help_doc_maps_wa)
        (i32.mul (local.get $i) (global.get $HELP_CONTEXT_SIZE))))
      (if (i32.eq (i32.load (local.get $record)) (local.get $map_id))
        (then (return (i32.load offset=4 (local.get $record)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (i32.const -1))

  (func $help_cstring_length_memory (param $ptr i32) (param $limit i32) (result i32)
    (local $memory_bytes i32) (local $i i32)
    (if (i32.or (i32.eqz (local.get $ptr)) (i32.eqz (local.get $limit)))
      (then (return (i32.const -1))))
    (local.set $memory_bytes (i32.shl (memory.size) (i32.const 16)))
    (if (i32.ge_u (local.get $ptr) (local.get $memory_bytes))
      (then (return (i32.const -1))))
    (block $terminated (loop $scan
      (if (i32.ge_u (local.get $i) (local.get $limit))
        (then (return (i32.const -1))))
      (if (i32.ge_u (i32.add (local.get $ptr) (local.get $i)) (local.get $memory_bytes))
        (then (return (i32.const -1))))
      (br_if $terminated
        (i32.eqz (i32.load8_u (i32.add (local.get $ptr) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (local.get $i))

  (func $help_session_owner_matches (param $caller i32) (result i32)
    (i32.or
      (i32.eqz (global.get $help_session_owner))
      (i32.eq (global.get $help_session_owner) (local.get $caller))))

  ;; Resolve completely before publishing state. A failed request cannot
  ;; clobber the visible topic or transfer ownership to another caller.
  (func $help_session_commit_topic
    (param $caller i32) (param $command i32) (param $topic_ref i32)
    (param $mode i32) (result i32)
    (local $topic_index i32)
    (local.set $topic_index (call $help_find_topic_index_in
      (global.get $help_doc_topics_wa) (global.get $help_doc_topic_count)
      (local.get $topic_ref)))
    (if (i32.lt_s (local.get $topic_index) (i32.const 0))
      (then
        (global.set $help_session_status (global.get $HELP_DISPATCH_UNRESOLVED))
        (return (i32.const 0))))
    (if (i32.eqz (global.get $help_session_owner))
      (then (global.set $help_session_owner (local.get $caller))))
    (global.set $help_session_topic_ref (local.get $topic_ref))
    (global.set $help_session_topic_index (local.get $topic_index))
    (global.set $help_session_mode (local.get $mode))
    (global.set $help_session_keyword_index (i32.const -1))
    (global.set $help_session_last_command (local.get $command))
    (global.set $help_session_status (global.get $HELP_DISPATCH_ACCEPTED))
    (i32.const 1))

  (func $help_session_commit_dialog
    (param $caller i32) (param $command i32) (param $mode i32)
    (param $keyword_index i32) (result i32)
    (if (i32.and
          (i32.ne (global.get $help_session_mode) (i32.const 3))
          (i32.ne (global.get $help_session_mode) (i32.const 4)))
      (then
        (global.set $help_topics_return_mode
          (if (result i32)
            (i32.or (i32.eq (global.get $help_session_mode) (i32.const 1))
                    (i32.eq (global.get $help_session_mode) (i32.const 2)))
            (then (global.get $help_session_mode))
            (else (select (i32.const 1) (i32.const 0)
              (i32.ge_s (global.get $help_session_topic_ref) (i32.const 0))))))))
    (if (i32.eqz (global.get $help_session_owner))
      (then (global.set $help_session_owner (local.get $caller))))
    (global.set $help_session_mode (local.get $mode))
    (global.set $help_session_keyword_index (local.get $keyword_index))
    (global.set $help_topics_first_visible (i32.const 0))
    (if (i32.eq (local.get $mode) (i32.const 3))
      (then
        (global.set $help_topics_contents_selection
          (select (i32.const 0) (i32.const -1)
            (i32.ne (global.get $help_doc_cnt_node_count) (i32.const 0))))))
    (global.set $help_session_last_command (local.get $command))
    (global.set $help_session_status (global.get $HELP_DISPATCH_ACCEPTED))
    (i32.const 1))

  ;; Dispatch against the currently loaded WAT-owned document. String data is
  ;; already normalized to a WA pointer by the ANSI/Unicode ABI boundary.
  (func $help_dispatch_loaded
    (param $caller i32) (param $command i32) (param $data i32) (result i32)
    (local $topic_ref i32) (local $length i32) (local $keyword_index i32)
    (global.set $help_session_last_command (local.get $command))
    (global.set $help_session_status (global.get $HELP_DISPATCH_NONE))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_QUIT))
      (then
        (if (i32.eqz (call $help_session_owner_matches (local.get $caller)))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_OWNER_MISMATCH))
            (return (i32.const 0))))
        (call $help_document_snapshot_release_all)
        (call $help_document_reset)
        (global.set $help_session_last_command (local.get $command))
        (global.set $help_session_status (global.get $HELP_DISPATCH_ACCEPTED))
        (return (i32.const 1))))

    (if (i32.eqz (global.get $help_doc_file_wa))
      (then
        (global.set $help_session_status (global.get $HELP_DISPATCH_NO_DOCUMENT))
        (return (i32.const 0))))
    (if (i32.eqz (call $help_session_owner_matches (local.get $caller)))
      (then
        (global.set $help_session_status (global.get $HELP_DISPATCH_OWNER_MISMATCH))
        (return (i32.const 0))))
    ;; Only hotspot selectors choose a secondary window. An API-issued command
    ;; always presents in the canonical main viewer.
    (global.set $help_session_window_index (i32.const -1))

    (if (i32.or
          (i32.eq (local.get $command) (global.get $HELP_COMMAND_CONTEXT))
          (i32.eq (local.get $command) (global.get $HELP_COMMAND_CONTEXTPOPUP)))
      (then
        (local.set $topic_ref (call $help_resolve_context_id (local.get $data)))
        (if (i32.lt_s (local.get $topic_ref) (i32.const 0))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_UNRESOLVED))
            (return (i32.const 0))))
        (return (call $help_session_commit_topic
          (local.get $caller) (local.get $command) (local.get $topic_ref)
          (if (result i32)
            (i32.eq (local.get $command) (global.get $HELP_COMMAND_CONTEXTPOPUP))
            (then (i32.const 2)) (else (i32.const 1)))))))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_CONTENTS))
      (then
        (local.set $topic_ref
          (if (result i32)
            (i32.ge_s (global.get $help_session_contents_override) (i32.const 0))
            (then (global.get $help_session_contents_override))
            (else (global.get $help_doc_contents_ref))))
        (return (call $help_session_commit_topic
          (local.get $caller) (local.get $command) (local.get $topic_ref)
          (i32.const 1)))))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_FINDER))
      (then
        (return (call $help_session_commit_dialog
          (local.get $caller) (local.get $command) (i32.const 3) (i32.const -1)))))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_KEY))
      (then
        (local.set $length (call $help_cstring_length_memory
          (local.get $data) (i32.const 512)))
        (if (i32.le_s (local.get $length) (i32.const 0))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_BAD_DATA))
            (return (i32.const 0))))
        (local.set $topic_ref (call $help_resolve_keyword
          (local.get $data) (local.get $length) (i32.const 0)))
        (if (i32.lt_s (local.get $topic_ref) (i32.const 0))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_UNRESOLVED))
            (return (i32.const 0))))
        (return (call $help_session_commit_topic
          (local.get $caller) (local.get $command) (local.get $topic_ref)
          (i32.const 1)))))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_PARTIALKEY))
      (then
        (local.set $length (call $help_cstring_length_memory
          (local.get $data) (i32.const 512)))
        (if (i32.lt_s (local.get $length) (i32.const 0))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_BAD_DATA))
            (return (i32.const 0))))
        (local.set $keyword_index (i32.const -1))
        (if (local.get $length)
          (then
            (local.set $keyword_index (call $help_find_keyword
              (local.get $data) (local.get $length) (i32.const 1)))
            (if (i32.lt_s (local.get $keyword_index) (i32.const 0))
              (then
                (global.set $help_session_status (global.get $HELP_DISPATCH_UNRESOLVED))
                (return (i32.const 0))))))
        (return (call $help_session_commit_dialog
          (local.get $caller) (local.get $command) (i32.const 4)
          (local.get $keyword_index)))))

    (if (i32.eq (local.get $command) (global.get $HELP_COMMAND_SETCONTENTS))
      (then
        (local.set $topic_ref (call $help_resolve_context_id (local.get $data)))
        (if (i32.lt_s (call $help_find_topic_index_in
              (global.get $help_doc_topics_wa) (global.get $help_doc_topic_count)
              (local.get $topic_ref)) (i32.const 0))
          (then
            (global.set $help_session_status (global.get $HELP_DISPATCH_UNRESOLVED))
            (return (i32.const 0))))
        (if (i32.eqz (global.get $help_session_owner))
          (then (global.set $help_session_owner (local.get $caller))))
        (global.set $help_session_contents_override (local.get $topic_ref))
        (global.set $help_session_status (global.get $HELP_DISPATCH_ACCEPTED))
        (return (i32.const 1))))

    ;; Context tables, MULTIKEY, placement, and macro execution are separate
    ;; bounded data formats. Until those parsers land they fail explicitly.
    (global.set $help_session_status (global.get $HELP_DISPATCH_UNSUPPORTED))
    (i32.const 0))

  ;; Focused parser/inspection exports. They expose immutable WAT-owned
  ;; records and never introduce an alternate host semantic path.
  (func (export "test_help_reset")
    (call $help_document_snapshot_release_all)
    (call $help_document_reset))
  (func (export "get_help_last_error") (result i32) (global.get $help_last_error))
  (func (export "get_help_last_error_offset") (result i32) (global.get $help_last_error_offset))
  (func (export "get_help_file_ptr") (result i32) (global.get $help_doc_file_wa))
  (func (export "get_help_file_size") (result i32) (global.get $help_doc_file_size))
  (func (export "get_help_document_path_ptr") (result i32) (global.get $help_doc_path_wa))
  (func (export "get_help_document_path_len") (result i32) (global.get $help_doc_path_len))
  (func (export "get_help_document_snapshot_count") (result i32)
    (global.get $help_document_snapshot_count))
  (func (export "get_help_directory_count") (result i32) (global.get $help_doc_directory_count))
  (func (export "get_help_directory_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_directory_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_directory_wa)
      (i32.mul (local.get $index) (global.get $HELP_INTERNAL_FILE_SIZE))))
  (func (export "test_help_find_internal")
    (param $name_wa i32) (param $name_length i32) (result i32)
    (call $help_find_internal_file (local.get $name_wa) (local.get $name_length)))
  (func (export "get_help_system_minor") (result i32) (global.get $help_doc_system_minor))
  (func (export "get_help_system_major") (result i32) (global.get $help_doc_system_major))
  (func (export "get_help_system_flags") (result i32) (global.get $help_doc_system_flags))
  (func (export "get_help_system_date") (result i32) (global.get $help_doc_system_date))
  (func (export "get_help_title_ptr") (result i32)
    (if (result i32) (global.get $help_doc_title_off)
      (then (i32.add (global.get $help_doc_file_wa) (global.get $help_doc_title_off)))
      (else (i32.const 0))))
  (func (export "get_help_title_len") (result i32) (global.get $help_doc_title_len))
  (func (export "get_help_contents_ref") (result i32) (global.get $help_doc_contents_ref))
  (func (export "get_help_cnt_ptr") (result i32)
    (if (result i32) (global.get $help_doc_cnt_off)
      (then (i32.add (global.get $help_doc_file_wa) (global.get $help_doc_cnt_off)))
      (else (i32.const 0))))
  (func (export "get_help_cnt_len") (result i32) (global.get $help_doc_cnt_len))
  (func (export "get_help_topic_gather_count") (result i32)
    (global.get $help_topic_gather_count))
  (func (export "get_help_window_count") (result i32)
    (global.get $help_doc_window_count))
  (func (export "get_help_window_record") (param $index i32) (result i32)
    (call $help_window_record_at (local.get $index)))
  (func (export "test_help_find_window_index")
    (param $name i32) (param $name_len i32) (result i32)
    (call $help_find_window_index (local.get $name) (local.get $name_len)))
  (func (export "get_help_active_window_index") (result i32)
    (global.get $help_session_window_index))
  (func (export "get_help_topic_count") (result i32) (global.get $help_doc_topic_count))
  (func (export "get_help_topic_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_topic_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_topics_wa)
      (i32.mul (local.get $index) (global.get $HELP_TOPIC_SIZE))))
  (func (export "get_help_context_dropped") (result i32)
    (global.get $help_doc_context_dropped))
  (func (export "get_help_context_count") (result i32) (global.get $help_doc_context_count))
  (func (export "get_help_context_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_context_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_contexts_wa)
      (i32.mul (local.get $index) (global.get $HELP_CONTEXT_SIZE))))
  (func (export "get_help_map_count") (result i32) (global.get $help_doc_map_count))
  (func (export "get_help_map_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_map_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_maps_wa)
      (i32.mul (local.get $index) (global.get $HELP_CONTEXT_SIZE))))
  (func (export "get_help_phrase_count") (result i32) (global.get $help_doc_phrase_count))
  (func (export "get_help_phrase_image_size") (result i32)
    (global.get $help_doc_phrase_image_size))
  (func (export "get_help_phrase_ptr") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_phrase_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_phrase_image_wa)
      (i32.load (i32.add (global.get $help_doc_phrase_offsets_wa)
        (i32.mul (local.get $index) (i32.const 4))))))
  (func (export "get_help_phrase_len") (param $index i32) (result i32)
    (local $offsets i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_phrase_count))
      (then (return (i32.const 0))))
    (local.set $offsets (i32.add (global.get $help_doc_phrase_offsets_wa)
      (i32.mul (local.get $index) (i32.const 4))))
    (i32.sub (i32.load offset=4 (local.get $offsets)) (i32.load (local.get $offsets))))
  (func (export "get_help_display_record_count") (result i32)
    (global.get $help_doc_display_record_count))
  (func (export "get_help_paragraph_count") (result i32)
    (global.get $help_doc_paragraph_count))
  (func (export "get_help_table_count") (result i32)
    (global.get $help_doc_table_count))
  (func (export "get_help_format_command_count") (result i32)
    (global.get $help_doc_format_command_count))
  (func (export "get_help_font_face_count") (result i32)
    (global.get $help_doc_font_face_count))
  (func (export "get_help_font_face_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_font_face_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_font_faces_wa)
      (i32.mul (local.get $index) (global.get $HELP_FONT_FACE_SIZE))))
  (func (export "get_help_font_face_ptr") (param $index i32) (result i32)
    (local $record i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_font_face_count))
      (then (return (i32.const 0))))
    (local.set $record (i32.add (global.get $help_doc_font_faces_wa)
      (i32.mul (local.get $index) (global.get $HELP_FONT_FACE_SIZE))))
    (i32.add (global.get $help_doc_file_wa) (i32.load (local.get $record))))
  (func (export "get_help_font_face_len") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_font_face_count))
      (then (return (i32.const 0))))
    (i32.load offset=4 (i32.add (global.get $help_doc_font_faces_wa)
      (i32.mul (local.get $index) (global.get $HELP_FONT_FACE_SIZE)))))
  (func (export "get_help_font_count") (result i32) (global.get $help_doc_font_count))
  (func (export "get_help_font_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_font_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_fonts_wa)
      (i32.mul (local.get $index) (global.get $HELP_FONT_SIZE))))
  (func (export "get_help_font_metric_mode") (result i32)
    (global.get $help_doc_font_metric_mode))
  (func (export "get_help_bitmap_count") (result i32)
    (global.get $help_doc_bitmap_count))
  (func (export "get_help_bitmap_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_bitmap_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_bitmaps_wa)
      (i32.mul (local.get $index) (global.get $HELP_BITMAP_SIZE))))
  (func (export "get_help_keyword_count") (result i32)
    (global.get $help_doc_keyword_count))
  (func (export "get_help_keyword_record") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_keywords_wa)
      (i32.mul (local.get $index) (global.get $HELP_KEYWORD_SIZE))))
  (func (export "get_help_keyword_ptr") (param $index i32) (result i32)
    (local $record i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_count))
      (then (return (i32.const 0))))
    (local.set $record (i32.add (global.get $help_doc_keywords_wa)
      (i32.mul (local.get $index) (global.get $HELP_KEYWORD_SIZE))))
    (i32.add (global.get $help_doc_file_wa) (i32.load (local.get $record))))
  (func (export "get_help_keyword_len") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_count))
      (then (return (i32.const 0))))
    (i32.load offset=4 (i32.add (global.get $help_doc_keywords_wa)
      (i32.mul (local.get $index) (global.get $HELP_KEYWORD_SIZE)))))
  (func (export "get_help_keyword_posting_count") (result i32)
    (global.get $help_doc_keyword_posting_count))
  (func (export "get_help_keyword_posting") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_posting_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_keyword_postings_wa)
      (i32.mul (local.get $index) (global.get $HELP_KEYWORD_POSTING_SIZE))))
  (func (export "test_help_find_keyword")
    (param $query i32) (param $length i32) (result i32)
    (call $help_find_keyword (local.get $query) (local.get $length) (i32.const 0)))
  (func (export "test_help_find_keyword_prefix")
    (param $query i32) (param $length i32) (result i32)
    (call $help_find_keyword (local.get $query) (local.get $length) (i32.const 1)))
  (func (export "test_help_resolve_keyword")
    (param $query i32) (param $length i32) (result i32)
    (call $help_resolve_keyword (local.get $query) (local.get $length) (i32.const 0)))
  (func (export "test_help_resolve_keyword_prefix")
    (param $query i32) (param $length i32) (result i32)
    (call $help_resolve_keyword (local.get $query) (local.get $length) (i32.const 1)))
  (func (export "test_help_find_bitmap")
    (param $resource_number i32) (param $picture_index i32) (result i32)
    (local $i i32) (local $record i32)
    (block $missing (loop $scan
      (br_if $missing (i32.ge_u (local.get $i) (global.get $help_doc_bitmap_count)))
      (local.set $record (i32.add (global.get $help_doc_bitmaps_wa)
        (i32.mul (local.get $i) (global.get $HELP_BITMAP_SIZE))))
      (if (i32.and
            (i32.eq (i32.load (local.get $record)) (local.get $resource_number))
            (i32.eq (i32.load offset=4 (local.get $record)) (local.get $picture_index)))
        (then (return (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (i32.const -1))
  (func (export "test_help_resolve_context_id") (param $map_id i32) (result i32)
    (call $help_resolve_context_id (local.get $map_id)))
  (func (export "test_help_dispatch_loaded")
    (param $caller i32) (param $command i32) (param $data i32) (result i32)
    (call $help_dispatch_loaded
      (local.get $caller) (local.get $command) (local.get $data)))
  (func (export "get_help_session_owner") (result i32)
    (global.get $help_session_owner))
  (func (export "get_help_session_topic_ref") (result i32)
    (global.get $help_session_topic_ref))
  (func (export "get_help_session_topic_index") (result i32)
    (global.get $help_session_topic_index))
  (func (export "get_help_session_contents_override") (result i32)
    (global.get $help_session_contents_override))
  (func (export "get_help_session_mode") (result i32)
    (global.get $help_session_mode))
  (func (export "get_help_session_keyword_index") (result i32)
    (global.get $help_session_keyword_index))
  (func (export "get_help_session_last_command") (result i32)
    (global.get $help_session_last_command))
  (func (export "get_help_dispatch_status") (result i32)
    (global.get $help_session_status))
  (func $help_resolve_context_hash (param $hash i32) (result i32)
    (local $lo i32) (local $hi i32) (local $mid i32)
    (local $record i32) (local $value i32)
    (local.set $hi (global.get $help_doc_context_count))
    (block $missing (loop $search
      (br_if $missing (i32.ge_u (local.get $lo) (local.get $hi)))
      (local.set $mid
        (i32.add (local.get $lo)
          (i32.shr_u (i32.sub (local.get $hi) (local.get $lo)) (i32.const 1))))
      (local.set $record (i32.add (global.get $help_doc_contexts_wa)
        (i32.mul (local.get $mid) (global.get $HELP_CONTEXT_SIZE))))
      (local.set $value (i32.load (local.get $record)))
      (if (i32.eq (local.get $value) (local.get $hash))
        (then (return (i32.load offset=4 (local.get $record)))))
      (if (i32.lt_s (local.get $value) (local.get $hash))
        (then (local.set $lo (i32.add (local.get $mid) (i32.const 1))))
        (else (local.set $hi (local.get $mid))))
      (br $search)))
    (i32.const -1))
  (func (export "test_help_resolve_context_hash") (param $hash i32) (result i32)
    (call $help_resolve_context_hash (local.get $hash)))
