  ;; ---- Bounded WAT-native CNT contents parser -----------------------

  (func $help_cnt_lower (param $ch i32) (result i32)
    (if (result i32) (i32.and
          (i32.ge_u (local.get $ch) (i32.const 65))
          (i32.le_u (local.get $ch) (i32.const 90)))
      (then (i32.add (local.get $ch) (i32.const 32)))
      (else (local.get $ch))))

  (func $help_cnt_char_is_space (param $ch i32) (result i32)
    (i32.or (i32.eq (local.get $ch) (i32.const 0x20))
            (i32.eq (local.get $ch) (i32.const 0x09))))

  (func $help_cnt_directive_kind
    (param $ptr i32) (param $length i32) (result i32)
    (local $c0 i32) (local $c1 i32) (local $c2 i32)
    (local $c3 i32) (local $c4 i32) (local $c5 i32) (local $c6 i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const 0))))
    (local.set $c0 (call $help_cnt_lower (i32.load8_u (local.get $ptr))))
    (if (i32.gt_u (local.get $length) (i32.const 1))
      (then (local.set $c1 (call $help_cnt_lower (i32.load8_u offset=1 (local.get $ptr))))))
    (if (i32.gt_u (local.get $length) (i32.const 2))
      (then (local.set $c2 (call $help_cnt_lower (i32.load8_u offset=2 (local.get $ptr))))))
    (if (i32.gt_u (local.get $length) (i32.const 3))
      (then (local.set $c3 (call $help_cnt_lower (i32.load8_u offset=3 (local.get $ptr))))))
    (if (i32.gt_u (local.get $length) (i32.const 4))
      (then (local.set $c4 (call $help_cnt_lower (i32.load8_u offset=4 (local.get $ptr))))))
    (if (i32.gt_u (local.get $length) (i32.const 5))
      (then (local.set $c5 (call $help_cnt_lower (i32.load8_u offset=5 (local.get $ptr))))))
    (if (i32.gt_u (local.get $length) (i32.const 6))
      (then (local.set $c6 (call $help_cnt_lower (i32.load8_u offset=6 (local.get $ptr))))))
    ;; 1=:Base, 2=:Title, 3=:Index, 4=:Include, 5=:Link, 6=:NoDef.
    (if (i32.and (i32.eq (local.get $length) (i32.const 4))
          (i32.and (i32.eq (local.get $c0) (i32.const 98))
            (i32.and (i32.eq (local.get $c1) (i32.const 97))
              (i32.and (i32.eq (local.get $c2) (i32.const 115))
                       (i32.eq (local.get $c3) (i32.const 101))))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 5))
          (i32.and (i32.eq (local.get $c0) (i32.const 116))
            (i32.and (i32.eq (local.get $c1) (i32.const 105))
              (i32.and (i32.eq (local.get $c2) (i32.const 116))
                (i32.and (i32.eq (local.get $c3) (i32.const 108))
                         (i32.eq (local.get $c4) (i32.const 101)))))))
      (then (return (i32.const 2))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 5))
          (i32.and (i32.eq (local.get $c0) (i32.const 105))
            (i32.and (i32.eq (local.get $c1) (i32.const 110))
              (i32.and (i32.eq (local.get $c2) (i32.const 100))
                (i32.and (i32.eq (local.get $c3) (i32.const 101))
                         (i32.eq (local.get $c4) (i32.const 120)))))))
      (then (return (i32.const 3))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 7))
          (i32.and (i32.eq (local.get $c0) (i32.const 105))
            (i32.and (i32.eq (local.get $c1) (i32.const 110))
              (i32.and (i32.eq (local.get $c2) (i32.const 99))
                (i32.and (i32.eq (local.get $c3) (i32.const 108))
                  (i32.and (i32.eq (local.get $c4) (i32.const 117))
                    (i32.and (i32.eq (local.get $c5) (i32.const 100))
                             (i32.eq (local.get $c6) (i32.const 101)))))))))
      (then (return (i32.const 4))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 4))
          (i32.and (i32.eq (local.get $c0) (i32.const 108))
            (i32.and (i32.eq (local.get $c1) (i32.const 105))
              (i32.and (i32.eq (local.get $c2) (i32.const 110))
                       (i32.eq (local.get $c3) (i32.const 107))))))
      (then (return (i32.const 5))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 5))
          (i32.and (i32.eq (local.get $c0) (i32.const 110))
            (i32.and (i32.eq (local.get $c1) (i32.const 111))
              (i32.and (i32.eq (local.get $c2) (i32.const 100))
                (i32.and (i32.eq (local.get $c3) (i32.const 101))
                         (i32.eq (local.get $c4) (i32.const 102)))))))
      (then (return (i32.const 6))))
    (i32.const 0))

  ;; Help compiler context-name hash from the documented 256-byte mapping.
  (func $help_cnt_hash_char (param $ch i32) (result i32)
    (if (i32.eqz (local.get $ch)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $ch) (i32.const 33))
      (then (return (i32.const 11))))
    (if (i32.eq (local.get $ch) (i32.const 46))
      (then (return (i32.const 12))))
    (if (i32.le_u (local.get $ch) (i32.const 90))
      (then (return (i32.sub (local.get $ch) (i32.const 48)))))
    (if (i32.le_u (local.get $ch) (i32.const 94))
      (then (return (i32.sub (local.get $ch) (i32.const 80)))))
    (if (i32.eq (local.get $ch) (i32.const 95))
      (then (return (i32.const 13))))
    (if (i32.eq (local.get $ch) (i32.const 96))
      (then (return (i32.const 16))))
    (if (i32.le_u (local.get $ch) (i32.const 127))
      (then (return (i32.sub (local.get $ch) (i32.const 80)))))
    (if (i32.eq (local.get $ch) (i32.const 132))
      (then (return (i32.const 11))))
    (i32.extend8_s (local.get $ch)))

  (func $help_cnt_hash (param $ptr i32) (param $length i32) (result i32)
    (local $i i32) (local $hash i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const 1))))
    (block $done (loop $chars
      (br_if $done (i32.ge_u (local.get $i) (local.get $length)))
      (local.set $hash (i32.add
        (i32.mul (local.get $hash) (i32.const 43))
        (call $help_cnt_hash_char
          (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $chars)))
    (local.get $hash))

  (func $help_cnt_resolve_target
    (param $ptr i32) (param $length i32) (result i32)
    (local $i i32) (local $numeric i32) (local $value i32) (local $ch i32)
    (local $hash_length i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const -1))))
    (local.set $numeric (i32.const 1))
    (local.set $hash_length (local.get $length))
    (block $done (loop $scan
      (br_if $done (i32.ge_u (local.get $i) (local.get $length)))
      (local.set $ch (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))
      (if (i32.or (i32.eq (local.get $ch) (i32.const 64))
                  (i32.eq (local.get $ch) (i32.const 62)))
        (then
          (local.set $hash_length (local.get $i))
          (br $done)))
      (if (i32.or (i32.lt_u (local.get $ch) (i32.const 48))
                  (i32.gt_u (local.get $ch) (i32.const 57)))
        (then (local.set $numeric (i32.const 0))))
      (if (local.get $numeric)
        (then
          (if (i32.gt_u (local.get $value) (i32.const 99882960))
            (then (local.set $numeric (i32.const 0)))
            (else (local.set $value (i32.add
              (i32.mul (local.get $value) (i32.const 10))
              (i32.sub (local.get $ch) (i32.const 48))))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $scan)))
    (if (i32.and (local.get $numeric)
          (i32.eq (local.get $hash_length) (local.get $length)))
      (then (return (call $help_resolve_context_id (local.get $value)))))
    (call $help_resolve_context_hash
      (call $help_cnt_hash (local.get $ptr) (local.get $hash_length))))

  (func $help_cnt_count_nodes
    (param $source i32) (param $size i32) (result i32)
    (local $pos i32) (local $line_start i32) (local $line_end i32)
    (local $ptr i32) (local $end i32) (local $count i32)
    (local $depth i32) (local $previous_depth i32) (local $ch i32)
    (block $all_done (loop $lines
      (br_if $all_done (i32.ge_u (local.get $pos) (local.get $size)))
      (local.set $line_start (local.get $pos))
      (block $line_done (loop $line
        (br_if $line_done (i32.ge_u (local.get $pos) (local.get $size)))
        (local.set $ch (i32.load8_u (i32.add (local.get $source) (local.get $pos))))
        (if (i32.eqz (local.get $ch))
          (then
            (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $pos))
            (return (i32.const -1))))
        (br_if $line_done (i32.or (i32.eq (local.get $ch) (i32.const 10))
                                  (i32.eq (local.get $ch) (i32.const 13))))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (if (i32.gt_u (i32.sub (local.get $pos) (local.get $line_start)) (i32.const 4096))
          (then
            (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
            (return (i32.const -1))))
        (br $line)))
      (local.set $line_end (local.get $pos))
      (block $breaks_done (loop $breaks
        (br_if $breaks_done (i32.ge_u (local.get $pos) (local.get $size)))
        (local.set $ch (i32.load8_u (i32.add (local.get $source) (local.get $pos))))
        (br_if $breaks_done (i32.and (i32.ne (local.get $ch) (i32.const 10))
                                     (i32.ne (local.get $ch) (i32.const 13))))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (br $breaks)))
      (local.set $ptr (i32.add (local.get $source) (local.get $line_start)))
      (local.set $end (i32.add (local.get $source) (local.get $line_end)))
      (block $leading_done (loop $leading
        (br_if $leading_done (i32.ge_u (local.get $ptr) (local.get $end)))
        (br_if $leading_done (i32.eqz (call $help_cnt_char_is_space
          (i32.load8_u (local.get $ptr)))))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (br $leading)))
      (if (i32.lt_u (local.get $ptr) (local.get $end))
        (then
          (local.set $ch (i32.load8_u (local.get $ptr)))
          (if (i32.and (i32.ne (local.get $ch) (i32.const 58))
                (i32.ne (local.get $ch) (i32.const 59)))
            (then
              (if (i32.or (i32.lt_u (local.get $ch) (i32.const 49))
                          (i32.gt_u (local.get $ch) (i32.const 57)))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                  (return (i32.const -1))))
              (local.set $depth (i32.const 0))
              (block $depth_done (loop $digits
                (br_if $depth_done (i32.ge_u (local.get $ptr) (local.get $end)))
                (local.set $ch (i32.load8_u (local.get $ptr)))
                (br_if $depth_done (i32.or (i32.lt_u (local.get $ch) (i32.const 48))
                                           (i32.gt_u (local.get $ch) (i32.const 57))))
                (local.set $depth (i32.add (i32.mul (local.get $depth) (i32.const 10))
                  (i32.sub (local.get $ch) (i32.const 48))))
                (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
                (br $digits)))
              (if (i32.or (i32.eqz (local.get $depth))
                    (i32.gt_u (local.get $depth) (global.get $HELP_MAX_CNT_DEPTH)))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                  (return (i32.const -1))))
              (if (i32.and (local.get $count)
                    (i32.gt_u (local.get $depth) (i32.add (local.get $previous_depth) (i32.const 1))))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                  (return (i32.const -1))))
              (if (i32.and (i32.eqz (local.get $count))
                    (i32.ne (local.get $depth) (i32.const 1)))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                  (return (i32.const -1))))
              (local.set $previous_depth (local.get $depth))
              (local.set $count (i32.add (local.get $count) (i32.const 1)))
              (if (i32.gt_u (local.get $count) (global.get $HELP_MAX_CNT_NODES))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CAPACITY) (local.get $line_start))
                  (return (i32.const -1))))))))
      (br $lines)))
    (local.get $count))

  (func $help_load_cnt_buffer
    (param $source i32) (param $size i32) (result i32)
    (local $memory_bytes i32) (local $count i32)
    (local $file_ga i32) (local $file_wa i32)
    (local $nodes_ga i32) (local $nodes_wa i32) (local $stack_ga i32) (local $stack_wa i32)
    (local $pos i32) (local $line_start i32) (local $line_end i32)
    (local $ptr i32) (local $end i32) (local $key_start i32) (local $key_len i32)
    (local $value_start i32) (local $value_end i32) (local $directive i32)
    (local $depth i32) (local $ch i32) (local $title_start i32) (local $title_end i32)
    (local $equals i32) (local $target_start i32) (local $target_end i32)
    (local $node_index i32) (local $node i32) (local $parent i32)
    (local $previous i32) (local $parent_node i32) (local $flags i32)
    (local $topic_ref i32) (local $i i32) (local $target_scan i32) (local $ok i32)
    (local $title_wa i32) (local $title_len i32) (local $base_wa i32) (local $base_len i32)
    (global.set $help_last_error (global.get $HELP_ERROR_NONE))
    (global.set $help_last_error_offset (i32.const 0))
    (local.set $memory_bytes (i32.shl (memory.size) (i32.const 16)))
    (if (i32.or (i32.eqz (local.get $size))
          (i32.or (i32.gt_u (local.get $size) (global.get $HELP_MAX_CNT_BYTES))
            (i32.or (i32.gt_u (local.get $source) (local.get $memory_bytes))
              (i32.gt_u (local.get $size) (i32.sub (local.get $memory_bytes) (local.get $source))))))
      (then
        (call $help_set_error
          (select (global.get $HELP_ERROR_CAPACITY) (global.get $HELP_ERROR_BAD_ARGUMENT)
            (i32.gt_u (local.get $size) (global.get $HELP_MAX_CNT_BYTES)))
          (i32.const 0))
        (return (i32.const 0))))
    (local.set $count (call $help_cnt_count_nodes (local.get $source) (local.get $size)))
    (if (i32.lt_s (local.get $count) (i32.const 0)) (then (return (i32.const 0))))
    (block $cleanup
    (local.set $file_ga (call $heap_alloc (i32.add (local.get $size) (i32.const 1))))
    (if (i32.eqz (local.get $file_ga))
      (then
        (call $help_set_error (global.get $HELP_ERROR_ALLOCATION) (i32.const 0))
        (return (i32.const 0))))
    (local.set $file_wa (call $g2w (local.get $file_ga)))
    (memory.copy (local.get $file_wa) (local.get $source) (local.get $size))
    (i32.store8 (i32.add (local.get $file_wa) (local.get $size)) (i32.const 0))
    (if (local.get $count)
      (then
        (local.set $nodes_ga (call $heap_alloc
          (i32.mul (local.get $count) (global.get $HELP_CNT_NODE_SIZE))))
        (if (i32.eqz (local.get $nodes_ga))
          (then
            (call $help_set_error (global.get $HELP_ERROR_ALLOCATION) (i32.const 0))
            (br $cleanup)))
        (local.set $nodes_wa (call $g2w (local.get $nodes_ga)))
        (memory.fill (local.get $nodes_wa) (i32.const 0xFF)
          (i32.mul (local.get $count) (global.get $HELP_CNT_NODE_SIZE)))))
    (local.set $stack_ga (call $heap_alloc
      (i32.mul (global.get $HELP_MAX_CNT_DEPTH) (i32.const 4))))
    (if (i32.eqz (local.get $stack_ga))
      (then
        (call $help_set_error (global.get $HELP_ERROR_ALLOCATION) (i32.const 0))
        (br $cleanup)))
    (local.set $stack_wa (call $g2w (local.get $stack_ga)))
    (memory.fill (local.get $stack_wa) (i32.const 0xFF)
      (i32.mul (global.get $HELP_MAX_CNT_DEPTH) (i32.const 4)))
    (block $all_done (loop $lines
      (br_if $all_done (i32.ge_u (local.get $pos) (local.get $size)))
      (local.set $line_start (local.get $pos))
      (block $line_done (loop $line
        (br_if $line_done (i32.ge_u (local.get $pos) (local.get $size)))
        (local.set $ch (i32.load8_u (i32.add (local.get $file_wa) (local.get $pos))))
        (br_if $line_done (i32.or (i32.eq (local.get $ch) (i32.const 10))
                                  (i32.eq (local.get $ch) (i32.const 13))))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (br $line)))
      (local.set $line_end (local.get $pos))
      (block $breaks_done (loop $breaks
        (br_if $breaks_done (i32.ge_u (local.get $pos) (local.get $size)))
        (local.set $ch (i32.load8_u (i32.add (local.get $file_wa) (local.get $pos))))
        (br_if $breaks_done (i32.and (i32.ne (local.get $ch) (i32.const 10))
                                     (i32.ne (local.get $ch) (i32.const 13))))
        (i32.store8 (i32.add (local.get $file_wa) (local.get $pos)) (i32.const 0))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (br $breaks)))
      (local.set $ptr (i32.add (local.get $file_wa) (local.get $line_start)))
      (local.set $end (i32.add (local.get $file_wa) (local.get $line_end)))
      (block $trim_end_done (loop $trim_end
        (br_if $trim_end_done (i32.ge_u (local.get $ptr) (local.get $end)))
        (br_if $trim_end_done (i32.eqz (call $help_cnt_char_is_space
          (i32.load8_u (i32.sub (local.get $end) (i32.const 1))))))
        (local.set $end (i32.sub (local.get $end) (i32.const 1)))
        (br $trim_end)))
      (i32.store8 (local.get $end) (i32.const 0))
      (block $trim_start_done (loop $trim_start
        (br_if $trim_start_done (i32.ge_u (local.get $ptr) (local.get $end)))
        (br_if $trim_start_done (i32.eqz (call $help_cnt_char_is_space
          (i32.load8_u (local.get $ptr)))))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (br $trim_start)))
      (if (i32.lt_u (local.get $ptr) (local.get $end))
        (then
          (local.set $ch (i32.load8_u (local.get $ptr)))
          (if (i32.eq (local.get $ch) (i32.const 58))
            (then
              (local.set $key_start (i32.add (local.get $ptr) (i32.const 1)))
              (local.set $value_start (local.get $key_start))
              (block $key_done (loop $key
                (br_if $key_done (i32.ge_u (local.get $value_start) (local.get $end)))
                (br_if $key_done (call $help_cnt_char_is_space
                  (i32.load8_u (local.get $value_start))))
                (local.set $value_start (i32.add (local.get $value_start) (i32.const 1)))
                (br $key)))
              (local.set $key_len (i32.sub (local.get $value_start) (local.get $key_start)))
              (local.set $directive (call $help_cnt_directive_kind
                (local.get $key_start) (local.get $key_len)))
              (if (i32.eqz (local.get $directive))
                (then
                  (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                  (br $cleanup)))
              (block $value_space_done (loop $value_space
                (br_if $value_space_done (i32.ge_u (local.get $value_start) (local.get $end)))
                (br_if $value_space_done (i32.eqz (call $help_cnt_char_is_space
                  (i32.load8_u (local.get $value_start)))))
                (local.set $value_start (i32.add (local.get $value_start) (i32.const 1)))
                (br $value_space)))
              (local.set $value_end (local.get $end))
              (if (i32.or (i32.eq (local.get $directive) (i32.const 1))
                          (i32.eq (local.get $directive) (i32.const 2)))
                (then
                  (if (i32.ge_u (local.get $value_start) (local.get $value_end))
                    (then
                      (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                      (br $cleanup)))
                  (if (i32.eq (local.get $directive) (i32.const 1))
                    (then
                      (local.set $base_wa (local.get $value_start))
                      (local.set $base_len (i32.sub (local.get $value_end) (local.get $value_start))))
                    (else
                      (local.set $title_wa (local.get $value_start))
                      (local.set $title_len (i32.sub (local.get $value_end) (local.get $value_start))))))))
            (else
              (if (i32.ne (local.get $ch) (i32.const 59))
                (then
                  (local.set $depth (i32.const 0))
                  (block $depth_done (loop $digits
                    (br_if $depth_done (i32.ge_u (local.get $ptr) (local.get $end)))
                    (local.set $ch (i32.load8_u (local.get $ptr)))
                    (br_if $depth_done (i32.or (i32.lt_u (local.get $ch) (i32.const 48))
                                               (i32.gt_u (local.get $ch) (i32.const 57))))
                    (local.set $depth (i32.add (i32.mul (local.get $depth) (i32.const 10))
                      (i32.sub (local.get $ch) (i32.const 48))))
                    (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
                    (br $digits)))
                  (block $title_space_done (loop $title_space
                    (br_if $title_space_done (i32.ge_u (local.get $ptr) (local.get $end)))
                    (br_if $title_space_done (i32.eqz (call $help_cnt_char_is_space
                      (i32.load8_u (local.get $ptr)))))
                    (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
                    (br $title_space)))
                  (local.set $title_start (local.get $ptr))
                  (local.set $equals (i32.const 0))
                  (block $equals_done (loop $find_equals
                    (br_if $equals_done (i32.ge_u (local.get $ptr) (local.get $end)))
                    (if (i32.eq (i32.load8_u (local.get $ptr)) (i32.const 61))
                      (then
                        (local.set $equals (local.get $ptr))
                        (br $equals_done)))
                    (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
                    (br $find_equals)))
                  (local.set $title_end (select (local.get $equals) (local.get $end)
                    (i32.ne (local.get $equals) (i32.const 0))))
                  (block $title_trim_done (loop $title_trim
                    (br_if $title_trim_done (i32.ge_u (local.get $title_start) (local.get $title_end)))
                    (br_if $title_trim_done (i32.eqz (call $help_cnt_char_is_space
                      (i32.load8_u (i32.sub (local.get $title_end) (i32.const 1))))))
                    (local.set $title_end (i32.sub (local.get $title_end) (i32.const 1)))
                    (br $title_trim)))
                  (if (i32.ge_u (local.get $title_start) (local.get $title_end))
                    (then
                      (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                      (br $cleanup)))
                  (i32.store8 (local.get $title_end) (i32.const 0))
                  (local.set $target_start (i32.const 0))
                  (local.set $target_end (i32.const 0))
                  (local.set $flags (global.get $HELP_CNT_BOOK))
                  (local.set $topic_ref (i32.const -1))
                  (if (local.get $equals)
                    (then
                      (local.set $target_start (i32.add (local.get $equals) (i32.const 1)))
                      (block $target_space_done (loop $target_space
                        (br_if $target_space_done (i32.ge_u (local.get $target_start) (local.get $end)))
                        (br_if $target_space_done (i32.eqz (call $help_cnt_char_is_space
                          (i32.load8_u (local.get $target_start)))))
                        (local.set $target_start (i32.add (local.get $target_start) (i32.const 1)))
                        (br $target_space)))
                      (local.set $target_end (local.get $end))
                      (if (i32.ge_u (local.get $target_start) (local.get $target_end))
                        (then
                          (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                          (br $cleanup)))
                      (local.set $flags (global.get $HELP_CNT_LEAF))
                      (if (i32.eq (i32.load8_u (local.get $target_start)) (i32.const 33))
                        (then (local.set $flags (i32.or (local.get $flags)
                          (i32.or (global.get $HELP_CNT_MACRO) (global.get $HELP_CNT_UNRESOLVED)))))
                        (else
                          (local.set $target_scan (local.get $target_start))
                          (block $external_done (loop $external
                            (br_if $external_done (i32.ge_u (local.get $target_scan) (local.get $target_end)))
                            (if (i32.eq (i32.load8_u (local.get $target_scan)) (i32.const 64))
                              (then
                                (local.set $flags (i32.or (local.get $flags)
                                  (global.get $HELP_CNT_EXTERNAL)))
                                (br $external_done)))
                            (local.set $target_scan (i32.add (local.get $target_scan) (i32.const 1)))
                            (br $external)))
                          (local.set $topic_ref (call $help_cnt_resolve_target
                            (local.get $target_start)
                            (i32.sub (local.get $target_end) (local.get $target_start))))
                          (if (i32.lt_s (local.get $topic_ref) (i32.const 0))
                            (then (local.set $flags (i32.or (local.get $flags)
                              (global.get $HELP_CNT_UNRESOLVED)))))))))
                  (local.set $parent (i32.const -1))
                  (if (i32.gt_u (local.get $depth) (i32.const 1))
                    (then
                      (local.set $parent (i32.load (i32.add (local.get $stack_wa)
                        (i32.shl (i32.sub (local.get $depth) (i32.const 2)) (i32.const 2)))))
                      (if (i32.lt_s (local.get $parent) (i32.const 0))
                        (then
                          (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                          (br $cleanup)))
                      (local.set $parent_node (i32.add (local.get $nodes_wa)
                        (i32.mul (local.get $parent) (global.get $HELP_CNT_NODE_SIZE))))
                      (if (i32.and (i32.load16_u offset=14 (local.get $parent_node))
                            (global.get $HELP_CNT_LEAF))
                        (then
                          (call $help_set_error (global.get $HELP_ERROR_CNT) (local.get $line_start))
                          (br $cleanup)))))
                  (local.set $node (i32.add (local.get $nodes_wa)
                    (i32.mul (local.get $node_index) (global.get $HELP_CNT_NODE_SIZE))))
                  (i32.store (local.get $node) (local.get $parent))
                  (i32.store offset=4 (local.get $node) (i32.const -1))
                  (i32.store offset=8 (local.get $node) (i32.const -1))
                  (i32.store16 offset=12 (local.get $node) (local.get $depth))
                  (i32.store16 offset=14 (local.get $node) (local.get $flags))
                  (i32.store offset=16 (local.get $node) (local.get $title_start))
                  (i32.store offset=20 (local.get $node)
                    (i32.sub (local.get $title_end) (local.get $title_start)))
                  (i32.store offset=24 (local.get $node) (local.get $topic_ref))
                  (i32.store offset=28 (local.get $node) (local.get $target_start))
                  (local.set $previous (i32.load (i32.add (local.get $stack_wa)
                    (i32.shl (i32.sub (local.get $depth) (i32.const 1)) (i32.const 2)))))
                  (if (i32.ge_s (local.get $previous) (i32.const 0))
                    (then
                      (local.set $parent_node (i32.add (local.get $nodes_wa)
                        (i32.mul (local.get $previous) (global.get $HELP_CNT_NODE_SIZE))))
                      (if (i32.eq (i32.load (local.get $parent_node)) (local.get $parent))
                        (then (i32.store offset=8 (local.get $parent_node) (local.get $node_index))))))
                  (if (i32.ge_s (local.get $parent) (i32.const 0))
                    (then
                      (local.set $parent_node (i32.add (local.get $nodes_wa)
                        (i32.mul (local.get $parent) (global.get $HELP_CNT_NODE_SIZE))))
                      (if (i32.lt_s (i32.load offset=4 (local.get $parent_node)) (i32.const 0))
                        (then (i32.store offset=4 (local.get $parent_node) (local.get $node_index))))))
                  (i32.store (i32.add (local.get $stack_wa)
                    (i32.shl (i32.sub (local.get $depth) (i32.const 1)) (i32.const 2)))
                    (local.get $node_index))
                  (local.set $i (local.get $depth))
                  (block $clear_done (loop $clear
                    (br_if $clear_done (i32.ge_u (local.get $i) (global.get $HELP_MAX_CNT_DEPTH)))
                    (i32.store (i32.add (local.get $stack_wa) (i32.shl (local.get $i) (i32.const 2)))
                      (i32.const -1))
                    (local.set $i (i32.add (local.get $i) (i32.const 1)))
                    (br $clear)))
                  (local.set $node_index (i32.add (local.get $node_index) (i32.const 1)))))))))
      (br $lines)))
    (if (i32.ne (local.get $node_index) (local.get $count))
      (then
        (call $help_set_error (global.get $HELP_ERROR_CNT) (i32.const 0))
        (br $cleanup)))
    (local.set $ok (i32.const 1)))
    (if (local.get $stack_ga) (then (call $heap_free (local.get $stack_ga))))
    (if (i32.eqz (local.get $ok))
      (then
        (if (local.get $nodes_ga) (then (call $heap_free (local.get $nodes_ga))))
        (if (local.get $file_ga) (then (call $heap_free (local.get $file_ga))))
        (return (i32.const 0))))
    ;; Publish only after the complete hierarchy and every binding validate.
    (if (global.get $help_doc_cnt_nodes_ga)
      (then (call $heap_free (global.get $help_doc_cnt_nodes_ga))))
    (if (global.get $help_doc_cnt_file_ga)
      (then (call $heap_free (global.get $help_doc_cnt_file_ga))))
    (global.set $help_doc_cnt_file_ga (local.get $file_ga))
    (global.set $help_doc_cnt_file_wa (local.get $file_wa))
    (global.set $help_doc_cnt_file_size (local.get $size))
    (global.set $help_doc_cnt_nodes_ga (local.get $nodes_ga))
    (global.set $help_doc_cnt_nodes_wa (local.get $nodes_wa))
    (global.set $help_doc_cnt_node_count (local.get $count))
    (global.set $help_doc_cnt_title_wa (local.get $title_wa))
    (global.set $help_doc_cnt_title_len (local.get $title_len))
    (global.set $help_doc_cnt_base_wa (local.get $base_wa))
    (global.set $help_doc_cnt_base_len (local.get $base_len))
    (i32.const 1))

  (func (export "test_help_load_cnt_buffer")
    (param $source i32) (param $size i32) (result i32)
    (call $help_load_cnt_buffer (local.get $source) (local.get $size)))
  (func (export "test_help_cnt_hash")
    (param $ptr i32) (param $length i32) (result i32)
    (call $help_cnt_hash (local.get $ptr) (local.get $length)))
  (func (export "test_help_cnt_directive_kind")
    (param $ptr i32) (param $length i32) (result i32)
    (call $help_cnt_directive_kind (local.get $ptr) (local.get $length)))
  (func (export "get_help_cnt_node_count") (result i32)
    (global.get $help_doc_cnt_node_count))
  (func (export "get_help_cnt_node") (param $index i32) (result i32)
    (if (i32.ge_u (local.get $index) (global.get $help_doc_cnt_node_count))
      (then (return (i32.const 0))))
    (i32.add (global.get $help_doc_cnt_nodes_wa)
      (i32.mul (local.get $index) (global.get $HELP_CNT_NODE_SIZE))))
  (func (export "get_help_cnt_title_ptr") (result i32)
    (global.get $help_doc_cnt_title_wa))
  (func (export "get_help_cnt_title_length") (result i32)
    (global.get $help_doc_cnt_title_len))
  (func (export "get_help_cnt_base_ptr") (result i32)
    (global.get $help_doc_cnt_base_wa))
  (func (export "get_help_cnt_base_length") (result i32)
    (global.get $help_doc_cnt_base_len))
