  ;; ---- WAT-native WinHelp typed topic layout ------------------------

  ;; A positioned run is 40 bytes:
  ;;   kind, x, y, width, height, raw_off, raw_len, font_index, color, flags.
  ;; Text offsets remain relative to the immutable decoded LinkData2 arena.
  (global $HELP_LAYOUT_RUN_SIZE i32 (i32.const 40))
  (global $HELP_MAX_LAYOUT_RUNS i32 (i32.const 131072))
  (global $HELP_LAYOUT_TEXT i32 (i32.const 1))
  (global $HELP_LAYOUT_SPACE i32 (i32.const 2))
  (global $HELP_LAYOUT_BITMAP i32 (i32.const 9))

  (global $help_view_tokens_ga (mut i32) (i32.const 0))
  (global $help_view_tokens_wa (mut i32) (i32.const 0))
  (global $help_view_token_count (mut i32) (i32.const 0))
  (global $help_view_payload_ga (mut i32) (i32.const 0))
  (global $help_view_payload_wa (mut i32) (i32.const 0))
  (global $help_view_payload_len (mut i32) (i32.const 0))
  (global $help_view_runs_ga (mut i32) (i32.const 0))
  (global $help_view_runs_wa (mut i32) (i32.const 0))
  (global $help_view_run_count (mut i32) (i32.const 0))
  (global $help_view_extent_height (mut i32) (i32.const 0))
  (global $help_view_layout_width (mut i32) (i32.const 0))

  ;; Private two-pass layout channel. A zero output pointer counts and
  ;; validates exact run requirements without writing any records.
  (global $help_layout_out (mut i32) (i32.const 0))
  (global $help_layout_capacity (mut i32) (i32.const 0))
  (global $help_layout_count (mut i32) (i32.const 0))
  (global $help_layout_extent (mut i32) (i32.const 0))

  (func $help_layout_emit
    (param $kind i32) (param $x i32) (param $y i32)
    (param $width i32) (param $height i32)
    (param $raw_off i32) (param $raw_len i32)
    (param $font_index i32) (param $color i32) (param $flags i32)
    (result i32)
    (local $run i32)
    (if (i32.ge_u (global.get $help_layout_count)
          (global.get $help_layout_capacity))
      (then (return (i32.const 0))))
    (if (global.get $help_layout_out)
      (then
        (local.set $run (i32.add (global.get $help_layout_out)
          (i32.mul (global.get $help_layout_count)
            (global.get $HELP_LAYOUT_RUN_SIZE))))
        (i32.store (local.get $run) (local.get $kind))
        (i32.store offset=4 (local.get $run) (local.get $x))
        (i32.store offset=8 (local.get $run) (local.get $y))
        (i32.store offset=12 (local.get $run) (local.get $width))
        (i32.store offset=16 (local.get $run) (local.get $height))
        (i32.store offset=20 (local.get $run) (local.get $raw_off))
        (i32.store offset=24 (local.get $run) (local.get $raw_len))
        (i32.store offset=28 (local.get $run) (local.get $font_index))
        (i32.store offset=32 (local.get $run) (local.get $color))
        (i32.store offset=36 (local.get $run) (local.get $flags))))
    (global.set $help_layout_count
      (i32.add (global.get $help_layout_count) (i32.const 1)))
    (i32.const 1))

  (func $help_layout_font_height (param $font_index i32) (result i32)
    (local $font i32) (local $height i32)
    (if (i32.ge_u (local.get $font_index) (global.get $help_doc_font_count))
      (then (return (i32.const 16))))
    (local.set $font (i32.add (global.get $help_doc_fonts_wa)
      (i32.mul (local.get $font_index) (global.get $HELP_FONT_SIZE))))
    (local.set $height (i32.load offset=4 (local.get $font)))
    (if (i32.lt_s (local.get $height) (i32.const 0))
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (global.get $help_doc_font_metric_mode)
      (then
        ;; MVB heights are twips at 96 DPI.
        (local.set $height (i32.div_u
          (i32.add (i32.mul (local.get $height) (i32.const 96)) (i32.const 1439))
          (i32.const 1440))))
      (else
        ;; Older descriptors store half-points.
        (local.set $height (i32.div_u
          (i32.add (i32.mul (local.get $height) (i32.const 96)) (i32.const 143))
          (i32.const 144)))))
    (if (i32.lt_u (local.get $height) (i32.const 8))
      (then (local.set $height (i32.const 8))))
    (if (i32.gt_u (local.get $height) (i32.const 96))
      (then (local.set $height (i32.const 96))))
    (i32.add (local.get $height) (i32.const 3)))

  (func $help_layout_measure
    (param $hdc i32) (param $text i32) (param $length i32) (result i32)
    (local $width i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const 0))))
    (local.set $width (call $host_measure_text
      (local.get $hdc) (local.get $text) (local.get $length) (i32.const 0)))
    ;; Headless or not-yet-realized DCs still get deterministic geometry.
    (if (i32.le_s (local.get $width) (i32.const 0))
      (then (local.set $width (i32.mul (local.get $length) (i32.const 8)))))
    (local.get $width))

  (func $help_layout_fit_prefix
    (param $hdc i32) (param $text i32) (param $length i32)
    (param $available i32) (result i32)
    (local $lo i32) (local $hi i32) (local $mid i32) (local $width i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const 0))))
    (if (i32.le_s (local.get $available) (i32.const 0))
      (then (return (i32.const 1))))
    (local.set $lo (i32.const 1))
    (local.set $hi (local.get $length))
    (block $done (loop $search
      (br_if $done (i32.ge_u (local.get $lo) (local.get $hi)))
      (local.set $mid (i32.shr_u
        (i32.add (i32.add (local.get $lo) (local.get $hi)) (i32.const 1))
        (i32.const 1)))
      (local.set $width (call $help_layout_measure
        (local.get $hdc) (local.get $text) (local.get $mid)))
      (if (i32.le_u (local.get $width) (local.get $available))
        (then (local.set $lo (local.get $mid)))
        (else (local.set $hi (i32.sub (local.get $mid) (i32.const 1)))))
      (br $search)))
    (local.get $lo))

  ;; Convert a validated formatted-token stream into deterministic positioned
  ;; runs. It owns wrapping, line state, font metadata, colors, and hotspot
  ;; membership; painting consumes the published records without reparsing.
  (func $help_layout_tokens_core
    (param $raw i32) (param $raw_len i32)
    (param $tokens i32) (param $token_count i32)
    (param $runs i32) (param $run_capacity i32)
    (param $client_width i32) (param $hdc i32) (result i32)
    (local $memory_bytes i32) (local $token i32) (local $kind i32)
    (local $off i32) (local $len i32) (local $value i32)
    (local $i i32) (local $pos i32) (local $span i32) (local $ch i32)
    (local $x i32) (local $y i32) (local $right i32)
    (local $width i32) (local $fit i32) (local $line_height i32)
    (local $font_index i32) (local $color i32) (local $hotspot i32)
    (local $saw_content i32) (local $ended i32)
    (global.set $help_layout_count (i32.const 0))
    (global.set $help_layout_extent (i32.const 0))
    (global.set $help_layout_out (local.get $runs))
    (global.set $help_layout_capacity (local.get $run_capacity))
    (local.set $memory_bytes (i32.shl (memory.size) (i32.const 16)))
    (if (i32.or
          (i32.or (i32.lt_u (local.get $client_width) (i32.const 32))
                  (i32.gt_u (local.get $client_width) (i32.const 4096)))
          (i32.or
            (i32.gt_u (local.get $token_count) (global.get $HELP_MAX_TOPIC_TOKENS))
            (i32.gt_u (local.get $run_capacity) (global.get $HELP_MAX_LAYOUT_RUNS))))
      (then (return (i32.const -1))))
    (if (i32.or
          (i32.or (i32.gt_u (local.get $raw) (local.get $memory_bytes))
                  (i32.gt_u (local.get $raw_len)
                    (i32.sub (local.get $memory_bytes) (local.get $raw))))
          (i32.or (i32.gt_u (local.get $tokens) (local.get $memory_bytes))
                  (i32.gt_u (local.get $token_count)
                    (i32.div_u (i32.sub (local.get $memory_bytes) (local.get $tokens))
                      (global.get $HELP_TOPIC_TOKEN_SIZE)))))
      (then (return (i32.const -1))))
    (if (i32.and (local.get $runs)
          (i32.or (i32.gt_u (local.get $runs) (local.get $memory_bytes))
                  (i32.gt_u (local.get $run_capacity)
                    (i32.div_u (i32.sub (local.get $memory_bytes) (local.get $runs))
                      (global.get $HELP_LAYOUT_RUN_SIZE)))))
      (then (return (i32.const -1))))
    (local.set $x (i32.const 8))
    (local.set $y (i32.const 8))
    (local.set $right (i32.sub (local.get $client_width) (i32.const 8)))
    (local.set $line_height (i32.const 16))
    (local.set $font_index (i32.const -1))
    (local.set $color (i32.const 0))
    (block $done (loop $tokens_loop
      (br_if $done (i32.ge_u (local.get $i) (local.get $token_count)))
      (local.set $token (i32.add (local.get $tokens)
        (i32.mul (local.get $i) (global.get $HELP_TOPIC_TOKEN_SIZE))))
      (local.set $kind (i32.load (local.get $token)))
      (local.set $off (i32.load offset=4 (local.get $token)))
      (local.set $len (i32.load offset=8 (local.get $token)))
      (local.set $value (i32.load offset=12 (local.get $token)))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_END_TOPIC))
        (then
          (local.set $ended (i32.const 1))
          (br $done)))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_PARAGRAPH))
        (then
          (if (local.get $saw_content)
            (then
              (local.set $y (i32.add (local.get $y) (local.get $line_height)))
              (local.set $x (i32.const 8))))
          (local.set $line_height (i32.const 16))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_FONT))
        (then
          (if (i32.ge_u (local.get $value) (global.get $help_doc_font_count))
            (then (return (i32.const -1))))
          (local.set $font_index (local.get $value))
          (local.set $line_height (call $help_layout_font_height (local.get $value)))
          (local.set $color (i32.load offset=20
            (i32.add (global.get $help_doc_fonts_wa)
              (i32.mul (local.get $value) (global.get $HELP_FONT_SIZE)))))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_COLOR))
        (then (local.set $color (local.get $value))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_HOTSPOT_BEGIN))
        (then (local.set $hotspot (i32.const 1))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_HOTSPOT_END))
        (then (local.set $hotspot (i32.const 0))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_LINE_BREAK))
        (then
          (local.set $y (i32.add (local.get $y) (local.get $line_height)))
          (local.set $x (i32.const 8))
          (local.set $saw_content (i32.const 1))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_SPACE))
        (then
          (local.set $width (select (i32.const 8) (i32.const 4)
            (i32.eq (local.get $value) (i32.const 0x8B))))
          (if (i32.and (i32.gt_u (local.get $x) (i32.const 8))
                (i32.gt_u (i32.add (local.get $x) (local.get $width)) (local.get $right)))
            (then
              (local.set $y (i32.add (local.get $y) (local.get $line_height)))
              (local.set $x (i32.const 8))))
          (if (i32.eqz (call $help_layout_emit
                (global.get $HELP_LAYOUT_SPACE) (local.get $x) (local.get $y)
                (local.get $width) (local.get $line_height)
                (i32.const 0) (i32.const 0) (local.get $font_index)
                (local.get $color) (local.get $hotspot)))
            (then (return (i32.const -1))))
          (local.set $x (i32.add (local.get $x) (local.get $width)))
          (local.set $saw_content (i32.const 1))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_BITMAP))
        (then
          ;; Preserve a positioned placeholder until bitmap materialization.
          (if (i32.gt_u (i32.add (local.get $x) (i32.const 16)) (local.get $right))
            (then
              (local.set $y (i32.add (local.get $y) (local.get $line_height)))
              (local.set $x (i32.const 8))))
          (if (i32.eqz (call $help_layout_emit
                (global.get $HELP_LAYOUT_BITMAP) (local.get $x) (local.get $y)
                (i32.const 16) (i32.const 16) (local.get $off) (local.get $len)
                (local.get $font_index) (local.get $color) (local.get $hotspot)))
            (then (return (i32.const -1))))
          (local.set $x (i32.add (local.get $x) (i32.const 16)))
          (local.set $saw_content (i32.const 1))))
      (if (i32.eq (local.get $kind) (global.get $HELP_TOKEN_TEXT))
        (then
          (if (i32.gt_u (local.get $off) (local.get $raw_len))
            (then (return (i32.const -1))))
          (if (i32.gt_u (local.get $len) (i32.sub (local.get $raw_len) (local.get $off)))
            (then (return (i32.const -1))))
          (local.set $pos (i32.const 0))
          (block $text_done (loop $text_loop
            (br_if $text_done (i32.ge_u (local.get $pos) (local.get $len)))
            (local.set $ch (i32.load8_u
              (i32.add (local.get $raw) (i32.add (local.get $off) (local.get $pos)))))
            (if (i32.eq (local.get $ch) (i32.const 0x20))
              (then
                (local.set $width (call $help_layout_measure (local.get $hdc)
                  (i32.add (local.get $raw) (i32.add (local.get $off) (local.get $pos)))
                  (i32.const 1)))
                (if (i32.and (i32.gt_u (local.get $x) (i32.const 8))
                      (i32.gt_u (i32.add (local.get $x) (local.get $width)) (local.get $right)))
                  (then
                    (local.set $y (i32.add (local.get $y) (local.get $line_height)))
                    (local.set $x (i32.const 8))))
                (if (i32.eqz (call $help_layout_emit
                      (global.get $HELP_LAYOUT_SPACE) (local.get $x) (local.get $y)
                      (local.get $width) (local.get $line_height)
                      (i32.add (local.get $off) (local.get $pos)) (i32.const 1)
                      (local.get $font_index) (local.get $color) (local.get $hotspot)))
                  (then (return (i32.const -1))))
                (local.set $x (i32.add (local.get $x) (local.get $width)))
                (local.set $pos (i32.add (local.get $pos) (i32.const 1))))
              (else
                (local.set $span (i32.const 0))
                (block $word_done (loop $word
                  (br_if $word_done
                    (i32.ge_u (i32.add (local.get $pos) (local.get $span)) (local.get $len)))
                  (br_if $word_done (i32.eq
                    (i32.load8_u (i32.add (local.get $raw)
                      (i32.add (local.get $off) (i32.add (local.get $pos) (local.get $span)))))
                    (i32.const 0x20)))
                  (local.set $span (i32.add (local.get $span) (i32.const 1)))
                  (br $word)))
                (block $span_done (loop $span_loop
                  (br_if $span_done (i32.eqz (local.get $span)))
                  (local.set $width (call $help_layout_measure (local.get $hdc)
                    (i32.add (local.get $raw) (i32.add (local.get $off) (local.get $pos)))
                    (local.get $span)))
                  (if (i32.and (i32.gt_u (local.get $x) (i32.const 8))
                        (i32.gt_u (i32.add (local.get $x) (local.get $width)) (local.get $right)))
                    (then
                      (local.set $y (i32.add (local.get $y) (local.get $line_height)))
                      (local.set $x (i32.const 8))))
                  (local.set $fit (local.get $span))
                  (if (i32.gt_u (i32.add (local.get $x) (local.get $width)) (local.get $right))
                    (then
                      (local.set $fit (call $help_layout_fit_prefix
                        (local.get $hdc)
                        (i32.add (local.get $raw) (i32.add (local.get $off) (local.get $pos)))
                        (local.get $span) (i32.sub (local.get $right) (local.get $x))))
                      (local.set $width (call $help_layout_measure (local.get $hdc)
                        (i32.add (local.get $raw) (i32.add (local.get $off) (local.get $pos)))
                        (local.get $fit)))))
                  (if (i32.eqz (call $help_layout_emit
                        (global.get $HELP_LAYOUT_TEXT) (local.get $x) (local.get $y)
                        (local.get $width) (local.get $line_height)
                        (i32.add (local.get $off) (local.get $pos)) (local.get $fit)
                        (local.get $font_index) (local.get $color) (local.get $hotspot)))
                    (then (return (i32.const -1))))
                  (local.set $x (i32.add (local.get $x) (local.get $width)))
                  (local.set $pos (i32.add (local.get $pos) (local.get $fit)))
                  (local.set $span (i32.sub (local.get $span) (local.get $fit)))
                  (local.set $saw_content (i32.const 1))
                  (if (local.get $span)
                    (then
                      (local.set $y (i32.add (local.get $y) (local.get $line_height)))
                      (local.set $x (i32.const 8))))
                  (br $span_loop)))))
            (br $text_loop)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $tokens_loop)))
    (if (i32.eqz (local.get $ended)) (then (return (i32.const -1))))
    (global.set $help_layout_extent
      (i32.add (local.get $y) (local.get $line_height)))
    (global.get $help_layout_count))

  ;; Public/internal entry point with an exact counting pass before any write.
  ;; Insufficient capacity therefore cannot leave a partial positioned list.
  (func $help_layout_tokens
    (param $raw i32) (param $raw_len i32)
    (param $tokens i32) (param $token_count i32)
    (param $runs i32) (param $run_capacity i32)
    (param $client_width i32) (param $hdc i32) (result i32)
    (local $required i32)
    (if (local.get $runs)
      (then
        (local.set $required (call $help_layout_tokens_core
          (local.get $raw) (local.get $raw_len)
          (local.get $tokens) (local.get $token_count)
          (i32.const 0) (global.get $HELP_MAX_LAYOUT_RUNS)
          (local.get $client_width) (local.get $hdc)))
        (if (i32.or (i32.lt_s (local.get $required) (i32.const 0))
              (i32.gt_u (local.get $required) (local.get $run_capacity)))
          (then (return (i32.const -1))))))
    (call $help_layout_tokens_core
      (local.get $raw) (local.get $raw_len)
      (local.get $tokens) (local.get $token_count)
      (local.get $runs) (local.get $run_capacity)
      (local.get $client_width) (local.get $hdc)))

  (func $help_typed_view_release
    (if (global.get $help_view_runs_ga)
      (then (call $heap_free (global.get $help_view_runs_ga))))
    (if (global.get $help_view_payload_ga)
      (then (call $heap_free (global.get $help_view_payload_ga))))
    (if (global.get $help_view_tokens_ga)
      (then (call $heap_free (global.get $help_view_tokens_ga))))
    (if (global.get $help_topic_wa)
      (then (call $heap_free (call $w2g (global.get $help_topic_wa)))))
    (global.set $help_view_runs_ga (i32.const 0))
    (global.set $help_view_runs_wa (i32.const 0))
    (global.set $help_view_run_count (i32.const 0))
    (global.set $help_view_payload_ga (i32.const 0))
    (global.set $help_view_payload_wa (i32.const 0))
    (global.set $help_view_payload_len (i32.const 0))
    (global.set $help_view_tokens_ga (i32.const 0))
    (global.set $help_view_tokens_wa (i32.const 0))
    (global.set $help_view_token_count (i32.const 0))
    (global.set $help_view_extent_height (i32.const 0))
    (global.set $help_view_layout_width (i32.const 0))
    (global.set $help_topic_wa (i32.const 0))
    (global.set $help_topic_len (i32.const 0)))

  ;; Decode, tokenize, lay out, and publish a topic as one viewer transaction.
  ;; Runtime rendering currently caps a single decoded topic at 64 KiB; the
  ;; parser's larger archival cap remains available to caller-owned APIs.
  (func $help_replace_typed_view (param $topic_index i32) (result i32)
    (local $raw_ga i32) (local $raw_wa i32) (local $raw_len i32)
    (local $tokens_ga i32) (local $tokens_wa i32) (local $token_count i32)
    (local $payload_ga i32) (local $payload_wa i32) (local $payload_len i32)
    (local $runs_ga i32) (local $runs_wa i32) (local $run_count i32)
    (local $hdc i32) (local $ok i32)
    (block $cleanup
    (local.set $raw_ga (call $heap_alloc (i32.const 65536)))
    (if (i32.eqz (local.get $raw_ga)) (then (return (i32.const 0))))
    (local.set $raw_wa (call $g2w (local.get $raw_ga)))
    (local.set $raw_len (call $help_decode_topic_raw
      (local.get $topic_index) (local.get $raw_wa) (i32.const 65536)))
    (if (i32.lt_s (local.get $raw_len) (i32.const 0)) (then (br $cleanup)))
    ;; Deliberately request zero output capacities: the formatted decoder's
    ;; first pass leaves exact token/payload requirements in its private channel.
    (drop (call $help_decode_topic_formatted
      (local.get $topic_index) (local.get $raw_wa) (i32.const 65536)
      (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
    (local.set $token_count (global.get $help_fmt_token_count))
    (local.set $payload_len (global.get $help_fmt_payload_used))
    (if (i32.or (i32.eqz (local.get $token_count))
          (i32.gt_u (local.get $token_count) (global.get $HELP_MAX_TOPIC_TOKENS)))
      (then (br $cleanup)))
    (local.set $tokens_ga (call $heap_alloc
      (i32.mul (local.get $token_count) (global.get $HELP_TOPIC_TOKEN_SIZE))))
    (if (i32.eqz (local.get $tokens_ga)) (then (br $cleanup)))
    (local.set $tokens_wa (call $g2w (local.get $tokens_ga)))
    (if (local.get $payload_len)
      (then
        (local.set $payload_ga (call $heap_alloc (local.get $payload_len)))
        (if (i32.eqz (local.get $payload_ga)) (then (br $cleanup)))
        (local.set $payload_wa (call $g2w (local.get $payload_ga)))))
    (if (i32.lt_s (call $help_decode_topic_formatted
          (local.get $topic_index) (local.get $raw_wa) (i32.const 65536)
          (local.get $tokens_wa) (local.get $token_count)
          (local.get $payload_wa) (local.get $payload_len)) (i32.const 0))
      (then (br $cleanup)))
    (local.set $hdc (i32.add
      (select (global.get $help_hwnd) (global.get $next_hwnd)
        (i32.ne (global.get $help_hwnd) (i32.const 0)))
      (i32.const 0x40000)))
    (local.set $run_count (call $help_layout_tokens
      (local.get $raw_wa) (local.get $raw_len)
      (local.get $tokens_wa) (local.get $token_count)
      (i32.const 0) (global.get $HELP_MAX_LAYOUT_RUNS)
      (i32.const 400) (local.get $hdc)))
    (if (i32.lt_s (local.get $run_count) (i32.const 0)) (then (br $cleanup)))
    (if (local.get $run_count)
      (then
        (local.set $runs_ga (call $heap_alloc
          (i32.mul (local.get $run_count) (global.get $HELP_LAYOUT_RUN_SIZE))))
        (if (i32.eqz (local.get $runs_ga)) (then (br $cleanup)))
        (local.set $runs_wa (call $g2w (local.get $runs_ga)))))
    (if (i32.ne (call $help_layout_tokens
          (local.get $raw_wa) (local.get $raw_len)
          (local.get $tokens_wa) (local.get $token_count)
          (local.get $runs_wa) (local.get $run_count)
          (i32.const 400) (local.get $hdc)) (local.get $run_count))
      (then (br $cleanup)))
    (call $help_typed_view_release)
    (global.set $help_topic_wa (local.get $raw_wa))
    (global.set $help_topic_len (local.get $raw_len))
    (global.set $help_view_tokens_ga (local.get $tokens_ga))
    (global.set $help_view_tokens_wa (local.get $tokens_wa))
    (global.set $help_view_token_count (local.get $token_count))
    (global.set $help_view_payload_ga (local.get $payload_ga))
    (global.set $help_view_payload_wa (local.get $payload_wa))
    (global.set $help_view_payload_len (local.get $payload_len))
    (global.set $help_view_runs_ga (local.get $runs_ga))
    (global.set $help_view_runs_wa (local.get $runs_wa))
    (global.set $help_view_run_count (local.get $run_count))
    (global.set $help_view_extent_height (global.get $help_layout_extent))
    (global.set $help_view_layout_width (i32.const 400))
    (global.set $help_last_error (global.get $HELP_ERROR_NONE))
    (global.set $help_last_error_offset (i32.const 0))
    (local.set $raw_ga (i32.const 0))
    (local.set $tokens_ga (i32.const 0))
    (local.set $payload_ga (i32.const 0))
    (local.set $runs_ga (i32.const 0))
    (local.set $ok (i32.const 1)))
    (if (local.get $runs_ga) (then (call $heap_free (local.get $runs_ga))))
    (if (local.get $payload_ga) (then (call $heap_free (local.get $payload_ga))))
    (if (local.get $tokens_ga) (then (call $heap_free (local.get $tokens_ga))))
    (if (local.get $raw_ga) (then (call $heap_free (local.get $raw_ga))))
    (local.get $ok))

  (func $help_paint_typed_view (param $hdc i32)
    (local $i i32) (local $run i32) (local $kind i32)
    (local $y i32) (local $height i32) (local $color i32)
    (block $done (loop $runs
      (br_if $done (i32.ge_u (local.get $i) (global.get $help_view_run_count)))
      (local.set $run (i32.add (global.get $help_view_runs_wa)
        (i32.mul (local.get $i) (global.get $HELP_LAYOUT_RUN_SIZE))))
      (local.set $kind (i32.load (local.get $run)))
      (local.set $y (i32.sub (i32.load offset=8 (local.get $run))
        (global.get $help_scroll_y)))
      (local.set $height (i32.load offset=16 (local.get $run)))
      (if (i32.and (i32.eq (local.get $kind) (global.get $HELP_LAYOUT_TEXT))
            (i32.and (i32.gt_s (i32.add (local.get $y) (local.get $height)) (i32.const 0))
                     (i32.lt_s (local.get $y) (i32.const 272))))
        (then
          (local.set $color (i32.load offset=32 (local.get $run)))
          (if (i32.load offset=36 (local.get $run))
            (then (local.set $color (i32.const 0xFF0000))))
          (drop (call $host_gdi_set_text_color (local.get $hdc) (local.get $color)))
          (drop (call $host_gdi_text_out
            (local.get $hdc) (i32.load offset=4 (local.get $run)) (local.get $y)
            (i32.add (global.get $help_topic_wa) (i32.load offset=20 (local.get $run)))
            (i32.load offset=24 (local.get $run)) (i32.const 0)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $runs))))

  (func (export "test_help_layout_tokens")
    (param $raw i32) (param $raw_len i32)
    (param $tokens i32) (param $token_count i32)
    (param $runs i32) (param $run_capacity i32)
    (param $width i32) (result i32)
    (call $help_layout_tokens
      (local.get $raw) (local.get $raw_len)
      (local.get $tokens) (local.get $token_count)
      (local.get $runs) (local.get $run_capacity)
      (local.get $width) (i32.const 0x40001)))
  (func (export "get_help_layout_extent") (result i32)
    (global.get $help_layout_extent))
  (func (export "get_help_view_run_count") (result i32)
    (global.get $help_view_run_count))
  (func (export "get_help_view_run_ptr") (result i32)
    (global.get $help_view_runs_wa))
  (func (export "get_help_view_extent_height") (result i32)
    (global.get $help_view_extent_height))

  ;; ---- WAT-native Help Topics window -------------------------------

  (global $help_topics_hwnd (mut i32) (i32.const 0))
  (global $help_topics_labels_ga (mut i32) (i32.const 0))
  (global $help_topics_labels_wa (mut i32) (i32.const 0))

  (func $help_topics_init_labels (result i32)
    (local $ga i32) (local $wa i32)
    (if (global.get $help_topics_labels_wa) (then (return (i32.const 1))))
    (local.set $ga (call $heap_alloc (i32.const 64)))
    (if (i32.eqz (local.get $ga)) (then (return (i32.const 0))))
    (local.set $wa (call $g2w (local.get $ga)))
    (memory.fill (local.get $wa) (i32.const 0) (i32.const 64))
    ;; Help Topics, Contents, Index, Display, Cancel, +, -, >.
    (i64.store (local.get $wa) (i64.const 0x706f5420706c6548))
    (i32.store offset=8 (local.get $wa) (i32.const 0x00736369))
    (i64.store offset=16 (local.get $wa) (i64.const 0x73746e65746e6f43))
    (i64.store offset=28 (local.get $wa) (i64.const 0x0000007865646e49))
    (i64.store offset=36 (local.get $wa) (i64.const 0x0079616c70736944))
    (i64.store offset=44 (local.get $wa) (i64.const 0x00006c65636e6143))
    (i32.store8 offset=52 (local.get $wa) (i32.const 43))
    (i32.store8 offset=54 (local.get $wa) (i32.const 45))
    (i32.store8 offset=56 (local.get $wa) (i32.const 62))
    (global.set $help_topics_labels_ga (local.get $ga))
    (global.set $help_topics_labels_wa (local.get $wa))
    (i32.const 1))

  (func $help_topics_destroy_window
    (if (global.get $help_topics_hwnd)
      (then
        (call $host_destroy_window (global.get $help_topics_hwnd))
        (call $wnd_table_remove (global.get $help_topics_hwnd))
        (global.set $help_topics_hwnd (i32.const 0))))
    (if (global.get $help_topics_labels_ga)
      (then (call $heap_free (global.get $help_topics_labels_ga))))
    (global.set $help_topics_labels_ga (i32.const 0))
    (global.set $help_topics_labels_wa (i32.const 0)))

  (func $help_topics_cancel
    (if (i32.or
          (i32.eq (global.get $help_session_mode) (i32.const 3))
          (i32.eq (global.get $help_session_mode) (i32.const 4)))
      (then (global.set $help_session_mode (global.get $help_topics_return_mode))))
    (call $help_topics_destroy_window))

  (func $help_topics_show
    (local $hwnd i32)
    (if (i32.eqz (call $help_topics_init_labels)) (then (return)))
    (if (global.get $help_topics_hwnd)
      (then
        (call $invalidate_hwnd (global.get $help_topics_hwnd))
        (return)))
    (local.set $hwnd (global.get $next_hwnd))
    (global.set $next_hwnd (i32.add (global.get $next_hwnd) (i32.const 1)))
    (drop (call $host_create_window
      (local.get $hwnd) (i32.const 0x10CF0000)
      (i32.const 140) (i32.const 80) (i32.const 440) (i32.const 330)
      (global.get $help_topics_labels_wa) (i32.const 0)))
    (call $wnd_table_set (local.get $hwnd) (global.get $WNDPROC_WAT_NATIVE))
    (global.set $help_topics_hwnd (local.get $hwnd))
    (drop (call $help_topics_wndproc
      (local.get $hwnd) (i32.const 0x000F) (i32.const 0) (i32.const 0))))

  (func $help_topics_draw_button
    (param $hdc i32) (param $left i32) (param $right i32)
    (param $text i32) (param $length i32)
    (drop (call $host_gdi_fill_rect (local.get $hdc)
      (local.get $left) (i32.const 275) (local.get $right) (i32.const 300)
      (i32.const 0x30011)))
    (drop (call $host_gdi_draw_edge (local.get $hdc)
      (local.get $left) (i32.const 275) (local.get $right) (i32.const 300)
      (i32.const 0x05) (i32.const 0x0F)))
    (drop (call $host_gdi_text_out (local.get $hdc)
      (i32.add (local.get $left) (i32.const 10)) (i32.const 281)
      (local.get $text) (local.get $length) (i32.const 0))))

  (func $help_topics_paint (param $hwnd i32)
    (local $hdc i32) (local $i i32) (local $row i32) (local $index i32)
    (local $record i32) (local $y i32) (local $x i32)
    (local $text i32) (local $length i32) (local $selected i32)
    (local $flags i32) (local $marker i32)
    (local.set $hdc (i32.add (local.get $hwnd) (i32.const 0x40000)))
    (drop (call $host_gdi_set_bk_mode (local.get $hdc) (i32.const 2)))
    (drop (call $host_gdi_set_text_color (local.get $hdc) (i32.const 0)))
    (drop (call $host_gdi_fill_rect (local.get $hdc)
      (i32.const 0) (i32.const 0) (i32.const 440) (i32.const 330)
      (i32.const 0x30011)))
    (if (i32.eq (global.get $help_session_mode) (i32.const 3))
      (then
        (drop (call $host_gdi_fill_rect (local.get $hdc)
          (i32.const 10) (i32.const 7) (i32.const 100) (i32.const 34)
          (i32.const 0x30010))))
      (else
        (drop (call $host_gdi_fill_rect (local.get $hdc)
          (i32.const 100) (i32.const 7) (i32.const 180) (i32.const 34)
          (i32.const 0x30010)))))
    (drop (call $host_gdi_text_out (local.get $hdc)
      (i32.const 24) (i32.const 14)
      (i32.add (global.get $help_topics_labels_wa) (i32.const 16))
      (i32.const 8) (i32.const 0)))
    (drop (call $host_gdi_text_out (local.get $hdc)
      (i32.const 118) (i32.const 14)
      (i32.add (global.get $help_topics_labels_wa) (i32.const 28))
      (i32.const 5) (i32.const 0)))
    (drop (call $host_gdi_fill_rect (local.get $hdc)
      (i32.const 10) (i32.const 38) (i32.const 430) (i32.const 260)
      (i32.const 0x30010)))
    (block $done (loop $rows
      (br_if $done (i32.ge_u (local.get $i) (i32.const 13)))
      (local.set $row (i32.add (global.get $help_topics_first_visible) (local.get $i)))
      (local.set $index
        (if (result i32) (i32.eq (global.get $help_session_mode) (i32.const 3))
          (then (call $help_cnt_visible_at (local.get $row)))
          (else (local.get $row))))
      (if (i32.lt_s (local.get $index) (i32.const 0)) (then (br $done)))
      (if (i32.eq (global.get $help_session_mode) (i32.const 3))
        (then
          (if (i32.ge_u (local.get $index) (global.get $help_doc_cnt_node_count))
            (then (br $done)))
          (local.set $record (call $help_cnt_node_address (local.get $index)))
          (local.set $text (i32.load offset=16 (local.get $record)))
          (local.set $length (i32.load offset=20 (local.get $record)))
          (local.set $x (i32.add (i32.const 18)
            (i32.mul (i32.sub (i32.load16_u offset=12 (local.get $record)) (i32.const 1))
              (i32.const 14))))
          (local.set $flags (i32.load16_u offset=14 (local.get $record)))
          (local.set $selected
            (i32.eq (local.get $index) (global.get $help_topics_contents_selection)))
          (if (i32.ge_s (i32.load offset=4 (local.get $record)) (i32.const 0))
            (then
              (local.set $marker
                (select (i32.const 54) (i32.const 52)
                  (i32.ne (i32.and (local.get $flags) (global.get $HELP_CNT_EXPANDED))
                    (i32.const 0)))))
            (else (local.set $marker (i32.const 56)))))
        (else
          (if (i32.ge_u (local.get $index) (global.get $help_doc_keyword_count))
            (then (br $done)))
          (local.set $record (i32.add (global.get $help_doc_keywords_wa)
            (i32.mul (local.get $index) (global.get $HELP_KEYWORD_SIZE))))
          (local.set $text (i32.add (global.get $help_doc_file_wa)
            (i32.load (local.get $record))))
          (local.set $length (i32.load offset=4 (local.get $record)))
          (local.set $x (i32.const 32))
          (local.set $marker (i32.const 56))
          (local.set $selected
            (i32.eq (local.get $index) (global.get $help_session_keyword_index)))))
      (local.set $y (i32.add (i32.const 44) (i32.mul (local.get $i) (i32.const 16))))
      (if (local.get $selected)
        (then
          (drop (call $host_gdi_fill_rect (local.get $hdc)
            (i32.const 13) (local.get $y) (i32.const 427)
            (i32.add (local.get $y) (i32.const 16)) (i32.const 14)))
          (drop (call $host_gdi_set_text_color (local.get $hdc) (i32.const 0xFFFFFF)))))
      (drop (call $host_gdi_text_out (local.get $hdc)
        (local.get $x) (local.get $y)
        (i32.add (global.get $help_topics_labels_wa) (local.get $marker))
        (i32.const 1) (i32.const 0)))
      (drop (call $host_gdi_text_out (local.get $hdc)
        (i32.add (local.get $x) (i32.const 14)) (local.get $y)
        (local.get $text) (local.get $length) (i32.const 0)))
      (if (local.get $selected)
        (then (drop (call $host_gdi_set_text_color (local.get $hdc) (i32.const 0)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $rows)))
    (call $help_topics_draw_button (local.get $hdc) (i32.const 250) (i32.const 335)
      (i32.add (global.get $help_topics_labels_wa) (i32.const 36)) (i32.const 7))
    (call $help_topics_draw_button (local.get $hdc) (i32.const 345) (i32.const 425)
      (i32.add (global.get $help_topics_labels_wa) (i32.const 44)) (i32.const 6)))

  (func $help_topics_present_activation (param $hwnd i32)
    (local $result i32)
    (local.set $result (call $help_topics_activate (global.get $help_session_owner)))
    (if (i32.eq (local.get $result) (i32.const 1))
      (then
        (call $help_topics_destroy_window)
        (call $help_present_dispatch (i32.const 1)
          (global.get $help_session_last_command))
        (return)))
    (if (i32.eq (local.get $result) (i32.const 2))
      (then (call $invalidate_hwnd (local.get $hwnd)))))

  (func $help_topics_wndproc
    (param $hwnd i32) (param $msg i32) (param $wParam i32) (param $lParam i32)
    (result i32)
    (local $x i32) (local $y i32) (local $row i32) (local $index i32)
    (local $node i32) (local $parent i32)
    (if (i32.eq (local.get $msg) (i32.const 0x000F))
      (then (call $help_topics_paint (local.get $hwnd)) (return (i32.const 0))))
    (if (i32.or (i32.eq (local.get $msg) (i32.const 0x0201))
                (i32.eq (local.get $msg) (i32.const 0x0203)))
      (then
        (local.set $x (i32.and (local.get $lParam) (i32.const 0xFFFF)))
        (local.set $y (i32.shr_u (local.get $lParam) (i32.const 16)))
        (if (i32.lt_u (local.get $y) (i32.const 35))
          (then
            (if (i32.lt_u (local.get $x) (i32.const 100))
              (then (drop (call $help_topics_set_tab (i32.const 0))))
              (else (drop (call $help_topics_set_tab (i32.const 1)))))
            (call $invalidate_hwnd (local.get $hwnd))
            (return (i32.const 0))))
        (if (i32.and (i32.ge_u (local.get $y) (i32.const 44))
              (i32.lt_u (local.get $y) (i32.const 252)))
          (then
            (local.set $row (i32.add (global.get $help_topics_first_visible)
              (i32.div_u (i32.sub (local.get $y) (i32.const 44)) (i32.const 16))))
            (if (i32.eq (global.get $help_session_mode) (i32.const 3))
              (then
                (local.set $index (call $help_cnt_visible_at (local.get $row)))
                (drop (call $help_topics_select_contents (local.get $index))))
              (else
                (if (i32.lt_u (local.get $row) (global.get $help_doc_keyword_count))
                  (then (global.set $help_session_keyword_index (local.get $row))))))
            (if (i32.eq (local.get $msg) (i32.const 0x0203))
              (then (call $help_topics_present_activation (local.get $hwnd)))
              (else (call $invalidate_hwnd (local.get $hwnd))))
            (return (i32.const 0))))
        (if (i32.ge_u (local.get $y) (i32.const 270))
          (then
            (if (i32.and (i32.ge_u (local.get $x) (i32.const 245))
                  (i32.lt_u (local.get $x) (i32.const 340)))
              (then (call $help_topics_present_activation (local.get $hwnd))))
            (if (i32.ge_u (local.get $x) (i32.const 340))
              (then (call $help_topics_cancel)))
            (return (i32.const 0))))))
    (if (i32.eq (local.get $msg) (i32.const 0x0100))
      (then
        (if (i32.eq (local.get $wParam) (i32.const 0x26))
          (then (drop (call $help_topics_move_selection (i32.const -1)))))
        (if (i32.eq (local.get $wParam) (i32.const 0x28))
          (then (drop (call $help_topics_move_selection (i32.const 1)))))
        (if (i32.eq (local.get $wParam) (i32.const 0x21))
          (then (drop (call $help_topics_move_selection (i32.const -13)))))
        (if (i32.eq (local.get $wParam) (i32.const 0x22))
          (then (drop (call $help_topics_move_selection (i32.const 13)))))
        (if (i32.eq (local.get $wParam) (i32.const 0x09))
          (then (drop (call $help_topics_set_tab
            (select (i32.const 0) (i32.const 1)
              (i32.eq (global.get $help_session_mode) (i32.const 4)))))))
        (if (i32.eq (local.get $wParam) (i32.const 0x27))
          (then
            (if (i32.eq (global.get $help_session_mode) (i32.const 3))
              (then (drop (call $help_topics_expand_contents
                (global.get $help_topics_contents_selection) (i32.const 2)))))))
        (if (i32.eq (local.get $wParam) (i32.const 0x25))
          (then
            (if (i32.eq (global.get $help_session_mode) (i32.const 3))
              (then
                (local.set $node (call $help_cnt_node_address
                  (global.get $help_topics_contents_selection)))
                (if (local.get $node)
                  (then
                    (if (i32.and
                          (i32.ne (i32.and (i32.load16_u offset=14 (local.get $node))
                            (global.get $HELP_CNT_EXPANDED)) (i32.const 0))
                          (i32.ge_s (i32.load offset=4 (local.get $node)) (i32.const 0)))
                      (then (drop (call $help_topics_expand_contents
                        (global.get $help_topics_contents_selection) (i32.const 1))))
                      (else
                        (local.set $parent (i32.load (local.get $node)))
                        (if (i32.ge_s (local.get $parent) (i32.const 0))
                          (then (drop (call $help_topics_select_contents
                            (local.get $parent)))))))))))))
        (if (i32.eq (local.get $wParam) (i32.const 0x0D))
          (then (call $help_topics_present_activation (local.get $hwnd))))
        (if (i32.eq (local.get $wParam) (i32.const 0x1B))
          (then (call $help_topics_cancel)))
        (if (global.get $help_topics_hwnd)
          (then (call $invalidate_hwnd (local.get $hwnd))))
        (return (i32.const 0))))
    (if (i32.eq (local.get $msg) (i32.const 0x0010))
      (then (call $help_topics_cancel) (return (i32.const 0))))
    (i32.const 0))

  (func (export "get_help_topics_hwnd") (result i32)
    (global.get $help_topics_hwnd))
  (func (export "test_help_topics_message")
    (param $msg i32) (param $wparam i32) (param $lparam i32) (result i32)
    (if (i32.eqz (global.get $help_topics_hwnd))
      (then (return (i32.const 0))))
    (call $help_topics_wndproc (global.get $help_topics_hwnd)
      (local.get $msg) (local.get $wparam) (local.get $lparam)))
