  ;; WAT-native bitmap record/query and raw DIB parsing foundation.
  ;;
  ;; The canonical 48-byte object record layout is:
  ;;   +0 handle, +4 type (3 bitmap), +8 width, +12 height, +16 bpp,
  ;;   +20 flags (bit0 DIB, bit1 top-down), +24 canonical bits WA,
  ;;   +28 stride, +32 palette WA, +36 palette count, +40 surface id,
  ;;   +44 reserved.
  ;; These helpers do not allocate handles, surfaces, or pixels.

  (func $gdi_bitmap_record_valid (param $record i32) (result i32)
    (i32.and (i32.ne (local.get $record) (i32.const 0))
      (i32.and (i32.eq (i32.load offset=4 (local.get $record)) (i32.const 3))
        (i32.and
          (i32.and (i32.gt_s (i32.load offset=8 (local.get $record)) (i32.const 0))
            (i32.gt_s (i32.load offset=12 (local.get $record)) (i32.const 0)))
          (i32.gt_u (i32.load offset=16 (local.get $record)) (i32.const 0))))))

  (func $gdi_bitmap_record_init (param $record i32) (param $handle i32)
        (param $width i32) (param $height i32) (param $bpp i32) (param $flags i32)
        (param $bits i32) (param $stride i32) (param $palette i32)
        (param $palette_count i32) (param $surface_id i32) (result i32)
    (if (i32.or (i32.eqz (local.get $record))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $bpp) (i32.const 0))
                (i32.le_s (local.get $stride) (i32.const 0))))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $record) (i32.const 0) (i32.const 48))
    (i32.store (local.get $record) (local.get $handle))
    (i32.store offset=4 (local.get $record) (i32.const 3))
    (i32.store offset=8 (local.get $record) (local.get $width))
    (i32.store offset=12 (local.get $record) (local.get $height))
    (i32.store offset=16 (local.get $record) (local.get $bpp))
    (i32.store offset=20 (local.get $record) (i32.and (local.get $flags) (i32.const 3)))
    (i32.store offset=24 (local.get $record) (local.get $bits))
    (i32.store offset=28 (local.get $record) (local.get $stride))
    (i32.store offset=32 (local.get $record) (local.get $palette))
    (i32.store offset=36 (local.get $record) (local.get $palette_count))
    (i32.store offset=40 (local.get $record) (local.get $surface_id))
    (i32.const 1))

  (func $gdi_bitmap_record_width (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=8 (local.get $record)))
  (func $gdi_bitmap_record_height (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=12 (local.get $record)))
  (func $gdi_bitmap_record_bpp (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=16 (local.get $record)))
  (func $gdi_bitmap_record_storage (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))
  (func $gdi_bitmap_record_dib_bits (param $record i32) (result i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.eqz (i32.and (i32.load offset=20 (local.get $record)) (i32.const 1))))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))

  ;; Write Win32 BITMAP (24 bytes) into linear memory. DDB private storage is
  ;; never exposed through bmBits; DIB section storage is translated to a guest
  ;; pointer. GetObjectA and GetObjectW use the same BITMAP layout.
  (func $gdi_bitmap_write_object (param $record i32) (param $buffer i32)
        (param $buffer_size i32) (result i32)
    (local $bits i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.or (i32.eqz (local.get $buffer))
            (i32.lt_u (local.get $buffer_size) (i32.const 24))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $buffer) (i32.const 0) (i32.const 24))
    (i32.store offset=4 (local.get $buffer) (i32.load offset=8 (local.get $record)))
    (i32.store offset=8 (local.get $buffer) (i32.load offset=12 (local.get $record)))
    (i32.store offset=12 (local.get $buffer) (i32.load offset=28 (local.get $record)))
    (i32.store16 offset=16 (local.get $buffer) (i32.const 1))
    (i32.store16 offset=18 (local.get $buffer) (i32.load offset=16 (local.get $record)))
    (local.set $bits (call $gdi_bitmap_record_dib_bits (local.get $record)))
    (if (local.get $bits)
      (then (i32.store offset=20 (local.get $buffer) (call $w2g (local.get $bits)))))
    (i32.const 24))

  ;; Parsed DIB metadata is a 40-byte plan:
  ;; +0 width, +4 height(abs), +8 bpp, +12 flags(bit1 top-down), +16 stride,
  ;; +20 palette WA, +24 palette count, +28 pixel WA, +32 pixel byte count,
  ;; +36 header size. It contains no semantic GDI handle or surface id.
  (func $gdi_bitmap_parse_dib (param $data i32) (param $size i32)
        (param $plan i32) (result i32)
    (local $header_size i32) (local $width i32) (local $height i32)
    (local $bpp i32) (local $compression i32) (local $top_down i32)
    (local $palette_count i32) (local $palette_bytes i32) (local $bits_offset i32)
    (local $stride i32) (local $image_size i64)
    (if (i32.or (i32.eqz (local.get $data))
          (i32.or (i32.eqz (local.get $plan)) (i32.lt_u (local.get $size) (i32.const 40))))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $data)))
    (if (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
          (i32.gt_u (local.get $header_size) (local.get $size)))
      (then (return (i32.const 0))))
    (local.set $width (i32.load offset=4 (local.get $data)))
    (local.set $height (i32.load offset=8 (local.get $data)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $data)))
    (local.set $compression (i32.load offset=16 (local.get $data)))
    (if (i32.or (i32.le_s (local.get $width) (i32.const 0))
          (i32.or (i32.eqz (local.get $height))
            (i32.or (i32.ne (i32.load16_u offset=12 (local.get $data)) (i32.const 1))
              (i32.and (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                  (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                    (i32.ne (local.get $bpp) (i32.const 8))))
                (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                  (i32.ne (local.get $bpp) (i32.const 32)))))))
      (then (return (i32.const 0))))
    ;; Foundation accepts only BI_RGB. RLE/bitfields remain explicit gaps.
    (if (i32.ne (local.get $compression) (i32.const 0))
      (then (return (i32.const 0))))
    (local.set $top_down (i32.lt_s (local.get $height) (i32.const 0)))
    (if (local.get $top_down)
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $data)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.shl (i32.const 1) (local.get $bpp)))
          (then (return (i32.const 0))))))
    (local.set $palette_bytes (i32.mul (local.get $palette_count) (i32.const 4)))
    (local.set $bits_offset (i32.add (local.get $header_size) (local.get $palette_bytes)))
    (if (i32.gt_u (local.get $bits_offset) (local.get $size))
      (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
        (i32.const 5)) (i32.const 2)))
    (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $image_size)
          (i64.extend_i32_u (i32.sub (local.get $size) (local.get $bits_offset))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 40))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=12 (local.get $plan) (i32.shl (local.get $top_down) (i32.const 1)))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (if (local.get $palette_count)
      (then (i32.store offset=20 (local.get $plan) (i32.add (local.get $data) (local.get $header_size)))))
    (i32.store offset=24 (local.get $plan) (local.get $palette_count))
    (i32.store offset=28 (local.get $plan) (i32.add (local.get $data) (local.get $bits_offset)))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
    (i32.store offset=36 (local.get $plan) (local.get $header_size))
    (i32.const 1))

  ;; CreateBitmap layout planner. Input scanlines use WORD alignment as Win32
  ;; BITMAP.bmWidthBytes specifies. The caller supplies allocation/copy policy.
  ;; Plan layout matches $gdi_bitmap_parse_dib except palette/header fields.
  (func $gdi_bitmap_plan_create_bitmap (param $width i32) (param $height i32)
        (param $planes i32) (param $bits_pixel i32) (param $plan i32) (result i32)
    (local $bpp i32) (local $stride i32) (local $size i64)
    (if (i32.or (i32.eqz (local.get $plan))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $planes) (i32.const 0))
                (i32.le_s (local.get $bits_pixel) (i32.const 0))))))
      (then (return (i32.const 0))))
    (local.set $bpp (i32.mul (local.get $planes) (local.get $bits_pixel)))
    (if (i32.gt_u (local.get $bpp) (i32.const 32)) (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 15))
        (i32.const 4)) (i32.const 1)))
    (local.set $size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $size) (i64.const 0xFFFFFFFF))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 40))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $size)))
    (i32.const 1))

  ;; Parse an application-supplied BITMAPINFOHEADER. Unlike an RT_BITMAP
  ;; payload, the pixel pointer is supplied separately to CreateDIBitmap, so
  ;; this validates metadata without assuming bytes follow the color table.
  (func $gdi_bitmap_plan_info (param $info i32) (param $plan i32) (result i32)
    (local $header_size i32) (local $width i32) (local $height i32)
    (local $bpp i32) (local $top_down i32) (local $palette_count i32)
    (local $stride i32) (local $image_size i64)
    (if (i32.or (i32.eqz (local.get $info)) (i32.eqz (local.get $plan)))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $info)))
    (local.set $width (i32.load offset=4 (local.get $info)))
    (local.set $height (i32.load offset=8 (local.get $info)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $info)))
    (if (i32.or
          (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
            (i32.gt_u (local.get $header_size) (i32.const 124)))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.eqz (local.get $height))
              (i32.or (i32.ne (i32.load16_u offset=12 (local.get $info)) (i32.const 1))
                (i32.or (i32.ne (i32.load offset=16 (local.get $info)) (i32.const 0))
                  (i32.and
                    (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                      (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                        (i32.ne (local.get $bpp) (i32.const 8))))
                    (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                      (i32.ne (local.get $bpp) (i32.const 32)))))))))
      (then (return (i32.const 0))))
    (local.set $top_down (i32.lt_s (local.get $height) (i32.const 0)))
    (if (local.get $top_down)
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $info)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.shl (i32.const 1) (local.get $bpp)))
          (then (return (i32.const 0))))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
        (i32.const 5)) (i32.const 2)))
    (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $image_size) (i64.const 0xFFFFFFFF))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 40))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=12 (local.get $plan) (i32.shl (local.get $top_down) (i32.const 1)))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (if (local.get $palette_count)
      (then (i32.store offset=20 (local.get $plan)
        (i32.add (local.get $info) (local.get $header_size)))))
    (i32.store offset=24 (local.get $plan) (local.get $palette_count))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
    (i32.store offset=36 (local.get $plan) (local.get $header_size))
    (i32.const 1))

  ;; Materialize a parsed bitmap as an owned DDB. Pixel and palette bytes are
  ;; copied into one DIB-arena allocation; JavaScript receives only the final
  ;; presentation descriptor through gdi_surface_create/upload.
  (func $gdi_bitmap_create_owned (param $plan i32) (param $pixels i32)
        (param $copy_pixels i32) (param $copy_palette i32) (result i32)
    (local $width i32) (local $height i32) (local $bpp i32) (local $flags i32)
    (local $stride i32) (local $image_size i32) (local $palette_src i32)
    (local $palette_count i32) (local $palette_size i32) (local $total i64)
    (local $storage_ga i32) (local $storage i32) (local $palette i32) (local $handle i32)
    (if (i32.eqz (local.get $plan)) (then (return (i32.const 0))))
    (local.set $width (i32.load (local.get $plan)))
    (local.set $height (i32.load offset=4 (local.get $plan)))
    (local.set $bpp (i32.load offset=8 (local.get $plan)))
    (local.set $flags (i32.load offset=12 (local.get $plan)))
    (local.set $stride (i32.load offset=16 (local.get $plan)))
    (local.set $palette_src (i32.load offset=20 (local.get $plan)))
    (local.set $palette_count (i32.load offset=24 (local.get $plan)))
    (local.set $image_size (i32.load offset=32 (local.get $plan)))
    (if (i32.or (i32.eqz (local.get $image_size))
          (i32.or (i32.eqz (local.get $stride))
            (i32.and (local.get $copy_pixels) (i32.eqz (local.get $pixels)))))
      (then (return (i32.const 0))))
    (local.set $palette_size (i32.mul (local.get $palette_count) (i32.const 4)))
    (local.set $total (i64.add (i64.extend_i32_u (local.get $image_size))
      (i64.extend_i32_u (local.get $palette_size))))
    (if (i64.gt_u (local.get $total) (i64.extend_i32_u (global.get $DIB_BACKING_BASE_SIZE)))
      (then (return (i32.const 0))))
    (local.set $storage_ga (call $dib_alloc (i32.wrap_i64 (local.get $total)))
    )
    (if (i32.eqz (local.get $storage_ga)) (then (return (i32.const 0))))
    (local.set $storage (call $g2w (local.get $storage_ga)))
    (if (local.get $copy_pixels)
      (then (memory.copy (local.get $storage) (local.get $pixels) (local.get $image_size))))
    (if (i32.and (i32.ne (local.get $copy_palette) (i32.const 0))
          (i32.and (i32.ne (local.get $palette_count) (i32.const 0))
            (i32.ne (local.get $palette_src) (i32.const 0))))
      (then
        (local.set $palette (i32.add (local.get $storage) (local.get $image_size)))
        (memory.copy (local.get $palette) (local.get $palette_src) (local.get $palette_size))))
    (local.set $handle (call $gdi_bitmap_alloc
      (local.get $width) (local.get $height) (local.get $bpp)
      (i32.or (local.get $flags) (i32.const 4))
      (local.get $storage) (local.get $stride) (local.get $palette) (local.get $palette_count)))
    (if (i32.eqz (local.get $handle))
      (then
        (call $dib_free_wasm (local.get $storage))
        (return (i32.const 0))))
    (drop (call $host_gdi_surface_upload (local.get $handle) (i32.const 0)
      (i32.const 0) (local.get $width) (local.get $height)))
    (local.get $handle))

  (func $gdi_bitmap_create_bitmap (param $width i32) (param $height i32)
        (param $planes i32) (param $bits_pixel i32) (param $pixels i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_plan_create_bitmap
          (local.get $width) (local.get $height) (local.get $planes)
          (local.get $bits_pixel) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN) (local.get $pixels)
      (i32.ne (local.get $pixels) (i32.const 0)) (i32.const 0)))

  (func $gdi_bitmap_create_dibitmap (param $info i32) (param $pixels i32)
        (param $init i32) (param $usage i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_plan_info
          (local.get $info) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    ;; DIB_PAL_COLORS tables contain WORD palette indexes rather than RGBQUADs.
    ;; Palette-object realization is not yet WAT-owned, so fail rather than
    ;; publishing incorrect colors for paletted inputs.
    (if (i32.and (i32.ne (local.get $usage) (i32.const 0))
          (i32.le_u (i32.load offset=8 (global.get $GDI_BITMAP_PLAN)) (i32.const 8)))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN) (local.get $pixels)
      (i32.and (local.get $init) (i32.ne (local.get $pixels) (i32.const 0)))
      (i32.const 1)))

  (func $gdi_bitmap_create_resource (param $data i32) (param $size i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_parse_dib
          (local.get $data) (local.get $size) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN)
      (i32.load offset=28 (global.get $GDI_BITMAP_PLAN))
      (i32.const 1) (i32.const 1)))

  ;; Convert a bounded LoadBitmapW name to the ASCII-compatible resource-name
  ;; form understood by the shared PE resource walker. Integer IDs pass through.
  (func $gdi_bitmap_resource_name (param $name i32) (param $wide i32) (result i32)
    (local $src i32) (local $i i32) (local $ch i32)
    (if (i32.or (i32.lt_u (local.get $name) (i32.const 0x10000))
          (i32.eqz (local.get $wide)))
      (then (return (local.get $name))))
    (local.set $src (call $g2w (local.get $name)))
    (block $done (loop $copy
      (if (i32.ge_u (local.get $i) (i32.const 255))
        (then (return (i32.const 0))))
      (local.set $ch (i32.load16_u
        (i32.add (local.get $src) (i32.shl (local.get $i) (i32.const 1)))))
      (br_if $done (i32.eqz (local.get $ch)))
      (if (i32.gt_u (local.get $ch) (i32.const 0x7F))
        (then (return (i32.const 0))))
      (i32.store8 (i32.add (global.get $GDI_BITMAP_NAME) (local.get $i)) (local.get $ch))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $copy)))
    (i32.store8 (i32.add (global.get $GDI_BITMAP_NAME) (local.get $i)) (i32.const 0))
    (call $w2g (global.get $GDI_BITMAP_NAME)))

  (func $gdi_bitmap_load_resource (param $instance i32) (param $name i32)
        (param $wide i32) (result i32)
    (local $resource_name i32) (local $data i32) (local $size i32)
    (local.set $resource_name
      (call $gdi_bitmap_resource_name (local.get $name) (local.get $wide)))
    (if (i32.eqz (local.get $resource_name)) (then (return (i32.const 0))))
    (call $push_rsrc_ctx (local.get $instance))
    (local.set $data (call $rsrc_find_data_wa (i32.const 2) (local.get $resource_name)))
    (local.set $size (global.get $rsrc_last_size))
    (local.set $resource_name
      (call $gdi_bitmap_create_resource (local.get $data) (local.get $size)))
    (call $pop_rsrc_ctx)
    (local.get $resource_name))

  (func (export "test_gdi_bitmap_record_init")
        (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_record_init (local.get 0) (local.get 1) (local.get 2)
      (local.get 3) (local.get 4) (local.get 5) (local.get 6) (local.get 7)
      (local.get 8) (local.get 9) (local.get 10)))
  (func (export "test_gdi_bitmap_record_width") (param i32) (result i32)
    (call $gdi_bitmap_record_width (local.get 0)))
  (func (export "test_gdi_bitmap_record_height") (param i32) (result i32)
    (call $gdi_bitmap_record_height (local.get 0)))
  (func (export "test_gdi_bitmap_record_bpp") (param i32) (result i32)
    (call $gdi_bitmap_record_bpp (local.get 0)))
  (func (export "test_gdi_bitmap_record_storage") (param i32) (result i32)
    (call $gdi_bitmap_record_storage (local.get 0)))
  (func (export "test_gdi_bitmap_record_dib_bits") (param i32) (result i32)
    (call $gdi_bitmap_record_dib_bits (local.get 0)))
  (func (export "test_gdi_bitmap_write_object") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_write_object (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_parse_dib") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_parse_dib (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_plan_create_bitmap")
        (param i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_plan_create_bitmap (local.get 0) (local.get 1)
      (local.get 2) (local.get 3) (local.get 4)))
  (func (export "test_gdi_bitmap_plan_info") (param i32 i32) (result i32)
    (call $gdi_bitmap_plan_info (local.get 0) (local.get 1)))
  (func (export "test_gdi_bitmap_create_resource") (param i32 i32) (result i32)
    (call $gdi_bitmap_create_resource (local.get 0) (local.get 1)))
