  ;; WAT-native bitmap record/query and raw DIB parsing foundation.
  ;;
  ;; The canonical 48-byte object record layout is:
  ;;   +0 handle, +4 type (3 bitmap), +8 width, +12 height, +16 bpp,
  ;;   +20 flags (bit0 DIB, bit1 top-down), +24 canonical bits WA,
  ;;   +28 stride, +32 palette WA, +36 palette count, +40 surface id,
  ;;   +44 reserved.
  ;; These helpers do not allocate handles, surfaces, or pixels.

  (func $gdi_bitmap_record_valid (param $record i32) (result i32)
    (i32.and (i32.ne (local.get $record) (i32.const 0))
      (i32.and (i32.eq (i32.load offset=4 (local.get $record)) (i32.const 3))
        (i32.and
          (i32.and (i32.gt_s (i32.load offset=8 (local.get $record)) (i32.const 0))
            (i32.gt_s (i32.load offset=12 (local.get $record)) (i32.const 0)))
          (i32.gt_u (i32.load offset=16 (local.get $record)) (i32.const 0))))))

  (func $gdi_bitmap_record_init (param $record i32) (param $handle i32)
        (param $width i32) (param $height i32) (param $bpp i32) (param $flags i32)
        (param $bits i32) (param $stride i32) (param $palette i32)
        (param $palette_count i32) (param $surface_id i32) (result i32)
    (if (i32.or (i32.eqz (local.get $record))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $bpp) (i32.const 0))
                (i32.le_s (local.get $stride) (i32.const 0))))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $record) (i32.const 0) (i32.const 48))
    (i32.store (local.get $record) (local.get $handle))
    (i32.store offset=4 (local.get $record) (i32.const 3))
    (i32.store offset=8 (local.get $record) (local.get $width))
    (i32.store offset=12 (local.get $record) (local.get $height))
    (i32.store offset=16 (local.get $record) (local.get $bpp))
    (i32.store offset=20 (local.get $record) (i32.and (local.get $flags) (i32.const 3)))
    (i32.store offset=24 (local.get $record) (local.get $bits))
    (i32.store offset=28 (local.get $record) (local.get $stride))
    (i32.store offset=32 (local.get $record) (local.get $palette))
    (i32.store offset=36 (local.get $record) (local.get $palette_count))
    (i32.store offset=40 (local.get $record) (local.get $surface_id))
    (i32.const 1))

  (func $gdi_bitmap_record_width (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=8 (local.get $record)))
  (func $gdi_bitmap_record_height (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=12 (local.get $record)))
  (func $gdi_bitmap_record_bpp (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=16 (local.get $record)))
  (func $gdi_bitmap_record_storage (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))
  (func $gdi_bitmap_record_dib_bits (param $record i32) (result i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.eqz (i32.and (i32.load offset=20 (local.get $record)) (i32.const 1))))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))

  ;; Write Win32 BITMAP (24 bytes) into linear memory. DDB private storage is
  ;; never exposed through bmBits; DIB section storage is translated to a guest
  ;; pointer. GetObjectA and GetObjectW use the same BITMAP layout.
  (func $gdi_bitmap_write_object (param $record i32) (param $buffer i32)
        (param $buffer_size i32) (result i32)
    (local $bits i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.or (i32.eqz (local.get $buffer))
            (i32.lt_u (local.get $buffer_size) (i32.const 24))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $buffer) (i32.const 0) (i32.const 24))
    (i32.store offset=4 (local.get $buffer) (i32.load offset=8 (local.get $record)))
    (i32.store offset=8 (local.get $buffer) (i32.load offset=12 (local.get $record)))
    (i32.store offset=12 (local.get $buffer) (i32.load offset=28 (local.get $record)))
    (i32.store16 offset=16 (local.get $buffer) (i32.const 1))
    (i32.store16 offset=18 (local.get $buffer) (i32.load offset=16 (local.get $record)))
    (local.set $bits (call $gdi_bitmap_record_dib_bits (local.get $record)))
    (if (local.get $bits)
      (then (i32.store offset=20 (local.get $buffer) (call $w2g (local.get $bits)))))
    (i32.const 24))

  ;; Parsed DIB metadata is a 40-byte plan:
  ;; +0 width, +4 height(abs), +8 bpp, +12 flags(bit1 top-down), +16 stride,
  ;; +20 palette WA, +24 palette count, +28 pixel WA, +32 pixel byte count,
  ;; +36 header size. It contains no semantic GDI handle or surface id.
  (func $gdi_bitmap_parse_dib (param $data i32) (param $size i32)
        (param $plan i32) (result i32)
    (local $header_size i32) (local $width i32) (local $height i32)
    (local $bpp i32) (local $compression i32) (local $top_down i32)
    (local $palette_count i32) (local $palette_bytes i32) (local $bits_offset i32)
    (local $stride i32) (local $image_size i64)
    (if (i32.or (i32.eqz (local.get $data))
          (i32.or (i32.eqz (local.get $plan)) (i32.lt_u (local.get $size) (i32.const 40))))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $data)))
    (if (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
          (i32.gt_u (local.get $header_size) (local.get $size)))
      (then (return (i32.const 0))))
    (local.set $width (i32.load offset=4 (local.get $data)))
    (local.set $height (i32.load offset=8 (local.get $data)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $data)))
    (local.set $compression (i32.load offset=16 (local.get $data)))
    (if (i32.or (i32.le_s (local.get $width) (i32.const 0))
          (i32.or (i32.eqz (local.get $height))
            (i32.or (i32.ne (i32.load16_u offset=12 (local.get $data)) (i32.const 1))
              (i32.and (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                  (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                    (i32.ne (local.get $bpp) (i32.const 8))))
                (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                  (i32.ne (local.get $bpp) (i32.const 32)))))))
      (then (return (i32.const 0))))
    ;; Foundation accepts only BI_RGB. RLE/bitfields remain explicit gaps.
    (if (i32.ne (local.get $compression) (i32.const 0))
      (then (return (i32.const 0))))
    (local.set $top_down (i32.lt_s (local.get $height) (i32.const 0)))
    (if (local.get $top_down)
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $data)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.shl (i32.const 1) (local.get $bpp)))
          (then (return (i32.const 0))))))
    (local.set $palette_bytes (i32.mul (local.get $palette_count) (i32.const 4)))
    (local.set $bits_offset (i32.add (local.get $header_size) (local.get $palette_bytes)))
    (if (i32.gt_u (local.get $bits_offset) (local.get $size))
      (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
        (i32.const 5)) (i32.const 2)))
    (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $image_size)
          (i64.extend_i32_u (i32.sub (local.get $size) (local.get $bits_offset))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 40))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=12 (local.get $plan) (i32.shl (local.get $top_down) (i32.const 1)))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (if (local.get $palette_count)
      (then (i32.store offset=20 (local.get $plan) (i32.add (local.get $data) (local.get $header_size)))))
    (i32.store offset=24 (local.get $plan) (local.get $palette_count))
    (i32.store offset=28 (local.get $plan) (i32.add (local.get $data) (local.get $bits_offset)))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
    (i32.store offset=36 (local.get $plan) (local.get $header_size))
    (i32.const 1))

  ;; CreateBitmap layout planner. Input scanlines use WORD alignment as Win32
  ;; BITMAP.bmWidthBytes specifies. The caller supplies allocation/copy policy.
  ;; Plan layout matches $gdi_bitmap_parse_dib except palette/header fields.
  (func $gdi_bitmap_plan_create_bitmap (param $width i32) (param $height i32)
        (param $planes i32) (param $bits_pixel i32) (param $plan i32) (result i32)
    (local $bpp i32) (local $stride i32) (local $size i64)
    (if (i32.or (i32.eqz (local.get $plan))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $planes) (i32.const 0))
                (i32.le_s (local.get $bits_pixel) (i32.const 0))))))
      (then (return (i32.const 0))))
    (local.set $bpp (i32.mul (local.get $planes) (local.get $bits_pixel)))
    (if (i32.gt_u (local.get $bpp) (i32.const 32)) (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 15))
        (i32.const 4)) (i32.const 1)))
    (local.set $size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $size) (i64.const 0xFFFFFFFF))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 40))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $size)))
    (i32.const 1))

  (func (export "test_gdi_bitmap_record_init")
        (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_record_init (local.get 0) (local.get 1) (local.get 2)
      (local.get 3) (local.get 4) (local.get 5) (local.get 6) (local.get 7)
      (local.get 8) (local.get 9) (local.get 10)))
  (func (export "test_gdi_bitmap_record_width") (param i32) (result i32)
    (call $gdi_bitmap_record_width (local.get 0)))
  (func (export "test_gdi_bitmap_record_height") (param i32) (result i32)
    (call $gdi_bitmap_record_height (local.get 0)))
  (func (export "test_gdi_bitmap_record_bpp") (param i32) (result i32)
    (call $gdi_bitmap_record_bpp (local.get 0)))
  (func (export "test_gdi_bitmap_record_storage") (param i32) (result i32)
    (call $gdi_bitmap_record_storage (local.get 0)))
  (func (export "test_gdi_bitmap_record_dib_bits") (param i32) (result i32)
    (call $gdi_bitmap_record_dib_bits (local.get 0)))
  (func (export "test_gdi_bitmap_write_object") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_write_object (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_parse_dib") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_parse_dib (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_plan_create_bitmap")
        (param i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_plan_create_bitmap (local.get 0) (local.get 1)
      (local.get 2) (local.get 3) (local.get 4)))
