  ;; WAT-native bitmap record/query and raw DIB parsing foundation.
  ;;
  ;; The canonical 48-byte object record layout is:
  ;;   +0 handle, +4 type (3 bitmap), +8 width, +12 height, +16 bpp,
  ;;   +20 flags (bit0 DIB, bit1 top-down), +24 canonical bits WA,
  ;;   +28 stride, +32 palette WA, +36 palette count, +40 surface id,
  ;;   +44 reserved.
  ;; These helpers do not allocate handles, surfaces, or pixels.

  (func $gdi_bitmap_record_valid (param $record i32) (result i32)
    (i32.and (i32.ne (local.get $record) (i32.const 0))
      (i32.and (i32.eq (i32.load offset=4 (local.get $record)) (i32.const 3))
        (i32.and
          (i32.and (i32.gt_s (i32.load offset=8 (local.get $record)) (i32.const 0))
            (i32.gt_s (i32.load offset=12 (local.get $record)) (i32.const 0)))
          (i32.gt_u (i32.load offset=16 (local.get $record)) (i32.const 0))))))

  (func $gdi_bitmap_record_init (param $record i32) (param $handle i32)
        (param $width i32) (param $height i32) (param $bpp i32) (param $flags i32)
        (param $bits i32) (param $stride i32) (param $palette i32)
        (param $palette_count i32) (param $surface_id i32) (result i32)
    (if (i32.or (i32.eqz (local.get $record))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $bpp) (i32.const 0))
                (i32.le_s (local.get $stride) (i32.const 0))))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $record) (i32.const 0) (i32.const 48))
    (i32.store (local.get $record) (local.get $handle))
    (i32.store offset=4 (local.get $record) (i32.const 3))
    (i32.store offset=8 (local.get $record) (local.get $width))
    (i32.store offset=12 (local.get $record) (local.get $height))
    (i32.store offset=16 (local.get $record) (local.get $bpp))
    (i32.store offset=20 (local.get $record) (i32.and (local.get $flags) (i32.const 3)))
    (i32.store offset=24 (local.get $record) (local.get $bits))
    (i32.store offset=28 (local.get $record) (local.get $stride))
    (i32.store offset=32 (local.get $record) (local.get $palette))
    (i32.store offset=36 (local.get $record) (local.get $palette_count))
    (i32.store offset=40 (local.get $record) (local.get $surface_id))
    (i32.const 1))

  (func $gdi_bitmap_record_width (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=8 (local.get $record)))
  (func $gdi_bitmap_record_height (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=12 (local.get $record)))
  (func $gdi_bitmap_record_bpp (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=16 (local.get $record)))
  (func $gdi_bitmap_record_storage (param $record i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))
  (func $gdi_bitmap_record_dib_bits (param $record i32) (result i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.eqz (i32.and (i32.load offset=20 (local.get $record)) (i32.const 1))))
      (then (return (i32.const 0))))
    (i32.load offset=24 (local.get $record)))

  ;; Write Win32 BITMAP (24 bytes) into linear memory. DDB private storage is
  ;; never exposed through bmBits; DIB section storage is translated to a guest
  ;; pointer. GetObjectA and GetObjectW use the same BITMAP layout.
  (func $gdi_bitmap_write_object (param $record i32) (param $buffer i32)
        (param $buffer_size i32) (result i32)
    (local $bits i32)
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.or (i32.eqz (local.get $buffer))
            (i32.lt_u (local.get $buffer_size) (i32.const 24))))
      (then (return (i32.const 0))))
    (memory.fill (local.get $buffer) (i32.const 0) (i32.const 24))
    (i32.store offset=4 (local.get $buffer) (i32.load offset=8 (local.get $record)))
    (i32.store offset=8 (local.get $buffer) (i32.load offset=12 (local.get $record)))
    (i32.store offset=12 (local.get $buffer) (i32.load offset=28 (local.get $record)))
    (i32.store16 offset=16 (local.get $buffer) (i32.const 1))
    (i32.store16 offset=18 (local.get $buffer) (i32.load offset=16 (local.get $record)))
    (local.set $bits (call $gdi_bitmap_record_dib_bits (local.get $record)))
    (if (local.get $bits)
      (then (i32.store offset=20 (local.get $buffer) (call $w2g (local.get $bits)))))
    (i32.const 24))

  ;; Parsed DIB metadata is a 48-byte plan:
  ;; +0 width, +4 height(abs), +8 bpp, +12 flags(bit1 top-down), +16 stride,
  ;; +20 palette WA, +24 palette count, +28 pixel WA, +32 pixel byte count,
  ;; +36 header size, +40 compression, +44 encoded byte count. It contains no
  ;; semantic GDI handle or surface id.
  (func $gdi_bitmap_parse_dib (param $data i32) (param $size i32)
        (param $plan i32) (result i32)
    (local $header_size i32) (local $width i32) (local $height i32)
    (local $bpp i32) (local $compression i32) (local $top_down i32)
    (local $palette_count i32) (local $palette_bytes i32) (local $bits_offset i32)
    (local $stride i32) (local $masks i32) (local $image_size i64)
    (if (i32.or (i32.eqz (local.get $data))
          (i32.or (i32.eqz (local.get $plan)) (i32.lt_u (local.get $size) (i32.const 12))))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $data)))
    ;; Win2/Win3 resources, including Win98 CARDS.DLL, use the 12-byte
    ;; BITMAPCOREHEADER and RGBTRIPLE palettes. Mark these plans with bit 3 so
    ;; the materializer expands the palette to canonical RGBQUAD entries.
    (if (i32.eq (local.get $header_size) (i32.const 12))
      (then
        (local.set $width (i32.load16_u offset=4 (local.get $data)))
        (local.set $height (i32.load16_u offset=6 (local.get $data)))
        (local.set $bpp (i32.load16_u offset=10 (local.get $data)))
        (if (i32.or (i32.eqz (local.get $width))
              (i32.or (i32.eqz (local.get $height))
                (i32.or (i32.ne (i32.load16_u offset=8 (local.get $data)) (i32.const 1))
                  (i32.and
                    (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                      (i32.ne (local.get $bpp) (i32.const 4)))
                    (i32.and (i32.ne (local.get $bpp) (i32.const 8))
                      (i32.ne (local.get $bpp) (i32.const 24)))))))
          (then (return (i32.const 0))))
        (if (i32.le_u (local.get $bpp) (i32.const 8))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (local.set $palette_bytes (i32.mul (local.get $palette_count) (i32.const 3)))
        (local.set $bits_offset (i32.add (i32.const 12) (local.get $palette_bytes)))
        (if (i32.gt_u (local.get $bits_offset) (local.get $size))
          (then (return (i32.const 0))))
        (local.set $stride (i32.shl
          (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
            (i32.const 5)) (i32.const 2)))
        (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
          (i64.extend_i32_u (local.get $height))))
        (if (i64.gt_u (local.get $image_size)
              (i64.extend_i32_u (i32.sub (local.get $size) (local.get $bits_offset))))
          (then (return (i32.const 0))))
        (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
        (i32.store (local.get $plan) (local.get $width))
        (i32.store offset=4 (local.get $plan) (local.get $height))
        (i32.store offset=8 (local.get $plan) (local.get $bpp))
        (i32.store offset=12 (local.get $plan) (i32.const 8))
        (i32.store offset=16 (local.get $plan) (local.get $stride))
        (if (local.get $palette_count)
          (then (i32.store offset=20 (local.get $plan) (i32.add (local.get $data) (i32.const 12)))))
        (i32.store offset=24 (local.get $plan) (local.get $palette_count))
        (i32.store offset=28 (local.get $plan) (i32.add (local.get $data) (local.get $bits_offset)))
        (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
        (i32.store offset=36 (local.get $plan) (i32.const 12))
        (return (i32.const 1))))
    (if (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
          (i32.gt_u (local.get $header_size) (local.get $size)))
      (then (return (i32.const 0))))
    (local.set $width (i32.load offset=4 (local.get $data)))
    (local.set $height (i32.load offset=8 (local.get $data)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $data)))
    (local.set $compression (i32.load offset=16 (local.get $data)))
    (if (i32.or (i32.le_s (local.get $width) (i32.const 0))
          (i32.or (i32.eqz (local.get $height))
            (i32.or (i32.ne (i32.load16_u offset=12 (local.get $data)) (i32.const 1))
              (i32.and (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                  (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                    (i32.ne (local.get $bpp) (i32.const 8))))
                (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                  (i32.and (i32.ne (local.get $bpp) (i32.const 16))
                    (i32.ne (local.get $bpp) (i32.const 32))))))))
      (then (return (i32.const 0))))
    ;; BI_RLE8 is valid only for 8-bpp and BI_RLE4 only for 4-bpp. Compressed
    ;; top-down DIBs are not defined by Win32.
    (if (i32.and (i32.ne (local.get $compression) (i32.const 0))
          (i32.and (i32.ne (local.get $compression) (i32.const 1))
            (i32.and (i32.ne (local.get $compression) (i32.const 2))
              (i32.ne (local.get $compression) (i32.const 3)))))
      (then (return (i32.const 0))))
    (if (i32.or
          (i32.and (i32.eq (local.get $compression) (i32.const 1))
            (i32.ne (local.get $bpp) (i32.const 8)))
          (i32.or
            (i32.and (i32.eq (local.get $compression) (i32.const 2))
              (i32.ne (local.get $bpp) (i32.const 4)))
            (i32.and (i32.eq (local.get $compression) (i32.const 3))
              (i32.ne (local.get $bpp) (i32.const 16)))))
      (then (return (i32.const 0))))
    (local.set $top_down (i32.lt_s (local.get $height) (i32.const 0)))
    (if (i32.and (i32.ne (local.get $top_down) (i32.const 0))
          (i32.and (i32.ne (local.get $compression) (i32.const 0))
            (i32.ne (local.get $compression) (i32.const 3))))
      (then (return (i32.const 0))))
    (if (local.get $top_down)
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $data)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.shl (i32.const 1) (local.get $bpp)))
          (then (return (i32.const 0))))))
    (if (i32.eq (local.get $bpp) (i32.const 16))
      (then
        (local.set $palette_count (i32.const 3))
        (if (i32.eq (local.get $compression) (i32.const 3))
          (then
            (local.set $masks (i32.add (local.get $data) (i32.const 40)))
            (if (i32.eq (local.get $header_size) (i32.const 40))
              (then
                (if (i32.lt_u (local.get $size) (i32.const 52))
                  (then (return (i32.const 0))))
                (local.set $palette_bytes (i32.const 12)))
              (else
                (if (i32.lt_u (local.get $header_size) (i32.const 52))
                  (then (return (i32.const 0))))))
            (if (i32.eqz (call $gdi_color_masks_valid (local.get $masks)))
              (then (return (i32.const 0)))))
          (else (local.set $masks (global.get $GDI_RGB555_MASKS))))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then (local.set $palette_bytes
        (i32.mul (local.get $palette_count) (i32.const 4)))))
    (local.set $bits_offset (i32.add (local.get $header_size) (local.get $palette_bytes)))
    (if (i32.gt_u (local.get $bits_offset) (local.get $size))
      (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
        (i32.const 5)) (i32.const 2)))
    (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i32.or (i32.eqz (local.get $compression))
          (i32.eq (local.get $compression) (i32.const 3)))
      (then
        (if (i64.gt_u (local.get $image_size)
              (i64.extend_i32_u (i32.sub (local.get $size) (local.get $bits_offset))))
          (then (return (i32.const 0))))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=12 (local.get $plan) (i32.shl (local.get $top_down) (i32.const 1)))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (if (local.get $palette_count)
      (then (i32.store offset=20 (local.get $plan)
        (select (local.get $masks)
          (i32.add (local.get $data) (local.get $header_size))
          (i32.eq (local.get $bpp) (i32.const 16))))))
    (i32.store offset=24 (local.get $plan) (local.get $palette_count))
    (i32.store offset=28 (local.get $plan) (i32.add (local.get $data) (local.get $bits_offset)))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
    (i32.store offset=36 (local.get $plan) (local.get $header_size))
    (i32.store offset=40 (local.get $plan) (local.get $compression))
    (if (i32.or (i32.eq (local.get $compression) (i32.const 1))
          (i32.eq (local.get $compression) (i32.const 2)))
      (then
        (local.set $palette_bytes (i32.load offset=20 (local.get $data)))
        (if (i32.or (i32.eqz (local.get $palette_bytes))
              (i32.gt_u (local.get $palette_bytes)
                (i32.sub (local.get $size) (local.get $bits_offset))))
          (then (local.set $palette_bytes
            (i32.sub (local.get $size) (local.get $bits_offset)))))
        (i32.store offset=44 (local.get $plan) (local.get $palette_bytes))))
    (i32.const 1))

  ;; CreateBitmap layout planner. Input scanlines use WORD alignment as Win32
  ;; BITMAP.bmWidthBytes specifies. The caller supplies allocation/copy policy.
  ;; Plan layout matches $gdi_bitmap_parse_dib except palette/header fields.
  (func $gdi_bitmap_plan_create_bitmap (param $width i32) (param $height i32)
        (param $planes i32) (param $bits_pixel i32) (param $plan i32) (result i32)
    (local $bpp i32) (local $stride i32) (local $size i64)
    (if (i32.or (i32.eqz (local.get $plan))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.or (i32.le_s (local.get $planes) (i32.const 0))
                (i32.le_s (local.get $bits_pixel) (i32.const 0))))))
      (then (return (i32.const 0))))
    (local.set $bpp (i32.mul (local.get $planes) (local.get $bits_pixel)))
    (if (i32.gt_u (local.get $bpp) (i32.const 32)) (then (return (i32.const 0))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 15))
        (i32.const 4)) (i32.const 1)))
    (local.set $size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $size) (i64.const 0xFFFFFFFF))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $size)))
    (i32.const 1))

  ;; Parse an application-supplied BITMAPINFOHEADER. Unlike an RT_BITMAP
  ;; payload, the pixel pointer is supplied separately to CreateDIBitmap, so
  ;; this validates metadata without assuming bytes follow the color table.
  (func $gdi_bitmap_plan_info (param $info i32) (param $plan i32) (result i32)
    (local $header_size i32) (local $width i32) (local $height i32)
    (local $bpp i32) (local $compression i32) (local $top_down i32)
    (local $palette_count i32) (local $masks i32)
    (local $stride i32) (local $image_size i64)
    (if (i32.or (i32.eqz (local.get $info)) (i32.eqz (local.get $plan)))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $info)))
    (if (i32.eq (local.get $header_size) (i32.const 12))
      (then
        (local.set $width (i32.load16_u offset=4 (local.get $info)))
        (local.set $height (i32.load16_u offset=6 (local.get $info)))
        (local.set $bpp (i32.load16_u offset=10 (local.get $info)))
        (if (i32.or (i32.eqz (local.get $width))
              (i32.or (i32.eqz (local.get $height))
                (i32.or (i32.ne (i32.load16_u offset=8 (local.get $info)) (i32.const 1))
                  (i32.and
                    (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                      (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                        (i32.ne (local.get $bpp) (i32.const 8))))
                    (i32.and (i32.ne (local.get $bpp) (i32.const 16))
                      (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                        (i32.ne (local.get $bpp) (i32.const 32))))))))
          (then (return (i32.const 0))))
        (if (i32.le_u (local.get $bpp) (i32.const 8))
          (then (local.set $palette_count
            (i32.shl (i32.const 1) (local.get $bpp)))))
        (local.set $stride (i32.shl
          (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp))
            (i32.const 31)) (i32.const 5)) (i32.const 2)))
        (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
          (i64.extend_i32_u (local.get $height))))
        (if (i64.gt_u (local.get $image_size) (i64.const 0xFFFFFFFF))
          (then (return (i32.const 0))))
        (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
        (i32.store (local.get $plan) (local.get $width))
        (i32.store offset=4 (local.get $plan) (local.get $height))
        (i32.store offset=8 (local.get $plan) (local.get $bpp))
        ;; Bit 3 tells the owned-bitmap materializer to expand RGBTRIPLEs.
        (i32.store offset=12 (local.get $plan) (i32.const 8))
        (i32.store offset=16 (local.get $plan) (local.get $stride))
        (if (local.get $palette_count)
          (then (i32.store offset=20 (local.get $plan)
            (i32.add (local.get $info) (i32.const 12)))))
        (i32.store offset=24 (local.get $plan) (local.get $palette_count))
        (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
        (i32.store offset=36 (local.get $plan) (i32.const 12))
        (return (i32.const 1))))
    (local.set $width (i32.load offset=4 (local.get $info)))
    (local.set $height (i32.load offset=8 (local.get $info)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $info)))
    (local.set $compression (i32.load offset=16 (local.get $info)))
    (if (i32.or
          (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
            (i32.gt_u (local.get $header_size) (i32.const 124)))
          (i32.or (i32.le_s (local.get $width) (i32.const 0))
            (i32.or (i32.eqz (local.get $height))
              (i32.or (i32.ne (i32.load16_u offset=12 (local.get $info)) (i32.const 1))
                (i32.or (i32.and (i32.ne (local.get $compression) (i32.const 0))
                      (i32.and (i32.ne (local.get $compression) (i32.const 1))
                        (i32.and (i32.ne (local.get $compression) (i32.const 2))
                          (i32.ne (local.get $compression) (i32.const 3)))))
                  (i32.and
                    (i32.and (i32.ne (local.get $bpp) (i32.const 1))
                      (i32.and (i32.ne (local.get $bpp) (i32.const 4))
                        (i32.ne (local.get $bpp) (i32.const 8))))
                    (i32.and (i32.ne (local.get $bpp) (i32.const 16))
                      (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                        (i32.ne (local.get $bpp) (i32.const 32))))))))))
      (then (return (i32.const 0))))
    ;; Same pairing rules the RT_BITMAP path enforces: BI_RLE8 is 8-bpp only,
    ;; BI_RLE4 is 4-bpp only, BI_BITFIELDS is 16- or 32-bpp.
    (if (i32.or
          (i32.and (i32.eq (local.get $compression) (i32.const 1))
            (i32.ne (local.get $bpp) (i32.const 8)))
          (i32.or
            (i32.and (i32.eq (local.get $compression) (i32.const 2))
              (i32.ne (local.get $bpp) (i32.const 4)))
            (i32.and (i32.eq (local.get $compression) (i32.const 3))
              (i32.and (i32.ne (local.get $bpp) (i32.const 16))
                (i32.ne (local.get $bpp) (i32.const 32))))))
      (then (return (i32.const 0))))
    ;; A 32-bpp BI_BITFIELDS DIB whose masks are the ordinary 8:8:8 layout is
    ;; byte-for-byte a BI_RGB one, so fold it into that path rather than
    ;; teaching every consumer a second 32-bpp pixel format. Winamp's wVis
    ;; plug-in asks for exactly this and got NULL back, which left its window
    ;; a blank grey rectangle for the whole session. Any other mask triple is
    ;; still refused: a wrong channel order would silently paint wrong colors.
    (if (i32.and (i32.eq (local.get $compression) (i32.const 3))
          (i32.eq (local.get $bpp) (i32.const 32)))
      (then
        (if (i32.and (i32.ne (local.get $header_size) (i32.const 40))
              (i32.lt_u (local.get $header_size) (i32.const 52)))
          (then (return (i32.const 0))))
        (if (i32.eqz (i32.and
              (i32.eq (i32.load offset=40 (local.get $info)) (i32.const 0x00FF0000))
              (i32.and
                (i32.eq (i32.load offset=44 (local.get $info)) (i32.const 0x0000FF00))
                (i32.eq (i32.load offset=48 (local.get $info)) (i32.const 0x000000FF)))))
          (then (return (i32.const 0))))
        (local.set $compression (i32.const 0))
        ;; With a plain 40-byte header the three masks sit between it and the
        ;; pixels, so a packed DIB's data starts 12 bytes further in. A V4/V5
        ;; header already contains them.
        (if (i32.eq (local.get $header_size) (i32.const 40))
          (then (local.set $header_size (i32.const 52))))))
    ;; Win32 does not define a top-down compressed DIB.
    (if (i32.and (i32.lt_s (local.get $height) (i32.const 0))
          (i32.or (i32.eq (local.get $compression) (i32.const 1))
            (i32.eq (local.get $compression) (i32.const 2))))
      (then (return (i32.const 0))))
    (local.set $top_down (i32.lt_s (local.get $height) (i32.const 0)))
    (if (local.get $top_down)
      (then (local.set $height (i32.sub (i32.const 0) (local.get $height)))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $info)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.shl (i32.const 1) (local.get $bpp)))
          (then (return (i32.const 0))))))
    (if (i32.eq (local.get $bpp) (i32.const 16))
      (then
        (local.set $palette_count (i32.const 3))
        (if (i32.eq (local.get $compression) (i32.const 3))
          (then
            (if (i32.and (i32.ne (local.get $header_size) (i32.const 40))
                  (i32.lt_u (local.get $header_size) (i32.const 52)))
              (then (return (i32.const 0))))
            (local.set $masks (i32.add (local.get $info) (i32.const 40)))
            (if (i32.eqz (call $gdi_color_masks_valid (local.get $masks)))
              (then (return (i32.const 0)))))
          (else (local.set $masks (global.get $GDI_RGB555_MASKS))))))
    (local.set $stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp)) (i32.const 31))
        (i32.const 5)) (i32.const 2)))
    (local.set $image_size (i64.mul (i64.extend_i32_u (local.get $stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $image_size) (i64.const 0xFFFFFFFF))
      (then (return (i32.const 0))))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
    (i32.store (local.get $plan) (local.get $width))
    (i32.store offset=4 (local.get $plan) (local.get $height))
    (i32.store offset=8 (local.get $plan) (local.get $bpp))
    (i32.store offset=12 (local.get $plan) (i32.shl (local.get $top_down) (i32.const 1)))
    (i32.store offset=16 (local.get $plan) (local.get $stride))
    (if (local.get $palette_count)
      (then (i32.store offset=20 (local.get $plan)
        (select (local.get $masks)
          (i32.add (local.get $info) (local.get $header_size))
          (i32.eq (local.get $bpp) (i32.const 16))))))
    (i32.store offset=24 (local.get $plan) (local.get $palette_count))
    (i32.store offset=32 (local.get $plan) (i32.wrap_i64 (local.get $image_size)))
    (i32.store offset=36 (local.get $plan) (local.get $header_size))
    (i32.store offset=40 (local.get $plan) (local.get $compression))
    ;; A compressed DIB arrives as a bare pointer here, with no surrounding
    ;; buffer to bound it — biSizeImage is the only length available, and Win32
    ;; requires it to be set for BI_RLE8/BI_RLE4. Without it the decoder has no
    ;; end to stop at, so refuse rather than read past the caller's data.
    (if (i32.or (i32.eq (local.get $compression) (i32.const 1))
          (i32.eq (local.get $compression) (i32.const 2)))
      (then
        (if (i32.eqz (i32.load offset=20 (local.get $info)))
          (then (return (i32.const 0))))
        (i32.store offset=44 (local.get $plan) (i32.load offset=20 (local.get $info)))))
    (i32.const 1))

  ;; Store one palette index into canonical packed DIB storage. RLE streams
  ;; enumerate scanlines from the bottom, which is also row zero in a
  ;; bottom-up DIB allocation.
  (func $gdi_bitmap_store_index (param $dst i32) (param $stride i32)
        (param $x i32) (param $y i32) (param $bpp i32) (param $index i32)
    (local $p i32) (local $old i32)
    (local.set $p (i32.add (local.get $dst)
      (i32.add (i32.mul (local.get $y) (local.get $stride))
        (select (local.get $x) (i32.shr_u (local.get $x) (i32.const 1))
          (i32.eq (local.get $bpp) (i32.const 8))))))
    (if (i32.eq (local.get $bpp) (i32.const 8))
      (then (i32.store8 (local.get $p) (local.get $index)))
      (else
        (local.set $old (i32.load8_u (local.get $p)))
        (if (i32.eqz (i32.and (local.get $x) (i32.const 1)))
          (then (i32.store8 (local.get $p)
            (i32.or (i32.and (local.get $old) (i32.const 0x0F))
              (i32.shl (i32.and (local.get $index) (i32.const 0x0F)) (i32.const 4)))))
          (else (i32.store8 (local.get $p)
            (i32.or (i32.and (local.get $old) (i32.const 0xF0))
              (i32.and (local.get $index) (i32.const 0x0F)))))))))

  ;; Decode bounded BI_RLE8/BI_RLE4 data into packed bottom-up scanlines.
  ;; Every command is validated before it changes destination memory.
  (func $gdi_bitmap_decode_rle (param $src i32) (param $src_size i32)
        (param $dst i32) (param $width i32) (param $height i32)
        (param $stride i32) (param $bpp i32) (result i32)
    (local $p i32) (local $end i32) (local $x i32) (local $y i32)
    (local $count i32) (local $value i32) (local $i i32)
    (local $bytes i32) (local $index i32) (local $dx i32) (local $dy i32)
    (if (i32.or (i32.eqz (local.get $src))
          (i32.or (i32.eqz (local.get $src_size))
            (i32.and (i32.ne (local.get $bpp) (i32.const 4))
              (i32.ne (local.get $bpp) (i32.const 8)))))
      (then (return (i32.const 0))))
    (local.set $p (local.get $src))
    (local.set $end (i32.add (local.get $src) (local.get $src_size)))
    (block $failed (loop $commands
      (br_if $failed (i32.gt_u (i32.add (local.get $p) (i32.const 2)) (local.get $end)))
      (local.set $count (i32.load8_u (local.get $p)))
      (local.set $value (i32.load8_u offset=1 (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 2)))
      (if (local.get $count)
        (then
          (br_if $failed (i32.or (i32.ge_u (local.get $y) (local.get $height))
            (i32.gt_u (i32.add (local.get $x) (local.get $count)) (local.get $width))))
          (local.set $i (i32.const 0))
          (block $run_done (loop $run
            (br_if $run_done (i32.ge_u (local.get $i) (local.get $count)))
            (local.set $index
              (if (result i32) (i32.eq (local.get $bpp) (i32.const 8))
                (then (local.get $value))
                (else (select (i32.and (local.get $value) (i32.const 0x0F))
                  (i32.shr_u (local.get $value) (i32.const 4))
                  (i32.and (local.get $i) (i32.const 1))))))
            (call $gdi_bitmap_store_index (local.get $dst) (local.get $stride)
              (i32.add (local.get $x) (local.get $i)) (local.get $y)
              (local.get $bpp) (local.get $index))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $run)))
          (local.set $x (i32.add (local.get $x) (local.get $count))))
        (else
          (if (i32.eqz (local.get $value))
            (then
              (local.set $x (i32.const 0))
              (local.set $y (i32.add (local.get $y) (i32.const 1))))
            (else (if (i32.eq (local.get $value) (i32.const 1))
              (then (return (i32.const 1)))
              (else (if (i32.eq (local.get $value) (i32.const 2))
                (then
                  (br_if $failed (i32.gt_u (i32.add (local.get $p) (i32.const 2)) (local.get $end)))
                  (local.set $dx (i32.load8_u (local.get $p)))
                  (local.set $dy (i32.load8_u offset=1 (local.get $p)))
                  (local.set $p (i32.add (local.get $p) (i32.const 2)))
                  (br_if $failed (i32.or
                    (i32.gt_u (i32.add (local.get $x) (local.get $dx)) (local.get $width))
                    (i32.ge_u (i32.add (local.get $y) (local.get $dy)) (local.get $height))))
                  (local.set $x (i32.add (local.get $x) (local.get $dx)))
                  (local.set $y (i32.add (local.get $y) (local.get $dy))))
                (else
                  (local.set $count (local.get $value))
                  (local.set $bytes
                    (if (result i32) (i32.eq (local.get $bpp) (i32.const 8))
                      (then (local.get $count))
                      (else (i32.shr_u (i32.add (local.get $count) (i32.const 1)) (i32.const 1)))))
                  (br_if $failed (i32.or
                    (i32.or (i32.ge_u (local.get $y) (local.get $height))
                      (i32.gt_u (i32.add (local.get $x) (local.get $count)) (local.get $width)))
                    (i32.gt_u (i32.add (local.get $p)
                      (i32.add (local.get $bytes) (i32.and (local.get $bytes) (i32.const 1))))
                      (local.get $end))))
                  (local.set $i (i32.const 0))
                  (block $absolute_done (loop $absolute
                    (br_if $absolute_done (i32.ge_u (local.get $i) (local.get $count)))
                    (local.set $value (i32.load8_u (i32.add (local.get $p)
                      (select (local.get $i) (i32.shr_u (local.get $i) (i32.const 1))
                        (i32.eq (local.get $bpp) (i32.const 8))))))
                    (local.set $index
                      (if (result i32) (i32.eq (local.get $bpp) (i32.const 8))
                        (then (local.get $value))
                        (else (select (i32.and (local.get $value) (i32.const 0x0F))
                          (i32.shr_u (local.get $value) (i32.const 4))
                          (i32.and (local.get $i) (i32.const 1))))))
                    (call $gdi_bitmap_store_index (local.get $dst) (local.get $stride)
                      (i32.add (local.get $x) (local.get $i)) (local.get $y)
                      (local.get $bpp) (local.get $index))
                    (local.set $i (i32.add (local.get $i) (i32.const 1)))
                    (br $absolute)))
                  (local.set $p (i32.add (local.get $p)
                    (i32.add (local.get $bytes) (i32.and (local.get $bytes) (i32.const 1)))))
                  (local.set $x (i32.add (local.get $x) (local.get $count)))))))))))
      (br $commands)))
    (i32.const 0))

  ;; Copy a source color table into canonical RGBQUAD-sized storage.
  ;; mode 0 copies RGBQUAD/RGBTRIPLE input, mode 1 resolves WORD indexes
  ;; through a logical palette, mode 2 preserves WORD indexes for deferred
  ;; DIB pattern-brush realization, and mode 3 clones preserved i32 indexes.
  (func $gdi_bitmap_copy_palette (param $dst i32) (param $src i32)
        (param $count i32) (param $flags i32) (param $mode i32)
        (param $palette_handle i32) (result i32)
    (local $i i32) (local $index i32) (local $color i32)
    (if (i32.eqz (local.get $count)) (then (return (i32.const 1))))
    (if (i32.or (i32.eqz (local.get $dst)) (i32.eqz (local.get $src)))
      (then (return (i32.const 0))))
    (if (i32.eqz (local.get $mode))
      (then
        (if (i32.and (local.get $flags) (i32.const 8))
          (then
            (block $done (loop $triples
              (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
              (i32.store (i32.add (local.get $dst) (i32.shl (local.get $i) (i32.const 2)))
                (i32.and (i32.load (i32.add (local.get $src)
                  (i32.mul (local.get $i) (i32.const 3)))) (i32.const 0x00FFFFFF)))
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br $triples))))
          (else (memory.copy (local.get $dst) (local.get $src)
            (i32.shl (local.get $count) (i32.const 2)))))
        (return (i32.const 1))))
    (if (i32.eq (local.get $mode) (i32.const 3))
      (then
        (memory.copy (local.get $dst) (local.get $src)
          (i32.shl (local.get $count) (i32.const 2)))
        (return (i32.const 1))))
    (block $done (loop $indexes
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $index (i32.load16_u (i32.add (local.get $src)
        (i32.shl (local.get $i) (i32.const 1)))))
      (if (i32.eq (local.get $mode) (i32.const 2))
        (then (i32.store (i32.add (local.get $dst)
          (i32.shl (local.get $i) (i32.const 2))) (local.get $index)))
        (else
          (local.set $color (call $gdi_palette_colorref
            (local.get $palette_handle) (local.get $index)))
          ;; Missing logical-palette slots are legal in a larger identity
          ;; DIB_PAL_COLORS table. Win9x resolves the usable prefix and leaves
          ;; the unused entries harmless; black is the deterministic fallback.
          (if (i32.eq (local.get $color) (i32.const -1))
            (then (local.set $color (i32.const 0))))
          (i32.store (i32.add (local.get $dst)
            (i32.shl (local.get $i) (i32.const 2)))
            (call $gdi_raster_swap_rb (local.get $color)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $indexes)))
    (i32.const 1))

  ;; Materialize a parsed bitmap as an owned DDB/DIB. Pixel and palette bytes are
  ;; copied into one DIB-arena allocation; JavaScript receives only the final
  ;; presentation descriptor through gdi_surface_create/upload.
  (func $gdi_bitmap_create_owned (param $plan i32) (param $pixels i32)
        (param $copy_pixels i32) (param $copy_palette i32)
        (param $object_flags i32) (param $palette_mode i32)
        (param $palette_handle i32) (result i32)
    (local $width i32) (local $height i32) (local $bpp i32) (local $flags i32)
    (local $stride i32) (local $image_size i32) (local $palette_src i32)
    (local $palette_count i32) (local $palette_size i32) (local $total i64)
    (local $compression i32) (local $encoded_size i32)
    (local $storage_ga i32) (local $storage i32) (local $palette i32) (local $handle i32)
    (if (i32.eqz (local.get $plan)) (then (return (i32.const 0))))
    (local.set $width (i32.load (local.get $plan)))
    (local.set $height (i32.load offset=4 (local.get $plan)))
    (local.set $bpp (i32.load offset=8 (local.get $plan)))
    (local.set $flags (i32.load offset=12 (local.get $plan)))
    (local.set $stride (i32.load offset=16 (local.get $plan)))
    (local.set $palette_src (i32.load offset=20 (local.get $plan)))
    (local.set $palette_count (i32.load offset=24 (local.get $plan)))
    (local.set $image_size (i32.load offset=32 (local.get $plan)))
    (local.set $compression (i32.load offset=40 (local.get $plan)))
    (local.set $encoded_size (i32.load offset=44 (local.get $plan)))
    (if (i32.or (i32.eqz (local.get $image_size))
          (i32.or (i32.eqz (local.get $stride))
            (i32.and (i32.ne (local.get $copy_pixels) (i32.const 0))
              (i32.eqz (local.get $pixels)))))
      (then (return (i32.const 0))))
    (local.set $palette_size (i32.mul (local.get $palette_count) (i32.const 4)))
    (local.set $total (i64.add (i64.extend_i32_u (local.get $image_size))
      (i64.extend_i32_u (local.get $palette_size))))
    (if (i64.gt_u (local.get $total) (i64.extend_i32_u (global.get $DIB_BACKING_BASE_SIZE)))
      (then (return (i32.const 0))))
    (local.set $storage_ga (call $dib_alloc (i32.wrap_i64 (local.get $total)))
    )
    (if (i32.eqz (local.get $storage_ga)) (then (return (i32.const 0))))
    (local.set $storage (call $g2w (local.get $storage_ga)))
    (if (local.get $copy_pixels)
      (then
        (if (i32.or (i32.eq (local.get $compression) (i32.const 1))
              (i32.eq (local.get $compression) (i32.const 2)))
          (then
            (if (i32.eqz (call $gdi_bitmap_decode_rle
                  (local.get $pixels) (local.get $encoded_size) (local.get $storage)
                  (local.get $width) (local.get $height) (local.get $stride) (local.get $bpp)))
              (then
                (call $dib_free_wasm (local.get $storage))
                (return (i32.const 0)))))
          (else (memory.copy (local.get $storage) (local.get $pixels) (local.get $image_size))))))
    (if (i32.and (i32.ne (local.get $copy_palette) (i32.const 0))
          (i32.and (i32.ne (local.get $palette_count) (i32.const 0))
            (i32.ne (local.get $palette_src) (i32.const 0))))
      (then
        (local.set $palette (i32.add (local.get $storage) (local.get $image_size)))
        (if (i32.eq (local.get $bpp) (i32.const 16))
          (then (memory.copy (local.get $palette) (local.get $palette_src) (i32.const 12)))
          (else
            (if (i32.eqz (call $gdi_bitmap_copy_palette
                  (local.get $palette) (local.get $palette_src) (local.get $palette_count)
                  (local.get $flags) (local.get $palette_mode) (local.get $palette_handle)))
              (then
                (call $dib_free_wasm (local.get $storage))
                (return (i32.const 0))))))))
    (if (i32.and (i32.le_u (local.get $bpp) (i32.const 8))
          (i32.or (i32.eq (local.get $palette_mode) (i32.const 2))
            (i32.eq (local.get $palette_mode) (i32.const 3))))
      (then (local.set $object_flags
        (i32.or (local.get $object_flags) (i32.const 0x10)))))
    (local.set $handle (call $gdi_bitmap_alloc
      (local.get $width) (local.get $height) (local.get $bpp)
      (i32.or (i32.or (local.get $flags) (local.get $object_flags)) (i32.const 4))
      (local.get $storage) (local.get $stride) (local.get $palette) (local.get $palette_count)))
    (if (i32.eqz (local.get $handle))
      (then
        (call $dib_free_wasm (local.get $storage))
        (return (i32.const 0))))
    (local.get $handle))

  (func $gdi_bitmap_create_bitmap (param $width i32) (param $height i32)
        (param $planes i32) (param $bits_pixel i32) (param $pixels i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_plan_create_bitmap
          (local.get $width) (local.get $height) (local.get $planes)
          (local.get $bits_pixel) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN) (local.get $pixels)
      (i32.ne (local.get $pixels) (i32.const 0)) (i32.const 0)
      (i32.const 0) (i32.const 0) (i32.const 0)))

  (func $gdi_bitmap_create_indirect (param $bitmap i32) (result i32)
    (if (i32.eqz (local.get $bitmap)) (then (return (i32.const 0))))
    (if (i32.ne (i32.load (local.get $bitmap)) (i32.const 0))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_bitmap
      (i32.load offset=4 (local.get $bitmap))
      (i32.load offset=8 (local.get $bitmap))
      (i32.load16_u offset=16 (local.get $bitmap))
      (i32.load16_u offset=18 (local.get $bitmap))
      (if (result i32) (i32.load offset=20 (local.get $bitmap))
        (then (call $g2w (i32.load offset=20 (local.get $bitmap))))
        (else (i32.const 0)))))

  (func $gdi_bitmap_bits (param $bitmap i32) (param $count i32)
        (param $buffer i32) (param $write i32) (result i32)
    (local $record i32) (local $size i32) (local $copied i32)
    (local.set $record (call $gdi_object_record (local.get $bitmap)))
    (if (i32.or (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
          (i32.lt_s (local.get $count) (i32.const 0)))
      (then (return (i32.const 0))))
    (local.set $size (i32.mul (i32.load offset=28 (local.get $record))
      (i32.load offset=12 (local.get $record))))
    (local.set $copied (local.get $count))
    (if (i32.gt_u (local.get $copied) (local.get $size))
      (then (local.set $copied (local.get $size))))
    (if (i32.eqz (local.get $copied)) (then (return (i32.const 0))))
    (if (i32.eqz (local.get $buffer)) (then (return (i32.const 0))))
    (if (local.get $write)
      (then
        (memory.copy (i32.load offset=24 (local.get $record))
          (local.get $buffer) (local.get $copied))
        (drop (call $host_gdi_surface_upload (i32.load offset=40 (local.get $record))
          (i32.const 0) (i32.const 0) (i32.load offset=8 (local.get $record))
          (i32.load offset=12 (local.get $record)))))
      (else (memory.copy (local.get $buffer)
        (i32.load offset=24 (local.get $record)) (local.get $copied))))
    (local.get $copied))

  ;; HINST_COMMCTRL names six standard toolbar strips that are owned by the
  ;; common-controls DLL rather than the caller's PE resources. Keep the
  ;; compatibility artwork in canonical WAT bitmap storage; JavaScript only
  ;; receives the normal presentation descriptor from gdi_bitmap_alloc.
  (func $gdi_common_toolbar_fill (param $bits i32) (param $stride i32)
        (param $left i32) (param $top i32) (param $right i32) (param $bottom i32)
        (param $color i32)
    (local $x i32) (local $y i32)
    (local.set $y (local.get $top))
    (block $done (loop $rows
      (br_if $done (i32.ge_s (local.get $y) (local.get $bottom)))
      (local.set $x (local.get $left))
      (block $row_done (loop $pixels
        (br_if $row_done (i32.ge_s (local.get $x) (local.get $right)))
        (i32.store (i32.add
          (i32.add (local.get $bits) (i32.mul (local.get $y) (local.get $stride)))
          (i32.shl (local.get $x) (i32.const 2))) (local.get $color))
        (local.set $x (i32.add (local.get $x) (i32.const 1)))
        (br $pixels)))
      (local.set $y (i32.add (local.get $y) (i32.const 1)))
      (br $rows))))

  (func $gdi_bitmap_create_common_toolbar (param $resource i32) (result i32)
    (local $icon_w i32) (local $height i32) (local $count i32)
    (local $width i32) (local $stride i32) (local $handle i32)
    (local $record i32) (local $bits i32) (local $i i32) (local $x i32)
    (local $margin i32) (local $color i32)
    (if (i32.eq (local.get $resource) (i32.const 0))
      (then (local.set $icon_w (i32.const 16)) (local.set $height (i32.const 15)) (local.set $count (i32.const 15)))
      (else (if (i32.eq (local.get $resource) (i32.const 1))
        (then (local.set $icon_w (i32.const 24)) (local.set $height (i32.const 24)) (local.set $count (i32.const 15)))
        (else (if (i32.eq (local.get $resource) (i32.const 4))
          (then (local.set $icon_w (i32.const 16)) (local.set $height (i32.const 15)) (local.set $count (i32.const 12)))
          (else (if (i32.eq (local.get $resource) (i32.const 5))
            (then (local.set $icon_w (i32.const 24)) (local.set $height (i32.const 24)) (local.set $count (i32.const 12)))
            (else (if (i32.eq (local.get $resource) (i32.const 8))
              (then (local.set $icon_w (i32.const 16)) (local.set $height (i32.const 15)) (local.set $count (i32.const 5)))
              (else (if (i32.eq (local.get $resource) (i32.const 9))
                (then (local.set $icon_w (i32.const 24)) (local.set $height (i32.const 24)) (local.set $count (i32.const 5)))
                (else (return (i32.const 0))))))))))))))
    (local.set $width (i32.mul (local.get $icon_w) (local.get $count)))
    (local.set $stride (i32.shl (local.get $width) (i32.const 2)))
    (memory.fill (global.get $GDI_BITMAP_PLAN) (i32.const 0) (i32.const 48))
    (i32.store (global.get $GDI_BITMAP_PLAN) (local.get $width))
    (i32.store offset=4 (global.get $GDI_BITMAP_PLAN) (local.get $height))
    (i32.store offset=8 (global.get $GDI_BITMAP_PLAN) (i32.const 32))
    (i32.store offset=12 (global.get $GDI_BITMAP_PLAN) (i32.const 2)) ;; top-down
    (i32.store offset=16 (global.get $GDI_BITMAP_PLAN) (local.get $stride))
    (i32.store offset=32 (global.get $GDI_BITMAP_PLAN)
      (i32.mul (local.get $stride) (local.get $height)))
    (local.set $handle (call $gdi_bitmap_create_owned
      (global.get $GDI_BITMAP_PLAN) (i32.const 0) (i32.const 0) (i32.const 0)
      (i32.const 0) (i32.const 0) (i32.const 0)))
    (if (i32.eqz (local.get $handle)) (then (return (i32.const 0))))
    (local.set $record (call $gdi_object_record (local.get $handle)))
    (local.set $bits (i32.load offset=24 (local.get $record)))
    (call $gdi_common_toolbar_fill (local.get $bits) (local.get $stride)
      (i32.const 0) (i32.const 0) (local.get $width) (local.get $height)
      (i32.const 0x00C0C0C0))
    (local.set $margin (select (i32.const 4) (i32.const 3)
      (i32.eq (local.get $icon_w) (i32.const 24))))
    (block $done (loop $icons
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $x (i32.add (i32.mul (local.get $i) (local.get $icon_w)) (local.get $margin)))
      (call $gdi_common_toolbar_fill (local.get $bits) (local.get $stride)
        (local.get $x) (i32.const 2)
        (i32.sub (i32.add (i32.mul (local.get $i) (local.get $icon_w)) (local.get $icon_w)) (local.get $margin))
        (i32.sub (local.get $height) (i32.const 2)) (i32.const 0x00FFFFFF))
      (call $gdi_common_toolbar_fill (local.get $bits) (local.get $stride)
        (local.get $x) (i32.const 2)
        (i32.sub (i32.add (i32.mul (local.get $i) (local.get $icon_w)) (local.get $icon_w)) (local.get $margin))
        (i32.const 3) (i32.const 0))
      (local.set $color (select (i32.const 0x00008000) (i32.const 0x00C04000)
        (i32.and (local.get $i) (i32.const 1))))
      (call $gdi_common_toolbar_fill (local.get $bits) (local.get $stride)
        (i32.add (local.get $x) (i32.const 2)) (i32.const 4)
        (i32.sub (i32.add (i32.mul (local.get $i) (local.get $icon_w)) (local.get $icon_w))
          (i32.add (local.get $margin) (i32.const 2)))
        (i32.sub (local.get $height) (i32.const 5)) (local.get $color))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $icons)))
    (drop (call $host_gdi_surface_upload (local.get $handle) (i32.const 0)
      (i32.const 0) (local.get $width) (local.get $height)))
    (local.get $handle))

  (func $gdi_bitmap_create_dibitmap (param $hdc i32) (param $info i32) (param $pixels i32)
        (param $init i32) (param $usage i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_plan_info
          (local.get $info) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $usage) (i32.const 1))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN) (local.get $pixels)
      (i32.and (i32.ne (local.get $init) (i32.const 0))
        (i32.ne (local.get $pixels) (i32.const 0)))
      (i32.const 1) (i32.const 0) (local.get $usage)
      (call $gdi_dc_selected_palette (local.get $hdc))))

  (func $gdi_bitmap_create_dib_section (param $hdc i32) (param $info i32)
        (param $usage i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_plan_info
          (local.get $info) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $usage) (i32.const 1))
      (then (return (i32.const 0))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN)
      (i32.const 0) (i32.const 0) (i32.const 1)
      (i32.const 1) (local.get $usage)
      (call $gdi_dc_selected_palette (local.get $hdc))))

  (func $gdi_bitmap_clone_owned (param $bitmap i32) (result i32)
    (local $record i32) (local $plan i32)
    (local.set $record (call $gdi_object_record (local.get $bitmap)))
    (if (i32.eqz (call $gdi_bitmap_record_valid (local.get $record)))
      (then (return (i32.const 0))))
    (local.set $plan (global.get $GDI_BITMAP_PLAN))
    (memory.fill (local.get $plan) (i32.const 0) (i32.const 48))
    (i32.store (local.get $plan) (i32.load offset=8 (local.get $record)))
    (i32.store offset=4 (local.get $plan) (i32.load offset=12 (local.get $record)))
    (i32.store offset=8 (local.get $plan) (i32.load offset=16 (local.get $record)))
    (i32.store offset=12 (local.get $plan)
      (i32.and (i32.load offset=20 (local.get $record)) (i32.const 2)))
    (i32.store offset=16 (local.get $plan) (i32.load offset=28 (local.get $record)))
    (i32.store offset=20 (local.get $plan) (i32.load offset=32 (local.get $record)))
    (i32.store offset=24 (local.get $plan) (i32.load offset=36 (local.get $record)))
    (i32.store offset=32 (local.get $plan)
      (i32.mul (i32.load offset=28 (local.get $record))
        (i32.load offset=12 (local.get $record))))
    (call $gdi_bitmap_create_owned (local.get $plan)
      (i32.load offset=24 (local.get $record)) (i32.const 1) (i32.const 1)
      (i32.and (i32.load offset=20 (local.get $record)) (i32.const 1))
      (select (i32.const 3) (i32.const 0)
        (i32.ne (i32.and (i32.load offset=20 (local.get $record)) (i32.const 0x10)) (i32.const 0)))
      (i32.const 0)))

  (func $gdi_bitmap_wrap_pattern_brush (param $bitmap i32) (param $style i32) (result i32)
    (local $brush i32) (local $record i32)
    (if (i32.ne (call $gdi_object_type (local.get $bitmap)) (i32.const 3))
      (then (return (i32.const 0))))
    (local.set $brush (call $gdi_object_alloc (i32.const 2)
      (local.get $style) (i32.const 0) (i32.const 0) (i32.const 0)))
    (if (i32.eqz (local.get $brush))
      (then
        (drop (call $gdi_object_delete_full (local.get $bitmap)))
        (return (i32.const 0))))
    (local.set $record (call $gdi_object_record (local.get $brush)))
    (i32.store offset=24 (local.get $record) (local.get $bitmap))
    (local.get $brush))

  ;; Pattern brushes own a snapshot. Deleting or changing the caller's bitmap
  ;; after CreatePatternBrush therefore cannot mutate the brush.
  (func $gdi_bitmap_create_pattern_brush (param $bitmap i32) (param $copy i32) (result i32)
    (local $owned i32)
    (drop (local.get $copy))
    (local.set $owned (call $gdi_bitmap_clone_owned (local.get $bitmap)))
    (if (i32.eqz (local.get $owned)) (then (return (i32.const 0))))
    (call $gdi_bitmap_wrap_pattern_brush (local.get $owned) (i32.const 3)))

  ;; packedDib points at BITMAPINFO followed by an RGBQUAD table or WORD
  ;; logical-palette indexes and then native pixels. Palette-index brushes
  ;; preserve those indexes and resolve them against the destination DC when
  ;; sampled, matching their deferred Win32 semantics.
  (func $gdi_bitmap_create_dib_pattern_brush (param $packed_dib i32)
        (param $usage i32) (result i32)
    (local $plan i32) (local $pixels i32) (local $bitmap i32)
    (if (i32.eqz (local.get $packed_dib)) (then (return (i32.const 0))))
    (local.set $plan (global.get $GDI_BITMAP_PLAN))
    (if (i32.eqz (call $gdi_bitmap_plan_info (local.get $packed_dib) (local.get $plan)))
      (then (return (i32.const 0))))
    (if (i32.gt_u (local.get $usage) (i32.const 1))
      (then (return (i32.const 0))))
    (local.set $pixels (i32.add (local.get $packed_dib)
      (i32.add (i32.load offset=36 (local.get $plan))
        (if (result i32) (i32.and (i32.ne (local.get $usage) (i32.const 0))
              (i32.le_u (i32.load offset=8 (local.get $plan)) (i32.const 8)))
          (then (i32.and (i32.add
            (i32.shl (i32.load offset=24 (local.get $plan)) (i32.const 1))
            (i32.const 3)) (i32.const -4)))
          (else
            (select
              (i32.mul (i32.load offset=24 (local.get $plan)) (i32.const 3))
              (select (i32.const 12)
                (i32.shl (i32.load offset=24 (local.get $plan)) (i32.const 2))
                (i32.and
                  (i32.eq (i32.load offset=8 (local.get $plan)) (i32.const 16))
                  (i32.and (i32.eq (i32.load offset=40 (local.get $plan)) (i32.const 3))
                    (i32.eq (i32.load offset=36 (local.get $plan)) (i32.const 40)))))
              (i32.ne (i32.and (i32.load offset=12 (local.get $plan)) (i32.const 8))
                (i32.const 0))))))))
    (local.set $bitmap (call $gdi_bitmap_create_owned
      (local.get $plan) (local.get $pixels) (i32.const 1) (i32.const 1)
      (i32.const 0) (select (i32.const 2) (i32.const 0)
        (i32.ne (local.get $usage) (i32.const 0))) (i32.const 0)))
    (if (i32.eqz (local.get $bitmap)) (then (return (i32.const 0))))
    (call $gdi_bitmap_wrap_pattern_brush (local.get $bitmap) (i32.const 6)))

  (func $gdi_bitmap_plan_palette_color (param $plan i32) (param $index i32) (result i32)
    (local $palette i32) (local $entry i32)
    (local.set $palette (i32.load offset=20 (local.get $plan)))
    (if (i32.or (i32.eqz (local.get $palette))
          (i32.ge_u (local.get $index) (i32.load offset=24 (local.get $plan))))
      (then (return (i32.const 0))))
    (if (i32.ne (i32.and (i32.load offset=12 (local.get $plan)) (i32.const 8))
          (i32.const 0))
      (then
        (local.set $entry (i32.add (local.get $palette)
          (i32.mul (local.get $index) (i32.const 3))))
        (return (i32.or
          (i32.or (i32.load8_u (local.get $entry))
            (i32.shl (i32.load8_u offset=1 (local.get $entry)) (i32.const 8)))
          (i32.shl (i32.load8_u offset=2 (local.get $entry)) (i32.const 16))))))
    (i32.and (i32.load (i32.add (local.get $palette)
      (i32.shl (local.get $index) (i32.const 2)))) (i32.const 0x00FFFFFF)))

  ;; LoadBitmap returns a display-compatible DDB. A 1-bpp resource remains a
  ;; monochrome mask only when both palette entries are black/white; colored
  ;; palettes such as CARDS.DLL's red suits must be materialized as color DDBs.
  (func $gdi_bitmap_plan_is_colored_mono (param $plan i32) (result i32)
    (local $color0 i32) (local $color1 i32)
    (if (i32.or (i32.ne (i32.load offset=8 (local.get $plan)) (i32.const 1))
          (i32.lt_u (i32.load offset=24 (local.get $plan)) (i32.const 2)))
      (then (return (i32.const 0))))
    (local.set $color0 (call $gdi_bitmap_plan_palette_color
      (local.get $plan) (i32.const 0)))
    (local.set $color1 (call $gdi_bitmap_plan_palette_color
      (local.get $plan) (i32.const 1)))
    (i32.or
      (i32.and (i32.ne (local.get $color0) (i32.const 0))
        (i32.ne (local.get $color0) (i32.const 0x00FFFFFF)))
      (i32.and (i32.ne (local.get $color1) (i32.const 0))
        (i32.ne (local.get $color1) (i32.const 0x00FFFFFF)))))

  (func $gdi_bitmap_create_colored_mono_resource (param $plan i32) (result i32)
    (local $width i32) (local $height i32) (local $src i32) (local $src_stride i32)
    (local $dst_ga i32) (local $dst i32) (local $dst_stride i32)
    (local $x i32) (local $y i32) (local $color0 i32) (local $color1 i32)
    (local $handle i32) (local $total i64)
    (local.set $width (i32.load (local.get $plan)))
    (local.set $height (i32.load offset=4 (local.get $plan)))
    (local.set $src (i32.load offset=28 (local.get $plan)))
    (local.set $src_stride (i32.load offset=16 (local.get $plan)))
    (if (i32.or (i32.eqz (local.get $src))
          (i32.gt_u (local.get $width) (i32.const 0x1FFFFFFF)))
      (then (return (i32.const 0))))
    (local.set $dst_stride (i32.shl (local.get $width) (i32.const 2)))
    (local.set $total (i64.mul (i64.extend_i32_u (local.get $dst_stride))
      (i64.extend_i32_u (local.get $height))))
    (if (i64.gt_u (local.get $total)
          (i64.extend_i32_u (global.get $DIB_BACKING_BASE_SIZE)))
      (then (return (i32.const 0))))
    (local.set $dst_ga (call $dib_alloc (i32.wrap_i64 (local.get $total))))
    (if (i32.eqz (local.get $dst_ga)) (then (return (i32.const 0))))
    (local.set $dst (call $g2w (local.get $dst_ga)))
    (local.set $color0 (call $gdi_bitmap_plan_palette_color
      (local.get $plan) (i32.const 0)))
    (local.set $color1 (call $gdi_bitmap_plan_palette_color
      (local.get $plan) (i32.const 1)))
    (block $rows_done (loop $rows
      (br_if $rows_done (i32.ge_u (local.get $y) (local.get $height)))
      (local.set $x (i32.const 0))
      (block $pixels_done (loop $pixels
        (br_if $pixels_done (i32.ge_u (local.get $x) (local.get $width)))
        (i32.store
          (i32.add (i32.add (local.get $dst)
            (i32.mul (local.get $y) (local.get $dst_stride)))
            (i32.shl (local.get $x) (i32.const 2)))
          (select (local.get $color1) (local.get $color0)
            (i32.ne (i32.and
              (i32.load8_u (i32.add
                (i32.add (local.get $src)
                  (i32.mul (local.get $y) (local.get $src_stride)))
                (i32.shr_u (local.get $x) (i32.const 3))))
              (i32.shr_u (i32.const 0x80)
                (i32.and (local.get $x) (i32.const 7)))) (i32.const 0))))
        (local.set $x (i32.add (local.get $x) (i32.const 1)))
        (br $pixels)))
      (local.set $y (i32.add (local.get $y) (i32.const 1)))
      (br $rows)))
    (local.set $handle (call $gdi_bitmap_alloc
      (local.get $width) (local.get $height) (i32.const 32)
      (i32.or (i32.and (i32.load offset=12 (local.get $plan)) (i32.const 2))
        (i32.const 4))
      (local.get $dst) (local.get $dst_stride) (i32.const 0) (i32.const 0)))
    (if (i32.eqz (local.get $handle))
      (then (call $dib_free_wasm (local.get $dst)) (return (i32.const 0))))
    (local.get $handle))

  (func $gdi_bitmap_create_resource (param $data i32) (param $size i32) (result i32)
    (if (i32.eqz (call $gdi_bitmap_parse_dib
          (local.get $data) (local.get $size) (global.get $GDI_BITMAP_PLAN)))
      (then (return (i32.const 0))))
    (if (call $gdi_bitmap_plan_is_colored_mono (global.get $GDI_BITMAP_PLAN))
      (then (return (call $gdi_bitmap_create_colored_mono_resource
        (global.get $GDI_BITMAP_PLAN)))))
    (call $gdi_bitmap_create_owned (global.get $GDI_BITMAP_PLAN)
      (i32.load offset=28 (global.get $GDI_BITMAP_PLAN))
      (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 0)))

  ;; Paint an RT_GROUP_ICON resource into an HDC without routing pixels through
  ;; Canvas. Classic icon DIBs contain a color (XOR) plane followed by a 1-bpp
  ;; transparency (AND) mask, and report twice their visible height. Static
  ;; SS_ICON controls use this path directly from their dialog resource ordinal.
  (func $gdi_icon_draw_resource (param $hdc i32) (param $resource_id i32)
        (param $control_w i32) (param $control_h i32) (param $origin_clip i32)
        (result i32)
    (call $gdi_icon_draw_resource_at (local.get $hdc) (local.get $resource_id)
      (local.get $control_w) (local.get $control_h) (local.get $origin_clip)
      (i32.const 0) (i32.const 0) (global.get $DI_NORMAL)))

  ;; The same painter with the two things DrawIconEx needs and a centered
  ;; static does not: an explicit destination origin, and the DI_* flags that
  ;; say which plane to write. ImageList building depends on both halves —
  ;; comctl32 renders each icon twice, DI_NORMAL into the colour sheet and
  ;; DI_MASK into the mask sheet, and blits the pair back with SRCAND/SRCPAINT.
  ;;
  ;;   DI_MASK  — write the AND plane as monochrome: white where the mask is
  ;;              set (transparent), black where it is clear (opaque).
  ;;   DI_IMAGE — write the XOR plane verbatim, mask ignored.
  ;;   DI_NORMAL— composite: mask clear writes the colour, mask set preserves
  ;;              the destination and XORs any inverse pixel over it.
  (func $gdi_icon_draw_resource_at (param $hdc i32) (param $resource_id i32)
        (param $control_w i32) (param $control_h i32) (param $origin_clip i32)
        (param $at_x i32) (param $at_y i32) (param $di_flags i32)
        (result i32)
    (local $group i32) (local $group_size i32) (local $entry i32)
    (local $image i32) (local $image_size i32) (local $image_id i32)
    (local $header_size i32) (local $width i32) (local $stored_h i32)
    (local $height i32) (local $bpp i32) (local $palette_count i32)
    (local $color_stride i32) (local $mask_stride i32)
    (local $color_offset i32) (local $mask_offset i32)
    (local $src i32) (local $dst i32) (local $src_x i32) (local $src_y i32)
    (local $dst_x i32) (local $dst_y i32) (local $draw_w i32) (local $draw_h i32)
    (local $x i32) (local $y i32) (local $mask_row i32) (local $mask_bit i32)
    (local $source_color i32) (local $dest_color i32)
    (if (i32.or (i32.eqz (local.get $resource_id))
          (i32.or (i32.le_s (local.get $control_w) (i32.const 0))
            (i32.le_s (local.get $control_h) (i32.const 0))))
      (then (return (i32.const 0))))
    (local.set $group (call $rsrc_find_data_wa (i32.const 14) (local.get $resource_id)))
    (local.set $group_size (global.get $rsrc_last_size))
    (if (i32.or (i32.eqz (local.get $group))
          (i32.or (i32.lt_u (local.get $group_size) (i32.const 20))
            (i32.or (i32.ne (i32.load16_u offset=2 (local.get $group)) (i32.const 1))
              (i32.eqz (i32.load16_u offset=4 (local.get $group))))))
      (then (return (i32.const 0))))
    ;; A group entry is 14 bytes. The first entry is the Win9x dialog icon;
    ;; multi-size groups put their default small image first as well.
    (local.set $entry (i32.add (local.get $group) (i32.const 6)))
    (local.set $image_id (i32.load16_u offset=12 (local.get $entry)))
    (local.set $image (call $rsrc_find_data_wa (i32.const 3) (local.get $image_id)))
    (local.set $image_size (global.get $rsrc_last_size))
    (if (i32.or (i32.eqz (local.get $image))
          (i32.lt_u (local.get $image_size) (i32.const 40)))
      (then (return (i32.const 0))))
    (local.set $header_size (i32.load (local.get $image)))
    (local.set $width (i32.load offset=4 (local.get $image)))
    (local.set $stored_h (i32.load offset=8 (local.get $image)))
    (local.set $bpp (i32.load16_u offset=14 (local.get $image)))
    (if (i32.lt_s (local.get $stored_h) (i32.const 0))
      (then (local.set $height (i32.sub (i32.const 0) (local.get $stored_h))))
      (else (local.set $height (local.get $stored_h))))
    (local.set $height (i32.shr_u (local.get $height) (i32.const 1)))
    ;; Bound dimensions before stride arithmetic and accept only the packed
    ;; BI_RGB formats supported by the shared software raster reader.
    (if (i32.or
          (i32.or (i32.lt_u (local.get $header_size) (i32.const 40))
            (i32.gt_u (local.get $header_size) (local.get $image_size)))
          (i32.or
            (i32.or (i32.le_s (local.get $width) (i32.const 0))
              (i32.gt_s (local.get $width) (i32.const 256)))
            (i32.or (i32.le_s (local.get $height) (i32.const 0))
              (i32.gt_s (local.get $height) (i32.const 256)))))
      (then (return (i32.const 0))))
    (if (i32.or (i32.ne (i32.load offset=16 (local.get $image)) (i32.const 0))
          (i32.and
            (i32.and (i32.ne (local.get $bpp) (i32.const 1))
              (i32.ne (local.get $bpp) (i32.const 4)))
            (i32.and (i32.ne (local.get $bpp) (i32.const 8))
              (i32.and (i32.ne (local.get $bpp) (i32.const 24))
                (i32.ne (local.get $bpp) (i32.const 32))))))
      (then (return (i32.const 0))))
    (if (i32.le_u (local.get $bpp) (i32.const 8))
      (then
        (local.set $palette_count (i32.load offset=32 (local.get $image)))
        (if (i32.eqz (local.get $palette_count))
          (then (local.set $palette_count
            (i32.shl (i32.const 1) (local.get $bpp)))))
        (if (i32.gt_u (local.get $palette_count) (i32.const 256))
          (then (return (i32.const 0))))))
    (local.set $color_stride (i32.shl
      (i32.shr_u (i32.add (i32.mul (local.get $width) (local.get $bpp))
        (i32.const 31)) (i32.const 5)) (i32.const 2)))
    (local.set $mask_stride (i32.shl
      (i32.shr_u (i32.add (local.get $width) (i32.const 31)) (i32.const 5))
      (i32.const 2)))
    (local.set $color_offset (i32.add (local.get $header_size)
      (i32.shl (local.get $palette_count) (i32.const 2))))
    (local.set $mask_offset (i32.add (local.get $color_offset)
      (i32.mul (local.get $color_stride) (local.get $height))))
    (if (i32.gt_u (i32.add (local.get $mask_offset)
          (i32.mul (local.get $mask_stride) (local.get $height)))
        (local.get $image_size))
      (then (return (i32.const 0))))

    (local.set $dst (global.get $GDI_BLIT_DST_DESC))
    (local.set $src (global.get $GDI_BLIT_SRC_DESC))
    (if (i32.eqz (call $gdi_surface_descriptor (local.get $hdc) (local.get $dst)))
      (then (return (i32.const 0))))
    (memory.fill (local.get $src) (i32.const 0) (i32.const 80))
    (i32.store (local.get $src) (i32.add (local.get $image) (local.get $color_offset)))
    (i32.store offset=4 (local.get $src) (local.get $width))
    (i32.store offset=8 (local.get $src) (local.get $height))
    (i32.store offset=12 (local.get $src) (local.get $color_stride))
    (i32.store offset=16 (local.get $src) (local.get $bpp))
    (i32.store offset=20 (local.get $src)
      (i32.lt_s (local.get $stored_h) (i32.const 0)))
    (i32.store offset=24 (local.get $src) (i32.add (local.get $image) (local.get $header_size)))
    (i32.store offset=28 (local.get $src) (local.get $palette_count))

    ;; Most dialog illustrations are centered in their static. Some compact
    ;; Win9x resources instead place a 16x16 glyph in the upper-left quadrant
    ;; of a 32x32 icon DIB and rely on origin clipping; the caller identifies
    ;; those resource layouts explicitly.
    (local.set $draw_w (local.get $width))
    (if (i32.gt_s (local.get $draw_w) (local.get $control_w))
      (then
        (if (i32.eqz (local.get $origin_clip))
          (then (local.set $src_x (i32.div_s
            (i32.sub (local.get $width) (local.get $control_w)) (i32.const 2)))))
        (local.set $draw_w (local.get $control_w)))
      (else
        (if (i32.eqz (local.get $origin_clip))
          (then (local.set $dst_x (i32.div_s
            (i32.sub (local.get $control_w) (local.get $width)) (i32.const 2)))))))
    (local.set $draw_h (local.get $height))
    (if (i32.gt_s (local.get $draw_h) (local.get $control_h))
      (then
        (if (i32.eqz (local.get $origin_clip))
          (then (local.set $src_y (i32.div_s
            (i32.sub (local.get $height) (local.get $control_h)) (i32.const 2)))))
        (local.set $draw_h (local.get $control_h)))
      (else
        (if (i32.eqz (local.get $origin_clip))
          (then (local.set $dst_y (i32.div_s
            (i32.sub (local.get $control_h) (local.get $height)) (i32.const 2)))))))
    (local.set $dst_x (call $gdi_line_map_x (local.get $dst)
      (i32.add (local.get $dst_x) (local.get $at_x))))
    (local.set $dst_y (call $gdi_line_map_y (local.get $dst)
      (i32.add (local.get $dst_y) (local.get $at_y))))

    (block $rows_done (loop $rows
      (br_if $rows_done (i32.ge_u (local.get $y) (local.get $draw_h)))
      (local.set $mask_row (i32.add (local.get $src_y) (local.get $y)))
      (if (i32.ge_s (local.get $stored_h) (i32.const 0))
        (then (local.set $mask_row
          (i32.sub (i32.sub (local.get $height) (local.get $mask_row)) (i32.const 1)))))
      (local.set $x (i32.const 0))
      (block $cols_done (loop $cols
        (br_if $cols_done (i32.ge_u (local.get $x) (local.get $draw_w)))
        (if (call $gdi_raster_clip_visible (local.get $hdc) (local.get $dst)
              (i32.add (local.get $dst_x) (local.get $x))
              (i32.add (local.get $dst_y) (local.get $y)))
          (then
            (local.set $mask_bit (i32.and
              (i32.shr_u (i32.load8_u (i32.add (local.get $image)
                    (i32.add (local.get $mask_offset)
                      (i32.add (i32.mul (local.get $mask_row) (local.get $mask_stride))
                        (i32.shr_u (i32.add (local.get $src_x) (local.get $x)) (i32.const 3))))))
                (i32.sub (i32.const 7)
                  (i32.and (i32.add (local.get $src_x) (local.get $x)) (i32.const 7))))
              (i32.const 1)))
            (local.set $source_color (call $gdi_raster_read (local.get $src)
              (i32.add (local.get $src_x) (local.get $x))
              (i32.add (local.get $src_y) (local.get $y))))
            ;; DI_MASK on its own asks for the transparency plane, not the
            ;; picture: the mask bit becomes the pixel and the colour plane is
            ;; never consulted.
            (if (i32.eqz (i32.and (local.get $di_flags) (global.get $DI_IMAGE)))
              (then
                (drop (call $gdi_raster_write (local.get $dst)
                  (i32.add (local.get $dst_x) (local.get $x))
                  (i32.add (local.get $dst_y) (local.get $y))
                  (select (i32.const 0x00FFFFFF) (i32.const 0)
                    (local.get $mask_bit))))
                (local.set $x (i32.add (local.get $x) (i32.const 1)))
                (br $cols)))
            ;; DI_IMAGE without DI_MASK is an opaque copy of the colour plane.
            (if (i32.eqz (i32.and (local.get $di_flags) (global.get $DI_MASK)))
              (then (local.set $mask_bit (i32.const 0))))
            (if (i32.eqz (local.get $mask_bit))
              (then (drop (call $gdi_raster_write (local.get $dst)
                (i32.add (local.get $dst_x) (local.get $x))
                (i32.add (local.get $dst_y) (local.get $y))
                (local.get $source_color))))
              (else
                ;; AND=1 preserves the destination, then XOR applies any
                ;; inverse pixel carried by the color plane.
                (if (local.get $source_color)
                  (then
                    (local.set $dest_color (call $gdi_raster_read (local.get $dst)
                      (i32.add (local.get $dst_x) (local.get $x))
                      (i32.add (local.get $dst_y) (local.get $y))))
                    (drop (call $gdi_raster_write (local.get $dst)
                      (i32.add (local.get $dst_x) (local.get $x))
                      (i32.add (local.get $dst_y) (local.get $y))
                      (i32.xor (local.get $dest_color) (local.get $source_color))))))))))
        (local.set $x (i32.add (local.get $x) (i32.const 1)))
        (br $cols)))
      (local.set $y (i32.add (local.get $y) (i32.const 1)))
      (br $rows)))
    (call $gdi_geometry_present (local.get $hdc) (local.get $dst)
      (local.get $dst_x) (local.get $dst_y)
      (i32.add (local.get $dst_x) (local.get $draw_w))
      (i32.add (local.get $dst_y) (local.get $draw_h)))
    (i32.const 1))

  ;; Convert a bounded LoadBitmapW name to the ASCII-compatible resource-name
  ;; form understood by the shared PE resource walker. Integer IDs pass through.
  (func $gdi_bitmap_resource_name (param $name i32) (param $wide i32) (result i32)
    (local $src i32) (local $i i32) (local $ch i32)
    (if (i32.or (i32.lt_u (local.get $name) (i32.const 0x10000))
          (i32.eqz (local.get $wide)))
      (then (return (local.get $name))))
    (local.set $src (call $g2w (local.get $name)))
    (block $done (loop $copy
      (if (i32.ge_u (local.get $i) (i32.const 255))
        (then (return (i32.const 0))))
      (local.set $ch (i32.load16_u
        (i32.add (local.get $src) (i32.shl (local.get $i) (i32.const 1)))))
      (br_if $done (i32.eqz (local.get $ch)))
      (if (i32.gt_u (local.get $ch) (i32.const 0x7F))
        (then (return (i32.const 0))))
      (i32.store8 (i32.add (global.get $GDI_BITMAP_NAME) (local.get $i)) (local.get $ch))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $copy)))
    (i32.store8 (i32.add (global.get $GDI_BITMAP_NAME) (local.get $i)) (i32.const 0))
    (call $w2g (global.get $GDI_BITMAP_NAME)))

  (func $gdi_bitmap_load_resource (param $instance i32) (param $name i32)
        (param $wide i32) (result i32)
    (local $resource_name i32) (local $data i32) (local $size i32)
    (if (i32.eq (local.get $instance) (i32.const -1))
      (then (return (call $gdi_bitmap_create_common_toolbar (local.get $name)))))
    (local.set $resource_name
      (call $gdi_bitmap_resource_name (local.get $name) (local.get $wide)))
    (if (i32.eqz (local.get $resource_name)) (then (return (i32.const 0))))
    (call $push_rsrc_ctx (local.get $instance))
    (local.set $data (call $rsrc_find_data_wa (i32.const 2) (local.get $resource_name)))
    (local.set $size (global.get $rsrc_last_size))
    (local.set $resource_name
      (call $gdi_bitmap_create_resource (local.get $data) (local.get $size)))
    (call $pop_rsrc_ctx)
    (local.get $resource_name))

  (func (export "test_gdi_bitmap_record_init")
        (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_record_init (local.get 0) (local.get 1) (local.get 2)
      (local.get 3) (local.get 4) (local.get 5) (local.get 6) (local.get 7)
      (local.get 8) (local.get 9) (local.get 10)))
  (func (export "test_gdi_bitmap_record_width") (param i32) (result i32)
    (call $gdi_bitmap_record_width (local.get 0)))
  (func (export "test_gdi_bitmap_record_height") (param i32) (result i32)
    (call $gdi_bitmap_record_height (local.get 0)))
  (func (export "test_gdi_bitmap_record_bpp") (param i32) (result i32)
    (call $gdi_bitmap_record_bpp (local.get 0)))
  (func (export "test_gdi_bitmap_record_storage") (param i32) (result i32)
    (call $gdi_bitmap_record_storage (local.get 0)))
  (func (export "test_gdi_bitmap_record_dib_bits") (param i32) (result i32)
    (call $gdi_bitmap_record_dib_bits (local.get 0)))
  (func (export "test_gdi_bitmap_write_object") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_write_object (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_parse_dib") (param i32 i32 i32) (result i32)
    (call $gdi_bitmap_parse_dib (local.get 0) (local.get 1) (local.get 2)))
  (func (export "test_gdi_bitmap_plan_create_bitmap")
        (param i32 i32 i32 i32 i32) (result i32)
    (call $gdi_bitmap_plan_create_bitmap (local.get 0) (local.get 1)
      (local.get 2) (local.get 3) (local.get 4)))
  (func (export "test_gdi_bitmap_plan_info") (param i32 i32) (result i32)
    (call $gdi_bitmap_plan_info (local.get 0) (local.get 1)))
  (func (export "test_gdi_bitmap_create_resource") (param i32 i32) (result i32)
    (call $gdi_bitmap_create_resource (local.get 0) (local.get 1)))
